vmware/clarity

package.json

[core] Update to TypeScript 2.0

---

README.md

[core] Adding TravisCI badge

---

README.md

[core] Update README with seed info

---

src/clarity/iconography/demo/icon-colors.demo.html
src/clarity/iconography/demo/icon-colors.ts
src/clarity/iconography/demo/icon-inverse-color.demo.html
src/clarity/iconography/demo/icon-inverse-color.ts
src/clarity/iconography/demo/icon-orientation.demo.html
src/clarity/iconography/demo/icon-orientation.ts
src/clarity/iconography/demo/icon-selection.demo.html
src/clarity/iconography/demo/icon-selection.ts
src/clarity/iconography/demo/icon-size.demo.html
src/clarity/iconography/demo/icon-size.ts
src/clarity/iconography/demo/iconography.demo.html
src/clarity/iconography/demo/iconography.demo.module.ts
src/clarity/iconography/demo/iconography.demo.routing.ts

- Break up the Icon Demos
- Remove text from Icon demos and move to the website
Tested on: Chrome. 

[UI,ICON] Breaking Icon Demos

---

src/clarity/nav/_responsive-nav.clarity.scss

- Fixed vertical alignment of the hamburger menu
- Added nav link appearance styling
- set cursor to pointer
Before:
After:
Fixes: #84 
Tested on: Chrome, IE10, 11, Edge, Safari, Firefox

[UI] Nav Trigger Bug Fixes

---

src/clarity/stack-view/_stack-view.clarity.scss

[UI] Fix a margin error in stack label arrow icon

---

src/app/app.html
src/clarity/nav/_header.clarity.scss
src/clarity/nav/demo/header-types.demo.html

Fixes
- Dropdown & Text Links Font Weights
- Dropdown & Text Links Hover Styles
in the header actions area
Updates
- Header Type Demo to add a text link
Tested on:
- Chrome
- Firefox
- IE10
- IE11
- Edge
- Safari

[UI] Dropdown font weight fix in the Header

---

package.json

[core] updating package.json for 0.7.1

---

_documentation/iconography.md

Please note that this should be only be merged to gh-pages when https://github.com/vmware/clarity/pull/70 is merged in and 0.7.1 is published

[WEB] Icons Docs Updates for Split Demos

---

CODING_GUIDELINES.md
CONTRIBUTING.md

Added coding guidelines that should be double-checked for each pull
requests. Also fixed the plunker link that was broken.
To see what they look like on GitHub, see [this Gist](https://gist.github.com/youdz/2e464ca3129015611e76ea30ee17ea9f).

[CORE] Coding guidelines

---

README.md

Just solving conflicts for @gdi2290's pull request.

docs(README): code highlight

---

src/clarity/forms/_forms.clarity.scss
src/clarity/input-fields/demo/input-fields.demo.html

- Added url type to the $styledInputs list

Fixes #74:

---

_documentation/datagrid.md

[WEB] Datagrid placeholder demo

---

.pullapprove.yml

[core] Combining two conditions in PullApprove config

---

src/clarity/datagrid/datagrid-placeholder.spec.ts

Removing a compile error in a spec file.

[NG] Datagrid Placeholder test typing

---

src/clarity/nav/demo/header-types.demo.html

Added an example for Dropdown Toggle with Text in the Header
Fixes: #76 

[UI] Header Actions Dropdown Text Example

---

.github/ISSUE_TEMPLATE.md
CONTRIBUTING.md
README.md

[core] Add Plunker Template

---

.gitignore
get-started/index.md

[web] Adds link to the Clarity Plunker Templage`

---

src/clarity/modal/demo/modal-sizes.demo.html

Added `.modal-xl` to the Modal documentation
Browser Tests: Chrome
Fixes: #194 

[UI,DOC] Added Extra Large Modal to the Doc

---

src/clarity/datagrid/_datagrid.clarity.scss
src/clarity/datagrid/built-in/filters/datagrid-string-filter.ts
src/clarity/datagrid/datagrid-column.ts
src/clarity/datagrid/datagrid-filter.ts

- Solve scaling column separator
- Solve placement of filter icon and title
- Closes #207
Signed-off-by: Robert Pamfile <robert.pamfile@gmail.com>
BY BYTEX ROMANIA

[UI] Datagrid column headers wrap fix

---

src/clarity/iconography/demo/icon-selection.demo.html
src/icons/svg-icon-templates.ts

Renamed icon documentation for 'dashboard'
#221
Signed-off-by: Ioan Ungurean <inungurean@gmail.com>

[UI] Update icon documentation for 'dashboard' to 'dashboard-gauge'

---

_documentation/forms.md

Adding forms documentation to the website.
**Note: Do not merge until 0.7.5 is published**

[WEB] Adding Forms Documentation to the Website | Do not merge until 0.7.5 is published

---

src/app/dropdown/dropdown-angular-close-item-false.demo.html
src/app/dropdown/dropdown-static-icon-toggle.demo.html
src/app/iconography/icon-colors.demo.html
src/app/iconography/icon-inverse-color.demo.html
src/app/iconography/icon-selection.ts
src/clarity-icons/clarity-icons.scss
src/clarity-icons/svg-icon-templates.ts

Tested on: Chrome, Firefox, Safari, Edge, IE11, IE10

[ICONS] removed deprecated classes and updated the icon demos

---

build/npm/clarity-angular.json

[core] Include main in package.json for bundlers like Browserify/Webpack

---

src/clarity-angular/stack-view/index.ts

[core] Export stackview components

---

angular-cli.json
src/polyfills.ts
src/styles/main.scss

Tested on IE10, Chrome, FF, Safari

[web] small refactors to fix IE10 issues

---

src/app/app.component.ts
src/index.html

• tested to make sure it was firing and also not firing as expected
Tested in:
✔︎ Chrome

[web] adding GA tracking to NG router subscription

---

CODING_GUIDELINES.md

[Docs] Add "clr" prefix to coding guidelines

---

src/clarity-icons/define-clarity-icons.ts
src/clarity-icons/extend-clarity-icons.ts

[ICONS] icon retrieval get method defined

---

gemini/tests/layout.js

• commented out for now until Aditya has a chance to fix CSS regression tests that are breaking due to font awesome
Tested in:
✔︎ Chrome

[core] CSS regression intermediate fix

---

src/demos/datagrid/selection/selection.html
src/demos/datagrid/selection/selection.ts

Documents (and obviously depends on) #345.

[WEB] Document Datagrid's 2-way binding on row selection

---

src/demos/alert/static/alert-app-level.demo.html
src/demos/alert/static/alert-cards.demo.html
src/demos/alert/static/alert-modals.demo.html
src/demos/alert/static/alert-sizes.demo.html
src/demos/alert/static/alert-styles.demo.html
src/demos/layout/layout-all.html
src/demos/modal/modal-animation-design.demo.html
src/demos/modal/modal-animation.demo.html
src/demos/modal/modal-sizes.demo.html
src/demos/modal/modal-static.demo.html
src/demos/wizard/wizard-not-closable.demo.html
src/demos/wizard/wizard-not-closable.demo.ts
src/demos/wizard/wizard-options.demo.html
src/demos/wizard/wizard-static.demo.html
src/pages/documentation/wizards.html

• this change affects modals, wizards, and alerts
• DO NOT MERGE THIS IN UNTIL AFTER #??? IS RELEASED

[web] updating demos to use clrIcon close - MERGE AFTER 0.8.2

---

src/demos/iconography/icon-selection.demo.html
src/demos/iconography/icon-selection.ts
src/demos/iconography/iconography.demo.scss
src/pages/documentation/iconography.html

[WEB] Updated Iconography demo page

---

src/app/progress-bars/progress-bar-examples.html

Found this while reading your (very good) docs, hope that helps.

[docs] Add missing space in progress bar demo markup

---

build/karma-test-shim.js
build/karma.conf.js
build/tasks/coding-rules.js
build/tasks/publish.js
build/tasks/typescript.js
src/app/index.html
src/clarity-icons/clarity-icons-api.ts
src/clarity-icons/clarity-icons.spec.ts
src/clarity-icons/index.ts
src/clarity-icons/shapes/basic-shapes.ts
src/clarity-icons/shapes/core-shapes.ts
src/clarity-icons/shapes/social-shapes.ts
src/clarity-icons/shapes/technology-shapes.ts

[ICONS] Unit testing for Clarity Icons

---

src/demos/iconography/icon-selection.demo.html
src/demos/iconography/icon-selection.ts

[AFTER-PUBLISH | WEB] Update icon selection demo

---

package.json
src/demos/iconography/icon-selection.demo.html
src/demos/iconography/icon-selection.ts
src/demos/iconography/iconography.demo.scss

[AFTER-PUBLISH][WEB] updated icon demo

---

src/app/datagrid/selection/selection.ts

Fixed the datagrid selection demo

[NG] Datagrid Example Fix

---

src/demos/iconography/icon-selection.ts

[web] Icons demo update

---

src/clarity-angular/main.scss

Tested in Clarity-Seed projects.
Resolves #506.

[UI] Removed overwrite.scss from main.scss

---

src/clarity-angular/tree-view/_tree-view.clarity.scss
src/clarity-angular/tree-view/abstract-tree-selection.spec.ts
src/clarity-angular/tree-view/tree-selection.ts
src/clarity-angular/tree-view/tree-view.html

Add copyright messages to TreeView source
No tests required.

[NG] Add copyright messages to TreeView

---

src/app/datagrid/datagrid.demo.html
src/app/datagrid/datagrid.demo.module.ts
src/app/datagrid/datagrid.demo.routing.ts
src/app/datagrid/selection-single/selection-single.html
src/app/datagrid/selection-single/selection-single.ts
src/clarity-angular/datagrid/datagrid-row.spec.ts
src/clarity-angular/datagrid/datagrid-row.ts
src/clarity-angular/datagrid/datagrid.html
src/clarity-angular/datagrid/datagrid.ts
src/clarity-angular/datagrid/providers/selection.spec.ts
src/clarity-angular/datagrid/providers/selection.ts
yarn.lock

Single-select only mode in a datagrid.
resolves #475.

[ng] single-selection for datagrid

---

src/clarity-angular/forms/_checkbox.clarity.scss
src/clarity-angular/forms/_forms.clarity.scss
src/clarity-angular/forms/_inputs.clarity.scss
src/clarity-angular/forms/_radio.clarity.scss
src/clarity-angular/forms/_select.clarity.scss
src/clarity-angular/forms/utils/form-variables.scss
src/clarity-angular/forms/utils/mixins.scss
src/clarity-angular/main.scss
src/clarity-angular/tree-view/_tree-view.clarity.scss

Modulazied Form CSS
New Files for:
1. Checkboxes
2. Radios
3. Selects
4. Inputs

[UI] Modularize Form Styles [Do Not Merge in 0.8.8]

---

build/tasks/aot.js
gulpfile.js
src/clarity-angular/datagrid/datagrid-pagination.ts
src/clarity-angular/datagrid/datagrid.ts
src/clarity-angular/stack-view/stack-header.ts
src/clarity-angular/stack-view/stack-input.ts
src/clarity-angular/stack-view/stack-select.ts
tsconfig.test.json

[CORE] AoT sanity test

---

src/demos/datagrid/filtering/examples.ts
src/demos/datagrid/filtering/filtering.html
src/demos/datagrid/filtering/filtering.ts
src/demos/datagrid/sorting/sorting.html
src/demos/datagrid/string-filtering/examples.ts
src/demos/datagrid/string-filtering/string-filtering.html
src/demos/datagrid/string-filtering/string-filtering.ts

[WEB] Updates datagrid documentation for presets and two way binding

---

src/pages/documentation/input-fields.html

This content should be tooltip-bottom-left
Signed-off-by: yanyx <yanyx@umcloud.com>

[WEB] This content should be tooltip-bottom-left

---

src/clarity-icons/clarity-icons.scss

https://www.dropbox.com/s/12muv48jlr9w9q4/transition.mov?dl=0
Tested on Chrome, Firefox, Safari, Edge, IE 11, IE 10 (choppy animation on IE10)
Resolves https://github.com/vmware/clarity/issues/577

[ICONS] inherit transition in svg shape

---

src/clarity-angular/datagrid/built-in/filters/datagrid-string-filter.ts
src/clarity-angular/datagrid/utils/datagrid-filter-registrar.ts

Added type casting to the datagrid component

[NG] Datagrid Type Cast

---

src/clarity-angular/datagrid/datagrid.spec.ts
src/clarity-angular/datagrid/datagrid.ts
src/clarity-angular/datagrid/providers/filters.spec.ts
src/clarity-angular/datagrid/providers/filters.ts

- Adds testing around the feature changes added in #355
- closes #600

[NG] Fix and unwrap data returned from DatagridPropertyStringFilter

---

src/demos/selects/selects.demo.html

Documentation for select multiple

[WEB] Select multiple documentation - DO NOT MERGE UNTIL 0.8.13 is published

---

src/app/documentation/documentation-templates-stub.ts
src/demos/button-group/angular-basic-structure.html
src/demos/button-group/angular-basic-structure.ts
src/demos/button-group/angular-directions.html
src/demos/button-group/angular-directions.ts
src/demos/button-group/angular-types.html
src/demos/button-group/angular-types.ts
src/demos/button-group/basic-structure.html
src/demos/button-group/basic-structure.ts
src/demos/button-group/button-group.demo.module.ts
src/demos/button-group/checkbox.html
src/demos/button-group/checkbox.ts
src/demos/button-group/icons.html
src/demos/button-group/icons.ts
src/demos/button-group/mixed.html
src/demos/button-group/mixed.ts
src/demos/button-group/radio.html
src/demos/button-group/radio.ts
src/demos/button-group/types.html
src/demos/button-group/types.ts
src/demos/demos.module.ts
src/pages/documentation/button-group.html
src/pages/documentation/buttons.html
src/settings/componentlist.json
src/styles/components.scss

Button Groups Documentation [DO NOT MERGE UNTIL 0.8.14 IS PUBLISHED]

---

src/clarity-angular/datagrid/_datagrid.clarity.scss
src/clarity-angular/datagrid/datagrid-column.ts
src/clarity-angular/datagrid/datagrid.html

Resolves https://github.com/vmware/clarity/issues/669
This fix will be also needed for https://github.com/vmware/clarity/issues/621

[NG] Fix datagrid column seperator

---

src/clarity-angular/progress-bars/_progress-bars.clarity.scss

[UI] Porting progress bar reset animation to 0.8

---

src/clarity-angular/datagrid/_datagrid.clarity.scss
src/clarity-angular/datagrid/datagrid-column.ts
src/clarity-angular/datagrid/datagrid.html

[NG] Fix datagrid column seperator (#699)

---

src/app/datagrid/selection/selection.html
src/clarity-angular/datagrid/datagrid-action-bar.spec.ts
src/clarity-angular/datagrid/datagrid-action-bar.ts

[ng] allow using datagrid action bar in non-selectable datagrids.

---

build/karma.conf.js
src/clarity-angular/datagrid/_datagrid.clarity.scss
src/clarity-angular/datagrid/all.spec.ts
src/clarity-angular/datagrid/datagrid-column.spec.ts
src/clarity-angular/datagrid/datagrid-column.ts
src/clarity-angular/datagrid/index.ts
src/clarity-angular/datagrid/providers/drag-dispatcher.ts
src/clarity-angular/datagrid/render/column-resizer.spec.ts
src/clarity-angular/datagrid/render/column-resizer.ts
src/clarity-angular/datagrid/render/dom-adapter.ts
src/clarity-angular/datagrid/render/header-renderer.spec.ts
src/clarity-angular/datagrid/render/header-renderer.ts
src/clarity-angular/datagrid/render/main-renderer.spec.ts
src/clarity-angular/datagrid/render/main-renderer.ts

Tested on Chrome, Firefox, Safari, Edge, IE 11, & IE 10
resolves #621

[NG] Column Resizing

---

src/clarity-angular/wizard/all.spec.ts
src/clarity-angular/wizard/providers/button-hub.spec.ts
src/clarity-angular/wizard/providers/page-collection.spec.ts
src/clarity-angular/wizard/providers/page-collection.ts
src/clarity-angular/wizard/providers/wizard-navigation.ts
src/clarity-angular/wizard/wizard.ts

[NG] wizard button hub tests now working
• had to skip one, added a TODO
• appears to be an issue with either the test context or how the test is testing things

[NG] got wizard page collection tests and button hub tests working

---

src/app/wizard/wizard-alt-next.demo.html
src/app/wizard/wizard-alt-next.demo.ts
src/app/wizard/wizard.demo.module.ts
src/app/wizard/wizard.demo.routing.ts
src/app/wizard/wizard.demo.ts
src/clarity-angular/wizard/providers/page-collection.ts
src/clarity-angular/wizard/providers/wizard-navigation.ts
src/clarity-angular/wizard/wizard-page.ts
src/clarity-angular/wizard/wizard.spec.ts
src/clarity-angular/wizard/wizard.ts

• installer team needed this
• needs some unit testing but works and doesn’t break any existing tests
• next step is adding dox to website

[NG] adding alt-next feature to wizard

---

src/clarity-angular/wizard/_wizard.clarity.scss

Tested in:
✔︎ Chrome
Closes: #782

[UI] adjusting padding in wizard header

---

src/demos/wizard/wizard-alt-next.demo.html
src/demos/wizard/wizard-alt-next.demo.ts
src/demos/wizard/wizard.demo.module.ts
src/pages/documentation/wizards.html

• This needs to go in AFTER the 0.9.2 release

[WEB] dox for preventDefaultNext functionality in wizards

---

src/clarity-angular/wizard/wizard-page.spec.ts

[NG] wizard page unit tests fixed

[NG] fixed new wizard page unit tests

---

package.json
yarn.lock

[core] fixing dependency issue with jasmine-core

---

src/app/app-routing.module.ts
src/app/documentation/documentation.module.ts
src/demos/datagrid/datagrid.demo.module.ts
src/demos/datagrid/hide-show-columns/hide-show-columns.html
src/demos/datagrid/hide-show-columns/hide-show-columns.ts
src/pages/documentation/datagrid.html

Adds a demo app for the *clrDgHideableColumn directive.

[WEB] Adds demo for hide/show columns NOTE: Do not merge until after hide/show columns has been released

---

src/pages/get-started.html

[CORE] angular-cli released, update getting started
Removed reference to angular-cli being in beta.  

[CORE] angular-cli released, update getting started

---

.editorconfig

Added a Editor Config
Fixes: #761 
Tested on Webstorm, Atom

[CORE] Editor Config

---

package.json

Fixes: #546
Just had to upgrade the custom elements package.
Before:
After:
Tested on Firefox and IE

[CORE] Upgrade Custom Elements version

---

BUILD.md
CONTRIBUTING.md
README.md
build/karma.conf.js
build/npm/clarity-angular-README.md
build/npm/clarity-angular.json
src/app/datagrid/basic-structure/basic-structure.html
src/clarity-angular/angular1/ng1-shim.ts
src/clarity-angular/iconography/iconography.ts
src/clarity-angular/stack-view/stack-view.ts
src/clarity-angular/wizard/wizard-custom-tags.ts

Angular2 to Angular
Signed-off-by: Chris Ha  <chunghha@users.noreply.github.com>

[NG] Angular rebranding changes

---

src/app/documentation/demos/wizard/wizard-async-completion.demo.ts
src/app/documentation/demos/wizard/wizard-async-validation.demo.ts
src/releases/final-template/auto-generated-news.component.html

• using forceNext is necessary because of a navigation bug introduced in 0.9.3
• this is fixed in 0.9.4 but using forceNext still works too

[WEB] some wizard demos not working

---

src/app/wizard/wizard-jump-to.demo.ts
src/app/wizard/wizard-options.demo.ts
src/clarity-angular/wizard/all.spec.ts
src/clarity-angular/wizard/providers/button-hub.spec.ts
src/clarity-angular/wizard/providers/header-actions.spec.ts
src/clarity-angular/wizard/providers/header-actions.ts
src/clarity-angular/wizard/providers/page-collection.mock.ts
src/clarity-angular/wizard/providers/page-collection.spec.ts
src/clarity-angular/wizard/providers/wizard-navigation.spec.ts
src/clarity-angular/wizard/providers/wizard-navigation.ts
src/clarity-angular/wizard/test-components/api-wizard.mock.ts
src/clarity-angular/wizard/test-components/basic-wizard.mock.ts
src/clarity-angular/wizard/test-components/dynamic-wizard.mock.ts
src/clarity-angular/wizard/test-components/header-action-wizard.mock.ts
src/clarity-angular/wizard/test-components/unopened-wizard.mock.ts
src/clarity-angular/wizard/wizard-button.ts
src/clarity-angular/wizard/wizard-page.spec.ts
src/clarity-angular/wizard/wizard-page.ts
src/clarity-angular/wizard/wizard-stepnav-item.spec.ts
src/clarity-angular/wizard/wizard.html
src/clarity-angular/wizard/wizard.spec.ts
src/clarity-angular/wizard/wizard.ts

• unit tests for the wizard revealed some deep, deep issues with the navigation service, current pages, and ngFor
• thus far, users have not been impacted by these issues but they would have been — we have demos on the website failing due to these problems
• these issues took a lot of time to refactor and prove out via unit tests
• used TestContext helper for all wizard unit tests
• tested all demos on app to make sure they worked as expected
Tested in:
✔︎ Chrome
[NG] unit tests
[NG] unit tests
• moved shared components to a test-components folder
[NG] dox for wizard.ts
[NG] dox for wizard.ts …

[NG] wizard unit tests and deep bug fixing

---

src/clarity-angular/datagrid/datagrid-items.spec.ts
src/clarity-angular/datagrid/datagrid-items.ts

[NG] Adds check and default for null/undefined input in DatagridItems

---

src/app/documentation/demos/wizard/wizard-force-forward.demo.html
src/app/documentation/demos/wizard/wizard-force-forward.demo.ts
src/app/documentation/demos/wizard/wizard.demo.html
src/app/documentation/demos/wizard/wizard.demo.module.ts

• make sure to double-check changes after 0.9.4 is released
• should be good to go after 0.9.4 is published

[WEB] updating wizard documentation with 0.9.4 changes - DO NOT MERGE

---

src/app/documentation/demos/header/header-colors.demo.html
src/app/documentation/demos/header/header-colors.ts

Header Color Demo Update. Added the new Header color

[WEB] Header Color Documentation Update - Merge after 0.9.4 is published

---

src/clarity-angular/wizard/providers/page-collection.ts
src/clarity-angular/wizard/providers/wizard-navigation.ts
src/clarity-angular/wizard/wizard-button.ts
src/clarity-angular/wizard/wizard-page.ts

[NG] code dox for wizard

---

src/clarity-angular/layout/main-container/_layout.clarity.scss

[UI] Fix to the modal issue in Firefox

---

package.json

[CORE] version 0.9.6

---

build/rollup-clarity.config.js

Fixes #867. 
Tested on:
- plunkr: https://plnkr.co/edit/nz1IA4gN8WjklYW0aOFu?p=preview
- sample-app
- seed (angular-cli)

[core] Fix rollup config to use RxJs's global (rxjs -> Rx)

---

src/app/index.html
src/sample-app/index.html

Sorry! I forgot to remove the mutation observer ref from index.html in the demo app

[CORE] Remove Mutation Observer ref from demo app

---

src/clarity-angular/code/syntax-highlight/syntax-highlight.ts
src/clarity-angular/data/datagrid/animation-hack/row-expand-animation.ts
src/clarity-angular/data/datagrid/built-in/filters/datagrid-string-filter.spec.ts
src/clarity-angular/data/datagrid/built-in/filters/datagrid-string-filter.ts
src/clarity-angular/data/datagrid/render/cell-renderer.ts
src/clarity-angular/data/datagrid/render/dom-adapter.ts
src/clarity-angular/data/datagrid/render/head-renderer.ts
src/clarity-angular/data/datagrid/render/header-renderer.ts
src/clarity-angular/data/datagrid/render/main-renderer.ts
src/clarity-angular/data/datagrid/render/table-renderer.ts

`Renderer` to `Renderer2`
Signed-off-by: Chris Ha <chunghha@users.noreply.github.com>

[NG] Move away from deprecated API

---

src/app/documentation/demos/login/login-example.demo.html
src/app/documentation/demos/login/login-example.demo.ts

[web] updating login doc - DO NOT MERGE UNTIL 0.9.7 IS PUBLISHED

---

src/app/documentation/demos/wizard/wizard-stop-navigation.demo.html
src/app/documentation/demos/wizard/wizard-stop-navigation.demo.ts
src/app/documentation/demos/wizard/wizard.demo.html
src/app/documentation/demos/wizard/wizard.demo.module.ts

• includes documentation and demo for disabling navigation and also for just disabling the stepnav
NOTE: pushed this as a topic branch so team could edit and merge if/when they need to...

[WEB] docs for new wizard feature - MERGE AFTER 0.9.7

---

src/clarity-angular/data/datagrid/datagrid-column-toggle.ts
src/clarity-angular/data/datagrid/datagrid-column.ts
src/clarity-angular/data/datagrid/datagrid-filter.ts
src/clarity-angular/data/datagrid/datagrid-pagination.ts
src/clarity-angular/data/datagrid/datagrid-row.ts
src/clarity-angular/data/tree-view/tree-node.html
src/clarity-angular/layout/nav/header.ts
src/clarity-angular/wizard/wizard-button.ts
src/clarity-angular/wizard/wizard-header-action.ts

[NG] Explicitly specified button type

---

README.md

Signed-off-by: Chris Ha <chunghha@users.noreply.github.com>

[CORE] Remove Mutation Observer ref from README

---

src/clarity-angular/data/datagrid/datagrid-column.spec.ts
src/clarity-angular/data/datagrid/datagrid-column.ts

[NG] Prevented undefined sortBy to replace default comparator value

---

.travis.yml

Required changes for upcoming Travis image changes. Read: https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2

[core] updating travis config as per travis' image change

---

src/app/documentation/demos/dropdown/dropdown-angular-close-item-false.demo.html
src/app/documentation/demos/dropdown/dropdown-angular-close-item-false.ts
src/app/documentation/demos/dropdown/dropdown-angular-positioning.demo.html
src/app/documentation/demos/dropdown/dropdown-angular-positioning.ts
src/app/documentation/demos/dropdown/dropdown-static-buttonlink-toggle.demo.html
src/app/documentation/demos/dropdown/dropdown-static-buttonlink-toggle.ts
src/app/documentation/demos/dropdown/dropdown-static-default.demo.html
src/app/documentation/demos/dropdown/dropdown-static-default.ts
src/app/documentation/demos/dropdown/dropdown-static-fontawesome-toggle.demo.html
src/app/documentation/demos/dropdown/dropdown-static-fontawesome-toggle.ts
src/app/documentation/demos/dropdown/dropdown-static-icon-toggle.demo.html
src/app/documentation/demos/dropdown/dropdown-static-icon-toggle.ts
src/app/documentation/demos/dropdown/dropdown-static-positioning.demo.html
src/app/documentation/demos/dropdown/dropdown-static-positioning.ts
src/app/documentation/demos/dropdown/dropdown.demo.html

We dont recommend using anchor tags in dropdowns. Updating code snippets & docs

[WEB] Fix dropdown docs

---

src/releases/0.10/0.10.0-alpha.html

[WEB] 0.10.0-alpha release note updates for alerts - DO NOT MERGE

---

src/app/datagrid/sorting/examples.ts
src/app/datagrid/sorting/sorting.html
src/clarity-angular/data/datagrid/datagrid-column.spec.ts
src/clarity-angular/data/datagrid/datagrid-column.ts

Fixes #1089
Signed-off-by: Chris Ha <chunghha@users.noreply.github.com>

[NG] Allow property shortcut for clrDgSortBy

---

src/app/documentation/demos/color/color-palette.ts

[WEB] update text contrast demo for colors in color palette

---

src/app/documentation/demos/typography/typography-text.html
src/app/documentation/demos/typography/typography-text.ts

[WEB] Updating dox with Monospace font

---

src/sample-app/app.component.html

[NG] Changed the old tabs markup to the new one in Sample App

---

src/app/datagrid/expandable-rows/expandable-rows.html
src/app/datagrid/expandable-rows/expandable-rows.ts
src/clarity-angular/data/datagrid/datagrid-row-detail.spec.ts
src/clarity-angular/data/datagrid/datagrid-row-detail.ts

- Adds hide / show behavior to expandable datagrid row cells that are also hideable columns
- Adds test for new behavior
- closes #1076

[NG] Fixes hideable column issue for rows with row detail cells

---

src/clarity-angular/layout/main-container/_layout.clarity.scss

Improvement of scrolling experience on iOS.
Signed-off-by: Denis Beklarov <danny@delar.de>

[ux] iOS smoth scrolling

---

src/clarity-icons/clarity-icons.spec.ts
src/clarity-icons/helpers.spec.ts
src/clarity-icons/shapes/all-shapes.ts

[ICONS] enabling to import all Clarity Icons shapes via the AllShapes set

---

src/clarity-angular/data/tree-view/_tree-view.clarity.scss
src/clarity-angular/data/tree-view/tree-node.ts

Fixes: #1218
Tested on: Edge, IE, Safari, Chrome, Firefox

[NG] Tree View Animation Fix - 0.9

---

build/write-svg-icons.js

[ICONS] add transparent bg in printed SVGs - v0.9

---

src/sample-app/app.component.html

[NG] Sample App Popover Fix

---

src/app/documentation/demos/alert/alerts.demo.html

[WEB] Fixes alert documentation for danger alert

---

src/clarity-icons/clarity-icons-sfx.ts

[ICONS] use all-shapes shortcut for importing icon sets

---

src/app/get-started/get-started.component.html

- Step 2c 3 is now "Import the ClarityModule into your Angular application's module. Your application's main module might look like this:"
Fixes #1273
Signed-off-by: Pratheek Hegde <ptk609@gmail.com>

[CORE] Fix duplicate Step 2c in Get Started

---

src/clarity-angular/layout/nav/_sidenav.clarity.scss

Fixes issue #875
Signed-off-by: Bojan Djurdjevic <bojan88@gmail.com>

[UX] Collapsible navigation menu scroll bug fix

---

src/app/documentation/demos/header/header-types.demo.html
src/app/documentation/demos/header/header-types.ts
src/app/documentation/demos/nav/header-types.ts

[WEB] Header Docs Bug Fix

---

src/app/documentation/demos/buttons/buttons.demo.html
src/app/documentation/demos/tabs/tabs-angular-overflow.demo.html
src/app/documentation/demos/tabs/tabs-angular-overflow.ts
src/app/documentation/demos/tabs/tabs-angular-simple.ts
src/app/documentation/demos/tabs/tabs.demo.html
src/app/documentation/demos/tabs/tabs.demo.module.ts

Adding documentation and code example on tab overflow.

[web] tab overflow doc

---

build/npm/clarity-angular.json

Upgrade Angular Peer Dependencies. 4.3 has an animation fix which is required for vertical nav and other components.

[CORE] Upgrade Angular Peer Dependencies

---

src/app/dropdown/dropdown-angular-nested.demo.html
src/clarity-angular/popover/dropdown/dropdown-item.ts
src/clarity-angular/popover/dropdown/dropdown.spec.ts
src/clarity-angular/popover/dropdown/dropdown.ts
src/clarity-angular/popover/dropdown/providers/dropdown.service.ts

[NG] Close all menus on item click

---

src/app/alert/static/alert-cards.demo.html

__placehold.it__ supports `https` as well.

[UI] Avoid HTTPS mixed-content warning on demo page

---

src/clarity-angular/utils/chocolate/chocolate-factory.spec.ts
src/clarity-angular/utils/chocolate/oompa-loompa.ts

Title says it all. :trollface:
Fixes #1215.

[NG] Oompa-Loompa now properly unsubscribes from Willy Wonka

---

src/clarity-angular/utils/chocolate/chocolate-factory.spec.ts
src/clarity-angular/utils/chocolate/oompa-loompa.ts

[v0.9] Oompa-Loompa now properly unsubscribes from Willy Wonka

---

build/karma-test-shim.js
build/karma.conf.js
build/npm/clarity-icons.json
build/tasks/bundle.js
package.json
src/app/index.html
src/app/ng1.html
src/clarity-icons/clarity-icons-api.ts
src/clarity-icons/clarity-icons.spec.ts
src/clarity-icons/helpers.spec.ts
src/typings.d.ts
yarn.lock

[ICONS] remove dompurify from Clarity Icons

---

src/clarity-icons/clarity-icons.spec.ts
src/clarity-icons/shapes/commerce-shapes.ts
src/clarity-icons/shapes/core-shapes.ts
src/clarity-icons/shapes/essential-shapes.ts
src/clarity-icons/shapes/media-shapes.ts
src/clarity-icons/shapes/social-shapes.ts
src/clarity-icons/shapes/technology-shapes.ts
src/clarity-icons/shapes/travel-shapes.ts

• This is to help screenreaders to not read down into the SVG tags

Adding img ARIA role to Clarity Icon SVGs

---

src/app/app.component.html
src/app/get-started/get-started.component.html
src/app/icons/icons-sets/icons-inventory.ts
src/app/icons/icons-sets/icons-sets.component.ts
src/app/icons/icons-sets/icons-tags.ts
src/app/icons/icons.component.html
src/app/icons/icons.component.scss
src/index.html

Fixes #1374
Preview here: https://shijir.github.io/clarity/icons/clarity-icons

[web] icons website refinement based on feedback

---

src/clarity-angular/data/datagrid/render/main-renderer.spec.ts
src/clarity-angular/data/datagrid/render/main-renderer.ts

[NG] Fixes datagrid height on page size changes

---

src/app/documentation/demos/button-group/icons.html
src/app/documentation/demos/button-group/icons.ts
src/app/documentation/demos/buttons/buttons.demo.html
src/app/documentation/demos/buttons/buttons.demo.module.ts
src/app/documentation/demos/buttons/icon-buttons.html
src/app/documentation/demos/buttons/icon-buttons.ts

[WEB] Icon Buttons Documentation

---

ATTRIBUTION.md

[CORE] Updated sass-planifolia attribution

---

src/app/documentation/demos/alert/static/alert-styles.ts
src/releases/0.10/0.10.0-alpha.2.html

[DOCS] Static Alerts Doc Fix

---

README.md
build/npm/clarity-icons-README.md
build/npm/clarity-icons.json
package.json

Signed-off-by: Cotton Hou <himcotton@gmail.com>

[CORE] Unpin Custom Elements from 1.0.0

---

src/app/icons/icons-sets/icon-detail-card/icon-detail-card.component.html
src/app/icons/icons-sets/icon-detail-card/icon-detail-card.component.scss
src/app/icons/icons-sets/icons-inventory.ts
src/app/icons/icons-sets/icons-tags.ts

- added in more tags for searching as well
Preview: https://shijir.github.io/clarity/icons/icon-sets

[WEB] icon detail snippet fix

---

src/app/documentation/demos/modal/modal-style-design.ts
src/app/documentation/demos/wizard/wizard-design.demo.ts
src/app/documentation/utils/disable-focus-trap.ts

Should be merged in after PR https://github.com/vmware/clarity/pull/1441 gets incorporated into master.

[WEB] disable focus trap in static modal and wizard demos

---

src/ks-app/src/app/containers/nav/vertical-nav.component.html
src/ks-app/src/styles/_app-style.scss
src/ks-app/src/styles/_clarity-overrides.scss

Fixed the Vertical Nav Demo in the Kitchen Sink App

[CORE,KS] Vertical Nav KS Fix

---

src/app/tabs/tabs-angular.demo.html
src/clarity-angular/layout/tabs/tab-content.ts
src/clarity-angular/layout/tabs/tab-link.directive.spec.ts
src/clarity-angular/layout/tabs/tab-link.directive.ts
src/clarity-angular/layout/tabs/tabs.spec.ts
src/clarity-angular/layout/tabs/tabs.ts

[NG] Fix tab issue with *ngIf directive

---

README.md

Signed-off-by: Willian Oliveira <williangd@yahoo.com.br>

Updated Plunker link description

---

src/app/get-started/get-started.component.html

This PR will update latest and v0.9.20 plunker links for the website. 
Signed-off-by: Matt Hippely <hippely@gmail.com>

[WEB] Update plunker links

---

src/polyfills.ts

[CORE] Include the custom elements polyfill in polyfills.ts

---

src/app/app.component.html
src/app/app.module.ts
src/app/content-container.component.ts
src/clarity-angular/layout/nav/header.spec.ts
src/clarity-angular/layout/nav/header.ts
src/clarity-angular/layout/nav/index.ts
src/clarity-angular/layout/nav/main-container-willy-wonka.ts
src/clarity-angular/layout/nav/nav-detection-oompa-loompa.ts
src/clarity-angular/layout/nav/navLevelDirective.ts

Fixes: #1268
clr-header - Oompa Loompa
clr-main-container - Willy Wonka
Also added the ks-app node-modules to the ignore sources array to avoid tslint from checking it.
cc: @hippee-lee 

[NG] Main Container + Header Oompa Loompa

---

webpack.config.js

add missing main.scss to our clarity-ui package + minor code clean up

[core] add missing main.scss to our clarity-ui package

---

src/app/datagrid/selection-row-mode/selection-row-mode.ts

This *should* fix issues running tests. 

[WEB] Remove module.id from demo module

---

src/app/documentation/demos/alert/alerts.demo.ts
src/app/documentation/utils/disable-focus-trap.ts

[WEB] fix persisting focus on Modal and Wizard pages

---

src/app/tabs/tabs.demo.ts

[CORE] Fixes demo app fixed height issue

---

package.json

[CORE] Open browser automatically in dev mode

---

src/app/tooltips/tooltips-angular.html
src/clarity-angular/popover/common/popover-host-anchor.token.ts
src/clarity-angular/popover/dropdown/dropdown-menu.ts
src/clarity-angular/popover/dropdown/dropdown.ts
src/clarity-angular/popover/signpost/signpost-content.spec.ts
src/clarity-angular/popover/signpost/signpost-content.ts
src/clarity-angular/popover/signpost/signpost.ts
src/clarity-angular/popover/tooltip/tooltip-content.ts
src/clarity-angular/popover/tooltip/tooltip.ts

[NG] ng container bug fix for popovers

---

src/app/documentation/demos/vertical-nav/routes/collapsible-nav/collapsible-nav.ts

[WEB] Vertical Nav Code Snippet Fix

---

src/app/documentation/demos/signposts/signpost-positions.demo.html
src/app/documentation/demos/signposts/signpost-triggers.demo.ts
src/app/documentation/demos/signposts/signpost.demo.html

- Changes clrSignpostPosition to clrPosition to reflect the new API
- Closes #1654

[WEB] Update Signpost Documentation

---

src/clarity-icons/clarity-icons-element.ts
src/clarity-icons/clarity-icons.scss
src/clarity-icons/clarity-icons.spec.ts
src/clarity-icons/helpers.spec.ts
src/typings.d.ts

Tested on: Chrome, FF, Safari, Edge, IE 11

[ICONS] let users set custom title to icons

---

src/ks-app/src/app/app.component.html

[CORE] Fix Nav in KS App

---

src/clarity-angular/modal/modal.ts

Fix: A modal window takes place when it is in a hidden state #1622 #1648
Signed-off-by: Govinda Alwani <govi2010@gmail.com>

Fix: A modal window takes place when it is in a hidden state #1622 #1648

---

src/clarity-angular/emphasis/alert/providers/multi-alert-service.spec.ts
src/clarity-angular/emphasis/alert/providers/multi-alert-service.ts

[NG] Enable cycling of alerts

---

src/clarity-angular/emphasis/alert/alerts.ts

- fixes 1714
Signed-off-by: Brian Duncan <bduncan@vmware.com>

[NG] Set alerts container to display block

---

CONTRIBUTING.md

Signed-off-by: Brian Duncan <bduncan@vmware.com>

[CORE] Update contributing documentation

---

src/app/documentation/demos/themes/themes.demo.html

• I had some typos in there. Sorry.

Some edits to the themes dox

---

src/app/progress-bars/progress-bar-loop.html
src/clarity-angular/progress/progress-bars/_progress-bars.clarity.scss

[UI] fix looping progress bar color options

---

src/app/documentation/demos/datagrid/compact/compact.html
src/app/documentation/demos/datagrid/compact/compact.ts
src/app/documentation/demos/datagrid/datagrid.demo.html
src/app/documentation/demos/datagrid/datagrid.demo.module.ts
src/app/documentation/demos/datagrid/datagrid.demo.routing.ts
src/app/documentation/documentation-routing.module.ts

Compact Datagrid Documentation

---

src/clr-angular/utils/_theme.dark.clarity.scss

I'll merge this into the 0.10 branch once it is approved.
Fixes: #1763 

[UI] update dark theme tab border to Lilia’s color

---

src/clarity-angular/utils/_theme.dark.clarity.scss

[UI] update dark theme tab border to Lilia’s color - v0.10

---

.gitignore
package-lock.json
package.json

The README.md  is missing in the alpha and I added several dependencies that were causing warnings. I think they are related to the `ng-packagr` upgrade and the `@angular/cli` bump in the original scope changes pull request. 
I'll generate the beta packages after this is merged in. 
- Fixes the missing README in dist
- Installs several dev-dependencies needed for building and running

[CORE] Update dependencies and build

---

scripts/publish.js

Found this when releasing 0.11.0-beta.1.
This is the proper fix for it. 

[CORE] build: fixes publish command

---

src/clr-angular/data/datagrid/datagrid-pagination.ts
src/clr-angular/data/datagrid/providers/drag-dispatcher.ts
src/clr-angular/wizard/wizard.ts

Simple changes to guard against something not being fully initialized before being destroyed which can happen with SSR lifecycle.

[NG] more server rendering fixes

---

src/releases/0.11/0.11.0-beta.1.html

Fix module scope @ng/* -> @clr/*
Fixes #1828

[WEB] Fix v0.11.0-beta.1 release note

---

src/app/documentation/demos/vertical-nav/routes/collapsible-nav/collapsible-nav.html
src/app/documentation/demos/vertical-nav/routes/collapsible-nav/collapsible-nav.ts

[WEB] Vertical Nav Bottom Trigger Update

---

src/clr-angular/layout/_card.clarity.scss

Fix from https://github.com/vmware/clarity/pull/1858/

[UI] Clickable Cards Fix

---

src/clarity-icons/clarity-icons-api.ts
src/clarity-icons/clarity-icons-element.ts
src/clarity-icons/clarity-icons.spec.ts
src/clarity-icons/helpers.spec.ts
src/clarity-icons/index.ts
src/clarity-icons/interfaces/icon-interfaces.ts
src/clarity-icons/interfaces/icon-template.ts
src/clarity-icons/utils/shape-template-observer.ts
webpack.icons.config.js

API
- Backporting #1777 to v0.10

[ICONS] update the templates of icons in DOM if they are updated in the

---

src/clr-angular/progress/progress-bars/_progress-bars.clarity.scss

[UI] Exports Typo Fix

---

src/ks-app/.angular-cli.json
src/ks-app/src/app/app.component.ts
webpack.icons.config.js

[ICONS] include missing interface in the publishing config file

---

src/app/datagrid/hide-show-columns/hide-show.html
src/clarity-angular/data/datagrid/all.spec.ts
src/clarity-angular/data/datagrid/datagrid-column-toggle-button.spec.ts
src/clarity-angular/data/datagrid/datagrid-column-toggle-button.ts
src/clarity-angular/data/datagrid/datagrid-column-toggle-title.spec.ts
src/clarity-angular/data/datagrid/datagrid-column-toggle-title.ts
src/clarity-angular/data/datagrid/datagrid-column-toggle.spec.ts
src/clarity-angular/data/datagrid/datagrid-column-toggle.ts
src/clarity-angular/data/datagrid/datagrid-footer.spec.ts
src/clarity-angular/data/datagrid/datagrid-footer.ts
src/clarity-angular/data/datagrid/datagrid.ts
src/clarity-angular/data/datagrid/index.ts
src/clarity-angular/data/datagrid/providers/column-toggle-buttons.service.spec.ts
src/clarity-angular/data/datagrid/providers/column-toggle-buttons.service.ts

Same as #1861 for v0.10 branch

V0.10 dg column toogler i18n

---

src/clarity-icons/clarity-icons-element.ts
src/clarity-icons/clarity-icons.spec.ts

backport https://github.com/vmware/clarity/pull/1961 to v0.10

[ICONS] fix unsubscription in Clarity Icon (v0.10 backport)

---

package-lock.json
package.json

Hi all, Hi @hippee-lee,
FYI, letting you know that ng-packagr is now v2 stable. Crossing fingers it's still working for you!

[NG] Update Build to ng-packagr 2.0.0 (latest, stable)

---

src/clarity-angular/utils/_theme.dark.clarity.scss

fix: [UI] Dark theme .btn font color (#1990)

---

src/clr-angular/data/datagrid/datagrid-row-detail.ts

[NG] Unsubscribe from datagrid cell changes sub

---

src/clr-angular/data/datagrid/providers/selection.spec.ts
src/clr-angular/data/datagrid/providers/selection.ts

[NG] Datagrid Selection Bug Fix

---

src/clr-angular/utils/drag-and-drop/all.spec.ts
src/clr-angular/utils/drag-and-drop/drag-and-drop.module.ts
src/clr-angular/utils/drag-and-drop/interfaces/drag-event.ts
src/clr-angular/utils/drag-and-drop/providers/drag-and-drop-event-bus.spec.ts
src/clr-angular/utils/drag-and-drop/providers/drag-and-drop-event-bus.ts

- setup DnD module
- Implemented a service class for Drag and Drop Event Bus.
- Tested the Drag and Drop Event Bus service class.
UML Reference: 
[dnd-UML-class-diagram.pdf](https://github.com/vmware/clarity/files/1826687/dnd-UML-class-diagram.pdf)

[WIP | NG] Drag and Drop - create module with event bus

---

src/app/datepicker/datepicker-KKJ.ts
src/app/datepicker/datepicker-hr.ts
src/app/datepicker/datepicker-locale-data.ts
src/app/datepicker/datepicker.demo.html
src/app/datepicker/datepicker.demo.module.ts
src/app/datepicker/datepicker.demo.routing.ts
src/app/datepicker/datepicker.demo.ts
src/clr-angular/forms/datepicker/_datepicker.clarity.scss
src/clr-angular/forms/datepicker/date-input.spec.ts
src/clr-angular/forms/datepicker/providers/date-io.service.spec.ts
src/clr-angular/forms/datepicker/providers/date-io.service.ts
src/clr-angular/forms/datepicker/utils/constants.ts

Fixes: #2055
https://github.com/angular/angular/blob/master/packages/common/locales/de.ts
https://github.com/angular/angular/blob/master/packages/common/locales/kkj.ts
https://github.com/angular/angular/blob/master/packages/common/locales/hr.ts
https://github.com/angular/angular/blob/master/packages/common/locales/ar.ts

[NG] CLDR Delimiter Support

---

src/clr-angular/emphasis/alert/alerts.spec.ts
src/clr-angular/emphasis/alert/alerts.ts

Fixes: #2119
Signed-off-by: Gerin Jacob <gerinjacob@gmail.com>

[NG] Bug fix for ClrAlerts

---

src/clr-angular/data/datagrid/_datagrid.clarity.scss
src/clr-angular/data/datagrid/_variables.datagrid.scss
src/clr-angular/utils/_theme.dark.clarity.scss

fix: Dark Theme - Adds variable for datagrid selected row color

---

src/clr-angular/utils/drag-and-drop/all.spec.ts
src/clr-angular/utils/drag-and-drop/interfaces/drag-event.ts
src/clr-angular/utils/drag-and-drop/providers/drag-and-drop-event-bus.spec.ts
src/clr-angular/utils/drag-and-drop/providers/drag-and-drop-event-bus.ts
src/clr-angular/utils/drag-and-drop/providers/drag-event-listener.spec.ts
src/clr-angular/utils/drag-and-drop/providers/drag-event-listener.ts

[WIP | NG] ClrDragEventListener implementation

---

src/clr-angular/data/_tables.clarity.scss

- Adds the themeable variable into scss for .table-noborder header bottom border

[UI] fix: dark theme

---

packages/schematics/src/add/index.ts

There are path changes in the latest CLI config files.

[SCHEMATICS] update paths for new builds

---

src/clr-angular/layout/tabs/tab-link.directive.ts
src/clr-angular/layout/tabs/tabs.ts

[NG] Add tab link type attribute.

---

src/clr-angular/layout/main-container/_variables.header.scss

closes #2227
Signed-off-by: Jewway <jewway@gmail.com>

[U] fix layout main-container variable missed semicolon (#2227)

---

CODING_GUIDELINES.md

- Do not name your methods `onClick()`, `onHover()`, etc.
- Use only the component you are currently testing.

[CORE] Additional coding guidelines

---

src/clr-angular/forms/select/_select-angular.clarity.scss
src/clr-angular/forms/select/all.spec.ts
src/clr-angular/forms/select/index.ts
src/clr-angular/forms/select/option.html
src/clr-angular/forms/select/option.spec.ts
src/clr-angular/forms/select/option.ts
src/clr-angular/forms/select/options.spec.ts
src/clr-angular/forms/select/select.module.ts
src/clr-angular/popover/dropdown/_dropdown.clarity.scss
src/clr-angular/popover/dropdown/_menu-mixins.clarity.scss
src/clr-angular/popover/dropdown/_variables.dropdown.scss
src/dev/src/app/selects/basic-ng-select.html

PR Scope:
1. Create `clr-option` component.
2. Style `clr-option` component.
3. Tests

[UI, NG] Select Option Component

---

npm/clr-angular/package.json
package.json
scripts/write-svg-icons.js
src/clr-angular/ng-package.json
src/clr-angular/package.json
webpack.icons.config.js

Some tweaks necessary for building and publishing.
* Schematics have to be built after Angular
* Fix icons build UMD to be same as it is today
* Remove unnecessary dependencies in Angular package

[CORE] Build tweaks for proper publishing

---

src/clr-angular/button/button-loading/loading-button.ts
src/ks-app/src/app/containers/buttons/buttons.component.html
src/ks-app/src/app/containers/buttons/buttons.component.ts

- Added demo/usage to ks-app for aot check
- fixes #2302

fix: [NG] Adds correct import for loading-button

---

src/clr-angular/code/code.module.ts
src/clr-angular/code/syntax-highlight/_code.clarity.scss
src/clr-angular/code/syntax-highlight/syntax-highlight.module.ts
src/clr-angular/code/syntax-highlight/syntax-highlight.spec.ts
src/clr-angular/code/syntax-highlight/syntax-highlight.ts
src/dev/src/app/_utils/code-example.ts
src/dev/src/app/_utils/code.scss
src/dev/src/app/code/code-highlight-imports.html
src/dev/src/app/code/code-highlight-imports.ts
src/dev/src/app/code/code-highlight-snippet.html
src/dev/src/app/code/code-highlight-snippet.ts
src/dev/src/app/code/code-highlight.demo.module.ts
src/dev/src/app/code/code-highlight.demo.routing.ts
src/dev/src/app/code/code-highlight.demo.scss
src/dev/src/app/code/code-highlight.demo.ts
src/dev/src/app/datagrid/utils/example.ts
src/dev/src/app/forms-deprecated/utils/example.ts
src/dev/src/app/tree-view/utils/example.ts
src/ks-app/src/app/containers/code/code-snippet.component.ts
src/ks-app/src/app/containers/code/code.component.html
src/ks-app/src/app/containers/code/code.component.ts

[core] deprecate code highlight (#2125)

---

src/clr-angular/modal/_modal.clarity.scss
src/clr-angular/modal/modal.html
src/clr-angular/modal/utils/ghost-page-animations.ts
src/clr-angular/utils/_theme.dark.clarity.scss
src/clr-angular/wizard/_variables.wizard.scss
src/clr-angular/wizard/_wizard.clarity.scss
src/clr-angular/wizard/providers/wizard-navigation.service.ts
src/clr-angular/wizard/wizard.html
src/clr-angular/wizard/wizard.ts

[core] deprecate wizard ghost pages (#2151)

---

.travis.yml
package-lock.json
package.json
scripts/travis.js

The daily testing has been maintained as a separate repo under my account, which keeps causing issues with merge conflicts. So this is a script that travis will run to determine if it is running a daily cron job on master and pull latest commits for Angular dependencies to test against latest Clarity.
This is our first line of defense against unexpected breaking changes in Angular.
When Travis runs, it sets a number of ENV variables, so it is checking for the TRAVIS_EVENT_TYPE (which should be `cron` for a cron job) and TRAVIS_BRANCH (which will be `master`) for the configured tests to run. Otherwise, it just runs the tests like usual.

[CORE] setup daily cron job in main clarity repo

---

src/clr-angular/data/datagrid/datagrid.spec.ts
src/clr-angular/data/datagrid/datagrid.ts
src/clr-angular/data/datagrid/providers/selection.spec.ts
src/clr-angular/data/datagrid/providers/selection.ts
src/dev/src/app/datagrid/full/full.html
src/dev/src/app/datagrid/full/full.ts

[ng] Clean up datagrid selection preservation (#2038)

---

src/dev/src/app/login/login.demo.html
src/ks-app/src/app/containers/login/login.component.html

See discussion in  #2367
This commit replaces `label` element, which purpose is to be used with interactive form elements, with `section` regular flow element (which can have headings, etc).
Thanks!

[WEB] Use section element in login component and docs

---

package-lock.json
package.json
src/clr-angular/forms/common/index.ts
src/clr-angular/forms/index.ts
src/clr-angular/package.json
src/ks-app/src/app/containers/forms/forms.component.ts

Somehow I missed a few exports to the public API, so added all new components/directives to ks-app to catch the error properly and fix it up.

[NG] fix forms exports

---

src/clr-angular/data/stack-view/stack-block.ts

Had a `private` variable used in the HTML template. Made that public

[NG] Stack View AOT Fix

---

latest/src/app/documentation/demos/color/color-palette-functional.demo.html
latest/src/app/documentation/demos/color/color-palette-functional.demo.scss
latest/src/app/documentation/demos/color/color-palette-functional.ts
latest/src/app/documentation/demos/color/color.demo.html
latest/src/app/documentation/demos/color/color.demo.module.ts

[WEB] Light and dark theme colors documentation

---

src/clr-angular/utils/conditional/if-active.directive.spec.ts
src/clr-angular/utils/conditional/if-active.directive.ts
src/clr-angular/utils/conditional/if-open.directive.spec.ts
src/clr-angular/utils/conditional/if-open.directive.ts
src/clr-angular/utils/conditional/index.ts
src/clr-angular/utils/expand/if-expanded.spec.ts
src/clr-angular/utils/expand/if-expanded.ts
src/clr-angular/utils/expand/index.ts
src/clr-angular/utils/index.ts

[NG] Export Conditional and Expand Directives

---

.travis.yml

This will fix the slack #clarity-build notifications for the Travis integration. 

fix(CORE): Update travis secure token and fix slack integration.

---

src/clr-angular/data/tree-view/tree-node.html
src/clr-angular/data/tree-view/tree-node.spec.ts
src/clr-angular/data/tree-view/tree-node.ts

Fixes: #2358
Reference: https://www.w3.org/TR/wai-aria-practices-1.1/#TreeView
Added ARIA attributes to the TreeView component.

[NG] ARIA attributes for TreeView

---

.github/ISSUE_TEMPLATE.md
README.md
golden/clr-angular.d.ts

[DOX] Adding v0.12 stack blitz links to readme

---

latest/src/app/documentation/demos/alert/alerts.demo.html
latest/src/app/documentation/demos/datagrid/expandable-rows/examples.ts
latest/src/app/documentation/demos/datagrid/expandable-rows/expandable-rows.html
latest/src/app/documentation/demos/grid/grid-items-horizontal-alignment.ts
latest/src/app/documentation/demos/input/ng/helpers.html
latest/src/app/documentation/get-started/get-started.component.html
latest/src/app/documentation/get-started/get-started.component.ts

Small changes for a few typos, omissions, and clarifications.
fixes #2450 #2506 #2475 #2483 #2389

A set of website fixes

---

latest/src/app/documentation/demos/forms/ng/errors.html

Fix the example for multiple validators
Closes: #2538

[WEB] Fix wrong example for from validation

---

latest/src/app/documentation/demos/datagrid/batch-action/batch-action.html
latest/src/app/documentation/demos/datagrid/batch-action/batch-action.ts
v0.11/package-lock.json

[web] updating dox on datagrid batch action to include export (#2286)

---

src/clr-angular/data/datagrid/datagrid-column-toggle-button.spec.ts
src/clr-angular/data/datagrid/datagrid-column-toggle-button.ts
src/clr-angular/data/datagrid/datagrid-column-toggle.spec.ts
src/clr-angular/data/datagrid/datagrid-column-toggle.ts
src/clr-angular/data/datagrid/providers/column-toggle-buttons.service.spec.ts
src/clr-angular/data/datagrid/providers/column-toggle-buttons.service.ts
src/dev/src/app/datagrid/hide-show-columns/hide-show.html

[ng] Remove OK/Apply button from column hide/show panel in datagrid

---

src/clr-angular/layout/nav/_header.clarity.scss

hover styles for enabled nav buttons only & disabled button cursor style
Signed-off-by: KingMario<gcyyq@hotmail.com>

hover styles for enabled nav buttons only & disabled button cursor style

---

latest/src/styles/global.scss

[Website] Fix stylesheet typo

---

src/clr-angular/data/datagrid/_datagrid.clarity.scss

[UI] Fix ClrDatagrid loading spinner when grid is in a ClrStackView

---

src/schematics/src/update/update-0.13.0.ts

[NG] Schematics update for using bootstrap's push / pull in Clarity grid

---

src/schematics/src/update/update-0.13.0.ts

[NG] Schematics update for using clrType (datagrid show/hide column)

---

latest/src/app/community/community.component.html

[web] updating open jobs for clarity

---

latest/src/app/documentation/demos/datagrid/hide-show-columns/hide-show-columns.html
latest/src/app/documentation/demos/datagrid/hide-show-columns/hide-show-columns.ts
latest/src/app/documentation/demos/datagrid/server-driven/examples.ts

[web] updating 0.13 code examples

---

latest/src/app/utils/utils.module.ts

Correctly export CodeHighlight from UtilsModule

---

src/clr-angular/emphasis/alert/_alert.clarity.scss

Signed-off-by: Abhishek Srivastava <nit.abhi85@gmail.com>

Adding left margin to alert-actions for smaller screens as rem

---

src/clr-angular/utils/_theme.dark.clarity.scss

[UI] fix(theme): Adds Dark Theme overrides for form elements

---

latest/src/app/documentation/demos/datagrid/single-selection/single-selection.html

[Docs] Warn against full-row click

---

latest/src/app/documentation/demos/modal/modal.demo.html

Add missing option in the `Summary of Options` section

[WEB] Add 'xl' value in the modal page in summary section

---

golden/clr-angular.d.ts
src/clr-angular/data/datagrid/datagrid-hideable-column.spec.ts
src/clr-angular/data/datagrid/datagrid-hideable-column.ts

Signed-off-by: Wallabeng <marcel@ring-mail.at>

Add two-way binding to ClrDatagridHideableColumn

---

latest/src/app/documentation/demos/progress-bars/progress-bars.demo.module.ts
v0.13/src/app/documentation/demos/progress-bars/progress-bars.demo.module.ts

Re-created #2795 because I messed up branch with rebase

[WEB] fix code highlight for progress bar demo

---

.github/ISSUE_TEMPLATE/icon-request.md

@colinreedmiller Here is that icon template for you, made a few tweaks if you don't mind.
closes #2796

[CORE] add icon request github template

---

latest/src/app/documentation/demos/color/color-palette-functional.ts
latest/src/app/documentation/demos/color/color-palette.ts
latest/src/app/documentation/demos/color/color.demo.html
latest/src/app/documentation/demos/color/color.demo.scss
v0.13/src/app/documentation/demos/color/color-palette-functional.ts
v0.13/src/app/documentation/demos/color/color-palette.ts
v0.13/src/app/documentation/demos/color/color.demo.html
v0.13/src/app/documentation/demos/color/color.demo.scss

Changes in global and functional palettes, merged from both issues.
Improvement in dark/light theme tab labels layout.

[WEB] Updated color palette for improved accessibility (#2535, #2784)

---

src/clr-angular/forms/common/providers/layout.service.ts

closes #2835
Signed-off-by: Gerd Jungbluth <gerd.jungbluth@engawa.de>

[NG]: remove unnecessary console log

---

src/ks-app/src/app/containers/progress/progress-bars.component.html

Added unique names to [SHOW] buttons and sidebar links.

A11y fixes - add unique names to items

---

CONTRIBUTING.md

Also updated the links to the StackBlitz templates, which were only for 0.10, 0.11

[DOCS] Design Contribution Guidelines update (#2893)

---

latest/src/app/documentation/demos/input/input.demo.html
latest/src/app/documentation/demos/password/password.demo.html
latest/src/app/documentation/demos/textarea/textarea.demo.html

[WEB] Fix links to "forms"

---

package.json
src/ks-app/src/app/containers/nav/tabs.component.html
src/ks-app/src/app/containers/popover/signposts.component.html
src/ks-app/src/app/containers/popover/tooltips.component.html
src/ks-app/src/app/containers/wizard/wizards.component.html

Badly named links, missing label-for attribs, missing aria attributes.

[KS-APP] A11Y issues (#1931, #1933, #1917)

---

src/clr-angular/data/datagrid/_datagrid.clarity.scss
src/clr-angular/utils/_layers.clarity.scss

z-index added for column switch

[NG] Data grid header overlaps column switch popup (#2915)

---

src/ks-app/src/app/containers/forms/radios.component.html

Missing clr-radio-wrapper. Added headers for better readability.

[KS-APP] Radios not rendering (#2912)

---

src/clr-angular/data/datagrid/_datagrid.clarity.scss
src/clr-angular/data/datagrid/datagrid.html
src/clr-angular/data/datagrid/datagrid.spec.ts
src/clr-angular/data/datagrid/enums/render-step.enum.ts
src/clr-angular/data/datagrid/providers/table-size.service.spec.ts
src/clr-angular/data/datagrid/providers/table-size.service.ts
src/clr-angular/data/datagrid/render/render-organizer.spec.ts
src/clr-angular/data/datagrid/render/render-organizer.ts
src/clr-angular/utils/_components.clarity.scss

[NG] fix(datagrid): Removes width calculation from datagrid render cycle

---

latest/src/app/documentation/demos/checkboxes/checkboxes.demo.html

This is the same issue found in #2811 but for a different page

[WEB] fix demo page for checkboxes

---

src/clr-angular/data/datagrid/all.spec.ts
src/clr-angular/data/datagrid/datagrid-column-separator.spec.ts
src/clr-angular/data/datagrid/providers/column-resizer.service.spec.ts
src/clr-angular/data/datagrid/providers/table-size.service.mock.ts
src/clr-angular/data/datagrid/render/header-renderer.spec.ts
src/clr-angular/data/datagrid/render/header-renderer.ts

[NG] tests are added and updated

---

src/clr-angular/data/datagrid/_datagrid.clarity.scss

add back pagination separator

---

src/clr-angular/forms/datepicker/datepicker.module.ts

fix import path in datepicker module

---

src/website/src/app/documentation/demos/checkboxes/checkboxes.demo.html
src/website/src/app/documentation/demos/lists/old-lists-in-cards.html
src/website/src/app/documentation/demos/progress-bars/progress-bar-cards.html
src/website/src/app/documentation/demos/progress-bars/progress-bar-static-cards.html
src/website/src/releases/1.0/1.0.2.html
src/website/src/releases/1.0/1.0.3-patch.html
src/website/src/releases/1.0/1.0.3.html
src/website/src/releases/release-list.json
src/website/src/releases/release-template-stub.json

This updates the website project with the latest changes from the website branch. It should also fix the netlify build errors.

Sync website with latest

---

src/website/src/app/documentation/demos/checkboxes/checkboxes.demo.html
src/website/src/app/documentation/demos/lists/old-lists-in-cards.html
src/website/src/app/documentation/demos/progress-bars/progress-bar-cards.html
src/website/src/app/documentation/demos/progress-bars/progress-bar-static-cards.html
src/website/src/app/documentation/get-started/get-started.component.html
src/website/src/community/contributors.json
src/website/src/releases/1.0/1.0.2.html
src/website/src/releases/1.0/1.0.3-patch.html
src/website/src/releases/1.0/1.0.3.html
src/website/src/releases/release-list.json
src/website/src/releases/release-template-stub.json

sync website before cutover

---

src/website/src/app/documentation/demos/checkboxes/checkboxes.demo.html
src/website/src/app/documentation/demos/checkboxes/checkboxes.demo.ts
src/website/src/app/documentation/demos/checkboxes/ng/disabled.html
src/website/src/app/documentation/demos/checkboxes/ng/indeterminate.html
src/website/src/app/documentation/demos/checkboxes/ui/disabled.html
src/website/src/app/documentation/demos/datagrid/datagrid.demo.html
src/website/src/app/documentation/demos/radio/ng/disabled.html
src/website/src/app/documentation/demos/radio/radio.demo.html
src/website/src/app/documentation/demos/radio/radio.demo.ts
src/website/src/app/documentation/demos/radio/ui/disabled.html

update radio and checkbox documentation for disabled and indeterminate states

---

src/website/generate-news.js
src/website/src/settings/versions.json
src/website/src/sitemap.xml

[DOCS] fix: Adds the correct base url for generating the website.

---

src/website/src/app/app-routing.module.ts
src/website/src/app/icons/icons.component.html

Also added redirect to make sure that old links and links from old
docs redirects based on GH are still resolved.

[WEB] Updated icons/get-started link (#3042)

---

src/website/src/sitemap.xml

[WEB] Updated icons/get-started link (2) (#3042)

---

src/website/src/app/documentation/demos/button-group/button-group.demo.html

Signed-off-by: 0xflotus <0xflotus@gmail.com>

fixed below

---

README.md
package.json
src/website/src/community/contributors.json

This cleans up a couple questions from the README that were reported, and fixes the function deployment. It also adds a new contributor that was just merged.

[web] run functions properly and update readme

---

scripts/write-svg-icons.js
src/clr-angular/wizard/providers/wizard-navigation.service.ts
src/clr-icons/clr-icons-api.ts
src/website/typings.d.ts

Hello there. I was reviewing your project and I found some [alerts on LGTM.com](https://lgtm.com/projects/g/vmware/clarity/alerts/?mode=tree). This may not be the type of contribution you normally receive, but I figured I could help clean up the codebase.
(Full disclosure: I'm part of the team behind LGTM.com)
Let me know if you have any questions.

Fixed some LGTM alerts

---

src/website/src/app/documentation/demos/tree-view/tree-view.demo.html

Finally done, it took me the whole week to get it right.

[DOCS] Missing link in Tree View documentation

---

golden/clr-angular.d.ts
src/clr-angular/data/datagrid/built-in/filters/datagrid-string-filter-impl.spec.ts
src/clr-angular/data/datagrid/built-in/filters/datagrid-string-filter-impl.ts
src/clr-angular/data/datagrid/datagrid-filter.spec.ts
src/clr-angular/data/datagrid/datagrid.spec.ts
src/clr-angular/data/datagrid/interfaces/filter.interface.ts
src/clr-angular/data/datagrid/interfaces/state.interface.ts
src/clr-angular/data/datagrid/providers/state.provider.ts
src/website/src/app/documentation/demos/datagrid/filtering/examples.ts
src/website/src/app/documentation/demos/datagrid/server-driven/examples.ts
src/website/src/app/documentation/demos/datagrid/server-driven/server-driven.html

Also exposed an "equals" method, for future needs.

[NG] Expose a "state" property on custom filters (#2846)

---

scripts/write-svg-icons.js
src/clr-angular/wizard/providers/page-collection.service.ts
src/clr-angular/wizard/providers/wizard-navigation.service.ts
src/clr-icons/clr-icons-api.ts
src/dev/src/app/vertical-nav/routing/vertical-nav-routing.demo.html
src/dev/src/app/vertical-nav/unstructured-routes/unstructured-routes.html
src/ks-app/src/app/containers/login/login.component.ts
src/ks-app/src/app/containers/nav/vertical-nav.component.html
src/website/typings.d.ts

Hi again! I am fixing the remaining alerts from [LGTM.com](https://lgtm.com/projects/g/vmware/clarity/alerts/?mode=tree), including adding a .lgtm.yml file to filter out certain unnecessary queries for your project. Let me know what you think.

Fixing remaining LGTM alerts

---

src/clr-angular/utils/_helpers.clarity.scss

Fixes missing pointer style for data grid actions.
closes #3065

[NG] fix missing pointer style

---

src/clr-angular/utils/_helpers.clarity.scss

Fixes missing pointer style for data grid actions.
closes #3065

[NG] fix missing pointer style (#3133)

---

src/website/src/app/documentation/demos/modal/modal-animation-design.demo.html

The modal body text had permanent misspelled.

Correct typo in modal body

---

src/clr-angular/forms/password/password-container.spec.ts
src/clr-angular/forms/password/password-container.ts
src/clr-angular/forms/styles/_input-group.clarity.scss
src/dev/src/app/forms/input-group/input-group.html
src/dev/src/app/forms/input-group/input-group.ts

Make show/hide icon button/focusable
closes #3122

[NG] fix a11y issue password input

---

src/clr-angular/forms/password/password-container.spec.ts
src/clr-angular/forms/password/password-container.ts
src/clr-angular/forms/styles/_input-group.clarity.scss
src/dev/src/app/forms/input-group/input-group.html
src/dev/src/app/forms/input-group/input-group.ts

* [NG] fix a11y issue password input
Make show/hide icon button/focusable
closes #3122

[NG] fix a11y issue password input (#3135)

---

golden/clr-angular.d.ts
src/clr-angular/button/button-group/button.spec.ts
src/clr-angular/button/button-group/button.ts

Properly set title attribute for button in button group.
closes #3132

[NG] fix button title for button group

---

src/website/src/app/documentation/demos/wizard/wizard.demo.html

This fix #3127 needed to be fixed.

website fix for wizard page not compiling

---

src/clr-angular/data/datagrid/datagrid-pagination.spec.ts
src/clr-angular/data/datagrid/datagrid-pagination.ts

Button with incorrect type caused form submit events if nested in a form
closes #3160

[NG] fix button issue for datagrid pagination

---

src/website/src/app/icons/icons-get-started/icons-get-started.component.html
src/website/src/app/icons/icons-get-started/icons-get-started.component.ts

[web] removed no longer valid documentation part in icons get started

---

src/clr-angular/data/datagrid/all.spec.ts
src/clr-angular/data/datagrid/providers/column-state.provider.ts
src/clr-angular/data/datagrid/render/header-renderer.spec.ts
src/clr-angular/data/datagrid/render/header-renderer.ts
src/clr-angular/data/datagrid/render/main-renderer.spec.ts
src/clr-angular/data/datagrid/render/main-renderer.ts
src/clr-angular/data/datagrid/render/row-renderer.spec.ts
src/clr-angular/data/datagrid/render/row-renderer.ts

[NG] column state provider is injected

---

src/website/src/app/documentation/demos/typography/typography.demo.html

This should fix the website build on netlify.

[WEBSITE] fix(docs): Adds a closing div for the typography page. 

---

src/website/src/app/news/news.component.ts

closes #3233
In some browsers the version order on the news page was incorrect.

[WEBSITE] fix version order on news page

---

src/clr-angular/data/datagrid/_datagrid.clarity.scss
src/dev/src/app/datagrid/kitchen-sink/kitchen-sink.html

Adds additional CSS to align an inline toggle input in the datagrid row.
closes #1775

[NG] support inline toggle input in datagrid row

---

src/website/src/app/news/news.component.ts

Fixes order for pre 1.x versions on news page.
closes #3233

[WEBSITE] fix order of pre 1.x versions

---

src/website/src/app/app.component.html
src/website/src/app/home/home.component.html
src/website/src/app/home/home.component.ts
src/website/src/app/utils/external-link.directive.ts
src/website/src/environments/environment.prod.ts
src/website/src/settings/versions.json

Sets the default website docs to v1 branch and makes master v2.

enable documentation to switch versions based on what is latest

---

src/clr-angular/layout/nav/providers/responsive-navigation.service.spec.ts
src/clr-angular/layout/nav/providers/responsive-navigation.service.ts

Fixes menu button missing if header was added dynamically to the page.
closes #3254

[NG] fix header nav menu button

---

src/clr-angular/forms/datepicker/date-input.spec.ts
src/clr-angular/forms/datepicker/providers/date-navigation.service.ts

fixes issue of value not being selectable after deleting input text
closes #3290

[NG] fix datepicker value bug

---

src/clr-angular/data/datagrid/built-in/filters/datagrid-string-filter.ts
src/dev/src/app/datagrid/full/full.html
src/dev/src/app/datagrid/kitchen-sink/kitchen-sink.ts
src/dev/src/app/popovers/dummy-anchor.ts

- Fixes style issue with datagrid filter inputs.
- Fixes various AOT/style bugs in dev app
closes #3311

[NG] datagrid style fix, dev app fixes

---

src/website/src/settings/versions.json

website: Adds link to v2.0 documentation.

---

src/website/src/app/documentation/demos/themes/themes.demo.html
src/website/src/app/documentation/demos/themes/themes.demo.ts

docs(themes): Updates custom theme configuration examples.

---

README.md

[CORE] fix: Updates readme badges for travis migration.

---

src/website/src/app/documentation/demos/toggles/toggles.demo.html

[DOCS] fix(v1): Corrects a typo in the docs

---

src/clr-angular/utils/_a11y.clarity.scss
src/clr-angular/utils/_components.clarity.scss
src/website/src/app/app.component.html
src/website/src/app/app.component.ts
src/website/src/app/app.module.ts
src/website/src/app/utils/skip-link.component.scss
src/website/src/app/utils/skip-link.component.ts
src/website/src/styles/global.scss

Update documentation to have a skip link shortcut for better a11y.

[WEBSITE] skip link a11y

---

src/website/src/app/documentation/demos/toggles/toggles.demo.html

[DOCS] fix(latest): Corrects a typo in the docs.

---

.compodocrc.json
netlify.toml
package-lock.json
package.json
tsconfig.api-docs.json

This uses [compodoc](https://compodoc.app/) to generate an automatic API documentation. This is to prove it out and we'll need some work to figure out details and verify it before we link to it as an official resource.

Create an API docs page, generated automatically

---

golden/clr-angular.d.ts
src/clr-angular/data/datagrid/datagrid-column.spec.ts
src/clr-angular/data/datagrid/datagrid-column.ts
src/clr-angular/utils/i18n/common-strings.interface.ts
src/clr-angular/utils/i18n/common-strings.service.ts

[NG] Adding aria-label to clr-dg-column button into V1 version.

---

CONTRIBUTING.md
src/website/src/releases/2.x/2.0.0.html

I'm not sure about the change in package-lock.json but if I'm right it should report the right version

[WEB] fix typos in CONTRIBUTING and Release Note

---

src/website/src/app/documentation/demos/buttons/buttons.demo.html
src/website/src/app/documentation/demos/buttons/icon-buttons.html
src/website/src/app/documentation/demos/buttons/icon-buttons.ts
src/website/src/app/documentation/demos/forms/forms.demo.html

Multiple minor improvements with the documentation and a11y.
closes #3188 
closes #3181

[WEBSITE] a11y fixes

---

src/website/src/app/home/home.component.html

This adds a badge to the site to support Netlify, in thanks for their free account services as an open source project.

add netlify badge

---

src/clr-angular/modal/modal.html
src/clr-angular/modal/modal.spec.ts

Adding `aria-label` to the close button on top of the modal header.

Backport: Issue 3413

---

src/clr-angular/popover/dropdown/dropdown-item.spec.ts
src/clr-angular/popover/dropdown/dropdown-item.ts
src/clr-angular/popover/dropdown/providers/dropdown-focus-handler.service.ts
src/clr-angular/popover/dropdown/providers/dropdown-focus-handler.spec.ts
src/clr-angular/utils/focus/focus.service.spec.ts
src/clr-angular/utils/focus/focus.service.ts
src/dev/src/app/dropdown/dropdown-angular-nested.demo.html
src/dev/src/app/dropdown/dropdown-angular-positioning.demo.html
src/website/src/app/documentation/demos/dropdown/dropdown-angular-close-item-false.ts
src/website/src/app/documentation/demos/dropdown/dropdown-angular-positioning.ts
src/website/src/app/documentation/demos/dropdown/dropdown-static-buttonlink-toggle.ts
src/website/src/app/documentation/demos/dropdown/dropdown-static-default.ts
src/website/src/app/documentation/demos/dropdown/dropdown-static-fontawesome-toggle.ts
src/website/src/app/documentation/demos/dropdown/dropdown-static-icon-toggle.ts
src/website/src/app/documentation/demos/dropdown/dropdown-static-positioning.ts

This PR is identical to https://github.com/vmware/clarity/pull/3440, which was stuck with netlify branch protection that was out of sync.

[ng] more a11y for dropdown menu + fix bug on arrow up/down key on trigger

---

golden/clr-angular.d.ts
src/clr-angular/data/datagrid/datagrid-column-toggle.spec.ts
src/clr-angular/data/datagrid/datagrid-column-toggle.ts

* adding aria-controls to toggleButton
* adding aria-label to the close button

[NG] Update button labels for datagrid-column-toggle

---

src/website/src/environments/environment.prod.ts
src/website/src/releases/2.x/2.0.0.html

- updated url to sketch 2.0.0 (closes #3491)
- fixed figma urls in 2.0.0 release notes (closes #3451)

[WEBSITE] fixes resource links

---

golden/clr-angular.d.ts
src/clr-angular/data/datagrid/datagrid-action-overflow.spec.ts
src/clr-angular/data/datagrid/datagrid-action-overflow.ts
src/clr-angular/data/datagrid/datagrid-filter.spec.ts
src/clr-angular/data/datagrid/datagrid-filter.ts
src/clr-angular/data/datagrid/datagrid.html
src/clr-angular/data/datagrid/datagrid.ts

* Page count select focus management
* Pagination focus management
* Filter focus and action overflow 1st item focus
* Hideable columns select/all
(cherry picked from commit 0dc08f9fced04c705f6bf8fd99f49c7a9c7daad7)

Backport to V1: Datagrid focus management (#3370) (#3481)

---

src/website/src/releases/1.x/1.1.5.html
src/website/src/releases/2.x/2.0.2.html
src/website/src/releases/release-list.json
src/website/src/releases/release-template-stub.json
src/website/src/sitemap.xml

[WEBSITE] Release notes for v2.0.2 and v1.1.5

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
commitlint.config.js
package-lock.json
package.json

Added PR template for github. Copied from the Angular repo with little modification. Any suggestions/discussion is appreciated.

chore: add github PR template

---

src/clr-icons/clr-icons-element.ts
src/clr-icons/clr-icons.spec.ts
src/website/src/app/documentation/demos/button-group/button-group.demo.html
src/website/src/app/documentation/demos/button-group/button-group.demo.ts
src/website/src/app/documentation/demos/buttons/buttons.demo.html

Backport PR #3555 to V1 
Close #3530

Backport Icons in buttons need accessible names 3530

---

src/clr-angular/data/datagrid/datagrid-hideable-column.spec.ts
src/clr-angular/data/datagrid/datagrid-hideable-column.ts
src/dev/src/app/datagrid/hide-show-columns/hide-show.html
src/dev/src/app/datagrid/hide-show-columns/hide-show.ts

Users currently cannot set Datagrid Column's `hidden` state via `clrDgHidden` and `clrDgHideableColumn` inputs.
Issue Number: closes #3545 
Users can now set Datagrid Column's `hidden` state via `clrDgHidden` and `clrDgHideableColumn` inputs. 

fix(datagrid): input on hideable column

---

src/dev/src/app/login/login.demo.html
src/website/src/app/documentation/demos/login/login-example.demo.html
src/website/src/app/documentation/demos/login/login-example.demo.ts
src/website/src/app/documentation/demos/login/login.demo.html

Also updated to use alerts, since those will announce when errors are triggered.
closes #3522

fix(login) the login screen was missing labels for form fields

---

golden/clr-angular.d.ts
src/clr-angular/accordion/accordion-panel.html
src/clr-angular/accordion/accordion-panel.spec.ts
src/clr-angular/accordion/accordion-panel.ts
src/clr-angular/accordion/stepper/models/stepper.model.ts
src/clr-angular/accordion/stepper/providers/stepper.service.spec.ts
src/clr-angular/accordion/stepper/providers/stepper.service.ts
src/clr-angular/accordion/stepper/stepper-panel.spec.ts
src/clr-angular/accordion/stepper/stepper-panel.ts

When navigating between steps using the next button the focus was not set on the next step heading button.
https://github.com/vmware/clarity/issues/3528
When the user clicks next on a valid step the next step is automatically focused.

fix: focus management for stepper

---

src/clr-icons/clr-icons-element.ts
src/clr-icons/clr-icons.spec.ts
src/dev/src/app/iconography/icon-selection.demo.html

Issue Number: https://github.com/vmware/clarity/issues/3683

fix(a11y): only set default icon role if it has no role defined by user

---

src/clr-angular/accordion/_accordion.clarity.scss

fix(accordion): remove rounded corners when last panel is open

---

src/website/src/app/documentation/demos/dropdown/dropdown.demo.html

Adding more detailed documentation regarding disabled items in dropdown.

docs(a11y): adding more detailed documentation on dropdown a11y

---

src/website/src/app/documentation/demos/header/header-links.demo.html
src/website/src/app/documentation/demos/header/header-links.ts
src/website/src/app/documentation/demos/header/header-types.demo.html
src/website/src/app/documentation/demos/header/header-types.ts
src/website/src/app/documentation/demos/header/header.demo.html
src/website/src/app/documentation/demos/header/sub-nav.demo.html

Header documentation was missing `aria-label` for icons
Issue Number: #3518 
**Need to be backported to V1**

docs(header): header have buttons without accessible names #3518

---

golden/clr-angular.d.ts
src/clr-angular/forms/datepicker/date-container.spec.ts
src/clr-angular/forms/datepicker/date-container.ts
src/clr-angular/forms/datepicker/datepicker-view-manager.spec.ts
src/clr-angular/forms/datepicker/datepicker-view-manager.ts
src/clr-angular/popover/common/popover-positions.ts

Fixes #2331
Signed-off-by: Roy Ling <royling0024@gmail.com>
Issue Number: #2331

feat(datepicker): support clrPosition

---

BUILD.md
CODING_GUIDELINES.md
CONTRIBUTING.md
DEVELOPMENT_CONTRIBUTION.md
FAQ.md

Update some of the documentation that we have ...
Close: #3709

docs: update documentation

---

src/website/src/app/documentation/demos/color/color-palette-functional/color-palette-functional.demo.html
src/website/src/app/documentation/demos/color/color-palette/color-palette.demo.html

closes #3176
Signed-off-by: Marcu Alexandru <alexandru.marcu@bytex.ro>
Issue Number: #3176

fix(color): visually hidden text is not hidden from screen readers

---

DEVELOPMENT_CONTRIBUTION.md

docs: fix typos in DEVELOPMENT_CONTRIBUTION

---

src/website/src/app/documentation/demos/alert/alerts.demo.html
src/website/src/app/documentation/demos/button-group/button-group.demo.html
src/website/src/app/documentation/demos/datagrid/built-in-filters/built-in-filters.html
src/website/src/app/documentation/demos/datagrid/filtering/filtering.html
src/website/src/app/documentation/demos/datagrid/fixed-height/fixed-height.html
src/website/src/app/documentation/demos/datepicker/demos/datepicker-api.demo.html
src/website/src/app/documentation/demos/datepicker/demos/datepicker-internationalization.demo.html
src/website/src/app/documentation/demos/dropdown/dropdown.demo.html
src/website/src/app/documentation/demos/header/header.demo.html
src/website/src/app/documentation/demos/input/input.demo.html
src/website/src/app/documentation/demos/labels/labels-with-badges.demo.html
src/website/src/app/documentation/demos/labels/labels.demo.html
src/website/src/app/documentation/demos/password/password.demo.html
src/website/src/app/documentation/demos/radio/radio.demo.html
src/website/src/app/documentation/demos/select/select.demo.html
src/website/src/app/documentation/demos/sidenav/sidenav.demo.html
src/website/src/app/documentation/demos/signposts/signpost.demo.html
src/website/src/app/documentation/demos/textarea/textarea.demo.html
src/website/src/app/documentation/demos/themes/themes.demo.html
src/website/src/app/documentation/demos/timeline/timeline-full-demo.component.html
src/website/src/app/documentation/demos/timeline/timeline.demo.html
src/website/src/app/documentation/demos/wizard/wizard.demo.html

docs: fix typos in website's pages

---

CODING_GUIDELINES.md
CONTRIBUTING.md
DEVELOPMENT_CONTRIBUTION.md

Backport of #3783 for `v1` branch 

docs: fix typos in documentation (v1)

---

src/clr-angular/deprecations.spec.ts
src/clr-angular/wizard/_wizard.clarity.scss
src/clr-angular/wizard/wizard.ts
src/dev/src/app/wizard/wizard-inline.demo.html
src/dev/src/app/wizard/wizard-inline.demo.ts
src/dev/src/app/wizard/wizard.demo.module.ts
src/dev/src/app/wizard/wizard.demo.routing.ts

closes #3591
Signed-off-by: Marcu Alexandru <alexandru.marcu@bytex.ro>
A warning that inform the user that the inline wizard is deprecated will appear in the console if the component its used
Issue Number: #3591

fix(wizard): deprecate inline wizard

---

golden/clr-angular.d.ts
src/clr-angular/forms/datepicker/calendar.html
src/clr-angular/forms/datepicker/calendar.spec.ts
src/clr-angular/forms/datepicker/calendar.ts
src/clr-angular/forms/datepicker/datepicker-view-manager.ts
src/clr-angular/forms/datepicker/daypicker.html
src/clr-angular/forms/datepicker/daypicker.spec.ts
src/clr-angular/forms/datepicker/interfaces/day-of-week.interface.ts
src/clr-angular/forms/datepicker/providers/locale-helper.service.ts

backport from master; also fix modal bumpers style
fix: bumpers in datepicker and modal

fix(a11y): add bumpers to the datepicker

---

src/clr-angular/data/datagrid/_datagrid.clarity.scss

Fixes #1279
Signed-off-by: Roy Ling <royling0024@gmail.com>
Issue Number: #1279

fix: keep consistent height if signpost in datagrid header

---

src/clr-angular/data/datagrid/_datagrid.clarity.scss
src/clr-angular/data/datagrid/datagrid-pagination.ts

closes #3747 
Signed-off-by: Marcu Alexandru alexandru.marcu@bytex.ro
Issue Number: #3747

fix(datagrid): datagrid current page not rendered correctly in IE 11

---

.travis.yml

Recently we have been getting Travis error messages like:
```
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
W: GPG error: https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
W: The repository 'https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease' is not signed.
W: There is no public key available for the following key IDs:
6B05F25D762E3157  
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install g++-4.8 google-chrome-stable" failed and exited with 100 during .
```
There were …

fix(build): remove google-chrome-stable from addon

---

angular.json
src/website/src/polyfills.ts

close #3769 
Issue Number: #3769

fix: missing icons for internet explorer

---

src/clr-angular/popover/signpost/_signposts.clarity.scss

Close: #3803
Issue Number: #3803

fix(signpost): use default cursor in popover

---

src/website/src/releases/final-template/news-template.html

closes #3168
Signed-off-by: Marcu Alexandru <alexandru.marcu@bytex.ro>
Issue Number: #3168

fix: download links don't indicate their purpose

---

src/clr-angular/progress/progress-bars/_progress-bars.clarity.scss
src/clr-angular/progress/progress-bars/_variables.progress-bars.scss
src/clr-angular/progress/progress-bars/progress-bar.ts
src/website/src/app/documentation/demos/progress-bars/progbar-example.ts
src/website/src/app/documentation/demos/progress-bars/progress-bar-animations.ts
src/website/src/app/documentation/demos/progress-bars/progress-bar-colors.html
src/website/src/app/documentation/demos/progress-bars/progress-bar-colors.ts
src/website/src/app/documentation/demos/progress-bars/progress-bar-component.demo.html
src/website/src/app/documentation/demos/progress-bars/progress-bar-story.ts
src/website/src/app/documentation/demos/progress-bars/progress-bars.demo.html
src/website/src/app/documentation/demos/progress-bars/progress-bars.demo.module.ts
src/website/src/app/documentation/demos/progress-bars/progress-bars.demo.scss
src/website/src/app/documentation/demos/progress-bars/progress-bars.demo.ts
src/website/src/app/documentation/documentation.component.ts

@colinreedmiller - I'll add a link in the comments when the preview is built. 
Deprecates parts of the ClrProgressBar api.
Adds a new style for user defined style (color)
Updates the documentation recommendations and examples for both colors and variations. 
This also adds a scss variable and class for a user defined progress color `$clr-progress-user-color`.

docs(progress-bar): update docs and deprecate for removal

---

src/dev/src/app/stack-view/stack-view-angular-lazyload.html
src/website/src/app/documentation/demos/stack-view/stack-view-angular-lazyload.html
src/website/src/app/documentation/demos/stack-view/stack-view-angular-lazyload.ts

#3565
Signed-off-by: Andrei Constantin <andrei.constantin@bytex.ro>
Issue Number: #3565

fix(stack-view): stack view async loading

---

src/website/src/app/documentation/get-started/get-started.component.html
src/website/src/app/documentation/get-started/get-started.component.ts
src/website/src/environments/environment.prod.ts
src/website/src/releases/1.x/1.3.1.html
src/website/src/releases/2.x/2.2.1.html
src/website/src/releases/release-list.json
src/website/src/releases/release-template-stub.json
src/website/src/sitemap.xml
src/website/typings.d.ts

Issue Number: closes #3628
Update release notes and design resources

chore: 2.2.1 and 1.3.1 website update

---

golden/clr-angular.d.ts
src/clr-angular/layout/vertical-nav/vertical-nav.html
src/clr-angular/layout/vertical-nav/vertical-nav.spec.ts
src/clr-angular/layout/vertical-nav/vertical-nav.ts
src/clr-angular/utils/i18n/common-strings.default.ts
src/clr-angular/utils/i18n/common-strings.interface.ts

Closes #3575, #3574
Signed-off-by: Andrei Constantin <andrei.constantin@bytex.ro>
Issue Number: #3575 , #3574

fix(vertical-nav): vertical nav accesibility

---

angular.json
src/dev/custom-webpack.config.js
src/dev/src/app/custom-props/custom-props.demo.module.ts
src/dev/src/app/custom-props/custom-props.demo.ts
src/dev/src/index.html
src/dev/src/polyfills.ts

IE fails to work for the Dev test app.
This fix allows the dev app to properly work in IE11 as well as the CSS custom properties test page.

build: fix ie build issue with dev app

---

DEVELOPMENT_CONTRIBUTION.md

Added:
- timeline
- wizard
Would be nice to fine a way to automatically keep in sync with "commitlint.config.js"

docs: add missing commit scopes

---

CODING_GUIDELINES.md

docs: remove duplicated section

---

src/website/src/app/documentation/demos/progress-bars/progress-bars.demo.scss

• duplicate imports were not flagged in rebase so github merged them in together

fix: website regression

---

golden/clr-angular.d.ts
src/clr-angular/data/datagrid/providers/selection.spec.ts
src/clr-angular/data/datagrid/providers/selection.ts

Travis let me push a broken clr-angular.d.ts file so this is updated version

fix: update clr-angular.d.ts

---

golden/clr-angular.d.ts
src/clr-angular/data/datagrid/datagrid-column.spec.ts
src/clr-angular/data/datagrid/datagrid-column.ts

closes #3823
Issue Number: #3823

fix(datagrid): toggling sorting icon

---

src/clr-angular/wizard/wizard-page.mock.ts
src/clr-angular/wizard/wizard-page.spec.ts
src/clr-angular/wizard/wizard-stepnav-item.spec.ts

Signed-off-by: Florin Borceanu <florin.borceanu@bytex.ro>
Tests for wizard step error

test(wizard): tests for step error state

---

src/clr-angular/data/datagrid/_datagrid.clarity.scss
src/website/src/app/documentation/demos/datagrid/datagrid.demo.module.ts
src/website/src/app/documentation/demos/datagrid/detail/detail.html
src/website/src/app/documentation/demos/datagrid/detail/detail.ts

This provides the detail pane documentation, as well as a small bugfix for the column toggle icon and forcing the detail pane widths to 1/3 | 2/3.

docs: add detail pane docs

---

src/clr-angular/utils/_variables.global.scss
src/clr-core/button/button.element.css.ts
src/clr-core/icon/icon.element.css.ts
src/clr-core/test-dropdown/test-dropdown.element.css.ts

• this is to help with teams upgrading from v1 to v3

feat: adding 3.0 sass rem-sizing variables to 2.0

---

bundlesize.json
docs/core/cwc-button.md
golden/clr-core.d.ts
src/clr-core/button/button.element.scss
src/clr-core/button/button.element.spec.ts
src/clr-core/button/button.element.ts
src/clr-core/common/base/button.base.ts
src/clr-core/common/index.ts
src/clr-core/common/utils/dom.spec.ts
src/clr-core/common/utils/dom.ts
src/clr-core/styles/_core-component.scss
src/clr-core/styles/global.scss
src/clr-ui/.stylelintrc
src/dev-core/src/app/button/button.demo.html
src/dev-core/src/app/button/button.demo.module.ts
src/dev-core/src/app/button/button.demo.scss
src/dev-core/src/app/button/button.demo.ts

feat(button): core buttons

---

src/website/src/app/documentation/demos/badges/badges.demo.html
src/website/src/app/documentation/demos/tree-view/tree-view.demo.html

Close: #3947
Issue Number: #3947

fix: missing dependency for clr-tree-node

---

src/website/src/app/documentation/demos/datagrid/datagrid.demo.html
src/website/src/app/documentation/demos/datagrid/datagrid.demo.module.ts
src/website/src/app/documentation/demos/datagrid/filtering/examples.ts
src/website/src/app/documentation/demos/datagrid/usage/usage.html
src/website/src/app/documentation/demos/datagrid/usage/usage.ts

A code snippet in the custom filters section of the datagrid docs contains a typo.  Usage notes for Datagrids appear in top level document component.
Issue Number: #3737 (and also makes other changes)
Fixes the typo and moves the usage notes out to a child component

Tweak datagrid docs

---

src/website/src/app/documentation/demos/stepper/angular-stepper-api.demo.html

Issue Number: #4049
Closes: #4049

docs(stepper): fix type for clrInitialStep Input

---

src/clr-angular/utils/animations/expandable-animation/expandable-animation.spec.ts
src/clr-angular/utils/animations/expandable-animation/expandable-animation.ts

issue #3864
Multitude of rows with expandable details (~500) lead to serious loading delay (~20 sec)
Issue Number: #3864 
No performance implications from the use of the animation helper component

fix: datagrid animation performance issues

---

docs/core/README.md
docs/core/cwc-badge.md
docs/core/cwc-tag.md
src/clr-angular/emphasis/_badges.clarity.scss
src/clr-angular/emphasis/_labels.clarity.scss
src/clr-angular/utils/_components.clarity.scss
src/clr-angular/utils/_variables.global.scss
src/clr-core/badge/badge.element.scss
src/clr-core/badge/badge.element.spec.ts
src/clr-core/badge/badge.element.ts
src/clr-core/badge/index.ts
src/clr-core/badge/package.json
src/clr-core/button/button.element.spec.ts
src/clr-core/package.json
src/clr-core/tag/index.ts
src/clr-core/tag/package.json
src/clr-core/tag/tag.element.scss
src/clr-core/tag/tag.element.spec.ts
src/clr-core/tag/tag.element.ts
src/clr-ui/.stylelintrc
src/dev-core/src/app/app-routing.module.ts
src/dev-core/src/app/app.component.html
src/dev-core/src/app/badge/badge.demo.html
src/dev-core/src/app/badge/badge.demo.module.ts
src/dev-core/src/app/badge/badge.demo.ts
src/dev-core/src/app/tag/tag.demo.html
src/dev-core/src/app/tag/tag.demo.module.ts
src/dev-core/src/app/tag/tag.demo.ts

feat(badge): core badge, feat(tag): core tag

---

src/clr-angular/layout/main-container/_properties.header.scss
src/clr-angular/layout/main-container/_variables.header.scss
src/clr-angular/layout/nav/_header.clarity.scss

Signed-off-by: Eamon Bauman <eamon@eamonbauman.com>
Not sure if fixing a spelling error constitutes a breaking change, but I tagged 'yes' anyways. 
(also remember to properly sign off this time :) )

fixed misspelling of opacity

---

bundlesize.json
src/clr-angular/data/tree-view/tree-node.spec.ts
src/clr-angular/data/tree-view/tree-node.ts
src/clr-angular/utils/focus/key-focus/key-focus.spec.ts
src/clr-angular/utils/focus/key-focus/key-focus.ts
src/clr-angular/utils/focus/key-focus/util.spec.ts
src/clr-angular/utils/focus/key-focus/util.ts
src/clr-core/button/button.element.scss
src/clr-core/button/button.element.spec.ts
src/clr-core/common/base/button.base.ts
src/clr-core/common/enums/aria-roles.ts
src/clr-core/common/enums/key-codes.ts
src/clr-core/common/index.ts
src/clr-core/common/utils/events.ts
src/dev-core/src/app/button/button.demo.html
src/dev-core/src/app/button/button.demo.module.ts
src/dev-core/src/app/button/button.demo.ts

- trigger form submits, render hidden button in light DOM
- enable anchor/link support
- emulate native keyboard behavior
- add demos to core dev app using native HTML form and anchor

fix(button): core button a11y fixes

---

docs/core/cwc-badge.md
docs/core/cwc-button.md
docs/core/cwc-icon.md
docs/core/cwc-tag.md
docs/core/cwc-test-dropdown.md
golden/clr-core.d.ts
src/clr-core/badge/badge.element.ts
src/clr-core/button/button.element.spec.ts
src/clr-core/button/button.element.ts
src/clr-core/common/base/button.base.ts
src/clr-core/icon/icon.element.ts
src/clr-core/tag/tag.element.ts
src/clr-core/test-dropdown/test-dropdown.element.ts

- Adds minimal docs to show import path and element usage for core components.
- Tags all core components as beta for 3.0
- Update attrs to default as props as reflect back to get better static typing support across frameworks

core: docs improvements

---

package.json
src/clr-core/badge/badge.element.ts
src/clr-core/tag/tag.element.ts

Adding pre-commit hook to update the core API doc generation

---

src/clr-angular/data/datagrid/datagrid-action-overflow.spec.ts
src/clr-angular/data/datagrid/datagrid-action-overflow.ts
src/dev/src/app/datagrid/full/full.html
src/dev/src/app/datagrid/full/full.ts

clrDgActionOverflowOpenChange is not trigger as expected.
Issue Number: #3904 
Close: #3904

fix(datagrid): clrDgActionOverflowOpenChange is not fire

---

src/clr-angular/layout/vertical-nav/_vertical-nav.clarity.scss
src/website/src/app/documentation/documentation.component.html
src/website/src/styles/global.scss

- fixes uncentered focus outline around the expand/collapse icon
- also fixes vertical nav's padding issue in V3 website
This PR fixes small style errors in Vertical Nav

fix: style issues in vertical nav

---

golden/clr-angular.d.ts
src/clr-angular/data/stack-view/stack-block.spec.ts
src/clr-angular/data/stack-view/stack-block.ts
src/website/src/app/documentation/demos/stack-view/stack-view-angular-basic.html
src/website/src/app/documentation/demos/stack-view/stack-view-angular-basic.ts
src/website/src/app/documentation/demos/stack-view/stack-view-angular-lazyload.html
src/website/src/app/documentation/demos/stack-view/stack-view-angular-lazyload.ts
src/website/src/app/documentation/demos/stack-view/stack-view-angular-modal-edit.html
src/website/src/app/documentation/demos/stack-view/stack-view-angular-modal-edit.ts
src/website/src/app/documentation/demos/stack-view/stack-view-static.html
src/website/src/app/documentation/demos/stack-view/stack-view-static.ts
src/website/src/app/documentation/demos/stack-view/stack-view.demo.html

Adding aria-level, aria-posinset and aria-setsize attributes to stack-view
Issue Number: #3568
Close #3568

feat(stack-view): a11y aria-level, aria-posinset and aria-setsize

---

src/clr-angular/forms/datalist/datalist-container.ts

Wrong import path.
Issue Number: #4185
Close #4185

fix(datalist): wrong import path for DynamicWrapper

---

docs/core/cwc-icon.md
src/clr-core/common/interfaces/index.ts
src/clr-core/icon-shapes/icon.element.scss
src/clr-core/icon-shapes/icon.element.spec.ts
src/clr-core/icon-shapes/icon.element.ts
src/dev-core/src/app/icon/icon.demo.html

• dir is being replaced by the direction attribute
• using dir as an attribute confuses ltr localization
Issue Number: #4179

feat: deprecating dir attr in core icons

---

docs/core/cwc-button.md
docs/core/cwc-test-dropdown.md
src/clr-core/button/button.element.ts
src/clr-core/common/decorators/event.spec.ts
src/clr-core/common/decorators/event.ts
src/clr-core/common/decorators/property.spec.ts
src/clr-core/common/decorators/property.ts
src/clr-core/common/index.ts
src/clr-core/common/utils/string.spec.ts
src/clr-core/common/utils/string.ts
src/clr-core/test-dropdown/test-dropdown.element.spec.ts
src/clr-core/test-dropdown/test-dropdown.element.ts

- Automatically convert properties from camelCase to kebab-case for attributes when reflected.
- Provide a `@event` decorator that allows custom events to have generic types
- Events must still be described in the class tsdoc comments for now, see test dropdown for example
```typescript
import { event, EventEmitter, property } from '@clr/core/common';
/**
* @element test-element
* @event {boolean} openChange - notify open state change of dropdown
*/
export class TestElement extends LitElement {
@property({ type: Boolean }) open = false;
@event() private openChange: EventEmitter<boolean>;
method() {
// will only allow boolean types since generic type was defined …
```

core: decorator improvements

---

src/schematics/README.md
src/schematics/package-lock.json
src/schematics/package.json

Bumped the packages for @angular-devkit packages, which also resolve minor security alerts in sub-dependencies.

chore: updated schematics packages

---

golden/clr-angular.d.ts
src/clr-angular/button/button-group/_button-group.clarity.scss
src/clr-angular/button/button-group/button-group.html
src/clr-angular/button/button-group/button-group.module.ts
src/clr-angular/button/button-group/button-group.spec.ts
src/clr-angular/button/button-group/button-group.ts
src/clr-angular/button/button-group/button.spec.ts
src/clr-angular/button/button-group/button.ts
src/clr-angular/button/providers/button-in-group.service.spec.ts
src/clr-angular/data/datagrid/datagrid.module.ts
src/clr-angular/utils/popover/enums/positions.enum.ts
src/dev/src/app/button-group/angular/basic-structure/basic-button-group.html
src/dev/src/app/button-group/angular/basic-structure/basic-button-group.ts
src/dev/src/app/button-group/button-group.demo.module.ts

This replaces the old popover implementation with the new one that has smarter positioning while retaining backwards compatibility for position configuration.
I expect some visual diff issues because positions are slightly different due to new positioning logic. 
Issue Number: #1757

feat(button): button group uses smart positioning in overflow menu

---

docs/core/cwc-icon.md
golden/clr-angular.d.ts
src/clr-angular/button/button-group/button-group.ts
src/clr-core/common/utils/identity.spec.ts
src/clr-core/common/utils/identity.ts
src/clr-core/icon-shapes/icon.element.scss
src/clr-core/icon-shapes/icon.element.spec.ts
src/clr-core/icon-shapes/icon.element.ts
src/clr-core/icon-shapes/utils/icon.classnames.spec.ts
src/clr-core/icon-shapes/utils/icon.classnames.ts
src/clr-core/styles/utils/_a11y.scss
src/dev-core/src/app/app-routing.module.ts
src/dev-core/src/app/app.component.html
src/dev-core/src/app/icon-deprecated/icon.demo.html
src/dev-core/src/app/icon-deprecated/icon.demo.module.ts
src/dev-core/src/app/icon-deprecated/icon.demo.ts
src/dev-core/src/app/icon-sets/icon-sets.demo.html
src/dev-core/src/app/icon-sets/icon-sets.demo.ts
src/dev-core/src/app/icon/icon.demo.html

• replaced .sr-only classname with shared .clr-sr-only classname
• deprecated classname-driven API (.is-solid, .has-alert, .has-badge, .is-green, .is-success, .is-red, .is-error, .is-danger, .is-warning, .is-blue, .is-info, .is-highlight, .is-white, .is-inverse, .has-badge--success, .has-badge--danger, .has-badge--info, .has-badge--error
• added 'solid' boolean attribute
• added 'inverse' boolean attribute
• added 'alert' boolean attribute
• added 'status' attribute
• added 'badge' attribute
• updated icon demo to use new properties
• split stateful badge property into badge boolean and badgeType string properties
• updated unit tests
• created deprecated icons demo page to validate 3.0 deprecations work as expected
• added a 'warning' color for badges for consistency with other statuses …

feat: refactoring cwc-icon to be consistent with newer components

---

src/website/src/app/documentation/demos/app-layout/app-layout.demo.html
src/website/src/app/documentation/demos/app-layout/app-layout.demo.ts
src/website/src/app/documentation/demos/themes/themes.demo.html
src/website/src/styles/components.scss
src/website/src/styles/global.scss

feat: 3.0 documentation for theming and rem-sizing

---

src/clr-core/common/utils/exists.spec.ts
src/clr-core/common/utils/exists.ts
src/clr-core/common/utils/register.ts
src/dev-core/src/app/icon-sets/icon-sets.demo.html

• added check for server-side rendering
• fixed an issue with the dev-core app icon sets page
Issue Number: #4240

fix: adding window check for server-side rendering

---

src/clr-angular/data/datagrid/datagrid-column.ts

Change button order to improve accessibility 
Issue Number: #4189 
Close #4189

fix(datagrid): change order of datagrid filter, sorting buttons

---

src/schematics/README.md
src/schematics/package-lock.json
src/schematics/src/add/index.ts
src/schematics/src/migration-collection.json
src/schematics/src/update/update-3.0.0.ts
src/website/src/app/documentation/get-started/get-started.component.html
src/website/src/app/documentation/get-started/get-started.component.ts

fixes #4032
Issue Number: #4032

chore: update documentation and schematics for webcomponents polyfill

---

src/clr-core/.storybook/public/demo.css
src/clr-core/alert/alert.base.ts
src/clr-core/alert/alert.element.ts
src/clr-core/alert/app-alert.element.ts
src/clr-core/welcome.stories.ts
src/website/src/app/documentation/component-status/component-status.component.html

- alerts icon issue
- changelog for core
- remove core from component status
- broken links in core getting started

fix: core cleanup

---

src/website/src/app/documentation/demos/a11y/accessibility.demo.ts

docs(a11y): fix wrong import

---

src/dev/src/app/typography/font-autopsy.demo.scss
src/dev/src/app/typography/line-height.demo.scss
src/dev/src/app/typography/typography-font-autopsy.html
src/dev/src/app/typography/typography-font-autopsy.ts
src/dev/src/app/typography/typography-line-height.html
src/dev/src/app/typography/typography-line-height.ts
src/dev/src/app/typography/typography.demo.module.ts
src/dev/src/app/typography/typography.demo.routing.ts
src/dev/src/app/typography/typography.demo.ts
src/dev/src/app/typography/utils/font-presets.ts
src/dev/src/app/typography/utils/font-switcher.css
src/dev/src/app/typography/utils/font-switcher.html
src/dev/src/app/typography/utils/font-switcher.ts

• proved out line-height eraser across multiple fonts
• ratios/measurements change for some fonts when font-weight is changed...
• ...but none of the fonts we care about
• code in demos forms foundation for the LHEs Core is delivering
• added line-height eraser demo to dev-app
• added font-autopsy demo to dev-app
What kind of change does this PR introduce? See bulletpoints ☝️ 

feat: line-height erasers exploration

---

src/website/src/app/documentation/demos/vertical-nav/vertical-nav.demo.html

Provide vertical navigation with `arai-current="page"` when there is `routerLinkActive` set.
* [] Documentation content changes
Issue Number: #3576 
Close #3576

feat(vertical-nav): add aria-current to active link

---

src/clr-core/.storybook/manager-head.html

Issue Number: #4324 
Adds google analytics to the core storybook docs

docs: add analytics to core docs

---

src/clr-angular/button/button-group/button.spec.ts
src/clr-angular/button/button-group/button.ts

Signed-off-by: KingMario <gcyyq@hotmail.com>
There could be many buttons with the same id.
If ID is not set, the button will have no id attribute.

fix: id="null" for clr-buttons

---

src/website/src/app/documentation/get-started/get-started.component.html

chore: update website get started with @clr/core info

---

src/website/src/app/app.component.html
src/website/src/app/app.component.ts
src/website/src/index.html
src/website/typings.d.ts

Adds an app wide alert to the website for a Clarity survey. 
n/a
The website has an app wide alert that opens a new tab with the survey.

docs: add clarity survey alert to website

---

golden/clr-angular.d.ts
src/clr-angular/utils/i18n/common-strings.service.ts

• crossing the streams with a service shared b/w core and angular was causing nx and jest to lose their minds
• much of the problem was due to when typescript or jest would decide to compile an import down to ES5 or not
• recent discussions have uncovered the potential for more significant divergence in the scope of what we previously felt would be shared services
• in the future, a shared resource may need to be pulled into angular proper – as opposed to being brought in as a dependency
• i verified this approach solves breakages in previously breaking apps
• users still need to use `transformIgnorePatterns` in their jest config to allow babel to compile core, lit, and ramada
• users will NOT need to override ClrCommonStrings in their spec configs
• that was a band-aid that was going to …

fix(i18n): restore angular common strings service

---

src/clr-core/alert/alert.element.ts
src/clr-core/alert/alert.stories.mdx
src/clr-core/alert/alert.stories.ts
src/clr-core/alert/app-alert.element.ts
src/clr-core/alert/app-alert.stories.mdx
src/clr-core/alert/app-alert.stories.ts
src/clr-core/badge/badge.stories.mdx
src/clr-core/badge/badge.stories.ts
src/clr-core/button/button.stories.mdx
src/clr-core/button/button.stories.ts
src/clr-core/icon-shapes/icon.element.ts
src/clr-core/icon-shapes/icon.stories.mdx
src/clr-core/icon-shapes/icon.stories.ts
src/clr-core/list/list.stories.mdx
src/clr-core/list/list.stories.ts
src/clr-core/tag/tag.stories.mdx
src/clr-core/tag/tag.stories.ts

Adds mdx doc support to core components.
closes https://github.com/vmware/clarity/issues/4413

fix: add missing mdx docs for core components

---

src/clr-core/.storybook/public/demo.css
src/clr-core/docs/welcome.stories.ts
src/clr-core/styles/layout/_type-grid.scss
src/clr-core/styles/layout/_type-horizontal.scss
src/clr-core/styles/layout/_type-vertical.scss
src/clr-core/styles/layout/docs/grid.stories.mdx
src/clr-core/styles/layout/layout.stories.ts

This fixes a couple minor issues from the initial layouts PR.
- cleanup props, unnecessary props were being applied in certain alignments
- fix item alignment bug, grid was not properly aligning item/cols together horizontally
- rename align-items to align, align-items is a specific css prop so to avoid confusion it is renamed

fix: core layout alignments

---

src/clr-core/button/button.element.scss
src/clr-core/button/button.element.spec.ts

adds the missing not allowed hover style on disabled buttons
Issue Number: closes #4335

fix: core button disabled style

---

src/clr-angular/forms/common/if-error/if-error.spec.ts
src/clr-angular/forms/common/if-error/if-error.ts
src/website/src/app/documentation/demos/forms/forms.demo.html
src/website/src/app/documentation/demos/forms/ng/generic.html

Close: #4345
Signed-off-by: Gerin Jacob <gerinjacob@gmail.com>
Issue Number: #4345

feat(form): add error object to clrIfError context

---

docs/CONTRIBUTING_DESIGN.md
src/website/src/app/documentation/get-started/get-started.component.html
src/website/src/app/documentation/get-started/get-started.component.ts
src/website/src/app/utils/sketch-template-link.directive.ts
src/website/src/environments/environment.prod.ts
src/website/src/releases/release-list.json

docs: update sketch file links

---

src/clr-core/styles/layout/_type-horizontal.scss
src/clr-core/styles/layout/_type-vertical.scss

Due to the low specificity of the ::slotted selector we have to use an !important to set the margin gap of slotted items. This PR adds an additional important to fix alignments on single child alignments that require margins as well.

fix: core gap space with alignement

---

src/website/src/app/documentation/demos/alert/alerts.demo.html

Signed-off-by: Tarik Demirci <tarikdemirci@users.noreply.github.com>

docs(alert): Fix typo 'genrated'

---

src/clr-angular/data/datagrid/datagrid-row.ts
src/clr-angular/data/datagrid/render/row-renderer.spec.ts
src/dev/src/app/datagrid/expandable-rows/expandable-rows.html
src/dev/src/app/datagrid/expandable-rows/expandable-rows.ts

These changes are needed for backporting 4469 to v3 and v2.
Addition to #4469 

fix: check destroyed cell views before inserting them

---

src/clr-angular/accordion/stepper/models/stepper.model.spec.ts
src/clr-angular/accordion/stepper/models/stepper.model.ts
src/website/src/app/documentation/demos/stepper/angular-stepper-reactive.demo.html

Backport fix #4385 that solve #4223 to v2 
Close #4223

[BACKPORT] fix(stepper): make sure openFirstPanel is call only once

---

package.json
src/clr-core/badge/badge.element.scss
src/clr-core/badge/badge.element.ts
src/clr-core/badge/badge.stories.ts
src/clr-core/button/base-button.element.scss
src/clr-core/button/button.element.scss
src/clr-core/button/button.element.spec.ts
src/clr-core/button/button.element.ts
src/clr-core/button/button.stories.mdx
src/clr-core/button/button.stories.ts
src/clr-core/button/entrypoint.tsconfig.json
src/clr-core/button/icon-button.element.scss
src/clr-core/button/icon-button.element.spec.ts
src/clr-core/button/icon-button.element.ts
src/clr-core/button/icon-button.stories.mdx
src/clr-core/button/icon-button.stories.ts
src/clr-core/button/index.ts
src/clr-core/icon-shapes/collections/collections.spec.ts
src/clr-core/internal/base/button.base.ts
src/clr-core/internal/utils/dom.spec.ts
src/clr-core/internal/utils/dom.ts
src/clr-core/karma.conf.js
src/clr-core/styles/tokens/tokens.yml
src/clr-core/tag/entrypoint.tsconfig.json
src/clr-core/tag/tag.element.scss
src/clr-core/tag/tag.element.spec.ts
src/clr-core/tag/tag.element.ts
src/clr-core/tag/tag.stories.mdx
src/clr-core/tag/tag.stories.ts
src/clr-core/test-bundles/bundlesize.json

• added theme-able css vars to allow for customization
• worked on centering vertically and horizontally
• refactored badges to work off single --padding CSS property
• updated custom example to test extreme case
• added custom props and knobs to dox
• tried getting badges inside buttons
• overhauled tag css
• readonly tags were still showing hover states
• active tags weren't showing borders as expected
• fixed alignment of tags
• got icons working inside of tags
• got badges working inside of tags
• adding closable property to tags
• updated tag entry point to address build blockage
• added closable property to tags
• added CSS to position/align the close icon inside tags
• adjusted CSS to support better vertical alignment
• added demos and stories
• made a slight adjustment to …

fix: refactor badges and tags to use design tokens and layouts

---

packages/core/src/icon-shapes/collections/collections.spec.ts
packages/core/src/icon-shapes/collections/mini.ts
packages/core/src/icon-shapes/icon.stories.ts
packages/core/src/icon-shapes/index.ts
packages/core/src/icon-shapes/shapes/arrow-mini.ts
packages/core/src/icon-shapes/shapes/calendar-mini.ts
packages/core/src/icon-shapes/shapes/check-circle-mini.ts
packages/core/src/icon-shapes/shapes/check-mini.ts
packages/core/src/icon-shapes/shapes/error-mini.ts
packages/core/src/icon-shapes/shapes/event-mini.ts
packages/core/src/icon-shapes/shapes/filter-grid-circle-mini.ts
packages/core/src/icon-shapes/shapes/filter-grid-mini.ts
packages/core/src/icon-shapes/shapes/info-circle-mini.ts
packages/core/src/icon-shapes/shapes/times-mini.ts
packages/core/src/icon-shapes/shapes/warning-mini.ts

feat(icons): mini icons set

---

packages/angular/projects/clr-angular/src/data/datagrid/datagrid-row.html
packages/angular/projects/clr-angular/src/data/datagrid/datagrid.spec.ts

This PR fixes the issue of asynchronously added rows that have cells displayed in a wrong order.

fix(datagrid): async row cell order

---

src/clr-angular/data/datagrid/datagrid-row.html
src/clr-angular/data/datagrid/datagrid.spec.ts

Backport of https://github.com/vmware/clarity/pull/4540 to v3

fix: async row cell order (backport to v3)

---

package.json
packages/core/.storybook/main.js
packages/core/src/button/base-button.element.scss
packages/core/src/button/button.element.spec.ts
packages/core/src/internal/base/base.element.scss
packages/core/src/internal/base/button.base.ts

- Fix touch target and focus outline for links when projected into base button
- Fix storybook input paths
- Fix missing pre-commit script

core: bugfixes

---

packages/angular/golden/clr-angular.d.ts
packages/angular/projects/clr-angular/src/data/datagrid/datagrid-if-expanded.service.spec.ts
packages/angular/projects/clr-angular/src/data/datagrid/datagrid-if-expanded.service.ts
packages/angular/projects/clr-angular/src/data/datagrid/datagrid-row-detail.spec.ts
packages/angular/projects/clr-angular/src/data/datagrid/datagrid-row-detail.ts
packages/angular/projects/clr-angular/src/data/datagrid/datagrid-row.html
packages/angular/projects/clr-angular/src/data/datagrid/datagrid-row.spec.ts
packages/angular/projects/clr-angular/src/data/datagrid/datagrid-row.ts
packages/angular/projects/clr-angular/src/data/datagrid/datagrid.spec.ts
packages/angular/projects/clr-angular/src/utils/i18n/common-strings.default.ts
packages/angular/projects/clr-angular/src/utils/i18n/common-strings.interface.ts
packages/core/src/internal/services/common-strings.default.ts
packages/core/src/internal/services/common-strings.interface.ts
src/website/src/app/documentation/demos/i18n/i18n.demo.ts

Provide helper text to be used for describing the expandable content. And aria control attribute to point what part of the visible aria is controlled by Expand/Collapse button.
Issue Number: #3375 
Close #3375

fix(a11y): datagrid expandable row accessibility limitations

---

golden/clr-angular.d.ts
src/clr-angular/data/datagrid/datagrid-if-expanded.service.spec.ts
src/clr-angular/data/datagrid/datagrid-if-expanded.service.ts
src/clr-angular/data/datagrid/datagrid-row-detail.spec.ts
src/clr-angular/data/datagrid/datagrid-row-detail.ts
src/clr-angular/data/datagrid/datagrid-row.html
src/clr-angular/data/datagrid/datagrid-row.spec.ts
src/clr-angular/data/datagrid/datagrid-row.ts
src/clr-angular/data/datagrid/datagrid.spec.ts
src/clr-angular/utils/i18n/common-strings.default.ts
src/clr-angular/utils/i18n/common-strings.interface.ts
src/clr-core/internal/services/common-strings.default.ts
src/clr-core/internal/services/common-strings.interface.ts
src/website/src/app/documentation/demos/i18n/i18n.demo.ts

feat(a11y): expandable datagrid-row (backport to v3)

---

src/clr-angular/emphasis/alert/_alert.clarity.scss

This is a backport of the fix on master (eaefd248f1ff47cd26cd27ba740ad370f6ca9398)
➜ fixes #4548

fix(alert): fix ie11 width issue for long alerts (V3 branch)

---

src/clr-angular/emphasis/alert/_alert.clarity.scss

This is a cherrypick of the fix on v3 (3b11300d5ddbe30445e3364f6c251ec46bd2721c)
➜ fixes #4548

fix(alert): fix ie11 width issue for long alerts (V2 branch)

---

src/clr-angular/emphasis/alert/_alert.clarity.scss

This is a cherrypick of the fix on v3 (3b11300d5ddbe30445e3364f6c251ec46bd2721c)
➜ fixes #4548

fix(alert): fix ie11 width issue for long alerts (V1 branch)

---

src/clr-angular/utils/popover/popover-content.spec.ts
src/clr-angular/utils/popover/popover-content.ts

BACKPORT fix: don't update view after opening and immediately closing a popover

---

src/clr-angular/data/datagrid/all.spec.ts
src/clr-angular/data/datagrid/providers/state.provider.spec.ts
src/dev/src/app/datagrid/full/full.ts
src/dev/src/app/datagrid/preserve-selection/preserve-selection.ts
src/dev/src/app/datagrid/selection-single/selection-single.ts
src/dev/src/app/datagrid/selection/selection.ts
src/dev/src/app/datagrid/server-driven/server-driven.ts
src/website/src/app/documentation/demos/datagrid/full/full.ts
src/website/src/app/documentation/demos/datagrid/pagination/pagination.html
src/website/src/app/documentation/demos/datagrid/server-driven/examples.ts
src/website/src/app/documentation/demos/datagrid/server-driven/server-driven.ts

Signed-off-by: KingMario <gcyyq@hotmail.com>
The value description of firstItem and lastItem is not complete.
The offset for API call is not accurate for server-driven datagrid.
The desciption is updated.
The offset is updated for server-driven datagrid.
This PR is for V3 to merge.

fix: firstItem-related issues

---

packages/angular/golden/clr-angular.d.ts
packages/angular/projects/clr-angular/src/data/datagrid/_datagrid.clarity.scss
packages/angular/projects/clr-angular/src/data/datagrid/datagrid-column-separator.spec.ts
packages/angular/projects/clr-angular/src/data/datagrid/datagrid-column-separator.ts
packages/angular/projects/clr-angular/src/data/datagrid/datagrid.spec.ts
packages/angular/projects/clr-angular/src/data/datagrid/providers/column-resizer.service.spec.ts
packages/angular/projects/clr-angular/src/data/datagrid/providers/column-resizer.service.ts
packages/angular/projects/clr-angular/src/utils/i18n/common-strings.default.ts
packages/angular/projects/clr-angular/src/utils/i18n/common-strings.interface.ts

The original PR https://github.com/vmware/clarity/pull/4368 is started with @aliitani. Thank you for your work, @aliitani!
This PR introduces a feature of Datagrid column resizing with keyboard.
Issue Number: #3372

feat: datagrid column resizing with keyboard

---

packages/angular/projects/clr-angular/src/emphasis/_properties.badges.scss
packages/angular/projects/clr-angular/src/emphasis/_properties.label.scss
packages/angular/projects/clr-angular/src/emphasis/_variables.badges.scss
packages/angular/projects/clr-angular/src/emphasis/_variables.label.scss
packages/angular/projects/clr-angular/src/emphasis/alert/_properties.alert.scss
packages/angular/projects/clr-angular/src/emphasis/alert/_variables.alert.scss
packages/angular/projects/clr-angular/src/utils/variables/_variables.color.scss

Issue Number: #4546
Updated colors for @clr/ui

fix(color): align clr/ui with clr/core colors

---

src/clr-angular/data/datagrid/wrapped-cell.ts
src/clr-angular/data/datagrid/wrapped-column.ts
src/clr-angular/data/datagrid/wrapped-row.ts

fix: clean up embedded views in wrapped components

---

src/clr-angular/data/datagrid/wrapped-cell.ts
src/clr-angular/data/datagrid/wrapped-column.ts
src/clr-angular/data/datagrid/wrapped-row.ts

fix: clean up embedded views in wrapped components - (v1)

---

.github/ISSUE_TEMPLATE/accessibility-report.md
.github/ISSUE_TEMPLATE/bug-report.md

This is to give us a special issue template for accessibility, also to help redirect any internal users to the accessibility team directly.

Add github issue template for accessibility reports

---

packages/ui/README.md

- N/A Tests for the changes have been added (for bug fixes / features)
- N/A If applicable, have a visual design approval
```
$ ll node_modules/clr-icons/clr-icons.min.js
ls: node_modules/clr-icons/clr-icons.min.js: No such file or directory
```
```
$ ll node_modules/@clr/icons/clr-icons.min.js
-rw-r--r--  1 jeremie  staff   657K Jul 10 13:56 node_modules/@clr/icons/clr-icons.min.js
```

Fix path in README

---

packages/angular/projects/clr-angular/src/data/datagrid/wrapped-cell.ts
packages/angular/projects/clr-angular/src/data/datagrid/wrapped-column.ts
packages/angular/projects/clr-angular/src/data/datagrid/wrapped-row.ts
packages/angular/projects/clr-angular/src/utils/ivy/if-ivy-enabled.spec.ts
packages/angular/projects/clr-angular/src/utils/ivy/if-ivy-enabled.ts

fix: backport datagrid missing cells issue

---

src/clr-angular/data/datagrid/wrapped-cell.ts
src/clr-angular/data/datagrid/wrapped-column.ts
src/clr-angular/data/datagrid/wrapped-row.ts
src/clr-angular/utils/ivy/if-ivy-enabled.spec.ts
src/clr-angular/utils/ivy/if-ivy-enabled.ts

This is backward compatibility check for non-Ivy build to call or not to call a method.
Issue Number: #4692
Close: #4692

Fix: backward compatibility for non Ivy build related to Datagrid

---

src/clr-angular/data/datagrid/_datagrid.clarity.scss
src/dev/src/app/datagrid/detail/detail.html
src/dev/src/app/datagrid/detail/detail.ts

closes: #4773
When datagrid height is fixed and there are few rows visible, there is a missing internal border between the list of rows and the detail pane.
Issue Number: #4773 
Internal border is visible.

fix: missing border with small number of rows

---

packages/angular/projects/clr-angular/src/data/datagrid/_datagrid.clarity.scss
packages/angular/projects/dev/src/app/datagrid/detail/detail.html
packages/angular/projects/dev/src/app/datagrid/detail/detail.ts

Missing internal border between datagrid and detail pane, when detail is larger than items list
Issue Number: #4773
Border restored

fix: port from v3 - missing border with small number of rows

---

src/website/src/app/documentation/demos/modal/modal.demo.html

Provide an explanation why it is aria-hidden with the value of true in the examples 
Issue Number: #4177 
Close #4177

docs: update modal documentation section about aria-hidden

---

src/clr-angular/layout/tabs/_tabs.clarity.scss

fix(tabs): width tab content in ie 11 backport

---

src/website/src/app/documentation/demos/stack-view/stack-view-static.html
src/website/src/app/documentation/demos/stack-view/stack-view-static.ts

Issue Number: #4765
The selected expanding row of static Stack View has a full-width background accent and all content in the Stack View is aligned equally.

docs: update static Stack View example

---

apps/website/.vuepress/theme/enhanceApp.js
apps/website/.vuepress/theme/global-components/DocIcons.vue
apps/website/.vuepress/theme/global-components/DocIconsSet.vue
apps/website/.vuepress/theme/global-components/services/icon-preview-service.js
apps/website/.vuepress/theme/global-components/services/icon-search-service.js
apps/website/.vuepress/theme/layouts/Layout.vue
apps/website/.vuepress/theme/util/route-guards.js
apps/website/data/icon-inventory.js
apps/website/foundation/color/README.md
apps/website/foundation/icons/README.md

docs: add TOC to icon and color pages

---

apps/website/.vuepress/theme/layouts/404.vue
apps/website/.vuepress/theme/layouts/Layout.vue

Simple 404 content.
Nicer looking 404 content.

docs: adds 404 content

---

apps/website/.vuepress/theme/components/Footer.vue
apps/website/.vuepress/theme/layouts/Layout.vue
apps/website/.vuepress/theme/styles/layout.scss
apps/website/.vuepress/theme/styles/overrides.scss
apps/website/components/datagrid/api.md
apps/website/components/form/README.md
apps/website/components/progress-bar/README.md
apps/website/components/spinner/README.md
apps/website/foundation/accessibility.md
apps/website/foundation/icons/accessibility.md
apps/website/foundation/icons/api.md
apps/website/foundation/icons/usage.md
apps/website/foundation/navigation/api.md
apps/website/foundation/navigation/demo.md
apps/website/foundation/themes/README.md
apps/website/get-started/design.md

- fix: remove footer tag from PageEdit
- fix: turn typescript snippets to javascript
- fix: code snippet clean ups in Foundation
- docs: link privacy policy
- fix: remove wcag section from accessibility
- docs: improve download buttons and design page layout

docs: fit and finish in the foundation section

---

apps/website/.vuepress/theme/layouts/Layout.vue

fix: home page footer

---

apps/website/.vuepress/public/demos/header/subnav.html
apps/website/.vuepress/public/demos/sidenav/icons-css.html
apps/website/.vuepress/public/demos/sidenav/nav-groups-css.html
apps/website/.vuepress/public/demos/sidenav/structure-css.html
apps/website/components/dropdown/README.md
apps/website/components/vertical-nav/README.md

Fixes three issues tracked in Trello. 

---

apps/website/components/vertical-nav/README.md

docs: add vertical nav layouts missing description

---

docs/CONTRIBUTING_DOCUMENTATION.md

The contributing guide says that the docs website is available at `localhost:4200`.
The contributing guide now points to the correct port - `8080`.

docs: update docs website port in the contributing guidelines

---

apps/website/.vuepress/public/demos/i18n/localize-ng.ts
apps/website/foundation/internationalization/README.md
apps/website/foundation/navigation/README.md
apps/website/get-started/README.md
apps/website/get-started/angular.md

docs: fix a few broken links and the wording in the documentation website

---

apps/website/.vuepress/theme/components/Home.vue
apps/website/.vuepress/theme/global-components/WhatsNew.vue

Second try. The first PR actions seem to have gotten disconnected and it stopped building. 
Updated layout for homepage.

docs: home updates

---

apps/website/.vuepress/public/demos/navigation/sidenav-css.html
apps/website/.vuepress/public/demos/navigation/sidenav-ng.html
apps/website/.vuepress/public/demos/navigation/subnav-sidenav-css.html
apps/website/.vuepress/public/demos/navigation/subnav-sidenav-ng.html
apps/website/.vuepress/public/demos/textarea/helper-css.html
apps/website/.vuepress/theme/components/NavToc.vue
apps/website/.vuepress/theme/components/Page.vue
apps/website/.vuepress/theme/components/PageSubnav.vue
apps/website/.vuepress/theme/core.js
apps/website/.vuepress/theme/global-components/DocIcons.vue
apps/website/.vuepress/theme/styles/overrides.scss
apps/website/components/vertical-nav/README.md

docs: fix layout spacing

---

apps/website/foundation/app-layout/README.md

docs: fix alert link in App-Layout

---

apps/website/components/vertical-nav/README.md

docs: remove duplicate descriptions in vertical-nav

---

packages/angular/projects/clr-angular/src/accordion/stepper/models/stepper.model.spec.ts
packages/angular/projects/clr-angular/src/accordion/stepper/models/stepper.model.ts

Backport of #4900 for v4/master

fix: handle stepper throwing TypeError (backport)

---

packages/core/src/forms/control-action/control-action.element.scss
packages/core/src/forms/control-label/control-label.element.scss
packages/core/src/forms/utils/index.ts
packages/core/src/icon/icon.element.ts
packages/core/src/input/input-groups.stories.ts
packages/core/src/internal/base/button.base.ts

- allow icon whitespace to be offset
- adjust form to fix corrected whitespace in labels
- fix missing button lifecycle check

fix(core): form alignment issues

---

packages/core/docs/welcome.stories.ts
packages/core/src/forms/form-group/form-group.element.ts
packages/core/src/forms/forms.stories.mdx
packages/core/src/forms/forms.stories.ts
packages/core/src/forms/utils/validate.ts

- fixed component docs tag with forms
- fixed minor layout issue with storybook page
- fixed form enum to be plain type for easier use

fix: core docs forms, improved types

---

packages/core/.storybook/preview.js
packages/core/docs/development/getting-started.stories.mdx
packages/core/docs/development/package.stories.mdx
packages/core/docs/development/public-api.stories.mdx
packages/core/docs/development/stateless.stories.mdx
packages/core/package.json
packages/core/src/internal-components/close-button/close-button.stories.mdx
packages/core/src/internal-components/close-button/close-button.stories.ts
packages/core/src/styles/layout/_type-horizontal.scss

- fixes issue with safari not aligning horizontal content bottom
- fixes a type dependency that can break in projects with TS strict mode (Angular)
- additional core dev docs

core: fixes layout,  docs

---

golden/clr-angular.d.ts
src/clr-angular/data/stack-view/stack-block.ts

fix(a11y): remove redundant title attribute (backport from v4)

---

packages/angular/golden/clr-angular.d.ts
packages/angular/projects/clr-angular/src/forms/combobox/combobox.html
packages/angular/projects/clr-angular/src/forms/combobox/combobox.spec.ts
packages/angular/projects/clr-angular/src/forms/combobox/combobox.ts
packages/angular/projects/dev/src/app/combobox/combobox.demo.html

Let passing placeholder value inside the internal input. 
Issue Number: #4949
Close #4943 
No backport needed.

fix(combobox): display placeholder text

---

packages/core/src/internal/base/base.element.scss
packages/core/src/tag/tag.element.scss
packages/core/src/tag/tag.stories.ts

- Added a disabled state for tags
- Fixed style scope that was breaking some css custom properties on tags
- Added basic button/disabled state to base style

fix: core mising disabled styles

---

packages/core/src/list/list.scss
packages/core/src/list/list.stories.mdx
packages/core/src/list/list.stories.ts
packages/core/src/styles/typography/_typography.scss

Lists and cds-layouts when combined with cds-text caused excess stacking margins.
This fixes the margins and adds some static list demos so its easy to grab code snippets.

fix: core list margins

---

packages/core/src/modal/modal.element.ts
packages/core/src/modal/modal.stories.ts

- Fix an issue on mobile where the close icon button wraps the heading content.
- Fix modal slot content for demo

fix: core modal prevent close button wrap

---

packages/core/src/button/icon-button.element.ts

The icon button has a aria-hidden attr which causes a11y issues since its a button element
Removed the aria-hidden attr

fix: core icon button a11y

---

packages/core/src/internal/base/base.element.scss
packages/core/src/internal/base/focus-trap.base.spec.ts
packages/core/src/internal/base/focus-trap.base.ts
packages/core/src/modal/modal.element.ts

Focus trap was missing from modal element
Add focus trap to modal element and check for hidden to prevent hidden focus traps

fix: core modal focus trap

---

packages/angular/projects/clr-angular/src/modal/_modal.clarity.scss
packages/angular/projects/clr-angular/src/modal/modal.html
packages/angular/projects/clr-angular/src/modal/modal.spec.ts
packages/angular/projects/clr-angular/src/wizard/_wizard.clarity.scss

Backport of https://github.com/vmware/clarity/pull/4922

fix: accept clrLabelSize values provided without binding (backport)

---

packages/core/src/internal/base/base.element.scss
packages/core/src/internal/base/focus-trap.base.spec.ts
packages/core/src/internal/base/focus-trap.base.ts
packages/core/src/modal/modal.element.ts

Back port of https://github.com/vmware/clarity/pull/4959

core: backport modal focus fix

---

packages/core/src/button/icon-button.element.ts

Back port fix https://github.com/vmware/clarity/pull/4955

core: backport icon button fix

---

packages/core/src/modal/modal.element.ts
packages/core/src/modal/modal.stories.ts

Back port of https://github.com/vmware/clarity/pull/4960

core: backport modal fix

---

packages/core/src/list/list.scss
packages/core/src/list/list.stories.mdx
packages/core/src/list/list.stories.ts
packages/core/src/styles/typography/_typography.scss

Back port of https://github.com/vmware/clarity/pull/4954

core: backport lists

---

packages/core/src/button/base-button.element.scss
packages/core/src/button/button.element.spec.ts
packages/core/src/button/button.stories.ts
packages/core/src/button/icon-button.stories.ts
packages/core/src/button/inline-button.stories.mdx
packages/core/src/button/inline-button.stories.ts
packages/core/src/internal/base/base.element.scss
packages/core/src/internal/base/button.base.ts
packages/core/src/styles/typography/_typography.scss
packages/core/src/tag/tag.element.scss
packages/core/src/tag/tag.stories.mdx
packages/core/src/tag/tag.stories.ts

Based on our internal conversations this adds support to wrap buttons with an anchor. This is not a breaking change the slotted anchor behavior remains in 4.0. The base button will detect the anchor and switch to readonly mode preserving the proper semantics and a11y of the link.
The wrapping style API seems to be far more consistent/predictable with styles and easier to support framework behavior with custom routing solutions.

fix: core improved link button behavior/docs

---

packages/core/src/tag/tag.element.scss
packages/core/src/tag/tag.stories.ts

Back port of https://github.com/vmware/clarity/pull/4957

backport: disabled tag styles

---

packages/core/src/button/base-button.element.scss
packages/core/src/button/button.element.spec.ts
packages/core/src/button/button.stories.ts
packages/core/src/button/icon-button.stories.ts
packages/core/src/button/inline-button.stories.mdx
packages/core/src/button/inline-button.stories.ts
packages/core/src/internal/base/base.element.scss
packages/core/src/internal/base/button.base.ts
packages/core/src/tag/tag.element.scss
packages/core/src/tag/tag.stories.mdx
packages/core/src/tag/tag.stories.ts

Signed-off-by: Cory Rylan <splintercode.cb@gmail.com>
Back port of https://github.com/vmware/clarity/pull/4961

backport: core improved link button behavior/docs

---

packages/angular/projects/clr-angular/src/forms/combobox/_combobox.clarity.scss
packages/angular/projects/clr-angular/src/forms/combobox/_properties.combobox.scss
packages/angular/projects/clr-angular/src/forms/combobox/_variables.combobox.scss
packages/angular/projects/clr-angular/src/utils/_theme.dark.clarity.scss

Also fixes a regression on the invalid state notification
Currently the pills are designed to design spec minus one - based on the labels styles
New style adheres to latest specs from design team, with smaller rounded borders, overall component border, different color scheme.

fix: update combobox design to latest spec

---

packages/angular/projects/clr-angular/src/forms/combobox/_combobox.clarity.scss
packages/angular/projects/clr-angular/src/forms/combobox/_properties.combobox.scss
packages/angular/projects/clr-angular/src/forms/combobox/_variables.combobox.scss
packages/angular/projects/clr-angular/src/utils/_theme.dark.clarity.scss

Pills are using the style of labels
Pills have a new unique style

fix: update combobox design - backport from master

---

packages/core/src/styles/layout/_type-horizontal.scss

The horizontal layout had a relative position leftover for safari that was no longer needed.
Remove the position relative style from horizontal layouts

fix: core remove unnecessary position on layout

---

packages/schematics/src/collection.json
packages/schematics/src/ng-core-migration/alert/index.ts
packages/schematics/src/ng-core-migration/alert/index_spec.ts

test: set up a sample unit test for Angular-Core migration

---

packages/core/src/styles/layout/_type-horizontal.scss

Back port of https://github.com/vmware/clarity/pull/4987

fix: core backport remove unnecessary position on layout

---

packages/core/src/internal/base/focus-trap.base.spec.ts
packages/core/src/internal/base/focus-trap.base.ts
packages/core/src/internal/utils/focus-trap.ts

- fix focus trap exception when modal initialized with hidden
Back port of https://github.com/vmware/clarity/pull/4992

fix: back port core modal exception

---

packages/core/src/button/icon-button.element.spec.ts
packages/core/src/button/icon-button.element.ts
packages/core/src/internal/base/button.base.ts
packages/core/src/range/range.element.scss

- icon button slots were broken, now fixed and simplified
- range input layout was broken due to relying on old incorrect behavior with horizontal layout

fix: core range/button layout fix

---

packages/angular/projects/clr-angular/src/forms/common/all.spec.ts
packages/angular/projects/clr-angular/src/forms/common/if-control-state/if-error.spec.ts
packages/angular/projects/clr-angular/src/forms/common/if-control-state/if-error.ts
packages/angular/projects/dev/src/app/forms/validation/validation.html

fix(form): display the correct error when validating (backport)

---

packages/angular/projects/clr-angular/src/forms/common/all.spec.ts
packages/angular/projects/clr-angular/src/forms/common/if-control-state/if-error.spec.ts
packages/angular/projects/clr-angular/src/forms/common/if-control-state/if-error.ts
packages/angular/projects/dev/src/app/forms/validation/validation.html

Issue Number: #4929 
Close #4929

fix(form): display the correct error when validating

---

packages/angular/projects/clr-angular/src/data/datagrid/providers/selection.spec.ts
packages/angular/projects/clr-angular/src/data/datagrid/providers/selection.ts

Signed-off-by: Skip Geldens <skip@skipgeldens.nl>

fix(datagrid): current selection immutability (backport)

---

packages/angular/projects/clr-angular/src/forms/common/if-control-state/if-control-state.service.spec.ts
packages/angular/projects/clr-angular/src/forms/common/if-control-state/if-control-state.service.ts

Backport of #5007 
Close #5010

fix: handle TypeError when calling triggerStatusChange

---

packages/angular/projects/clr-angular/src/data/datagrid/datagrid.spec.ts
packages/angular/projects/clr-angular/src/data/datagrid/datagrid.ts

fix: datagrid pane was losing state when rows update

---

packages/angular/golden/clr-angular.d.ts
packages/angular/projects/clr-angular/src/accordion/accordion-panel.ts

fixes #5015
backport of ce59aaa01067acc769e9a8575394f2ffea2d21ca from master

fix(accordion): updated panel property to match stepper panel for TS 4

---

packages/react/src/button/index.tsx

fix: typo in button react wrapper

---

packages/react/src/button/index.tsx

fix: typo in button react wrapper (v4 backport)

---

packages/core/src/range/range.element.scss

backport of https://github.com/vmware/clarity/pull/5002

fix: core range input layout (backport)

---

packages/angular/projects/clr-angular/src/data/datagrid/datagrid-row.spec.ts
packages/angular/projects/clr-angular/src/data/datagrid/datagrid-row.ts
packages/angular/projects/dev/src/app/datagrid/conditional-selection/conditional-selection.html
packages/angular/projects/dev/src/app/datagrid/conditional-selection/conditional-selection.ts

fix: datagrid-row correct way of assigning clrDgSelectable (backport)

---

src/clr-angular/data/datagrid/datagrid-items.spec.ts
src/clr-angular/data/datagrid/datagrid-items.ts

fix(datagrid): trackBy items by provided trackBy option v2 port

---

packages/angular/projects/clr-angular/src/data/datagrid/datagrid-items.spec.ts
packages/angular/projects/clr-angular/src/data/datagrid/datagrid-items.ts

fix(datagrid): trackBy items by provided trackBy option v4 port

---

packages/core/.storybook/preview.js
packages/core/package.json
yarn.lock

Fixes issue where storybook would not hot reload component when source code changes.

fix: core update hot reload for storybook

---

packages/angular/projects/clr-angular/src/data/datagrid/datagrid-items.spec.ts
packages/angular/projects/clr-angular/src/data/datagrid/datagrid-items.ts

fix(datagrid): trackBy items by provided trackBy option port

---

packages/angular/projects/website/src/app/documentation/demos/app-layout/app-layout.demo.html

closes #5063
Fixes a broken link for the website on the v4 branch. 
Issue Number: #5063 
The link works now.

fix: broken link in website documentation

---

.github/workflows/website.yml
package.json

Icons are not downloadable
Makes icons available to download

docs: fix website icon download svg

---

packages/react/src/converter/react-wrapper.test.tsx
packages/react/src/converter/react-wrapper.tsx

test: add test to ensure className is properly passed down
Signed-off-by: Jérémie Astori <jeremie@cloudhealthtech.com>

fix: Allow className to be passed down to the underlying component (backport v4)

---

src/clr-angular/data/datagrid/_datagrid.clarity.scss

This is a manual backport for this fix: https://github.com/vmware/clarity/commit/ee7cbc562b981c0cb31135aa88178e4e36a7f226
------------------------------------------------------------------------------------------
Commit on master: https://github.com/vmware/clarity/commit/ee7cbc562b981c0cb31135aa88178e4e36a7f226
Manual backport for a fix applied to v3. 
Issue Number: #4889

fix(v3 backport): datagrid sticky header fix

---

apps/website/.vuepress/public/demos/table/basic.html
apps/website/.vuepress/public/demos/table/borderless.html
apps/website/.vuepress/public/demos/table/compact.html
apps/website/.vuepress/public/demos/table/left-align.html
apps/website/.vuepress/public/demos/table/multiline.html
apps/website/.vuepress/public/demos/table/vertical.html
apps/website/.vuepress/theme/global-components/DocVideo.vue
apps/website/foundation/navigation/README.md

- added more description to the navigation images
- added a caption to each of the table demo html files
- added video controls to the DocVideo component so that video can be
controlled by user
Adds accessibility for DocVideo component, navigation page and table demos. 

fix: navigation and table pages

---

apps/website/.vuepress/theme/components/Sidebar.vue
apps/website/.vuepress/theme/global-components/DocIcon.vue
apps/website/foundation/app-layout/README.md
apps/website/get-started/README.md

- update image labels for app-layout images
- fixes for icon buttons
- properly label getting started intro for supported browsers image
Adds more accessible behavior to website content.
Adds more accessible behavior to website content.

fix: website accessibility fixes

---

packages/core/src/alert/alert-group.element.spec.ts
packages/core/src/alert/alert.element.scss
packages/core/src/alert/alert.element.spec.ts
packages/core/src/alert/alert.element.ts
packages/core/src/button/base-button.element.scss
packages/core/src/button/button.element.ts
packages/core/src/button/icon-button.element.ts
packages/core/src/internal/base/button.base.ts

fix: replace base64 spinners with circular progress component

---

packages/angular/projects/clr-angular/src/accordion/_accordion.clarity.scss

• some css properties were not applied to the accordion
• this fixes that issue

fix(accordion): css variables for accordion (backport v4)

---

apps/website/.vuepress/theme/global-components/DocIconDetail.vue
apps/website/.vuepress/theme/global-components/DocIconsSearch.vue
apps/website/.vuepress/theme/global-components/DocIconsSet.vue

fix: enable svg downloads for individual icons

---

apps/website/.vuepress/theme/global-components/DocIconsSet.vue

This change removes unused code in a website component. 
n/a
It is the same as before.

fix: remove unused method from DocIconSet

---

apps/website/.vuepress/sidebar.js
apps/website/.vuepress/theme/global-components/ComponentsOverview.vue
apps/website/.vuepress/theme/global-components/ItemOverview.vue
apps/website/components/README.md

docs: add components overview page

---

packages/angular/projects/clr-angular/src/data/datagrid/datagrid.ts

fix: (datagrid) filtering not working well with Ivy off (backport)

---

packages/angular/projects/clr-angular/src/data/datagrid/datagrid.spec.ts
packages/angular/projects/clr-angular/src/data/datagrid/providers/selection.spec.ts
packages/angular/projects/clr-angular/src/data/datagrid/providers/selection.ts

#5126
Issue Number: #5126 
The latest change is detected and the views are updated.

fix(datagrid): skipped change detection cycle on select

---

packages/angular/projects/clr-angular/src/forms/combobox/_combobox.clarity.scss
packages/angular/projects/clr-angular/src/forms/combobox/_variables.combobox.scss
packages/angular/projects/dev/src/app/combobox/combobox.demo.html

The problem was coming mostly from inappropriate type and size of the icon used for demo purposes. Also minor adjustments of color and placement were added.
Text looks misaligned with icon on combobox pills examples. Text color too black.
Issue Number: #5115 
Cosmetic: Icon changed with a roundish one, as the house icon was visually perceived as non-centered, size reduced.
Actual: Color updated, X-close icon moved 2px to compensate padding inside the icon image itself.

fix: (combobox) update of pill design and demo

---

packages/angular/projects/clr-angular/src/forms/combobox/_combobox.clarity.scss
packages/angular/projects/clr-angular/src/forms/combobox/_variables.combobox.scss
packages/angular/projects/dev/src/app/combobox/combobox.demo.html

The problem was coming mostly from inappropriate type and size of the icon used for demo purposes. Also minor adjustments of color and placement were added.

fix: (combobox) update of pill design and demo (backport)

---

package.json
packages/eslint-plugin-clarity-migration/.gitignore
packages/eslint-plugin-clarity-migration/README.md
packages/eslint-plugin-clarity-migration/docs/rules/no-clr-button.md
packages/eslint-plugin-clarity-migration/package.json
packages/eslint-plugin-clarity-migration/src/index.ts
packages/eslint-plugin-clarity-migration/src/rules/no-clr-button/index.ts
packages/eslint-plugin-clarity-migration/src/rules/utils.ts
packages/eslint-plugin-clarity-migration/test/no-clr-button.spec.ts
packages/eslint-plugin-clarity-migration/test/test-helper.ts
packages/eslint-plugin-clarity-migration/tsconfig.json
packages/eslint-plugin-clarity-migration/tslint.json
yarn.lock

This PR adds a new package to the repository - `@clr/eslint-plugin-clarity-migration`. This ESLint plugin can be used to discover the usage of deprecated components in Angular and non-Angular projects and report it as a warning or error, depending on the configuration in the project.
Currently, the plugin contains a single rule - `no-clr-button`. This rule reports the usage of `<button class="btn btn-primary"></button>` inside HTML files or inside inlined Angular components templates (TS files).
For parsing the TS files in the project, the plugin uses [`@typescript-eslint/plugin`](https://www.npmjs.com/package/@typescript-eslint/eslint-plugin). Then, it parses the HTML within the component template with …

feat: eslint plugin for reporting the usage of clarity Angular elements

---

src/clr-angular/data/datagrid/datagrid.spec.ts
src/clr-angular/data/datagrid/providers/selection.spec.ts
src/clr-angular/data/datagrid/providers/selection.ts

fix(datagrid): skipped change detection cycle on select (backport)

---

apps/website/.vuepress/theme/components/Footer.vue
apps/website/.vuepress/theme/components/Home.vue
apps/website/.vuepress/theme/components/NavToc.vue
apps/website/.vuepress/theme/components/Page.vue
apps/website/.vuepress/theme/global-components/WhatsNew.vue
apps/website/.vuepress/theme/layouts/Layout.vue
apps/website/.vuepress/theme/styles/overrides.scss
commitlint.config.js

adds images and new content for the updated home page layout. 

docs(website): new home page design

---

apps/website/.vuepress/config.js
apps/website/.vuepress/theme/enhanceApp.js
apps/website/package.json
yarn.lock

Turning on search and adding the hotjar feedback tool. 
Turning on search and adding the hotjar feedback tool.  
n/a

docs(website): enable search and add hotjar

---

packages/angular/projects/clr-angular/src/forms/combobox/_combobox.clarity.scss
packages/angular/projects/clr-angular/src/forms/combobox/combobox.html
packages/angular/projects/clr-angular/src/forms/combobox/combobox.spec.ts

fix(combobox): disable openClose button (backport)

---

apps/website/.vuepress/config.js
apps/website/.vuepress/theme/components/Home.vue

This change is based on feedback from non engineers. I'll keep it open for a few days until everyone has a change to review the preview. 
website home page content vertical rhythm. 
some content to close. 
Some content has better spacing.

docs(website): small change for content vertical rhythym

---

apps/website/.vuepress/config.js
apps/website/.vuepress/theme/components/AlgoliaSearchBox.vue
apps/website/.vuepress/theme/components/Home.vue
apps/website/.vuepress/theme/components/Sidebar.vue
apps/website/.vuepress/theme/global-components/Release.vue
apps/website/.vuepress/theme/global-components/ReleaseGroup.vue
apps/website/.vuepress/theme/global-components/ReleaseItem.vue
changelogs/schema.json
changelogs/v4/v4.json
netlify.toml
scripts/netlify-build.sh

- This includes Home page fixes for lilia
- Addition of search config to use the new index
- An update for netlify to try to turn of any build actions that trigger
a yarn install

docs(website): updates

---

packages/angular/.eslintrc.js
packages/angular/package.json
packages/angular/projects/clr-angular/src/deprecations.spec.ts
packages/angular/projects/clr-angular/src/forms/common/if-control-state/if-success.ts
packages/angular/projects/clr-angular/src/utils/popover/popover-close-button.spec.ts
packages/angular/src/stories/combobox/combobox.stories.ts
packages/angular/src/stories/signpost/signpost.stories.ts

and fix files that break the rule

chore: add back no-unused-imports lint rule (backport)

---

apps/website/.vuepress/theme/components/Home.vue
apps/website/.vuepress/theme/enhanceApp.js

fixes hotjar id for current vmware account id, adds one more homepage spacing change
Hotjar wasn't configured correctly and spacing wasn't consistent with the latest design. 
Hotjar widget works, space is consistent.

docs(website): hotjar id fix + homepage spacing token change

---

packages/core/src/icon/icon.stories.ts

- [N/A] Tests for the changes have been added (for bug fixes / features)
- [N/A] Docs have been added / updated (for bug fixes / features)
- [N/A] If applicable, have a visual design approval

chore: use `direction` in lieu of deprecated `dir` in Icon's story

---

packages/angular/projects/website/src/app/app.component.html
packages/angular/projects/website/src/styles/header.scss

Adds the link to current website to the preview site. Removed the GitHub stars component, didn't have enough room for it.

docs: add link to preview site

---

apps/website/.vuepress/sidebar.js
apps/website/.vuepress/theme/components/Sidebar.vue
apps/website/.vuepress/theme/global-components/DocCode.vue
apps/website/components/date-picker/api.md
apps/website/components/label/api.md
apps/website/components/vertical-nav/api.md
apps/website/data/api.json
apps/website/foundation/accessibility/README.md
apps/website/foundation/internationalization/README.md
apps/website/foundation/typography/README.md

There were a few issues in the API content and updated the links in the sidenav. I also removed the Foundations/Accessibility page for now, it had no real content.

docs: update some apis in website and links in sidenav

---

apps/core-angular-cli/src/app/app.component.html
apps/core-angular-cli/src/app/app.component.ts
apps/core-vue-cli/src/App.vue
packages/core/import-map.importmap
packages/core/src/accordion/accordion-content.element.spec.ts
packages/core/src/accordion/accordion-content.element.ts
packages/core/src/accordion/accordion-header.element.spec.ts
packages/core/src/accordion/accordion-header.element.ts
packages/core/src/accordion/accordion-panel.element.scss
packages/core/src/accordion/accordion-panel.element.spec.ts
packages/core/src/accordion/accordion-panel.element.ts
packages/core/src/accordion/accordion-panel.stories.mdx
packages/core/src/accordion/accordion-panel.stories.ts
packages/core/src/accordion/accordion.element.scss
packages/core/src/accordion/accordion.element.spec.ts
packages/core/src/accordion/accordion.element.ts
packages/core/src/accordion/accordion.stories.mdx
packages/core/src/accordion/accordion.stories.ts
packages/core/src/accordion/entrypoint.tsconfig.json
packages/core/src/accordion/index.ts
packages/core/src/accordion/package.json
packages/core/src/accordion/register.ts
packages/core/src/internal/utils/metadata.ts
packages/core/tokens.yml
packages/react/App.tsx
packages/react/src/accordion/__snapshots__/index.test.tsx.snap
packages/react/src/accordion/entrypoint.tsconfig.json
packages/react/src/accordion/index.test.tsx
packages/react/src/accordion/index.tsx

Core implementation of the Clarity accordion.
- Core accordion doesn't manage state and therefore does not automatically close a panel if another is open, etc. This logic, along with any other logic (e.g. intercept when user expands / closes a panel) can be implemented on the application side
- Slide animation for expand / close (animating from `height: 0` to `height: auto`) is not included in this PR. Our current goal, if possible, is to not use javascript in our animation. If we were to use javascript to grab the content's height there are some challenges with responding to dynamic changes in accordion content's height at runtime. We'll have to revisit the animation part especially in the context of Clarity motion and how they might fit in with the rest of the components in the system. …

feat: core accordion
