vmware/clarity

- src/clarity/nav/_nav.clarity.scss
Fixed:
1. box-shadow alignment bug
2. Button font color on hover
Before:
After:
Tested on: IE10, IE11, Edge, Chrome, Safari, Firefox
fixes #48 
Signed-of-by: Aditya Bhandari <adityab@vmware.com>
Signed-of-by: Aditya Bhandari <arb492@nyu.edu>
> [UI] Nav/Nav-Item box-shadow bug fix

- _sass/global.scss
Added a not selector for `.nav` since the margin-top: 24px style is only meant for unordered lists on the website. These lists don't use the `.nav` class.
Before:
After:
Unordered lists used on the website remain unaffected:
Datagrid Pagination remains unaffected:
fixes #39 
> [WEB] Clarity nav margin-top fix

- _sass/header.scss
Styles specific to the header on the website were being applied to the header demos in the header documentation as well.
Before:
After:
Tested on: Chrome only because just added a stricter selector to apply the styles on the website header instead of the demos.
fixes #56 
> [WEB] Header Demo Styles Fix

- src/clarity/dropdown/dropdown.spec.ts
Fixed a false positive test to detect clicks outside of the dropdown component.
Unit Tests:
Dropdown
✔ projects content
✔ adds the .dropdown class on clr-dropdown
✔ adds the .dropdown-toggle class on clrDropdownToggle
✔ adds the .dropdown-item class on clrDropdownItem
✔ supports clrMenuDirection option
✔ toggles the menu when clicked on the host
✔ closes the menu when clicked outside of the host
✔ supports clrMenuClosable option. Closes the dropdown menu when clrMenuClosable is set to true
✔ does not close the menu when a disabled item is clicked
Browser Tests:
> [NG] Fix Dropdown Test

- src/clarity/progress-bars/_progress-bars.clarity.scss
BEFORE
AFTER
Tested in:
✔︎ Chrome
Closes: https://github.com/vmware/clarity/issues/60
> [ui] Padding around progress blocks in cards is no longer necessary

- src/clarity/nav/_responsive-nav.clarity.scss
Hide branding icon on medium and smaller breakpoints.
Before:
After:
Fixes: #82 
> [UI] Hide branding icon on smaller screens

- src/clarity/alert/_alert.clarity.scss
`.alert-text` in small alerts didn't have the correct line-height set.
Before:
After:
Tested on: Chrome, Firefox, IE10, 11, Edge, Safari
Fixes: #92 
> [UI] Fixing small alert line height

- src/clarity/datagrid/all.spec.ts
- src/clarity/datagrid/built-in/filters/datagrid-string-filter.spec.ts
- src/clarity/datagrid/built-in/filters/datagrid-string-filter.ts
- src/clarity/datagrid/datagrid-filter.spec.ts
- src/clarity/datagrid/datagrid.spec.ts
- src/clarity/datagrid/datagrid.ts
- src/clarity/datagrid/demo/basic-structure/basic-structure.html
- src/clarity/datagrid/demo/server-driven/server-driven.html
- src/clarity/datagrid/demo/string-filtering/string-filtering.html
- src/clarity/datagrid/helpers.spec.ts
- Removed a console.log that sneaked in the last PR.
- Remove router links from demos (they were breaking the website).
- Removed hard-coded text from filter dropdowns.
- Additional unit tests.
Closes #97.
> [NG] Datagrid misc fixes

- build/npm/clarity-icons.json
- package.json
Our peer dependency (and our internal one) was to their GitHub repo
directly, which creates a lot of issues. Moved to their NPM package
with a hard version number for now.
> [ICONS] Depend on custom-elements NPM package

- README.md
- build/npm/clarity-icons-README.md
This is for our README.md to reflect the changes made in the following commit:
- 80a4d89072675f611a9573e9310230927869f1de
> [ICONS] CE v1 install guide uses npm package instead of github now

- get-started/index.md
HTTPS is the preferred way to clone a repo by GitHub, as SSH only works if you have the key setup in your account.
> update git clone instructions

- _sass/components.scss
• previous breakpoint wasn’t aggressive enough and the badges overlapped the page title
• also responsively adjusted the font-size and line-height of h1s on smaller devices to improve use of space
Tested in:
✔︎ Chrome
Closes: #108
> [web] adjusting breakpoint for hiding HTML/CSS/NG badges on website

- _sass/whats-new.scss
This issue only affected Chrome.
• It appeared to be related to card-blocks, position relative, and floats.
• Setting the What’s New Summary block to position: static fixed it
Tested in:
✔︎ Chrome
✔︎ Firefox
✔︎ Safari
✔︎ IE10
✔︎ IE11
✔︎  Edge
Closes: #109
> [web] scrollbar fix for Chrome

- src/clarity/datagrid/datagrid-items.spec.ts
- src/clarity/datagrid/datagrid-items.ts
- src/clarity/datagrid/datagrid.html
- src/clarity/datagrid/datagrid.spec.ts
We overwrote our differ every time instead of just on initialization,
which makes no sense.
Also fixes an uncaught bug with the trackBy option which was not
correctly renamed during a refactor. Added a unit test to make sure
it wouldn't happen again.
Fixes #131.
> [NG] Datagrid: proper change detection for the smart iterator

- src/clarity/forms/_forms.clarity.scss
• compact forms margin bottom is 0
• regular forms margin is 6px
• form headers are no longer titlecase
BEFORE
AFTER
COMPACT FORM (AFTER)
Tested in:
✔︎ Chrome
Closes: #100 
> [ui] adjusting margin/capitalization of form headers

- src/clarity/dropdown/_dropdown.clarity.scss
Removed Dropdown Menu Close Transition
Browser Tests: Chrome
Fixes #86 
> Removing Dropdown Menu Close Transition

- src/clarity/modal/modal.ts
We still close the modal when the user presses escape, but we can
remove our workaround now that Angular fixed the key filtering issue.
So much easier to read.
> [NG] Modal keybinding cleanup

- src/clarity/dropdown/demo/dropdown-angular-close-item-false.demo.html
- src/clarity/utils/_variables.clarity.scss
- src/icons/svg-icon-templates.ts
Caret Icon update
Dropdown Caret distance reduced to 2px
Before:
After:
Browser Tests: Chrome, IE 10, 11, Edge, Firefox, Safari
> [ICONS,UI] Caret Icon update + Dropdown Fixes

- src/app/app.html
- src/clarity/alert/demo/angular/alert-angular-not-closable.demo.html
- src/clarity/alert/demo/static/alert-styles.demo.html
- src/clarity/card/demo/card-dropdown.html
- src/clarity/dropdown/_dropdown.clarity.scss
- src/clarity/dropdown/demo/dropdown-angular-close-item-false.demo.html
- src/clarity/dropdown/demo/dropdown-angular-positioning.demo.html
- src/clarity/dropdown/demo/dropdown-static-buttonlink-toggle.demo.html
- src/clarity/dropdown/demo/dropdown-static-default.demo.html
- src/clarity/dropdown/demo/dropdown-static-fontawesome-toggle.demo.html
- src/clarity/dropdown/demo/dropdown-static-icon-toggle.demo.html
- src/clarity/dropdown/demo/dropdown-static-positioning.demo.html
- src/clarity/dropdown/dropdown.spec.ts
- src/clarity/nav/_header.clarity.scss
- src/clarity/nav/demo/header-types.demo.html
Updated carets in dropdowns to use this markup:
`<clr-icon shape=“caret” class=“icon-orient-down”></clr-icon>`
to:
`<clr-icon shape=“caret down”></clr-icon>`
Tested on: Chrome, IE10, IE11, Edge, Firefox, Safari
> [UI] Dropdown Caret Examples Update

- src/clarity/datagrid/datagrid-placeholder.spec.ts
- src/clarity/datagrid/datagrid-placeholder.ts
- src/clarity/datagrid/datagrid.ts
- src/clarity/datagrid/providers/items.ts
The placeholder image and projected text are not displayed if the
data is currently loading.
Fixes #162.
> [NG] Datagrid: no placeholder while loading

- src/clarity/alert/demo/angular/alert-angular-not-closable.demo.html
- src/clarity/alert/demo/static/alert-styles.demo.html
- src/clarity/card/demo/card-clickable.html
- src/clarity/card/demo/card-dropdown.html
- src/clarity/card/demo/card-grid.html
- src/clarity/card/demo/card-images.html
- src/clarity/card/demo/card-list-group.html
- src/clarity/card/demo/card-masonry.html
- src/clarity/card/demo/card-old.html
- src/clarity/dropdown/demo/dropdown-angular-close-item-false.demo.html
- src/clarity/dropdown/demo/dropdown-angular-positioning.demo.html
- src/clarity/dropdown/demo/dropdown-static-buttonlink-toggle.demo.html
- src/clarity/dropdown/demo/dropdown-static-default.demo.html
- src/clarity/dropdown/demo/dropdown-static-fontawesome-toggle.demo.html
- src/clarity/dropdown/demo/dropdown-static-icon-toggle.demo.html
- src/clarity/dropdown/demo/dropdown.demo.ts
- src/clarity/labels/demo/labels-clickable.demo.html
- src/clarity/labels/demo/labels-with-badges.demo.html
- src/clarity/login/demo/login.demo.html
- src/clarity/nav/demo/header-types.demo.html
- src/clarity/nav/demo/sidenav.demo.html
- src/clarity/progress-bars/demo/progress-bar-cards.html
- src/clarity/progress-bars/demo/progress-bar-inline-cards.html
- src/clarity/progress-bars/demo/progress-bar-static-cards.html
- src/clarity/tooltips/demo/tooltips-directions.html
- src/clarity/tooltips/demo/tooltips-sizes.html
Documentation Updates:
1. Change href=“javascript://“ to href=“…” in the code snippets
2. Update Dropdown Clarity Icon to use a smaller icon
3. Fix an issue with the header branding doc
Browser Tests: 
Chrome
> [UI,WEB] Documentation Updates

- build/tasks/sass.js
- src/clarity/main.scss
- src/icons/clarity-icons.scss
- Changes sass tasks to preprocess clarity-ui & clarity-icons css output with the clarity version number
- closes #110
> [core] Adds clarity version to generated css files

- src/clarity/card/_card.clarity.scss
- src/clarity/typography/demo/typography-headers.html
- Added the card title style in the header section of the Typography documentation
- Marked .card-subtitle for deprecation in 0.8.0
Browser: Chrome
> [UI,DOC] Card Title Doc Update

- src/clarity/wizard/demo/wizard-options.demo.html
- src/clarity/wizard/wizard.html
- src/clarity/wizard/wizard.spec.ts
- src/clarity/wizard/wizard.ts
For issue #152
This is a new implementation of an onCancel event in wizard component (first try was on PR 179).
The first implementation was wrong because it was binded on wizardPage instead of main component.
I still need help on testing the feature:
* i want to test that the property of the component has been modified by the onCancel method
* i want to test that the _close method has been called after clicking on cancel
but my test doesn't work coz i have certainly missed something around the component
Signed-off-by: Benjamin RICHARD <benjamin.richard@ext.euronews.com>
> Implement an onCancel event fo Wizard component

- src/clarity/iconography/demo/icon-colors.demo.html
- src/icons/clarity-icons.scss
- made .icon-color-danger the same color as .icon-color-warning
- added .icon-color-error that is the same color as .icon-color-warning
- updated the icon colors demo to reflect the changes
> [ICONS] created a class for icon error color

- src/clarity/wizard/demo/wizard-angular.demo.html
- src/clarity/wizard/demo/wizard-not-closable.demo.html
- src/clarity/wizard/demo/wizard-not-closable.demo.ts
- src/clarity/wizard/demo/wizard-options.demo.html
- src/clarity/wizard/demo/wizard.demo.module.ts
- src/clarity/wizard/wizard.html
- src/clarity/wizard/wizard.spec.ts
- src/clarity/wizard/wizard.ts
• added clrWizardClosable flag to wizard component
• this delegates to clrModalClosable
• effectively removes X from top-right corner of modal
• defaults to true, which is the current default
• added unit tests
• moved emission of onCancel event on close out of the private function
• when we moved the close functionality to be a delegate of the modal closing functionality, the onCancel event was not being fired
Tested in:
✔︎ Chrome
Closes: #155
> [ng] adding clrWizardClosable attribute to wizards

- src/clarity/stack-view/_stack-view.clarity.scss
Applied the negative margin just to the link button as a Stack Action so that if users use some other button (even though we only recommend using link buttons) in the Stack header, a negative margin is not applied to that. 
Partially Resolves: #153
After fix: **(Please note that this is not a standard way of using Stack Actions)**
> [UI,NG] Stack Action Negative Margin Fix

- src/clarity/code/_code.clarity.scss
- closes #185
- this preserves the existing code snippets as is but makes sure that all pre elements have newlines by default
- changes were tested on the following: IE 10, 11 Edge, Chrome (latest) Firefox (Latest) and Safari (Latest)
See the below screen capture of a pre tag on the website
See screen captures of existing pre elements for checkboxes and buttons are below:
> [ui] Update pre style to have newlines by default

- src/clarity/forms/_forms.clarity.scss
Fixed bug where Validated Inputs didn’t occupy 100% of the width on smaller screens
Before:
After:
Tested on:
Chrome,
IE 10,
IE 11,
Edge,
Safari,
Firefox
Fixes: #212 
> [UI] Input Validation Bug Fix

- src/clarity/nav/_header.clarity.scss
Fixes #242: Text Dropdown Bug in Header Actions
Before:
After:
Tested on:
Chrome
Firefox
Safari
IE 10
IE 11
Edge
Note: I have not updated `app.html` to reflect the screenshot above. The demo app header still remains to be a settings gear dropdown
> [UI] Text Dropdowns in Header Actions Fix

- build/tasks/bundle.js
This change fixes the [error](https://github.com/vmware/clarity/issues/257) logged out during bundling process. Thanks for catching this, @jeeyun!
> [CORE] fixed bundle error

- README.md
- src/app/app.module.ts
- src/clarity/alert/alert.spec.ts
- src/clarity/checkboxes/checkbox.spec.ts
- src/clarity/clarity.module.ts
- src/clarity/code/code-highlight.spec.ts
- src/clarity/datagrid/datagrid-items.spec.ts
- src/clarity/datagrid/helpers.spec.ts
- src/clarity/dropdown/dropdown.spec.ts
- src/clarity/layout/main-container.spec.ts
- src/clarity/modal/modal.spec.ts
- src/clarity/nav/header.spec.ts
- src/clarity/stack-view/stack-block.spec.ts
- src/clarity/stack-view/stack-header.spec.ts
- src/clarity/stack-view/stack-view.spec.ts
- src/clarity/tabs/tab-content.spec.ts
- src/clarity/tabs/tab-link.spec.ts
- src/clarity/tabs/tabs.spec.ts
- src/clarity/wizard/wizard-page.spec.ts
- src/clarity/wizard/wizard-step.spec.ts
- src/clarity/wizard/wizard.spec.ts
This is a cover version of #88, I preserved his commit.
Fixes #59.
> [NG] Add forRoot() and forChild() to ClarityModule

- src/clarity/clarity.module.ts
Fixed the ImplicitAny build error.
Before:
`tmp/clarity-angular/clarity.module.ts(70,13): error TS7018: Object literal's property 'providers' implicitly has an 'any' type.`
After: All good!
> [CORE] ImplicitAny Build Error Fix

- gemini/tests/lists.js
- src/clarity/card/_card.clarity.scss
- src/clarity/lists/demo/lists-in-cards.html
- src/clarity/nav/_header.clarity.scss
1. Deprecate old card classes
.card-subtitle
.group
.icon
.description
.title
.card-link
.card-overflow-menu
2. Update list demo to use the card layout that we recommend
3. Commented out a regression test for old cards
**4. Marked header classes for deprecation in 0.9.0. We need to add them to the release notes for 0.8.0**
**Note:** I have decided not to deprecate `.card-divider` because Scott and I discussed a couple of weeks back that `.card-divider` might be useful in `.card-block`.
**CSS Regression Diff**: https://s3.amazonaws.com/travis-ci-jeeyun/adityarb88/clarity/33/33.2/home/travis/build/adityarb88/clarity/gemini-report/index.html
> [UI] Deprecate Old Card Classes

- package.json
Removed clarity-demos publish command because after AOT and the new angular website, the demos are being moved to the website branch
> [CORE] Remove clarity-demos publish command

- build/rollup-clarity.config.js
Not explicitly giving names for external modules in the `rollup-clarity-config.js` file produces the following output in console:
```
No name was provided for external module '@angular/common' in options.globals – guessing '_angular_common'
No name was provided for external module '@angular/forms' in options.globals – guessing '_angular_forms'
No name was provided for external module '@angular/core' in options.globals – guessing '_angular_core'
No name was provided for external module 'rxjs' in options.globals – guessing 'rxjs'
No name was provided for external module '@angular/platform-browser' in options.globals – guessing '_angular_platformBrowser'
```
Opting to explicitly name them rather than rely on rollup to come up with a name.
> [core] name globals in rollup config

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- README.md
This updates three files that use the plunker template link.
> [docs] Updated plunkr template link for 0.8.0

- src/clarity-angular/checkboxes/checkbox.ts
- src/clarity-angular/dropdown/dropdown.ts
I realized I missed a couple of components in making sure that all their inputs and outputs are public. The following components will currently (v0.8.1) throw an error when compiling (when the consuming app compiles in AoT):
- dropdown
- checkbox
Tested by building npm package candidates and testing on a seed.
> [core] Making inputs/outputs public for AoT

- build/npm/clarity-icons.json
This adds an entry point for `clarity-icons`. It allows to better use `webpack` or other module loaders.
> Adding entry point for clarity-icons

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- README.md
I added multiple plunker links for latest and the last three Clarity Versions. This may not be the best way to surface multiple Clarity Plunker Templates in the project files so I am open to suggestions.
> [docs] Update readme / issue files with links to multiple plunkers

- build/npm/clarity-icons.json
- build/tasks/bundle.js
- build/tasks/publish.js
- src/app/index.html
- src/clarity-icons/clarity-icon.ts
- src/clarity-icons/clarity-icons-api.ts
- src/clarity-icons/index.ts
- Made Clarity-Icons importable and loadable in typescript files in the following way:
`import { ClarityIcons } from "clarity-icons"`
> [ICONS] made clarity-icons importable in typescript

- src/clarity-angular/modal/_modal.clarity.scss
This PR fixes: #252 
Scrollbars appear inside of the modals whenever a grid is used because the `.modal-body` does not have the `overflow-x: hidden` property and because of the negative margins on the `.row` of the bootstrap grid.
Before:
After:
Tested on: Chrome, Firefox, IE
> [UI] Modal Grid Overflow Fix

- src/clarity-angular/login/_login.clarity.scss
> [UI] Login Form support for validation tooltips

- src/clarity-angular/datagrid/datagrid-row.spec.ts
- src/clarity-angular/datagrid/datagrid-row.ts
- src/clarity-angular/datagrid/datagrid.spec.ts
- src/clarity-angular/datagrid/providers/selection.ts
We now offer a boolean two-way binding on the <clr-dg-row> component for its selected state. This allows users to select items programmatically more easily, or keep up-to date with the current selection status of a single row:
```
<clr-dg-row *clrDgItems="let item of users" [clrDgItem]="item"
[(clrDgSelected)]="item.selected">
...
</clr-dg-row>
```
Fixes #111. The first commit addresses the opening description, the second one handles the unrelated issue several people raised in the comments.
> [NG] Two-way binding on row selection

- src/clarity-angular/nav/_header.clarity.scss
- src/clarity-angular/nav/_responsive-nav.clarity.scss
Fixes: #347 
Fixed the alignment issue when the header-overflow-trigger is directly after the `.header-nav` or the `.branding`
Before:
After:
Tested on: Chrome, Firefox, IE 10, 11, Edge, Safari
> [UI] Header overflow trigger bug fix

- src/clarity-angular/datagrid/datagrid-row.spec.ts
- src/clarity-angular/datagrid/datagrid-row.ts
Binding to [clrDgSelected] was completely ignored when the entire datagrid was not selectable, which prevented people from manually creating single-row selection with the entire row as click target. They had to bind to an internal class, and even then it resulted in conflicts with our own implementation overriding their initial value.
To fix this, we now support the [clrDgSelected] input on rows all the time, but it only handles styling when the whole datagrid is not selectable.
Fixes #388.
> [NG] Support manual selection of Datagrid row

- build/tasks/bundle.js
- src/clarity-angular/datagrid/built-in/filters/datagrid-string-filter.ts
- src/clarity-angular/datagrid/datagrid-column.spec.ts
- src/clarity-angular/datagrid/datagrid-filter.spec.ts
- src/clarity-angular/datagrid/datagrid-pagination.ts
- src/clarity-angular/datagrid/datagrid.spec.ts
- src/clarity-angular/datagrid/datagrid.ts
- src/clarity-angular/datagrid/interfaces/filter.ts
- src/clarity-angular/datagrid/providers/filters.spec.ts
- src/clarity-angular/datagrid/providers/filters.ts
- src/clarity-angular/datagrid/providers/items.spec.ts
- src/clarity-angular/datagrid/providers/items.ts
- src/clarity-angular/datagrid/providers/page.ts
- src/clarity-angular/datagrid/providers/selection.ts
- src/clarity-angular/datagrid/providers/sort.ts
- src/clarity-angular/layout/main-container.ts
- src/clarity-angular/nav/clrResponsiveNavigationService.ts
- src/clarity-angular/nav/header.ts
Instead of importing from 'rxjs', import from specific modules e.g. 'rxjs/Subject', etc. This will minimize the number of requests in dev mode and prod mode in which treeshaking is not done.
Resolves #285.
> [core] Import specific modules from RxJs

- src/clarity-angular/nav/_nav.clarity.scss
Currently, we apply the "active" style of an anchor tag on hover, active, and focus. This introduces a bug in which when the user navigates to another page through back/forward button on browser, the previous active anchor tag in nav keeps the "active" style until the focus is taken out by user clicking on another area. Let me know if this fix of removing the style for focus sounds reasonable, or if there's a better alternative fix.
Tested the newly generated css on seed.
Fixes #374.
> [ui] Remove active style for focused anchor tag

- src/demos/checkboxes/checkboxes.demo.html
- src/demos/checkboxes/checkboxes.demo.module.ts
- src/demos/checkboxes/checkboxes.demo.ts
- src/demos/checkboxes/data/server.ts
- src/demos/checkboxes/data/status.ts
- src/demos/checkboxes/data/values.ts
**NOTE: Do not merge this to the website branch until after v0.8.4 is release to npm.**
- Adds code and docs for the website for clr-checkbox, native checkbox usage by porting over the demo app from clarity-angular
- closes #319
> [ng,web] Make the checkbox component public

- src/clarity-angular/tree-view/_tree-view.clarity.scss
Overflow hidden was not being applied by default in firefox using the collapse animation function
Issue:
Tested on Firefox
> [UI] TreeView Firefox Animation Fix

- src/clarity-angular/utils/_helpers.clarity.scss
- src/clarity-angular/utils/_variables.clarity.scss
- This PR is the fix to the error we've faced while publishing the website.
> [ui] moved rem method to _variables.clarity.scss

- src/clarity-angular/datagrid/datagrid.spec.ts
- src/clarity-angular/datagrid/datagrid.ts
- src/clarity-angular/datagrid/providers/items.spec.ts
- src/clarity-angular/datagrid/providers/items.ts
When consumers mutate the data they pass to the Datagrid, we have no way of detecting that the data has changed and that it should be re-processed by the filters, the comparators, ...
Although we recommend the data given to Datagrid should be immutable, we now provide a way for consumers to manually re-trigger this processing if they still decide to mutate the data. The way to do this is simply to grab the instance the the Datagrid (through @ViewChild, template variables, ...) and to call `.dataChanged()` on it.
Fixes #140 (kinda).
NOTE: once this is merged in, I will add an example of this on the website's datagrid documentation. Which is going to start growing slightly to big, if we continue adding to it.
> [NG] Datagrid: expose a method to allow manual refresh

- src/clarity-angular/datagrid/_datagrid.clarity.scss
- src/clarity-angular/datagrid/datagrid.html
Tested on:
- Chrome
- FF
- Safari
- IE 10
- IE 11
- IE edge
Screenshots:
Resolves #395.
> [ui] Datagrid content should scroll within its container when content is too wide

- build/rollup-clarity.config.js
- src/clarity-angular/datagrid/datagrid-action-overflow.spec.ts
- src/clarity-angular/layout/main-container.ts
- src/clarity-angular/nav/clrResponsiveNavigationService.ts
- src/clarity-angular/nav/header.ts
- src/clarity-angular/nav/navLevelDirective.spec.ts
- src/clarity-angular/tree-view/providers/treeSelection.service.ts
- Removed BehaviorSubjects
- Exposed Observables instead of RXJS Subjects
Browser Tests: Chrome
Unit Tests:
MainContainer
✔ projects content
✔ toggles the ClrResponsiveNavCodes.NAV_CLASS_HAMBURGER_MENU class to the host when NAV_LEVEL_1 is passed
✔ toggles the ClrResponsiveNavCodes.NAV_CLASS_OVERFLOW_MENU class to the host when NAV_LEVEL_2 is passed
✔ removes the open trigger classes when NAV_CLOSE_ALL is passed
✔ adds the NAV_CLASS_HAMBURGER_MENU class when NAV_OPEN_LEVEL_1 is passed
✔ removes the NAV_CLASS_HAMBURGER_MENU class when NAV_CLOSE_LEVEL_1 is passed
✔ adds the NAV_CLASS_OVERFLOW_MENU class when NAV_OPEN_LEVEL_2 is passed
✔ removes the NAV_CLASS_OVERFLOW_MENU class when NAV_CLOSE_LEVEL_2 is passed
ResponsiveNavigationService
✔ #initializes an empty nav level list
✔ #registers …
> [NG] Responsive Nav - Expose Observables instead of Subjects

- build/tasks/karma.js
so that Travis build would fail if there's any test failure
> [core] Output non-zero exit code if unit tests fail

- src/clarity-angular/layout/_layout.clarity.scss
Creates a utility class `.u-main-container` which can be used as a wrapper in cases where the `.subnav` and the `.content-container` are not the direct children of the `.main-container`. The `.u-main-container` class is a vertical flex box which occupies the rest of the `100vh` after the `.header`.
Fixes: #481 
Tested on:
Chrome,
Firefox,
IE 10, 11
Edge
> [UI] Main Container Utility Class

- src/app/_utils/code.scss
Override z-index just for the docs so that the navigation remains accessible on smaller screens
Before:
After:
> [DOCS] Override Modal z-index for documentation

- src/clarity-angular/tooltips/_tooltips.clarity.scss
Added focus styles for tooltips.
Tested on: Chrome, IE 10, 11, Edge, Safari, Firefox
> [UI] Making tooltips accessible via keyboard

- src/clarity-angular/button-group/_button-group.clarity.scss
- src/clarity-angular/datagrid/_datagrid.clarity.scss
Earlier implementation was rendering inconsistently in browsers. Now using `display: flex` rather than a fixed value to change the margin.
Before:
After:
Also added some padding to datagrid's action bar.
Tested manually on:
- IE 10/11/Edge
- FF
- Chrome
- Safari
Note: the icons are not rendering in demo app but I am not including those icons in our component, as they are inside projected content, which should be added by the implementing app.
> [ui] fixed minor css bug in button group + added padding to datagrid's action bar

- README.md
- build/karma-test-shim.js
- src/app/index.html
- src/app/ng1.html
- src/clarity-angular/tree-view/providers/treeSelection.service.ts
It slept through the cracks because it was worked on in parallel of #400.
To avoid further issues, I removed the `main` configuration from all setups, so that using `import {} from "rxjs"` again will raise an actual error.
> [NG] Remove last import from RxJS' main

- src/clarity-angular/datagrid/built-in/comparators/datagrid-property-comparator.spec.ts
- src/clarity-angular/datagrid/built-in/comparators/datagrid-property-comparator.ts
The built-in datagrid property comparator handles comparison of undefined values, but not null values. This can lead to incorrect sorting if such values are present in the data source.
> [NG] Fix datagrid property comparator - handle null values

- src/clarity-angular/modal/modal.html
- src/clarity-angular/modal/modal.spec.ts
- src/clarity-angular/modal/modal.ts
- src/clarity-angular/wizard/wizard.spec.ts
The `(clrModelOpenChange)` output is now emitted when the modal has finished hiding, so that potential teardown or cleanup from the application isn't visible to the user.
Fixes #449.
> [NG] Modal: wait for the fade out animation before emitting output

- src/clarity-angular/forms/_forms.clarity.scss
Removed incorrect padding styles for input fields on Small screens
Before: 12px
After: 6px
> [UI] Input Fields Padding Fix

- src/pages/documentation/wizards.html
• Added a section in the wizard documentation to point out the workaround for two-way binding
• Able to be merged whenever.
Tested in:
✔︎ Chrome
Closes: #530
> [WEB] Add a note about the workaround for two-way binding old wizard

- src/clarity-angular/datagrid/_datagrid.clarity.scss
- src/clarity-angular/datagrid/datagrid-row.ts
- src/clarity-angular/forms/_radio.clarity.scss
Resolves #556.
Note that label inside radio/radio-inline class has a padding-left which is visually noticeable:
Should we override this padding for datagrid single select? Or do we want to provide input option for label for the radio buttons? Thoughts?
> [ng] Add clarity style to clrDgSingleSelected radio input

- src/clarity-angular/datagrid/_datagrid.clarity.scss
Fixes: #633 
Before:
After:
Tested on: IE10, 11, Edge, Safari, Firefox, Chrome
> [NG] Datagrid Filter Positioning Fix

- src/app/datagrid/sorting/sorting.html
- src/app/datagrid/sorting/sorting.ts
- src/clarity-angular/datagrid/datagrid-column.spec.ts
- src/clarity-angular/datagrid/datagrid-column.ts
- src/clarity-angular/datagrid/index.ts
- src/clarity-angular/datagrid/interfaces/sort-order.ts
- src/clarity-angular/datagrid/interfaces/state.ts
- src/clarity-angular/datagrid/providers/sort.spec.ts
- src/clarity-angular/datagrid/providers/sort.ts
Changing current datagrid-column implementation to take into account the reverse sorting order. 
Instead of introducing a new 2-way binding as advised in the original issue #586, I replaced the existing  boolean `[(clrDgSorted)]` by a number `[(clrDgSortOrder)]` one. I chose not to go with a `[(clrDgSortedReverse)]` 2-way binding for two main reasons:
- it would have complexify the usage of the datagrid component, by having to maintain 2 boolean flags for the same concept
- race conditions would have occurred when the value of each of those 2 flags changes: they are dependent on each other and there's no way to predict the order in which they are updated
Details about the proposed implementation:
- Introduced an exported const Enum `SortOrder` that defines the 3 possible
sorting states …
> [NG] Allow reverse order in datagrid 2-way binding sort attribute

- src/app/datagrid/sorting/sorting.ts
- src/clarity-angular/datagrid/interfaces/sort-order.ts
"Const enums can only use constant enum expressions and unlike regular enums they are completely removed during compilation."
reference: https://www.typescriptlang.org/docs/handbook/enums.html
> [ng] removing const in SortOrder enum so it's not removed during compilation

- src/app/button-group/angular/basic-structure/basic-button-group.html
- src/app/button-group/angular/basic-structure/basic-button-group.ts
- src/clarity-angular/button-group/button.spec.ts
- src/clarity-angular/button-group/button.ts
Fixes: https://github.com/vmware/clarity/issues/691
Added a `click` `EventEmitter` to the Angular `clr-button` component.
----EDIT----
Note: This PR only adds a `EventEmitter` for the `clr-button` component and not the `clr-button-group` component.
> [NG] Button Group Click Event Fix

- src/app/wizard/wizard-alt-cancel.demo.html
- src/app/wizard/wizard-alt-cancel.demo.ts
- src/app/wizard/wizard-async-validation.demo.html
- src/app/wizard/wizard-async-validation.demo.ts
- src/clarity-angular/modal/modal.ts
- src/clarity-angular/wizard/providers/wizard-navigation.ts
- src/clarity-angular/wizard/wizard.html
- src/clarity-angular/wizard/wizard.ts
These changes Address the following issues with the 0.9.0 wizard:
• an issue where and alt cancel routine was fired twice at the wizard level
• an issue where a page level alt cancel routine fired and was followed by a wizard level alt cancel
• an issue with enter and leave animations in the modal
To resolve this issue, I gave precedence to page level alt cancel routines. If the current page has defined either and preventDefault or stopCancel, it will prevent comparable events at the wizard level from firing. This was already the case for finish, previous, next, and danger buttons. The logic was not implemented for cancel buttons, however.
Tested in:
✔︎ Chrome
> [NG] Fixing alt cancel issue in new wizard

- src/app/datagrid/datagrid.demo.html
- src/app/datagrid/datagrid.demo.module.ts
- src/app/datagrid/datagrid.demo.routing.ts
- src/app/datagrid/preserve-selection/preserve-selection.html
- src/app/datagrid/preserve-selection/preserve-selection.ts
- src/clarity-angular/datagrid/_datagrid.clarity.scss
- src/clarity-angular/datagrid/datagrid-footer.spec.ts
- src/clarity-angular/datagrid/datagrid-footer.ts
- src/clarity-angular/datagrid/datagrid-items.spec.ts
- src/clarity-angular/datagrid/datagrid-items.ts
- src/clarity-angular/datagrid/datagrid.html
- src/clarity-angular/datagrid/providers/items.ts
- src/clarity-angular/datagrid/providers/selection.spec.ts
- src/clarity-angular/datagrid/providers/selection.ts
Before:
User selection was cleared whenever any change to items, filtering or page changes occurred.
After:
1. The selection is cleared when a new filter is applied on the datagrid
2. The selection is preserved when a page is changed
3. When the user uses `clrDgItems` or the smart datagrid, we make use of the trackBy function if provided to preserve selection from the updated items.
Issues:
We still have a `Expression has changed` issue on the demo that @youdz and I have to resolve.
UX Feedback:
@yen and @red have to discuss complex cases when the selection might have to be preserved after a filter has been applied. This PR is blocked until we get more info on which pattern to use.
> [NG] Datagrid Selection Clear - DO NOT MERGE

- src/clarity-angular/progress-bars/_progress-bars.clarity.scss
We can simply disable animation for when value=“0” to prevent the “negative” progress feel.
---
---
Resolves #380
Signed-off-by: Victor Mejia <victor.a.mejia@gmail.com>
> [UI] Progress bars: Fix reset animation

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- There is now a  -> running ng4 & Clarity 0.9.x
- Changed the legacy plunker to  -> running on ng2
closes #722, closes #721
> Updates links to the Clarity Plunkr's:

- src/clarity-angular/datagrid/providers/items.spec.ts
- src/clarity-angular/datagrid/providers/items.ts
- src/clarity-angular/datagrid/render/main-renderer.spec.ts
- src/clarity-angular/datagrid/render/main-renderer.ts
We were only listening to content children, but `*clrDgItems` render as part of the view.
Fixes #643, #623, #622.
Should be merged in both 0.9.1 and 0.8.16.
> [NG] Align columns with dynamically loaded *clrDgItems

- src/clarity-angular/datagrid/_datagrid.clarity.scss
- src/clarity-angular/datagrid/datagrid-footer.spec.ts
- src/clarity-angular/datagrid/datagrid-footer.ts
Fixes #730
Also fixes an existing bug with datagrid footer in IE10.
Before:
After:
Tested on:
IE10, 11, Edge, Chrome, Firefox, Safari
> [UI] Datagrid Footer CSS Bug Fixes

- src/app/iconography/icon-orientation.demo.html
- src/clarity-icons/clarity-icons.scss
Adds ability to flip icons vertically or horizontally. Thank you @Shijir for the hint 😄. Was not entirely sure how to word the usage example. Also, are the docs site in a separate repo?
Resolves #638
Signed-off-by: Victor Mejia <victor.a.mejia@gmail.com>
> [UI] Iconography: Ability to flip icons

- src/pages/documentation/iconography.html
- src/pages/get-started.html
- fixed interpolation issue on the Iconography page
Resolves https://github.com/vmware/clarity/issues/725
> [WEB] Updated the documentation on loading Clarity Icons in Typescript

- src/app/datagrid/binding-properties/binding-properties.html
- src/clarity-angular/datagrid/built-in/comparators/datagrid-property-comparator.spec.ts
- src/clarity-angular/datagrid/built-in/comparators/datagrid-property-comparator.ts
Default sort order for strings should be case-insensitive.
Resolves #491
Signed-off-by: Victor Mejia <victor.a.mejia@gmail.com>
> [NG] Datagrid: default case-insensitive order

- src/clarity-angular/datagrid/datagrid.spec.ts
- src/clarity-angular/datagrid/datagrid.ts
- src/clarity-angular/datagrid/render/render-organizer.ts
Adds a `resize` method on the datagrid component for users to be able to manually trigger the resizing the datagrid.
Note that I am using the `done` Observable. It wasn't just added for the test. Its coming with the datagrid placeholder fix anyway :-)
> [NG] Add a resize method on Datagrid

- src/clarity-angular/datagrid/datagrid-row.ts
Somehow this slipped through.
Fixes #718.
> [NG] Proper [attr.dir] binding on a clarity-icons caret

- src/styles/components.scss
Something in the layout changed that caused the NG/CSS/HTML logos to creep over into the margin. This change adjusts their positioning so they no longer creep over.
> [WEB] Adjusting right edge of the NG/CSS/HTML bugs

- src/clarity-angular/wizard/providers/wizard-navigation.ts
- src/clarity-angular/wizard/wizard-page.spec.ts
- src/clarity-angular/wizard/wizard-page.ts
• pageOnLoad was only being emitted on page.makeCurrent() which means we had two different outcomes for making a page current depending upon which method was used.
• this fix unites the two paths to make a page the current page and now pageOnLoad fires no matter how a page is made the current page.
Closes #765
NOTE: Depending on my meeting today with H5 devs, this may need to be released in a 0.9.2-alpha release...
> [NG] fixing pageOnLoad call in new wizard

- src/app/datagrid/datagrid.demo.html
- src/app/datagrid/datagrid.demo.module.ts
- src/app/datagrid/datagrid.demo.routing.ts
- src/app/datagrid/pagination-scrolling/pagination-scrolling.html
- src/app/datagrid/pagination-scrolling/pagination-scrolling.ts
- src/app/datagrid/test-cases-async/test-cases-async.html
- src/app/datagrid/test-cases-async/test-cases-async.ts
- src/app/datagrid/test-cases/test-cases.html
- src/app/datagrid/test-cases/test-cases.ts
- src/clarity-angular/datagrid/_datagrid.clarity.scss
- src/clarity-angular/datagrid/datagrid-placeholder.spec.ts
- src/clarity-angular/datagrid/datagrid-placeholder.ts
- src/clarity-angular/datagrid/datagrid.html
- src/clarity-angular/datagrid/providers/page.ts
- src/clarity-angular/datagrid/render/dom-adapter.ts
- src/clarity-angular/datagrid/render/main-renderer.ts
Fixes: #631, #583
Changes:
1. Moves the placeholder into the `.datagrid-body`
2. `.datagrid-body` is now `display: flex`. This helps to position to placeholder in the center of the body.
3. `main-renderer` now calculates and sets the height on paginated datagrids. This ensures that the datagrid height is consistent when pages are changed and when the items displayed are less/more that what the page height can support.
4. Removes the datagrid placeholder min height logic and the corresponding tests.
Tested on:
IE11, Edge, Chrome, Safari, Firefox
My VM kept freezing when I ran IE10 so couldn't test on that.
> [NG] Datagrid Placeholder Fix

- src/app/buttons/button-loading.html
- src/app/buttons/button-loading.ts
- src/app/buttons/buttons.demo.module.ts
- src/app/buttons/buttons.demo.routing.ts
- src/app/buttons/buttons.demo.ts
- src/clarity-angular/button-loading/index.ts
- src/clarity-angular/button-loading/loading-button.spec.ts
- src/clarity-angular/button-loading/loading-button.ts
- src/clarity-angular/clarity.module.ts
Leverages the `[clrLoading]` directive.
Wanted to get some input here. The injected `LoadingListener` in the `Loading` directive seems to be coming in as null: https://github.com/vmware/clarity/blob/master/src/clarity-angular/loading/loading.ts#L16
I'm unsure why, the new `LoadingButton` component here is implementing the `LoadingListener` abstract class. While trying to get it to work, I changed the type from `LoadingListener` to the `LoadingButton` type, and the instance seems to be injected fine. Any thoughts?
Resolves #463
Signed-off-by: Victor Mejia <victor.a.mejia@gmail.com>
> [NG] Buttons: allow spinner inside of button

- build/npm/clarity-angular.json
See its wiki page - https://github.com/rollup/rollup/wiki/jsnext:main
> [CORE] obsolete jsnext:main by pkg.module

- src/clarity-angular/datagrid/_datagrid.clarity.scss
- src/clarity-angular/datagrid/datagrid-column.ts
- Needed to define `[clrDgField]` input property before `[clrDgSortOrder]`
- Guarded against using undefined for Sort comparator
- Used "pointer" for the sortable column header hover cursor
> [NG] Fixes for #771 and #781

- src/clarity-angular/wizard/all.spec.ts
- src/clarity-angular/wizard/providers/button-hub.spec.ts
- src/clarity-angular/wizard/providers/header-actions.spec.ts
- src/clarity-angular/wizard/providers/wizard-navigation.spec.ts
- src/clarity-angular/wizard/providers/wizard-navigation.ts
- src/clarity-angular/wizard/wizard.ts
• this also uncovered a number of odd issues with the logic around the alt-next changes, yay for unit testing!
[NG] header action service tests fixed and running
• i also fixed some tests that recent changes broke with the button hub service
> [NG] wizard provider tests fixed and running

- src/clarity-angular/wizard/wizard-page.spec.ts
- src/clarity-angular/wizard/wizard-page.ts
• this is partly a bug and partly an enhancement.
• some people were using array indices as their ids but WizardPage was only set up to handle strings being passed to it. this fixes that.
• unit tests too! because TDD, yo!
> [NG] allowing numeric ids for wizard pages

- src/clarity-angular/datagrid/_datagrid.clarity.scss
- src/clarity-angular/datagrid/datagrid-action-overflow.ts
- src/clarity-angular/datagrid/datagrid-filter.ts
- src/clarity-angular/datagrid/datagrid.html
- src/clarity-angular/dropdown/dropdown.ts
- src/clarity-angular/popover/popover.directive.spec.ts
- src/clarity-angular/popover/popover.directive.ts
- src/clarity-angular/popover/popover.spec.ts
- src/clarity-angular/popover/popover.ts
- src/clarity-angular/tooltips/tooltip.ts
Addressed in this commit are:
- change in popover to allow multiple to be open (thru options)
- ui/ng change to prevent filter popovers from shifting when the loading spinner is on (i.e. refactor loading spinner to not rely on datagrid class having `position:relative`)
- changing popover implementation to close on scroll (as per discussion with @reddolan)
Fixes #668 and #706.
> [ng] allow multiple filters to be open

- src/clarity-angular/tooltips/_tooltips.clarity.scss
• this was only affecting some browsers, not all
Tested in:
✔︎ Chrome
✔︎ Firefox
Closes: #734
> [ICONS,UI] getting rid of icon hints in tooltip hovers

- src/app/wizard/wizard-alt-next.demo.ts
- src/app/wizard/wizard-async-validation.demo.ts
- src/app/wizard/wizard-custom-buttons.demo.ts
- src/app/wizard/wizard-force-forward.demo.html
- src/app/wizard/wizard-force-forward.demo.ts
- src/app/wizard/wizard-options.demo.ts
- src/app/wizard/wizard-reset.demo.ts
- src/app/wizard/wizard.demo.module.ts
- src/app/wizard/wizard.demo.routing.ts
- src/app/wizard/wizard.demo.ts
- src/clarity-angular/wizard/_wizard.clarity.scss
- src/clarity-angular/wizard/providers/page-collection.mock.ts
- src/clarity-angular/wizard/providers/page-collection.spec.ts
- src/clarity-angular/wizard/providers/page-collection.ts
- src/clarity-angular/wizard/providers/wizard-navigation.spec.ts
- src/clarity-angular/wizard/providers/wizard-navigation.ts
- src/clarity-angular/wizard/wizard-header-action.ts
- src/clarity-angular/wizard/wizard-page.spec.ts
- src/clarity-angular/wizard/wizard-stepnav-item.spec.ts
- src/clarity-angular/wizard/wizard-stepnav-item.ts
- src/clarity-angular/wizard/wizard.ts
• adds a forceForward input to the wizard that marks pages incomplete when navigating backwards. useful for when you need to do validation on the primary button click of every page.
• fixes an issue where step-nav items that could not be navigated to but could still get focus
• fixes an issue where reset was happening before the last page was committed, meaning the final page would show up completed even after reset
• fixes an issue where users could not click not the step nav item to navigate to the next step
Closes: #610, #784
[NG] wizard bifurcating next/finish from wizard calls
• adding ability to pass a boolean to wizard.next() and wizard.finish() to avoid running event emissions and checks. this can cause an event loop if fired from …
> [NG] wizard force forward feature and nav fixes

- src/clarity-angular/utils/testing/helpers.spec.ts
- src/clarity-angular/utils/testing/slow-specs.spec.ts
• to use this, all you need to do is uncomment two lines in the helper spec
• I wanted to push this so that it didn't atrophy on my branch
• I'm going to use it in the future to help speed up our unit tests
> [CORE] optional spec helper to log how long it takes our unit tests run

- src/app/datagrid/test-cases-async/test-cases-async.html
- src/app/datagrid/test-cases-async/test-cases-async.ts
- src/app/datagrid/test-cases/test-cases.html
- src/app/datagrid/test-cases/test-cases.ts
- src/clarity-angular/datagrid/_datagrid.clarity.scss
- src/clarity-angular/datagrid/datagrid.html
CSS fix to the datagrid placeholder for loading indications. 
Also included are changes to the test cases, test cases async for testing _loading spinner_  in a variety of conditions. Thanks @adityarb88 for those pages.
- closes #847
> [NG] Fixes datagrid error when loading active

- src/clarity-angular/data/datagrid/_datagrid.clarity.scss
I missed something or changed something in my code and didn't re-check the vertical scrolling with the fix for #847. 
This fix makes fixed height datagrids have vertical scrolling.  
> [NG] Fixes vertical scrolling for fixed height datagrids

- src/clarity-angular/data/datagrid/_datagrid.clarity.scss
Tested on Chrome, FF, Safari, IE11, Edge
(Safari has issues with `flex: 0 auto` and `height: 100%` hence the `min-height` and bitly link)
> [NG] Fixes height of datagrid when it has a fixed height

- src/app/documentation/demos/header/header.demo.html
• see attached screenshots
• added a responsive section on headers page that links to responsive nav dox
• turned plain link in code section to an info alert
> [WEB] improved responsive nav links in header dox

- src/app/forms/form-grid-validation/form-grid-validation.demo.html
- src/app/forms/form-grid-validation/form-grid-validation.demo.scss
- src/app/forms/form-grid-validation/form-grid-validation.ts
- src/app/forms/forms.demo.module.ts
- src/app/forms/forms.demo.routing.ts
- src/app/forms/forms.demo.ts
- src/clarity-angular/forms/_forms.clarity.scss
Remove `position: relative` from `.form-group` and the first `label` inside of forms in grids only.
This PR fixes clipping issues when you use tooltips inside of forms in grids.
Note:
1. Regular forms don't fix this problem yet. Fixing clipping issues with regular forms might be a breaking change. More info here #932
2. I am not sure if we have the tooltip angular component working for validation. So as of now I believe that validation messages clip inside of forms in an overflowing container. We need to check whether our angular tooltips support validation and if not then file an issue for adding that feature.
1. No clipping
2. Wrapping
Tested on:
Chrome, Firefox, Safari, IE 11, Edge
> [UI] Remove position: relative from forms in grid only

- build/karma-test-shim.js
- build/karma.conf.js
- build/npm/clarity-icons.json
- build/tasks/bundle.js
- package.json
- src/app/index.html
- src/app/ng1.html
- src/clarity-icons/clarity-icons-api.ts
- src/clarity-icons/clarity-icons-element.ts
- src/clarity-icons/clarity-icons.spec.ts
- src/clarity-icons/index.ts
- src/typings.d.ts
• allows for the assigning of any white-listed html element to the ClarityIcons namespace
• sanitization added for increased security
• existing unit tests updated and new unit tests added
[ICONS] wip
[ICONS] wip
[ICONS] wip -- build working
[ICONS] wip - working global
[ICONS] wip - working with imports
[ICONS] wip
[ICONS] wip
[ICONS] wip
> [ICONS] Added ability to assign non-SVG templates to ClarityIcons namespace

- src/app/datagrid/selection/selection.html
- src/clarity-angular/data/datagrid/datagrid-column-toggle.spec.ts
- src/clarity-angular/data/datagrid/datagrid-column-toggle.ts
- src/clarity-angular/data/datagrid/datagrid-footer.spec.ts
- src/clarity-angular/data/datagrid/datagrid-footer.ts
- src/clarity-angular/data/datagrid/datagrid.ts
- closes #950
- Fixes issue with  component when using  on the datagrid itself that casued  error
I had to make a change to the footer spec related to using ChangeDetectorRef to manage updates to the child component. I'm not 100% sure its the right way to use it in testing. 
Tested in Chrome, Firefox, Safari, Edge & IE11
> [NG] Add change detector ref to footer

- src/app/button-group/angular/basic-structure/basic-button-group.html
- src/clarity-angular/button/button-group/button.ts
Fixes: #1009
Added type, name and disabled attribute for `clr-button`
Tested on Chrome, Firefox, Safari, IE11, Edge
> [NG] Add disabled, type & name attr to clr-button

- build/tasks/gemini.js
It looks like Gemini removed the html reporter recently: 
https://github.com/gemini-testing/gemini/commit/e2613e4c80f013902f3f8df3a92e0bd37fa1d2c4
I'm not sure if we need/use the html reporter but this PR will allow builds to run gemini tests again until we change the gemini setup.
> [CORE] Remove the html reporter from gemini test command.

- src/app/datagrid/selection/selection.html
- src/clarity-angular/data/datagrid/providers/hideable-column.service.spec.ts
- src/clarity-angular/data/datagrid/providers/hideable-column.service.ts
- Adds a guard to getColumnById lookup
- Adds a test for getColumnById fn (both defined and undefined hideable columns
- closes #837
> [NG] Fixes HideableColumnService error when looking up by undefined id

- src/clarity-angular/popover/signpost/signpost.specs.ts
- src/clarity-angular/popover/signpost/signpost.ts
- Reverses the popoverPoint for `left-top` and `left-bottom` them so that the left-top is above trigger and left-bottom is below the trigger
- updates specs accordingly
> [NG] Fix 2 incorrect signpost positions

- .travis.yml
- build/tasks/gemini.js
- This uses an older version of gemini until we can work out why the html-reporter plugin is not working with the v5x alpha
> [CORE] Use gemini version 4.19.3

- src/app/spinners/spinner-sizes.html
- src/app/spinners/spinner.demo.scss
- src/clarity-angular/progress/spinner/_spinner.clarity.scss
Fixes: #1044 
Before:
After:
Note: The change to the demo html is because the code snippets were not rendering properly.
> [UI] Fixed the size of large spinners

- .gemini.conf.yml
- .travis.yml
- build/tasks/gemini.js
Updates the build process for `gemini, gemini config and travis config` to allow us to run the latest gemini with the `html-reporter` plugin.
> [CORE] Adds html-reporter plugin for gemini@latest

- src/clarity-angular/data/datagrid/_datagrid.clarity.scss
Applies to action-items in an acton-overflow component and closes #1085
- Chrome
- Safari
- Firefox
- IE11
- Edge
> [NG] Adds disabled pseudo-class for disabled action-items

- build/tasks/bundle.js
They were named XXX.umd.js, but were self-executing. That means whatever the internal format was, it didn't matter, you would never import anything from them. If we plan on shipping actual UMD bundles that do not do anything until imported, we need to rename the self-executing bundles first.
Plz no :trollface:.
> [BREAKING CHANGE][CORE] Rename SFX icons bundles

- src/clarity-angular/wizard/providers/wizard-navigation.spec.ts
- src/clarity-angular/wizard/providers/wizard-navigation.ts
> [NG] fixing double onCommit event firing with AltNext Wizard

- src/app/documentation/demos/alert/static/alert-modals.demo.html
Updated examples of alerts in modals on web dox to show proper placement below modal title, instead of above it.
> [WEB] updating examples of alerts in modals

- src/app/index.html
Short and simple. All this does is change umd -> min for the clarity-icons-lite script link in the demo app we use for dev. 
> [CORE] Updates link in demo app to s/min/umd/g for clarity-icons-lite.

- src/app/documentation/demos/code/code-highlight-snippet.ts
- '{' and '}' make code highlight example break (angular reporst template syntax error)
- use '&#' style to escape
Signed-off-by: Seven Lju <dna2gle@gmail.com>
> [WEB] bugfix: Code Highlight example not work

- src/clarity-angular/popover/dropdown/dropdown.spec.ts
- src/clarity-angular/popover/dropdown/dropdown.ts
- Uses a subscription to IfOpenService.openChange
- Unsubscribes in ngOnDestroy
- closes #1195
- We talked about implementing this unsubscribe pattern before and since the `IfOpenService.openChange` observable is of the type infinate value I used the takeUntil operator / pattern for unsubscribe. I can unsubscribe the old way if we do not want to do this pattern here. 
- There are a few formatting changes in `dropdown.spec.ts` as I try to get the files to the formatting standard we discussed (no spaces in the import braces).
> [NG] Emit clrDropdownOpenChange state on changes:

- build/write-svg-icons.js
Fixes #1026
(One on the left side is the screenshot taken before the fix.)
> [ICONS] added transparent bg in printed SVGs

- src/releases/0.10/0.10.0-alpha.2.html
- src/releases/0.10/0.10.0-alpha.5.html
with more complete deprecated input/output info for tabs.
> [web] updating 0.10.0-alpha.5 doc 

- build/karma.conf.js
It seems like headless Chrome is supported in Linux/Windows/Mac with latest versions of Chrome. Removing conditional logic to run karma tests with Canary in local env. Devs should install the latest version of Chrome to run unit tests locally.
> [core] Use headless Chrome in all OSs for unit tests

- src/clarity-icons/clarity-icons-element.ts
> [ICONS] make Safari's HTMLElement.prototype.constructor writable in iOS 9.x

- src/clarity-icons/clarity-icons-element.ts
Backporting https://github.com/vmware/clarity/pull/1301 to v0.9
> [ICONS] make Safari's HTMLElement.prototype.constructor writable

- src/clarity-angular/data/stack-view/_stack-view.clarity.scss
When the content of the stack-view appears to be too long in some of the
browsers it doesn't fit in the container and scrollers appear.
This will:
* Allow the browser to brake unbreakable words, so the content fits in the container
* Avoid appearance of the scrollers around the stack-view
Fixes #1304
Before:
After:
> Improve the word wrapping of the stack-view

- src/clarity-angular/data/datagrid/render/row-renderer.ts
For some reason we missed it when it was removed in 9581b7e6b552b2045b8de3eb2f9be96fd3522747. We need to be more careful with 2k-lines reviews.
Fixes #1417.
> [NG] Put back the unsubscription in the row renderer

- build/compile-ts.js
- package.json
- src/clarity-angular/data/datagrid/datagrid.spec.ts
- src/clarity-angular/data/datagrid/datagrid.ts
- yarn.lock
This allows you to set the `clrDgSingleSelected` value to null, and clear the selection of that row. The previous check did not account for going from selected to null if you passed a non-truthy value.
It also adds plumber to the typescript gulp task so it doesn't die so easily on compile errors.
> [NG] fix datagrid single selection to deselect when value is set to null

- src/app/documentation/demos/signposts/signpost.demo.html
This PR addresses three typos on the `Signpost` documentation page.
Signed-off-by: Matt Hippely <hippely@gmail.com>
> [WEB] Fixes typos in Signpost documentation.

- src/clarity-angular/button/_buttons.clarity.scss
Icon Buttons Fix for min-width. `min-width: unset` doesnt work on IE. Overriding with `min-width: 0`
Tested on IE11, Edge, Safari, Firefox, Chrome
> [UI] Icon Buttons Fix

- src/clarity-angular/modal/modal.spec.ts
- src/clarity-angular/modal/modal.ts
> [NG] Fixes the undefined FocusTrap when a modal is closed

- src/clarity-angular/data/datagrid/built-in/filters/datagrid-string-filter.spec.ts
- src/clarity-angular/data/datagrid/datagrid-column.spec.ts
- src/clarity-angular/data/datagrid/datagrid-filter.spec.ts
- src/clarity-angular/data/datagrid/datagrid-footer.spec.ts
- src/clarity-angular/data/datagrid/datagrid-hideable-column.directive.spec.ts
- src/clarity-angular/data/datagrid/datagrid-hideable-column.spec.ts
- src/clarity-angular/data/datagrid/datagrid-items.spec.ts
- src/clarity-angular/data/datagrid/datagrid-pagination.spec.ts
- src/clarity-angular/data/datagrid/datagrid-placeholder.spec.ts
- src/clarity-angular/data/datagrid/datagrid-row-detail.spec.ts
- src/clarity-angular/data/datagrid/datagrid-row.spec.ts
- src/clarity-angular/data/datagrid/datagrid.spec.ts
- src/clarity-angular/data/datagrid/datagrid.ts
- src/clarity-angular/data/datagrid/providers/filters.spec.ts
- src/clarity-angular/data/datagrid/providers/filters.ts
- src/clarity-angular/data/datagrid/providers/items.spec.ts
- src/clarity-angular/data/datagrid/providers/page.spec.ts
- src/clarity-angular/data/datagrid/providers/page.ts
- src/clarity-angular/data/datagrid/providers/selection.spec.ts
- src/clarity-angular/data/datagrid/providers/sort.spec.ts
- src/clarity-angular/data/datagrid/providers/sort.ts
- src/clarity-angular/data/datagrid/providers/state-debouncer.provider.ts
- src/clarity-angular/data/datagrid/providers/state.provider.ts
- src/clarity-angular/data/datagrid/render/header-renderer.spec.ts
- src/clarity-angular/data/datagrid/render/row-renderer.spec.ts
Our previous solution actually emitted too late, which broke
server-driven datagrids that relied on the `[clrDgLoading]` input.
~Also fixes #1099 as a nice side-effect.~ My bad, it didn't.
I am not 100% happy with this pattern, having to remember to call `changeStart()` and `changeDone()` everywhere is tedious, but at the same time allows us to catch more of these cases if they come from somewhere else the the 3 main state providers. I tried using zones for this, only emitting when they were no more microtasks left, but Angular subscribes before us so change detection happens before we can emit (subscribers are called in order).
Also, it's pretty painful to add a single provider anywhere in the Datagrid right now, we have to go through dozens of spec files to update them. We need to …
> [NG] Properly debounce state changes for Datagrid

- src/clarity-angular/wizard/providers/button-hub.mock.ts
- src/clarity-angular/wizard/providers/button-hub.ts
- src/clarity-angular/wizard/wizard-button.spec.ts
- src/clarity-angular/wizard/wizard-button.ts
- src/clarity-angular/wizard/wizard.ts
The problem was in the lifecycle of the buttons the host binding for isHidden on a button would flip between true/false, due to the change of state in the navigation service provider. This delays the evaluation of the button's host binding until later in the cycle.
closes #1439
> [NG] fix wizard issue where buttons with NgIf would throw expression has changed error

- .github/ISSUE_TEMPLATE.md
This will update the issues template with new plunker links for Latest and v0.9.20.
> [CORE] Update plunker links in issues template.

- src/app/tabs/tabs-angular.demo.html
- src/clarity-angular/data/datagrid/helpers.spec.ts
- src/clarity-angular/data/datagrid/render/body-renderer.spec.ts
- src/clarity-angular/data/datagrid/render/cell-renderer.spec.ts
- src/clarity-angular/data/datagrid/render/head-renderer.spec.ts
- src/clarity-angular/data/datagrid/render/header-renderer.spec.ts
- src/clarity-angular/data/datagrid/render/row-master-renderer.spec.ts
- src/clarity-angular/data/datagrid/render/row-renderer.spec.ts
- src/clarity-angular/data/datagrid/render/table-renderer.spec.ts
- src/clarity-angular/layout/tabs/chocolate/active-oompa-loompa.ts
- src/clarity-angular/layout/tabs/chocolate/tabs-willy-wonka.ts
- src/clarity-angular/layout/tabs/index.ts
- src/clarity-angular/layout/tabs/tab-content.spec.ts
- src/clarity-angular/layout/tabs/tab-content.ts
- src/clarity-angular/layout/tabs/tab-link.directive.spec.ts
- src/clarity-angular/layout/tabs/tab-link.directive.ts
- src/clarity-angular/layout/tabs/tab.spec.ts
- src/clarity-angular/layout/tabs/tabs.spec.ts
- src/clarity-angular/layout/tabs/tabs.ts
#1514 introduced chocolate errors in tabs. So I reverted it and rewrote a new fix for #1318.
As now standard with chocolate errors, we let Willy Wonka and the Oompa Loompas handle it. The actual fix is 10 lines long, but I wanted to add unit tests for it and got sucked in when trying to improve the helpers slightly. So there is a bunch on non-related tests cleanups, all revolving around stronger, safer typing.
> Tabs chocolate

- src/app/datagrid/datagrid.demo.html
- src/app/datagrid/datagrid.demo.module.ts
- src/app/datagrid/datagrid.demo.routing.ts
- src/app/datagrid/selection-row-mode/selection-row-mode.html
- src/app/datagrid/selection-row-mode/selection-row-mode.ts
- src/clarity-angular/data/datagrid/datagrid-action-overflow.spec.ts
- src/clarity-angular/data/datagrid/datagrid-row.spec.ts
- src/clarity-angular/data/datagrid/datagrid-row.ts
- src/clarity-angular/data/datagrid/datagrid.html
- src/clarity-angular/data/datagrid/datagrid.ts
- src/clarity-angular/data/datagrid/providers/selection.ts
Implementation of whole row selection
* New `clDgRowSelection` input property for Datagrid indicating if the row selection should be enabled.
Selection works the same way if you click on the input in the first column.
For Multi selection on second click the row gets deselected.
* New `clDgRowSelection` input property for Datagrid indicating if the selection column should be available
This automatically turns on `clDgRowSelection` in case of Single and Multi selection
* Added support for row actions in case of Row selection enabled
* Added "Selection (Row mode)" demo page on Datagrid demo page with examples of the newly introduced functunality
Fixes #476
Signed-off-by: Mincho Tonev <mtonev@vmware.com>
> Implementation of whole row selection 

- src/app/documentation/demos/tables/tables.demo.html
[Docs] Fix escaped code tag
A `<code>` tag was escaped in the documentation for Compact Tables.
> [Docs] Fix escaped code tag

- src/clarity-angular/utils/focus-trap/focus-trap.directive.ts
- Addresses use cases for IE11 where the `FocusTrap._previousActiveElement` may not have the focus method
- Closes #1587
> Adds focus method detection to FocusTrap

- CONTRIBUTING.md
[CORE] Mention location of documentation website in CONTRIBUTING.md
The documentation for clarity is provided by the https://vmware.github.io/clarity/documentation/ website.  This is stored in this repository under the `new-website` branch, which is not indexed by github, so searching for text snippets from the documentation will not return any results.  This adds a brief mention to `CONTRIGBUTING.md` which tells people where to look for the documentation if they need to propose changes. 
> [CORE] Mention location of docs in CONTRIBUTING.md

- src/clarity-icons/clarity-icons.scss
> Allowing non-SVG items added to Clarity Icons to be sized

- src/app/documentation/demos/app-layout/app-layout.demo.html
- src/app/documentation/demos/app-layout/app-layout.demo.ts
- src/app/documentation/demos/color/color-palette.ts
• updated color palette with #737373
• #747474 was incorrectly indicated as being accessible vs. #fafafa; it is not
• updated app-layout dox with info about rem units and using them to update layout
Tested in:
✔︎ Chrome
> [WEB] Update website with rem unit info

- src/app/tooltips/tooltips-angular.html
- src/clarity-angular/popover/tooltip/_tooltips.clarity.scss
Fixes: #1617 
Before:
After:
Tested on Chrome, Firefox, Safari
> [UI] Tooltip in Dropdown Wrap Fix

- karma.conf.js
- src/clarity-angular/wizard/wizard.spec.ts
- src/clarity-angular/wizard/wizard.ts
The wizard API is used everywhere to verify behavior, and when you use the two way binding directly to toggle the wizard it was not setting the buttons to ready state. This adds a setter for the clrWizardOpen binding.
We didn't have any tests on the clrWizardOpen binding, so added one to guard against it in the future. Also set mocha reporter to ignore skipped.
closes #1615, related to 4610fd46e3dfcc9c4e4766b42da3a399c1216c31.
> [NG] set buttons to ready when using the clrWizardOpen binding

- src/clarity-angular/popover/dropdown/dropdown-menu.ts
- src/clarity-angular/popover/signpost/signpost-content.ts
- src/clarity-angular/popover/tooltip/tooltip-content.ts
Throw error when:
1. `clr-dropdown-menu` is used outside of `clr-dropdown`
2. `clr-signpost-content` is used outside of `clr-signpost`
3. `clr-tooltip-content` is used outside of `clr-tooltip`
> [NG] Flag Popover outside of Host

- src/clarity-angular/wizard/_wizard.clarity.scss
> [UI] Fix Spinner Positioning Issue in Wizards

- src/clarity-angular/wizard/wizard-button.spec.ts
- src/clarity-angular/wizard/wizard-button.ts
Tested in Chrome, FF, IE11, and Edge.
Fixes: #1551
Signed-off-by: Brian Duncan <bduncan@vmware.com>
> [NG] Set disabled attribute when clrWizardButtonDisabled is true

- package.json
New flagship feature of ng-packagr are secondary entrypoints
- https://github.com/dherges/ng-packagr#secondary-entry-points
- https://github.com/dherges/ng-packagr/pull/184
Do you plan to follow the [Angular Material style of splitting up the library into sub-packages](https://github.com/angular/material2/blob/master/CHANGELOG.md#breaking-changes-2)?
> [NG] update dependency ng-packagr to ^1.5.0

- src/clarity-angular/data/datagrid/render/column-resizer.spec.ts
- src/clarity-angular/data/datagrid/render/column-resizer.ts
Fixes #1537
Fixes #1666 
This PR fixes the problem that Datagrid columns instantiate even when it's in a hidden state modal. As such, it tries to call methods in our DomAdapter, which returns `Nan` as the dom is not yet rendered. The solution I am providing here is that it will call the DomAdapter methods only on the first drag attempt by a user after the Datagrid is fully rendered. 
One of the unit tests check that if it sets the minumum width only after the first drag attempt (`dragStartHandler()`). I have added one more unit that makes sure that if one column keeps expanding, the other columns shouldn't shrink beyond its minimum width. Also, I've fixed some typos in the unit tests.
Tested on: Chrome, Firefox, Safari, Edge, IE.
> [NG] access the minimum width only on the first drag attempt

- src/clarity-angular/utils/scrolling/scrolling-service.spec.ts
- src/clarity-angular/utils/scrolling/scrolling-service.ts
instead of @angular/platform-browser. NG5 support.
Signed-off-by: Chris Ha <chunghha@users.noreply.github.com>
> [NG] Import DOCUMENT from @angular/common

- src/clarity-angular/wizard/_wizard.clarity.scss
- closes #1711
Tested in:
- Chrome
- Safari
- Firefox
- IE 11
- Edge
> [NG] Adjust step nav height for inline wizards.

- src/clarity-angular/layout/tabs/tab-link.directive.spec.ts
- src/clarity-angular/layout/tabs/tab-link.directive.ts
- src/clarity-angular/layout/tabs/tab.spec.ts
- src/clarity-angular/layout/tabs/tabs-id.provider.ts
- src/clarity-angular/layout/tabs/tabs.spec.ts
- src/clarity-angular/layout/tabs/tabs.ts
- src/ks-app/src/app/containers/nav/tabs.component.html
- Fixes 1494
Tabs component will now only project its immediate TabLinkDirectives.  
Before:
After:
Preview: http://nested-tabs-demo.surge.sh/tabs
> [NG] Fix nested tabs link

- src/clarity-angular/progress/spinner/_variables.spinner.scss
This fixes the light theme spinner with the correct snake color. 
> [UI] Fixes light theme spinner color

- package-lock.json
- package.json
- src/clarity-angular/data/datagrid/render/noop-dom-adapter.spec.ts
- src/clarity-angular/emphasis/alert/alerts.spec.ts
- src/clarity-angular/emphasis/alert/alerts.ts
- src/clarity-angular/layout/tabs/tabs.spec.ts
• previously only recognized “info” and such
• now recognizes both “info” and deprecated “alert-info” alert types
• also added tests for this functionality
Tested in:
✔︎ Chrome
Closes: #1747
> [NG] Update global alerts pager to recognize deprecated alert types

- src/clarity-angular/utils/_theme.dark.clarity.scss
- Dark theme can use `.header-6` for an additional dark theme nav header
- closes #1749
> [UI] Adds additional header color to dark theme

- src/clarity-angular/data/datagrid/datagrid-cell.ts
- src/clarity-angular/data/datagrid/datagrid.spec.ts
- src/ks-app/src/app/containers/data/datagrid.component.html
- Fixes 1069
Datagrid cell was throwing a 🍫  error when a user sets columns hidden by default. The main reason was that mapping the cell with the corresponding column header was taking place after the cell's view was checked and as a result, the cell properties had to change. 
This PR solution is to give the hidden class to a cell only after the mapping process completes with the help of `Renderer2`.
I have added one unit test that makes sure there is no 🍫  error when the columns are hidden by default. Also, I have done a manual testing in our `ks-app`.
> [NG] fix chocolate error in columns hidden by default

- npm/clarity-ui/package.json
This updates the Clarity-ui `peerDependencies` with the version of bootstrap needed.
- Closes #1769
> [UI] Adds bootstrap as a peer dependency for clarity-ui 

- src/clarity-angular/progress/progress-bars/_progress-bars.clarity.scss
• I went with the direct edit to the top positioning of the inner looping progress bar because it was a more surgical, precise edit.
• Changing vertical alignment, positioning, and max-height led to unintended regressions in static/inline progress bars. It was also more complicated due to the relationship of the heigh/max-height values.
• I also fixed the percent label that can be displayed on progress bars in the dark theme. It was being set to #565656. I changed that.
Closes: #1785
Tested in:
✔︎ Chrome
✔︎ Firefox
✔︎ Safari
✔︎ IE11
✔︎ Edge
> [UI] remUnits pushed looping progress bar down

- src/clr-angular/data/datagrid/datagrid-action-overflow.ts
I also checked: 
- HeadableColumn toggle
- ExpandableRow toggle
- Filter toggle
- Sort toggle
- ColumnResizer handle
and they were of `type"button". 
- closes #1781
> [NG] Adds type to datagrid-action-toggle buttons.

- src/clr-angular/data/datagrid/_datagrid.clarity.scss
- src/clr-angular/data/datagrid/_variables.datagrid.scss
- src/clr-angular/utils/_theme.dark.clarity.scss
- Adds background color to datagrid in loading state (closes #1795)
- Updates drop-shadow color for dropdowns
Tested on:
- Chrome
- Safari
- Firefox
- IE11
- Edge
> [UI] Updates dark theme color issues

- src/clr-angular/button/_toggles.clarity.scss
This change allows labels to be placed after toggle switches when they are given the .right-label class. This is in response to #1778.
This is my first pull request for the clarity project, please let me know if changes need to be made.
Note: I added the DCO. So the original pull request can be closed. Sorry about that.
> Add Right-Labeled Toggle Switch

- src/app/icons/icons-api/icons-api.component.html
- src/app/icons/icons-get-started/icons-get-started.component.html
This seems like a common mistake so I thought it would make sense to add another brief warning in the custom icon page.
#689
vmware/clarity-seed#63
(https://github.com/vmware/clarity/pull/1818 was the same pull request but I forgot the DCO).
> Note importance of not double-importing clarity-icons

- src/clr-angular/button/button-group/button-group.module.ts
- src/clr-angular/button/button-loading/loading-button.module.ts
- src/clr-angular/code/syntax-highlight/syntax-highlight.module.ts
- src/clr-angular/data/datagrid/datagrid.module.ts
- src/clr-angular/data/stack-view/stack-view.module.ts
- src/clr-angular/data/tree-view/tree-view.module.ts
- src/clr-angular/deprecations.spec.ts
- src/clr-angular/emphasis/alert/alert.module.ts
- src/clr-angular/forms/checkbox/checkbox.ts
- src/clr-angular/forms/forms.module.ts
- src/clr-angular/icon/icon.module.ts
- src/clr-angular/layout/nav/navigation.module.ts
- src/clr-angular/layout/tabs/tabs.module.ts
- src/clr-angular/layout/vertical-nav/index.ts
- src/clr-angular/layout/vertical-nav/vertical-nav.module.ts
- src/clr-angular/modal/modal.module.ts
- src/clr-angular/popover/dropdown/dropdown.module.ts
- src/clr-angular/popover/signpost/signpost.module.ts
- src/clr-angular/popover/tooltip/tooltip.module.ts
- src/clr-angular/utils/loading/loading.module.ts
- src/clr-angular/wizard/wizard.module.ts
- src/ks-app/package.json
It appears that something in the build chain tree-shakes unused variables. To address this, exporting a class that extends another does not tree-shake the objects.
> [NG] update deprecated exports to not be tree shaken

- src/releases/0.11/0.11.0-beta.1.html
- Fixed the scope name to the correct name `@clr`
- Adds a breaking change note for the peerDependency bump to Angular 5
- closes #1828
> [WEB] Fixes Clarity v11 release notes

- package-lock.json
- src/app/datagrid/datagrid.demo.html
- src/app/datagrid/datagrid.demo.scss
- src/app/datagrid/inventory/inventory.ts
- src/app/datagrid/selection-single/selection-single.html
- src/app/datagrid/selection-single/selection-single.ts
- src/app/datagrid/selection/selection.html
- src/app/datagrid/selection/selection.ts
- src/app/datagrid/sorting/sorting.ts
- src/app/tree-view/utils/example.ts
- src/clr-angular/data/datagrid/all.spec.ts
- src/clr-angular/data/datagrid/datagrid-items-trackby.spec.ts
- src/clr-angular/data/datagrid/datagrid-items-trackby.ts
- src/clr-angular/data/datagrid/datagrid-row.ts
- src/clr-angular/data/datagrid/datagrid.module.ts
- src/clr-angular/data/datagrid/providers/items.ts
- src/clr-angular/data/datagrid/providers/selection.spec.ts
- src/clr-angular/data/datagrid/providers/selection.ts
- src/clr-angular/data/datagrid/render/main-renderer.spec.ts
- src/clr-angular/data/datagrid/render/row-renderer.spec.ts
This will update the current value instance when new items are set, such as from pagination, by using trackby to ensure that current array or item maps correctly to the instances of the currently displayed items.
It does this by always updating the `current` or `currentSingle` value with the updated instance if it could be matched based on the trackBy. This way our current equality checks work and the only time that we have to do lookups is during setting the state of a selected item. Gets should remain as fast as before.
There are 8 scenarios for selection and pagination that we can properly support. They are the following four scenarios for both single and multi-selection (2x4=8, yay math). There are explicit unit tests for each of these 8 scenarios.
* client side, no trackBy
* client …
> [NG] fix selection with pagination in datagrid

- CONTRIBUTING.md
This adds brief instructions to CONTRIBUTING.md on how to serve up the documentation website locally. 
This is half of a proposed fix to the issue mentioned by @adityarb88 here: https://github.com/vmware/clarity/issues/1820#issuecomment-354438343 
The other half is a pull request against the `new-website` branch here: https://github.com/vmware/clarity/pull/1823
> [Docs] Add note on serving documentation locally

- package.json
Users should now be able to run npm start to serve up the documentation locally.  This is half of a proposed fix to the issue mentioned by @adityarb88 here: https://github.com/vmware/clarity/issues/1820#issuecomment-354438343
> [Docs] Add template generation to npm start script

- src/app/buttons/button-loading.html
- src/app/buttons/button-loading.ts
- src/clr-angular/progress/spinner/_spinner.clarity.scss
Fixes: #1836 
Spinner in small buttons changed to 13px according to the specs mentioned here: https://github.com/vmware/clarity/issues/1488
Tested on: IE, Edge, Safari, Chrome, Firefox
Firefox alignment is a bit off but we can't do anything about it. Noticeable only if you stare at the screen very closely.
> [UI] Fix spinners in small buttons

- src/app/progress-bars/progress-bar-cards.html
- src/clr-angular/progress/progress-bars/_progress-bars.clarity.scss
Fixes: #1719 
Before:
https://plnkr.co/edit/n0BcXi28jSZdeWBjliVZ?p=preview
After:
Tested on Chrome, Safari, Firefox
> [UI] Fix looping progress bars in cards

- src/app/vertical-nav/collapsible/vertical-nav-collapsible.demo.html
- src/clr-angular/layout/vertical-nav/_vertical-nav.clarity.scss
Partially Addresses #1328
Added a class (`.nav-trigger--bottom`) which can be used with the existing `.clr-vertical-nav` class. This will render the nav trigger at the bottom of the vertical nav instead of the top (default).
Tested on Firefox, IE, Edge, Safari, Chrome
> [UI] Vertical Nav Bottom Nav Trigger

- src/app/dropdown/dropdown-angular-close-item-false.demo.html
- src/app/dropdown/dropdown-static-positioning.demo.html
- src/clr-angular/button/_buttons.clarity.scss
- src/clr-angular/data/datagrid/_datagrid.clarity.scss
- src/clr-angular/popover/dropdown/_dropdown.clarity.scss
Fixes: #1128 
Issue addressed in:
Buttons
Dropdown Items
Datagrid Overflow Action Items
Disabled Button (Before):
Disabled Button (After):
> [UI] Add styling for button disabled attribute

- src/clr-angular/layout/vertical-nav/_variables.vertical-nav.scss
@reddolan asked me to reduce the spacing before the links in the vertical nav. spacing reduced from 24px to 18px.
Before:
After:
> [UI] Vertical Nav Top Padding Fix

- src/app/datagrid/datagrid.demo.html
- src/app/datagrid/datagrid.demo.module.ts
- src/app/datagrid/datagrid.demo.routing.ts
- src/app/datagrid/datagrid.demo.scss
- src/app/datagrid/pagination-conditional/pagination-conditional.html
- src/app/datagrid/pagination-conditional/pagination-conditional.ts
- src/clr-angular/data/datagrid/_datagrid.clarity.scss
- src/clr-angular/data/datagrid/datagrid-pagination.spec.ts
- src/clr-angular/data/datagrid/datagrid-pagination.ts
- src/clr-angular/data/datagrid/providers/page.spec.ts
- src/clr-angular/data/datagrid/providers/page.ts
Fixes: #1838
1. Resets the page size when the pagination is destroyed.
2. Introduced a pagination description section.
Note: In case the datagrid height is restricted, it has to be restricted via a class. Adding a style attribute doesn't work because when you enable and then disable pagination, the height is reset when added through the style attribute. Works when you have a class though.
Tested on Chrome, IE, Edge, Safari, Firefox
> [NG] Datagrid Pagination Bug Fix

- src/clr-angular/utils/_theme.dark.clarity.scss
- closes #1871
Tested in Chrome. 
> [UI] fix: dark theme navigation subnav box-shadows

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- README.md
This is a maintenance commit that updates project files with new support links.  
> [CORE] fix: adds four support links for light/dark themes and v10/v11 

- src/clr-icons/clr-icons-api.ts
- src/clr-icons/clr-icons-element.ts
- src/clr-icons/clr-icons.spec.ts
- src/clr-icons/helpers.spec.ts
- src/clr-icons/index.ts
- src/clr-icons/interfaces/icon-interfaces.ts
- src/clr-icons/utils/shape-template-observer.ts
updated in the API
- Fixes 1758
With this PR, it will be possible for users to update icons' templates when they are already in the DOM. This will also solve the case that if users load 3rd party JS libraries (e.g. `clarity-icons.min.js`) right before the closing body tag, not in the head.
I have added two unit tests that make sure the injected templates get updated whenever they are updated in the API and properly show the title if it's specified.  
Before:
https://plnkr.co/edit/3jcwnYDre4MUtUiYQssX?p=preview
After:
https://plnkr.co/edit/9hCdFy9xBA9InLEE23xE?p=preview
Fixes the errors reproduced in the original issue poster's pen:
https://codepen.io/anon/pen/opgMgP
Another example in Angular app:
https://plnkr.co/edit/BoqUNY?p=preview
Tested on: Chrome, Firefox, Safari, Edge, IE11 …
> [ICONS] Update already injected icons' templates if their templates are

- README.md
change "Clarity Plunker Templates" to "Clarity Stackblitz Templates"
Signed-off-by: Neil Kalman <neilkalman@gmail.com>
> change template demo site name to the correct name

- .gemini.conf.yml
- .gitignore
- .travis.yml
- package-lock.json
The html-reporter released a breaking change and we don't version control it in Travis. This locks versions and updates to the current release.
> [CORE] fix gemini reporter latest release

- src/community/contributors.json
- src/community/team.json
• moved Yen to contributors page
• made a few description updates to reflect changing roles of team
• did not update Jeeyun’s description yet
Tested in:
✔︎ Chrome
> [WEB] Updates to the community page

- src/clr-angular/popover/dropdown/dropdown-item.ts
- src/clr-angular/popover/dropdown/dropdown.spec.ts
We now wait until the view for each dropdown item is ready before
attaching the click listener. This lets us register our event listener
last, which means the custom ones provided by the consumer will
execute before ours.
> [NG] Fix #1642

- src/app/datagrid/hide-show-columns/hide-show.html
- src/clr-angular/data/datagrid/all.spec.ts
- src/clr-angular/data/datagrid/datagrid-column-toggle-button.spec.ts
- src/clr-angular/data/datagrid/datagrid-column-toggle-button.ts
- src/clr-angular/data/datagrid/datagrid-column-toggle-title.ts
- src/clr-angular/data/datagrid/datagrid-column-toggle.spec.ts
- src/clr-angular/data/datagrid/datagrid-column-toggle.ts
- src/clr-angular/data/datagrid/datagrid-footer.spec.ts
- src/clr-angular/data/datagrid/datagrid-footer.ts
- src/clr-angular/data/datagrid/datagrid.module.ts
- src/clr-angular/data/datagrid/datagrid.ts
- src/clr-angular/data/datagrid/providers/column-toggle-buttons.service.spec.ts
- src/clr-angular/data/datagrid/providers/column-toggle-buttons.service.ts
Does not break compatibility because it will fall back to existing implementation. To use, just add the `clr-dg-column-toggle` component into the footer, and then project the `clr-dg-column-toggle-title` and `clr-dg-column-toggle-button` components into the footer.
This can be ported to 0.10 without a breaking change.
Fixes #1129
> [NG] fix to remove datagrid column toggle hard coded strings

- src/clr-icons/clr-icons-element.ts
- src/clr-icons/clr-icons.spec.ts
- Fixes 1904
Icon subscription was taking place whenever the shape attribute name changes while unsubscription happens when icons are removed/detached from the DOM. So if icons are placed inside `ng-content`, they are still created virtually and already subscribes to `ShapeTemplateObserver`. However, when the component with the `ng-content` disappears, the icons inside `ng-content` unsubscribe from the `ShapeTemplateObserver`. However, when the component appears again, the icons wouldn't subscribe again because their shape names didn't get changed. if the component disappears again, the icons would try to unsubsribe again. But as subscriptions didn't take place for the icons, those unsubscription attempts would cause an error.
My fix here is that making subscription process take place …
> [ICONS] fix unsubscription in Clarity Icon

- src/clr-angular/data/datagrid/datagrid-row.spec.ts
- src/clr-angular/data/datagrid/providers/items.ts
- src/clr-angular/data/datagrid/providers/selection.spec.ts
- src/clr-angular/data/datagrid/providers/selection.ts
Fixes several bugs at once where we used the wrong variables (or didn't use them at all) to try and preserve selection, which meant we cleared it every time.
Also fixes the corresponding spec, which were completely broken for two reasons: a nested `beforeEach()` that didn't do anything, and the fact that we tested synchronously that an asynchronous operation didn't change anything. In other words, we were testing that code that hasn't run yet did not have any effects...
Fixes #1593.
> [NG] Preserve selection on items refresh for client-side datagrids

- src/clr-angular/forms/common/all.spec.ts
- src/clr-angular/forms/common/common.module.ts
- src/clr-angular/forms/common/common.spec.ts
- src/clr-angular/forms/common/form-control.service.spec.ts
- src/clr-angular/forms/common/form-control.service.ts
- src/clr-angular/forms/common/index.ts
- src/clr-angular/forms/common/label.spec.ts
- src/clr-angular/forms/common/label.ts
- src/clr-angular/forms/common/wrapped-form-control.spec.ts
- src/clr-angular/forms/common/wrapped-form-control.ts
- src/clr-angular/utils/host-wrapping/dynamic-wrapper.ts
- src/clr-angular/utils/host-wrapping/empty-anchor.ts
- src/clr-angular/utils/host-wrapping/host-wrapper.ts
- src/clr-angular/utils/host-wrapping/host-wrapping.module.ts
- src/clr-angular/utils/host-wrapping/host-wrapping.spec.ts
- src/clr-angular/utils/host-wrapping/index.ts
This commit provides an internal utility for a directive to wrap its host in a container element. For information on how to use it, check out the spec file.
> [NG] Host wrapping hack

- scripts/docker-cdc.js
This is a core fix for running `npm run cssTest set#` so that the webserver running the demo app on port 3000 is killed before the Clarity Docker Control process exits.
> [CORE] Fixes orphaned webserver for gemini tests.

- src/clr-angular/utils/_theme.dark.clarity.scss
Tested in Chrome. 
- Fixes #1973
> fix: [UI] Dark theme .btn font color

- package-lock.json
- package.json
- src/clr-angular/utils/virtual-scroll/virtual-for-of.spec.ts
- tests/tests.helpers.ts
This adds the test organization needed to run against Safari. There is one test
that doesn't work properly with Safari and it is ignored for the moment.
> [NG] Safari unit testing

- README.md
The `forRoot()` method is `@deprecated` and should not be used anymore.
Duplicate PR with dco. Original PR: https://github.com/vmware/clarity/pull/1898
> [CORE] Fix NgModule Imports in README

- src/clr-angular/data/stack-view/_stack-view.clarity.scss
- src/clr-angular/data/stack-view/stack-block.ts
When using stack-view with angular universal, there is an error with the animation because overflow-y is not a supported CSS property for animations. This moves it from the animation to CSS.
Signed-off-by: Alyssa Brunswick <abrunswick@oriental.com>
> [NG] Fix stack view overflow-y issue with Angular universal

- .gemini.conf.yml
- .gitignore
- .travis.yml
- README.md
- karma.conf.js
- package-lock.json
- package.json
- webpack.test.config.js
This improves our CI to use Saucelabs for running our unit tests, and runs it against Chrome, Firefox, and Safari. Code coverage now reports again.
I've enabled Chrome (Win 8), Safari (macOS), and Firefox (Win 8) latest versions to run tests. Our account has 5 concurrent sessions allowed, so I would like to eventually enable IE and Edge, but that means fixing some tests.
SauceLabs will only run after a PR is merged (from a fork), or for a PR made from a branch in this repo. This has to do with how private ENV vars are treated in Travis, where they aren't exposed when running the tests from a fork. See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
You can see a build running on SauceLabs from this job (local branch `ci-unit-tests`) at …
> [CORE] setup saucelabs with travis, fix code coverage

- package-lock.json
- src/app/button-group/angular/button-group-angular.ts
- src/app/button-group/angular/loading-buttons/loading-button-group.html
- src/app/button-group/angular/loading-buttons/loading-button-group.ts
- src/app/button-group/button-group.demo.module.ts
- src/app/button-group/button-group.demo.routing.ts
- src/clr-angular/button/button-group/button.spec.ts
- src/clr-angular/button/button-group/button.ts
Fixes: #1681
Adds tests to this PR: #1685
- Had to rewrite tests for the `clr-button` component as the previous tests were not testing everything.
> [NG] Support loading buttons in button groups

- src/clr-angular/button/button-group/button.ts
FIxes issues Clarity consumers will have when compiling with aot.
> [NG] Loads the loading listener from the file 

- karma.conf.js
- src/clr-icons/clr-icons.spec.ts
- tests/tests.helpers.ts
There were some newer tests that were added and fail in Firefox between Saucelabs being setup and enabled, this resolves those tests. Firefox reorders some of the attributes so you can't expect a string with a DOM element definition to match innerHTML. Also, the browser sniffing library required a change.
This also disables Safari, because its been very flaky and need to investigate further.
Signed-off-by: Jeremy Wilken <gnomation@gnomeontherun.com>
> [CORE] fix firefox testing

- package-lock.json
- src/clr-angular/data/tree-view/tree-node.html
- src/clr-angular/data/tree-view/tree-node.ts
- src/clr-angular/forms-deprecated/checkbox/checkbox.spec.ts
- src/clr-angular/forms-deprecated/checkbox/checkbox.ts
- src/clr-angular/utils/id-generator/id-generator.service.ts
- src/clr-angular/utils/id-generator/id-generator.spec.ts
- Adds a generic id-generator service
- Fixes #1926
@youdz - I'm not happy about the one test in `id-generator.spec`. I only really test that the ids generated are unique. The main thing I ran into is that `let NB_INSTANCES = 0;` seems to retain its state across tests and it felt hacky to write a second test expecting the starting value to be 'clr-id-4'.  I wasn't able to reset t` NB_INSTANCES` between the first and a second test's. I tried using the `TestBed`'s
```
static resetTestEnvironment()
Reset the providers for the test injector.
```
([docs](https://angular.io/api/core/testing/TestBed#resetTestEnvironment))
But that was resetting `this` to `{}`. If you have something specific that should be tested please advise. 
> [NG] Adds aria-labelledby to clr-checkboxes

- src/app/checkboxes/checkboxes.demo.html
- src/app/checkboxes/checkboxes.demo.module.ts
- src/app/radios/radios.demo.html
- src/app/radios/radios.demo.module.ts
- src/clr-angular/forms-deprecated/forms.module.ts
- src/clr-angular/forms/checkbox/all.spec.ts
- src/clr-angular/forms/checkbox/checkbox-container.spec.ts
- src/clr-angular/forms/checkbox/checkbox-container.ts
- src/clr-angular/forms/checkbox/checkbox.module.ts
- src/clr-angular/forms/checkbox/checkbox.spec.ts
- src/clr-angular/forms/checkbox/checkbox.ts
- src/clr-angular/forms/checkbox/index.ts
- src/clr-angular/forms/forms.module.ts
- src/clr-angular/forms/radio/all.spec.ts
- src/clr-angular/forms/radio/index.ts
- src/clr-angular/forms/radio/radio-container.spec.ts
- src/clr-angular/forms/radio/radio-container.ts
- src/clr-angular/forms/radio/radio.module.ts
- src/clr-angular/forms/radio/radio.spec.ts
- src/clr-angular/forms/radio/radio.ts
- src/clr-angular/utils/host-wrapping/host-wrapping.module.ts
- src/ks-app/src/app/app.module.ts
- src/ks-app/src/app/containers/forms/checkboxes.component.html
- src/ks-app/src/app/containers/forms/radios.component.html
New radio and checkbox components, using the host wrapping trick to provide a simpler API. These two new components are part of #1878.
@gnomeontherun: What's the plan for forms deprecation here? We have a naming conflict, so I'm marking this PR as "Do not merge" until we know exactly what we want to do.
> [NG] Radios and Checkboxes

- latest/README.md
- latest/src/app/documentation/demos/datagrid/datagrid.demo.html
- v0.10/README.md
- v0.10/src/app/documentation/demos/datagrid/datagrid.demo.html
This supersedes https://github.com/vmware/clarity/pull/2035 and pushes against the correct branch, while also changing mentions of the old branch to the new one in the website.
> [Docs] Minor typo and mention new website branch

- src/clr-angular/utils/host-wrapping/host-wrapping.module.ts
Fixed an issue with the build.
Without this fix `npm run build` fails.
> [NG] Remove @private annotation

- package.json
- scripts/aot-check.js
- installs Clarity artifacts into the ks-app and builds that for production to test for AOT
- catches ks-app build errors and notifies on the command line
- closes #2028
I kept it pretty simple but if there is something a script like this should do that I missed. Let me know. 
> fix: [CORE] Adds a check for AOT compilation on Clarity artifacts

- src/clr-angular/forms/datepicker/providers/date-navigation.service.spec.ts
- src/clr-angular/forms/datepicker/providers/date-navigation.service.ts
- src/clr-angular/forms/datepicker/yearpicker.spec.ts
- src/clr-angular/forms/datepicker/yearpicker.ts
Calendar and Year Range Generation Optimizations
If on the current displayed calendar or current decade, dont generate the calendar or year range again.
> [NG] Cal + Year Range Generation Optimizations

- src/clr-angular/data/datagrid/_datagrid.clarity.scss
Fixes: #1631
`translateY` was causing issues with dropdown menus and modals. Replaced that by a negative margin. @hippee-lee's PR will fix this better but this can be a temp fix until that goes in.
Before:
After:
Before:
After:
> [UI] Datagrid Action Overflow Fix

- src/clr-angular/popover/common/abstract-popover.spec.ts
- src/clr-angular/popover/common/abstract-popover.ts
- src/clr-angular/utils/key-codes/key-codes.ts
Fixes: #2062
Closes a popover when the `ESC` key is pressed.
Note: For some reason `abstract-popover.ts` didn't have any tests. I have added tests related to this change in this PR. Will add the remaining tests in a separate PR.
> [NG] Closes a Popover on ESC

- src/app/datepicker/datepicker-in-reactive-forms.html
- src/app/datepicker/datepicker-in-reactive-forms.ts
- src/app/datepicker/datepicker-in-template-driven-forms.ts
- src/clr-angular/forms/datepicker/date-input.spec.ts
- src/clr-angular/forms/datepicker/date-input.ts
Fixes: #2093
The initial value set by the user in Reactive Forms wasn't being processed by the Date Picker. Fixes that issue. For more details see #2093
> [NG] Bug Fix for Datepicker in Reactive Forms

- src/clr-angular/data/datagrid/providers/selection.spec.ts
- src/clr-angular/data/datagrid/providers/selection.ts
Moved select and deselect into private methods to keep current and
selection in sync.
toggleAll calls select and deselect when adding or removing items.
closes #2083
Signed-off-by: Marc Viger <mviger@gmail.com>
> [NG] Fix toggleAll selection tracking

- latest/src/app/documentation/demos/button-group/button-group.demo.html
- latest/src/app/documentation/demos/datagrid/binding-properties/binding-properties.html
- latest/src/app/documentation/demos/datagrid/single-action/single-action.html
- latest/src/app/documentation/demos/tabs/tabs.demo.html
- latest/src/app/documentation/demos/vertical-nav/vertical-nav.demo.html
- latest/src/releases/0.8/0.8.5.html
- v0.10/src/app/documentation/demos/button-group/button-group.demo.html
- v0.10/src/app/documentation/demos/datagrid/binding-properties/binding-properties.html
- v0.10/src/app/documentation/demos/datagrid/single-action/single-action.html
- v0.10/src/app/documentation/demos/tabs/tabs.demo.html
- v0.10/src/app/documentation/demos/vertical-nav/vertical-nav.demo.html
Correct several minor typos, mostly related to the Datagrid component documentation.
> [Docs] Minor typos

- npm/clr-angular/package.json
- packages/schematics/package-lock.json
- packages/schematics/package.json
- packages/schematics/src/add/index.ts
- src/clr-angular/package.json
Schematics needs to handle both versions of the angular cli config files coming with Angular 6. This also moves the schematics dependencies from peerDependencies to dependencies to ensure they are installed and users don't get an unnecessary warning.
fixes #2181
> [SCHEMATICS] update schematics to handle new config schemas

- src/app/_utils/code.scss
- src/app/layout/layout.demo.scss
- src/app/vertical-nav/vertical-nav.demo.scss
- src/clr-angular/emphasis/alert/_alert.clarity.scss
- src/clr-angular/forms-deprecated/_forms.clarity.scss
- src/clr-angular/layout/_card.clarity.scss
- src/clr-angular/layout/_login.clarity.scss
- src/clr-angular/layout/nav/_header.clarity.scss
- src/clr-angular/layout/nav/_responsive-nav.clarity.scss
- src/clr-angular/modal/_modal.clarity.scss
- src/clr-angular/popover/dropdown/_dropdown.clarity.scss
- src/clr-angular/typography/_typography.clarity.scss
- src/clr-angular/utils/_bs4-grid-breakpoint-overrides.clarity.scss
- src/clr-angular/utils/_components.clarity.scss
- src/clr-angular/utils/_dependencies.clarity.scss
- src/clr-angular/utils/_maps.clarity.scss
- src/clr-angular/utils/_overwrites.clarity.scss
- moved _maps.clarity back to components so -breakpoints map can be overwritten
- fixes #2066
> [UI] Breakpoints to be overwritable (#2195)

- src/app/datagrid/selection-row-mode/selection-row-mode.html
- src/app/datagrid/selection-row-mode/selection-row-mode.ts
- src/clr-angular/data/datagrid/datagrid.spec.ts
- src/clr-angular/data/datagrid/datagrid.ts
- Fix data grid row selection attribute typo.
- I can't run **npm install** , then i use yarn to install but run **npm test** fail , package missed `@ngtools/webpack `
**NPM version : 5.6.0**
Signed-off-by: Jewway jewway@gmail.com
> [NG] fix: clDgRowSelection attribute naming (#2019)

- karma.conf.js
- eliminate timeouts that cause (Safari) unit tests to fail on travis
> fix: remove safari from sauce labs browsers

- src/clr-angular/data/datagrid/datagrid-column.spec.ts
- src/clr-angular/data/datagrid/datagrid-column.ts
- src/ks-app/src/app/containers/data/datagrid.component.html
When a user types in to filter, `clr-dg-string-filter` emits value through the `clrFilterValueChange` output. However, `clr-dg-column` was merely setting its `filterValue` property on those filter value changes sourced from `clr-dg-string-filter`, but wasn't emitting them from itself. 
So this fix lets `clr-dg-column` emit the filter value changes, that are first emitted from `clr-dg-string-filter`.
The demo of this fix (in the "Sort and Filter" section): http://2004-after-fix.surge.sh/datagrids
- Fixes #2004
> [NG] emitting on string filter value change

- src/clr-angular/modal/modal.html
When using a screen reader (i.e. for visually-impaired users), other
portions of the application work fine, however readers ignore the
content inside of modals (clr-modal) and wizards (clr-wizard) due
to the aria-hidden="true" in the modal.html.  With this change, the
screen readers properly read just like the rest of the clr-angular
components currently do.
To reproduce the problem, use a browser with screen reading
capability, e.g. by installing ChromeVox extension into Chrome, and
using the kitchen-sink app open a model or wizard and tab/click
through.  Reader will not read the elements audibly.
After applying this simple fix, the reader will properly read
the elements, buttons, wizard steps, etc.
This does not address the demo pieces, since they do not use
clr-modal nor clr-wizard. …
> [NG] Enable Angular modals and wizards to support aria.

- src/clr-angular/data/datagrid/_datagrid.clarity.scss
Fixes: #2269
Removed the z-index on the datagrid-column-handle
Needs to be reviewed by @Shijir 
> [UI] Remove z-index from datagrid column handle

- src/clr-angular/package.json
- webpack.icons.config.js
Master build was failing because of an extra comma in webpack.icons.config.js.
After the fix, `npm run build` also generated the new `clr-angular/package.json` file.
> [CORE] Fix master build

- gemini/tests/set2/datagrid-compact.js
- gemini/tests/set2/datagrid.js
- src/clr-angular/button/button-group/button.spec.ts
- src/clr-angular/button/button-group/button.ts
- src/clr-angular/button/button-loading/loading-button.module.ts
- src/clr-angular/button/button-loading/loading-button.spec.ts
- src/clr-angular/button/button-loading/loading-button.ts
- src/clr-angular/image/_icons.clarity.scss
- src/clr-angular/progress/spinner/_spinner.clarity.scss
- src/clr-angular/utils/expand/providers/expand.spec.ts
- src/clr-angular/utils/expand/providers/expand.ts
- src/clr-angular/utils/loading/loading-listener.ts
- src/clr-angular/utils/loading/loading.spec.ts
- src/clr-angular/utils/loading/loading.ts
- src/dev/src/app/_utils/fake-loader.ts
- src/dev/src/app/buttons/button-loading.html
- src/dev/src/app/buttons/button-loading.ts
- src/ks-app/src/app/containers/data/fake-loader.ts
Implementation of the new spinner button. After reviewing with @youdz came to a couple of realization which led to the approach in this PR:
- the new implementation should be non-breaking, so need to continue to support [clrLoading] on button with a boolean value input, while allowing newer approach of taking in different button states
- we want to continue to use clrLoading / LoadingListener to not duplicate this logic in button when many other components already utilize this directive.
- clrLoading is now modified to handle more than two states (loading / not loading)
> [ng] new spinner button (#1488)

- tsconfig.spec.json
If you had old build files in the `dist` directory (with d.ts files) it would pick them up when it shouldn't. Updated the paths to only load from `src/`.
> [CORE] fix tests from loading files from directories other than src

- src/clr-angular/data/datagrid/render/dom-adapter.ts
- src/clr-angular/data/datagrid/render/main-renderer.ts
Use getBoundingClientRect().height to determine clr-datagrid height rather than getComputedStyle(element).getPropertyValue("height"), since IE11 returns the latter incorrectly.
Refer to issue #2256.
Signed-off-by: Your Name <sstrobel99@gmail.com>
> [NG] v11 clr-datagrid height not calculated correctly on IE

- src/clr-angular/forms/datepicker/all.spec.ts
- src/clr-angular/forms/datepicker/calendar.spec.ts
- src/clr-angular/forms/datepicker/date-container.spec.ts
- src/clr-angular/forms/datepicker/date-container.ts
- src/clr-angular/forms/datepicker/date-input.spec.ts
- src/clr-angular/forms/datepicker/date-input.ts
- src/clr-angular/forms/datepicker/datepicker-view-manager.spec.ts
- src/clr-angular/forms/datepicker/day.spec.ts
- src/clr-angular/forms/datepicker/day.ts
- src/clr-angular/forms/datepicker/daypicker.spec.ts
- src/clr-angular/forms/datepicker/providers/date-form-control.service.spec.ts
- src/clr-angular/forms/datepicker/providers/date-form-control.service.ts
- src/dev/src/app/datepicker/datepicker-in-reactive-forms.html
- src/dev/src/app/datepicker/datepicker-in-template-driven-forms.html
- src/dev/src/app/datepicker/datepicker-in-template-driven-forms.ts
Fixes: #2263 
**Changes:**
1. Date Control marked as `touched` when the datepicker toggle is clicked.
2. Date Control marked as `dirty` when a date is selected from the popover.
**Tested on Chrome**
> [NG] Fix Date Picker State

- package-lock.json
- src/clr-angular/utils/drag-and-drop/all.spec.ts
- src/clr-angular/utils/drag-and-drop/drag-handle.spec.ts
- src/clr-angular/utils/drag-and-drop/drag-handle.ts
- src/clr-angular/utils/drag-and-drop/draggable.spec.ts
- src/clr-angular/utils/drag-and-drop/draggable.ts
- src/clr-angular/utils/drag-and-drop/index.ts
- src/clr-angular/utils/drag-and-drop/providers/drag-event-listener.mock.ts
- src/clr-angular/utils/drag-and-drop/providers/drag-handle-registrar.mock.ts
- src/clr-angular/utils/drag-and-drop/providers/drag-handle-registrar.spec.ts
- src/clr-angular/utils/drag-and-drop/providers/drag-handle-registrar.ts
API for users will look like:
```html
<div class="card" clrDraggable>
...
<button clrDragHandle><clr-icon shape="folder"></clr-icon></button>
...
</div>
```
Beside `ClrDragEventListener` now, `ClrDragHandleRegistrar` is also provided into `ClrDraggable`. So `ClrDragHandleRegistrar` has access to `ClrDragEventListener`. Now `ClrDraggable` itself doesn't directictly call the `.attachListeners()` method of `ClrDragEventListener` on its element. It provides for its element to `ClrDragHandleRegistrar`, which configures which element to be attached to the listeners.
> [NG] clrDragHandle directive

- src/clr-angular/popover/dropdown/dropdown-trigger.ts
When running a strict configuration of ngc (e.g. ng-packagr) against a library
which imports the ClrDropdownModule (e.g. ng-packagr), ngc errors out because
the dropdown's private property is used in the "host" component. Note that
even though the compiler appears to access clarity, the component isn't actually
bundled in the resulting output.
Signed-off-by: Michael Krotscheck <krotscheck@gmail.com>
> [NG] Set isRootLevelToggle to public

- src/clr-angular/forms/datepicker/date-input.spec.ts
- src/clr-angular/forms/datepicker/providers/date-form-control.service.spec.ts
- src/clr-angular/forms/datepicker/providers/date-form-control.service.ts
This PR updates imports for v11 so it can use rxjs v5.x and fixes `npm run tslint:check`
> fix: rxjs versions are different between master and v11

- src/clr-angular/forms/datepicker/date-input.spec.ts
- src/clr-angular/forms/datepicker/date-input.ts
- src/clr-angular/forms/datepicker/providers/date-navigation.service.ts
- src/dev/src/app/datepicker/datepicker-in-reactive-forms.html
- src/dev/src/app/datepicker/datepicker-in-reactive-forms.ts
Fixes: #2300
Date Picker did not emit an output when the user manually changed Date in the input without using the Date Picker popover. This happened in Reactive and Template Driven Forms.
We want to output the date when the following conditions are true:
1. User has updated the input and focused out of the input.
2. Modified Date is not equal to the current Selected Date.
Since, in `date-input.ts`, we subscribe to `ngControl.valueChanges`, the selected date was updated before to the modified date before it could be compared to decide whether to emit the output or not.
This PR fixes the issue mentioned above.
> [NG] Date Picker Output Bug Fix

- angular.json
- karma.conf.js
- package-lock.json
- package.json
- src/clr-angular/utils/_components.clarity.scss
- src/clr-angular/utils/_dependencies.clarity.scss
Using relative links to node_modules in our build works fine for our build, but if someone tries to build a theme and imports our file, the file paths are no longer correct. We had the tilde importer in the past, but it doesn't seem to work the same without additional webpack functionality. This will require anyone building a custom theme to add the `--include-path=node_modules` to their build as well, or if they are using the Angular CLI they can add the following in angular.json to the `build.options` object (next to `styles`). 
```
"stylePreprocessorOptions": {
"includePaths": [
"node_modules"
]
},
```
Fixes #2330
> [UI] fix build for 0.12 where relative paths cause issues for theming

- src/clr-angular/utils/loading/loading.spec.ts
- src/clr-angular/utils/loading/loading.ts
- src/dev/src/app/buttons/button-loading.html
- src/dev/src/app/buttons/button-loading.ts
The recent refactoring of loading buttons allows strict true/false values, but previously it also supported falsy values. This reenables that functionality for backwards compatibility.
closes #2355
> [NG] fix to allow loading binding to be falsy values

- latest/src/app/documentation/demos/buttons/button-loading.html
- latest/src/app/documentation/demos/buttons/button-loading.ts
Adding documentation about loading button states in v0.12
> [WEB] 0.12 New Spinner Button docs

- src/clr-angular/data/datagrid/datagrid-column-toggle-button.ts
This addresses this comment https://github.com/vmware/clarity/pull/1861/files#r196707052, and upon testing it seems this is unnecessary to have.
> [NG] remove unneeded block styling from datagrid column toggle button

- .travis.yml
- scripts/publish-build.sh
- This will only run on master branch.
- It published to [clr-team](https://github.com/clr-team) build repositories for each of the Clarity packages
- Automatic commit messages will include a link to the commit on master that triggered the build and the commit message.
- clr-angular has an example of the automatic commit message but its left over from testing I did on my fork so it doesn't actually link to a published commit (yet).
- the publish should not run if any of the test jobs fail
> [CORE] feature: Adds automatic publishing to build repos

- src/clr-angular/data/datagrid/providers/selection.spec.ts
- src/clr-angular/data/datagrid/providers/selection.ts
The datagrid clears the current selection to empty array when filter is applied and we have a separate ticket (https://github.com/vmware/clarity/issues/2342) to preserve selection when filter is applied. 
My code was not accounting for this fact, and was trying to re-select the previous selections when data is refreshed in the case where filter is applied as well. This results in having inaccurate current selection data post-filter, since `prevSelectionRefs` still contained refs for selection even though current is cleared.
> [ng] Datagrid bug fix for when selection is cleared by applying filter

- src/clr-angular/forms/common/layout.ts
- src/clr-angular/forms/common/providers/layout.service.spec.ts
- src/clr-angular/forms/common/providers/layout.service.ts
This is basically a polyfill for Object.values(), which IE11 and Node <9 don't support :(
String enums cannot be reverse-mapped, meaning Layouts['COMPACT'] does not return 'compact' so this exists to deal with this little caveat to get the list of the values of a string enum.
Source: https://github.com/tc39/proposal-object-values-entries/blob/master/polyfill.js
> [NG] fix layout to not use Object.values since its not ie11 supported

- package.json
Simple change to add a build step to our tests to catch potential build errors that don't appear otherwise.
> [CORE] add a build step to testing

- src/clr-angular/emphasis/alert/_alert.clarity.scss
Fixes: #2338
Before:
After:
Note: This PR removes the `max-height` restriction from alerts. The reasoning behind this being that the user can add a max-height if required but we by default shouldn't clip/scroll important content that the app level alert is supposed to display.
cc: @reddolan 
> [UI] Alerts overflow bug fix

- src/clr-angular/forms/common/layout.ts
- src/clr-angular/popover/tooltip/_tooltips.clarity.scss
- src/clr-angular/popover/tooltip/tooltip-trigger.ts
Fixes: #1927
This is not the perfect solution for this issue but we need to refactor the Angular component. Before refactoring the Angular component, we also need to solidify the tooltip design guidelines. As of now, we recommend tooltips to be used only on actionable icons but UX is looking in other valid use cases too. Until we can finalize that, this PR fixes but it solves the high priority accessibility bug.
Before:
After:
> [NG] Fix tooltip visibility issue on trigger focus

- src/schematics/src/add/index.ts
- src/schematics/src/add/schema.d.ts
- src/schematics/src/add/schema.json
This brings support for a mono-repo with schematics by declaring the `--project` flag. Originally it only would install into the main app module, now it can _optionally_ target a different project.
This fixes a bug where webcomponents polyfill was after the icons script.
Closes #2406 #2410
> Schematic fix for webcomponents script ordering and monorepo support

- src/clr-angular/data/datagrid/providers/selection.spec.ts
- src/clr-angular/data/stack-view/_stack-view.clarity.scss
- src/clr-angular/data/stack-view/_variables.stack-view.scss
- src/clr-angular/data/stack-view/stack-block.spec.ts
- src/clr-angular/data/stack-view/stack-block.ts
- src/clr-angular/data/stack-view/stack-view.module.ts
- src/clr-angular/utils/_theme.dark.clarity.scss
Fixes: #2357, #1946
**Demo:**
**NOTE:** 
1. The static markup cannot be fixed without a breaking change. This PR fixes the accessibility issues in the Angular component. We still have the generated icon in use for the static markup but the angular component uses `clr-icon`.
2. Tested on Chrome, Firefox and Safari. My VM isn't working properly so couldnt test on IE and Edge. 🤞 
3. @youdz: I am pretty sure you wont like the way the tests are structured, but I didn't want to fix that in this PR.
**Fixes:**
1. Adds a `button` `role` to the `.stack-block-label`
2. Adds a `tabindex` to the `.stack-block-label`
3. Opens the stack block on `enter` and `space`
4. Uses `clr-icon` instead of the generated icon.
> [NG] StackView Accessibility Bug Fixes

- src/clr-angular/data/stack-view/stack-block.spec.ts
- src/clr-angular/data/stack-view/stack-block.ts
Fixes: #2429
@youdz mentioned that only the `aria-expanded` attributes are needed because StackView is already semantic as we already use `dd` and `dt`
More info here: https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html
> [NG] Add Stack View aria-expanded attribute

- src/clr-angular/button/button-loading/loading-button.spec.ts
- src/clr-angular/button/button-loading/loading-button.ts
- src/dev/src/app/buttons/button-loading.html
- src/dev/src/app/buttons/button-loading.ts
- Now spinner button respects the [disabled] input after state change
- Using `getBoundingClientRect` instead of `getComputedStyle` to set the width of the button
> [ng] Bug fix on spinner button to work with [disabled] input (#2375)

- src/clr-angular/forms/input/input-container.spec.ts
- src/clr-angular/forms/input/input.spec.ts
- src/clr-angular/forms/input/input.ts
- src/clr-angular/forms/tests/container.spec.ts
- src/clr-angular/forms/tests/control.spec.ts
- src/clr-angular/forms/textarea/textarea-container.spec.ts
- src/clr-angular/forms/textarea/textarea.spec.ts
- src/clr-angular/forms/textarea/textarea.ts
fixes #2438
We need to use ngOnInit to give the form control more time to initialize for reactive forms, and reformatted some tests to run the same test suite on template driven and reactive forms for inputs and textareas.
> Reactive form fix, and tests

- src/clr-angular/forms/datepicker/providers/locale-helper.service.spec.ts
- src/clr-angular/forms/datepicker/providers/locale-helper.service.ts
This PR changes the currently used CLDR data strings provided by Angular (month names and day names) from their genitive to nominative form.
The change is motivated by the current (incorrect) form of strings for the Polish locale. For example September is rendered as `września` while it should be `wrzesień`.
The change itself doesn't make a visible difference for most languages (i.e. English, German) but fixes the form for the Polish locale and possibly others.
Signed-off-by: Paweł Białaszczyk <pawelbialaszczyk@gmail.com>
> [NG] Change locale strings to nominative form

- golden/clr-angular.d.ts
- src/clr-angular/data/datagrid/_datagrid.clarity.scss
- src/clr-angular/data/datagrid/datagrid-cell.spec.ts
- src/clr-angular/data/datagrid/datagrid-cell.ts
- src/clr-angular/data/datagrid/datagrid-column.spec.ts
- src/clr-angular/data/datagrid/datagrid-column.ts
- src/clr-angular/data/datagrid/datagrid-row.spec.ts
- src/clr-angular/data/datagrid/datagrid-row.ts
- src/clr-angular/data/datagrid/datagrid.html
- src/clr-angular/data/datagrid/datagrid.spec.ts
- src/clr-angular/data/datagrid/render/table-renderer.spec.ts
- src/clr-angular/data/datagrid/render/table-renderer.ts
Highlights:
- Datagrid is now accessible by screen reader
- No longer using HostListener on click or keypress.
- We are wrapping the datagrid row's content inside a label for full row click mode
preview of demo-app with the implementation: http://dg-aria.surge.sh/datagrids
> [ng] add ARIA attributes to datagrid (#2431)

- src/clr-angular/wizard/_wizard.clarity.scss
• This was caused by a combination of justify-content flexbox settings that Microsoft browsers didn't care for complicated by Microsoft browsers being confused over the max-height vs. height settings when the content in either the stepnav or content panel exceeded the available height
• I did some whack-a-mole through the SASS to find the guilty parties and removed/amended them
• I'm marking this as Low priority and only back porting it to 0.12 because it only happens on XL wizards when the vertical height of the screen goes below a certain range determined by the height of EITHER the stepnav or the content area
Tested in:
✔︎ Chrome
✔︎ Firefox
✔︎ Safari
✔︎ IE11
✔︎ Edge
Closes: #2493
> [BUG] Odd wizard vertical height issue when resizing browser

- src/clr-angular/utils/_components.clarity.scss
- src/clr-angular/utils/_mixins.clarity.scss
- src/clr-angular/utils/focus-trap/_focus-trap.clarity.scss
- src/clr-angular/utils/focus-trap/focus-trap-tracker.service.ts
- src/clr-angular/utils/focus-trap/focus-trap.directive.spec.ts
- src/clr-angular/utils/focus-trap/focus-trap.directive.ts
Fixes #2396 
This solution adds offscreen tabbable dummy elements to document as the first and the last child elements. Multiple nested focus-trapper directives will share the same focus rebounding elements.
Tested on: Chrome, Safari, Firefox.
> Trap focus inside doc

- src/clr-angular/button/button-group/_button-group.clarity.scss
- src/dev/src/app/datagrid/kitchen-sink/kitchen-sink.html
- src/dev/src/app/datagrid/kitchen-sink/kitchen-sink.ts
I was working on implementing #2286, and noticed that our dropdown doesn't align with the other buttons in a button group. This PR fixes the alignment issue for buttons inside our button group.
Before:
After:
> [ui] vertical align the buttons inside button group

- src/clr-angular/data/datagrid/providers/selection.spec.ts
- src/clr-angular/data/datagrid/providers/selection.ts
- src/dev/src/app/datagrid/selection-single/selection-single.html
This is a fix for #2500. 
Here are my observations of current (broken) behavior:
- In the bug scenario, setting of the `clrDgSingleSelected` happens before setting of the `clrDgItems`.
- Usually, setting the `clrDgSingleSelected` updates the `prevSingleSelectionRef` IF the datagrid's `all` (i.e. `clrDgItems`) has been defined. But since this hasn't happened yet, `prevSingleSelectionRef` remains undefined.
- The setting of the `clrDgItems` triggers an update, where our code looks for the `newSingle` by comparing it against `prevSingleSelectionRef`. Since `prevSingleSelectionRef` remains undefined, this updates the `newSingle` to `undefined`. This overrides the `clrDgSingleSelected` that was set by the user in the beginning.
Proposed fix:
- We should only update `newSingle` to `undefined` …
> [ng] allow pre-selection of currentSingle when `all` hasn't been set

- CODING_GUIDELINES.md
Adds detail for when to move providers or interfaces or enums into subfolders.
> fix(guidelines): Update coding guidelines for sub-folders.

- src/clr-angular/layout/_card.clarity.scss
- src/clr-angular/typography/_code.clarity.scss
- src/clr-angular/utils/_components.clarity.scss
- src/clr-angular/utils/_dependencies.clarity.scss
- src/clr-angular/utils/_reboot.clarity.scss
- src/clr-angular/utils/_variables.global.scss
The goal is to completely move off of bootstrap by 2.0, so making note of both direct imports from bootstrap, as well as variables that are overwriting values from bootstrap. In the second case, we would probably need to do a sweep of our scss files to see if those variables need to be replaced if they are being used in our components. 
> [UI] Deprecate non-documented bootstrap files (#2163)

- src/schematics/src/update/update-0.13.0.ts
> [NG] Schematics update for deprecated icons

- karma.conf.js
This _should_  prevent DISCONNECT errors when unit tests are run on Travis.
> [CORE] Update karma.conf

- src/schematics/src/migration-collection.json
- src/schematics/src/update/update-0.13.0.ts
I'm not very great with RegEx so any suggestion to improve it is greatly welcome. Basically the goal was to catch any imports from `@clr/angular` where the classname didn't start with `Cl`. I used `Cl` instead of `Clr` for simplicity so that `ClarityModule` would be included in that.
Here are some of the test strings I've used for the regex:
```
import { foo } from '@clr/angular';
import { 
foo 
} from '@clr/angular';
import { 
foo,
bar,
} from '@clr/angular';
import { foo, bar, baz, bat } from '@clr/angular';
import { clrfoo, bar, baz, bat } from '@clr/angular';
import { foo, clrbar, baz, bat } from '@clr/angular';
import { foo, bar, clrbaz, bat } from '@clr/angular';
import { foo, bar, baz, clrbat } from '@clr/angular';
import { clrfoo, clrbar, baz, bat } from '@clr/angular';
``` …
> [NG] Schematics update for importing deprecated non-Clr classes

- src/clr-angular/layout/_card.clarity.scss
> [UI] Dark theme for list-items inside card

- CODING_GUIDELINES.md
- src/clr-angular/button/button-group/_button-group.clarity.scss
This will enable a workaround for people who want to use tooltips in their button groups. It is a fix specific to Firefox. To enable the angular tooltips in Firefox we would need to do a much more involved refactor of the API.
Tested in:
✔︎ Chrome
✔︎ Firefox
> [ENH] Allowing tooltips to be used inside static button groups

- src/clr-angular/data/datagrid/datagrid.ts
- src/clr-angular/data/datagrid/providers/selection.spec.ts
- src/clr-angular/data/datagrid/providers/selection.ts
We were emitting multiple outputs for a single change, which made debugging on the app side pretty hard. In particular, we have [a guideline](https://github.com/vmware/clarity/blob/master/CODING_GUIDELINES.md#gotchas) stating:
> An `@Output` should not fire when we receive a new `@Input` value from the app.
Due to this change, a few unit tests needed to be cleaned up to reflect the correct behavior.
> [NG] Datagrid: reduce the number of outputs for selection changes

- src/clr-angular/data/datagrid/datagrid-row.ts
fixes #2644
We are double bumping the index for each row, so this does it only once.
> [NG] fix index for radios and rows to be consistent

- src/clr-angular/utils/i18n/common-strings.service.ts
Using `Required` type from TS 2.8 caused us to break support for Angular 6 projects using TS 2.7, this removes it for now with a note to put it back when we can.
> [NG] fix support for TS 2.7+

- .gitignore
- package.json
- src/clr-angular/button/button-group/button.spec.ts
- src/clr-angular/button/button-group/button.ts
- src/clr-angular/button/button-loading/loading-button.spec.ts
- src/clr-angular/forms/common/wrapped-control.ts
- src/clr-angular/forms/datepicker/date-container.ts
- src/clr-angular/forms/datepicker/date-input.spec.ts
- src/clr-angular/popover/signpost/signpost-content.spec.ts
- src/clr-angular/utils/expand/providers/expand.spec.ts
- src/clr-angular/utils/expand/providers/expand.ts
- src/dev/src/app/grid/grid.demo.module.ts
- tests/tslint/README.md
- tests/tslint/src/noBarrelImportsRule.ts
- tests/tslint/tsconfig.json
- tslint.json
This has been a challenge to always catch correctly in reviews, so this will automatically throw linting errors (even in your IDE) if you are importing from a barrel instead of the file directly. This also fixes several instances of this issue that don't seem to cause build issues, because they are just interfaces and dropped from the final build anyways or are in spec files.
> [BUILD] This adds a custom TSLint rule for us to guard against barrel imports

- golden/clr-angular.d.ts
- src/clr-angular/popover/dropdown/dropdown.ts
When the client app is using OnPush detection strategy, clicking outside of a clr-dropdown doesn't hide the dropdown menu. This PR fixes the bug by using `ChangeDetectorRef` to mark the component for checking since our `AbstractPopover` class sets the `ifOpenService`'s `open` to false when a click event happens outside.
All unit tests passing. Tested across browsers.
> [NG] Fix bug with clr-dropdown with OnPush detection strategy

- src/clr-angular/data/datagrid/_datagrid.clarity.scss
- src/clr-angular/data/datagrid/render/main-renderer.spec.ts
- Added  fix that properly calculates row width when row actions are present
- Added tests for each possible row action that could be declared
- fixes #2692
> [NG] fix(datagrid-renderer):

- golden/clr-angular.d.ts
- src/clr-angular/clr-angular.module.ts
- src/clr-angular/data/datagrid/datagrid.module.ts
- src/clr-angular/data/tree-view/tree-view.module.ts
- src/clr-angular/forms-deprecated/checkbox/checkbox.spec.ts
- src/clr-angular/forms-deprecated/forms.module.ts
- src/clr-angular/forms/datepicker/date-input.spec.ts
- src/clr-angular/forms/forms.module.ts
- src/dev/src/app/button-group/button-group.demo.module.ts
- src/dev/src/app/checkboxes/checkboxes.demo.module.ts
- src/dev/src/app/datagrid/datagrid.demo.module.ts
- src/dev/src/app/datepicker/datepicker.demo.module.ts
- src/dev/src/app/forms/forms.demo.module.ts
- src/dev/src/app/input/input.demo.module.ts
- src/dev/src/app/password/password.demo.module.ts
- src/dev/src/app/radios/radios.demo.module.ts
- src/dev/src/app/selects/selects.demo.module.ts
- src/dev/src/app/textarea/textarea.demo.module.ts
- src/ks-app/src/app/app.module.ts
This change removes and renames the old forms module.
- The `ClrFormsModule` becomes `ClrFormsDeprecatedModule`
- The `ClrFormsNextModule`becomes `ClrFormsModule`
- `ClrFormsDeprecatedModule` is no longer published in `ClarityModule` and will need to be explicetly imported if an app still has old forms. (TODO: Document this on the website)
> [NG] Replace old forms module

- latest/src/app/documentation/demos/alert/alerts.demo.html
- latest/src/app/documentation/demos/alert/angular/alert-angular-app-level-alerts.demo.html
- latest/src/app/documentation/demos/alert/angular/alert-angular-close-event.demo.html
- latest/src/app/documentation/demos/alert/angular/alert-angular-close-event.ts
- latest/src/app/documentation/demos/alert/angular/alert-angular-not-closable.demo.html
- latest/src/app/documentation/demos/alert/angular/alert-angular-not-closable.ts
- latest/src/app/documentation/demos/alert/angular/alert-angular-small.demo.html
- latest/src/app/documentation/demos/alert/angular/alert-angular-small.ts
- latest/src/app/documentation/demos/alert/angular/alert-angular-success.demo.html
- latest/src/app/documentation/demos/alert/angular/alert-angular-success.ts
- latest/src/app/documentation/demos/alert/static/alert-app-level.ts
- latest/src/app/documentation/demos/alert/static/alert-cards.ts
- latest/src/app/documentation/demos/alert/static/alert-content-area.ts
- latest/src/app/documentation/demos/alert/static/alert-modals.ts
- latest/src/app/documentation/demos/alert/static/alert-sizes.ts
- latest/src/app/documentation/demos/alert/static/alert-styles.ts
• Added examples of using ARIA role "alert" to the static alert examples
• Removed instances of using div.alert-item in Angular examples to using the preferred cir-alert-item
• Did not add ARIA roles to examples on page in order to prevent screenreaders from freaking out on the number of example alerts
Tested in:
✔︎ Chrome
> [a11y] Updating alerts dox

- src/clr-angular/emphasis/alert/alert.html
- src/clr-angular/emphasis/alert/alert.spec.ts
• Adding an aria role of "alert" to the clr-alert component
• Also added unit test to make sure they are there
Tested in:
✔︎ Chrome
Closes: #2582
> [a11y] Adding aria role to alerts

- src/clr-angular/modal/modal.ts
Our boolean testing in modals was very weird. Being too strict could be a problem, so I'm changing it back to a more standard syntax.
Yes, this commit is only here for me to catch up to Scott.
Fixes #2760.
> Fix modal boolean testing

- latest/src/app/utils/code-snippet.ts
- v0.10/src/app/utils/code-snippet.ts
- v0.11/src/app/utils/code-snippet.ts
- v0.12/src/app/utils/code-snippet.ts
It's too often that default `pre { max-height: 15rem }` gets in the way while reading sample code on the doc site, given that other sites (e.g. MDN / Bootstrap / Angular.io) would just show code snippet in full-size, suggest to take out the squeezing to make it more readable.
> [WEB] Unset max-height on pre of code-snippet

- golden/clr-angular.d.ts
- src/clr-angular/wizard/providers/wizard-navigation.service.spec.ts
- src/clr-angular/wizard/providers/wizard-navigation.service.ts
- src/clr-angular/wizard/wizard.spec.ts
- src/clr-angular/wizard/wizard.ts
This removes the deprecated wizard `prev()` method, and nav service `setCurrentPage()` method.
> [NG] remove deprecated wizard features

- golden/clr-angular.d.ts
- src/clr-angular/data/datagrid/datagrid-column-toggle-button.spec.ts
- src/clr-angular/data/datagrid/datagrid-column-toggle-button.ts
- src/clr-angular/data/datagrid/datagrid.spec.ts
- src/clr-angular/data/datagrid/datagrid.ts
- src/clr-angular/data/datagrid/providers/column-toggle-buttons.service.spec.ts
- src/clr-angular/data/datagrid/providers/column-toggle-buttons.service.ts
This removes the `clrType` input on the toggle button, and the typo input `clDgRowSelection`
> [NG] remove deprecated datagrid features

- golden/clr-angular.d.ts
- src/clr-angular/modal/_modal.clarity.scss
- src/clr-angular/modal/modal.html
- src/clr-angular/modal/modal.ts
• Verified this does not affect the layout unexpectedly.
Tested in:
✔︎ Chrome
> [a11y] Adding aria-labelledby to modals

- src/clr-angular/emphasis/alert/alert-item.ts
- src/clr-angular/emphasis/alert/alert.spec.ts
- src/clr-angular/emphasis/alert/alerts-pager.spec.ts
- src/clr-angular/emphasis/alert/alerts.spec.ts
- src/clr-angular/emphasis/alert/alerts.ts
- src/clr-angular/emphasis/alert/all.spec.ts
- src/clr-angular/emphasis/alert/providers/icon-and-types.service.spec.ts
- src/clr-angular/emphasis/alert/providers/icon-and-types.service.ts
- src/clr-angular/emphasis/alert/providers/multi-alert.service.spec.ts
- src/clr-angular/emphasis/alert/utils/alert-types.ts
- src/dev/src/app/alert/angular/alert-angular-app-level-alerts.demo.html
- src/dev/src/app/alert/angular/alert-angular-app-level.demo.html
- src/dev/src/app/alert/angular/alert-angular-close-event.demo.html
- src/dev/src/app/alert/angular/alert-angular-not-closable.demo.html
- src/dev/src/app/alert/angular/alert-angular-small.demo.html
- src/dev/src/app/alert/angular/alert-angular-success.demo.html
- src/dev/src/app/wizard/wizard-async-validation.demo.html
This removes support for `alert-info` types and updates to use `clr-alert-item` for proper icon support.
> [NG] remove support for deprecated `alert-X` variations of alert types

- src/clr-angular/utils/loading/loading.spec.ts
- src/clr-angular/utils/loading/loading.ts
`listener` has `@Optional()` decorator, therefore we have to check it's not null before calling it.
> [NG] Check listener is defined before invoking it

- src/clr-angular/data/datagrid/_datagrid.clarity.scss
> fix(dark-theme): Selected datagrid row font color should be white

- src/clr-angular/utils/focus-trap/focus-trap.directive.ts
**Before**:
Angular Render2's `createElement` keeps the traces of the detached doms. Each time I open a modal component, the JS heap size kept getting the retained size of 40 bytes.
**After**:
After resorting the native DOM's `createElement` method, I found no traces of left over objects and the retained size became 0 bytes.
Also, I communicated with Mustafa and received his confirmation on the solution.
> [NG] fix memory leak in focus trap

- latest/src/app/documentation/demos/button-group/button-group.demo.html
Between 0.13 and 1.0 the checkbox text was extracted to label. This requires
a parent div.btn.checkbox though, which was missing.
> [WEB] Checkboxes in wrong format (#2822)

- src/clr-angular/data/datagrid/datagrid.spec.ts
- src/clr-angular/data/datagrid/providers/page.ts
During 0.9 -> 0.10 refactoring, the refresh has no longer been managed locally in the datagrid component, but delegated to the state provider service. Thus, we're no longer listening to page.change events directly.
StateDebouncer calls added to the _size_ setter, similar to the _current_ setter.
Tests are checking initial size change (from not set), then transition from one size to another, finally a size reset.
> [NG] Page size change was not triggering a state change (#1752)

- latest/src/app/documentation/demos/wizard/wizard-design.demo.ts
- v0.12/src/app/documentation/demos/wizard/wizard-design.demo.ts
- v0.13/src/app/documentation/demos/wizard/wizard-design.demo.ts
I am piercing shadow DOM with ::ng-deep, which is not recommended generally,
but I'm using it exceptionally to fix an issue, that will only be available
on the website. I am protecting this change not to spread to other components
on the site by preceding it with a :host, which makes the CSS more specific.
Tested on Chrome Canary, Chrome normal, Safari, FF, Edge, IE11.
Change merged to 1.0, 0.12, 0.13, as the issue is not observed on older versions.
> [WEB] Fix wizard overflow on the website (#2828)

- golden/clr-angular.d.ts
- src/clr-angular/data/tree-view/tree-node.html
- src/clr-angular/data/tree-view/tree-node.spec.ts
- src/clr-angular/data/tree-view/tree-node.ts
- src/clr-angular/data/tree-view/tree-view.module.ts
- src/dev/src/app/tree-view/lazy-declarative-tree/lazy-declarative-tree.html
- src/dev/src/app/tree-view/lazy-declarative-tree/lazy-declarative-tree.ts
- src/dev/src/app/tree-view/lazy-recursive-tree/lazy-recursive-tree.html
- src/dev/src/app/tree-view/lazy-recursive-tree/lazy-recursive-tree.ts
- src/dev/src/app/tree-view/utils/async-infinite-tree.ts
This commit adds the integration of our loading directive to the tree, to display a nice spinner instead of a caret when waiting for the children to be fetched. Works for both the declarative and recursive cases.
No gemini tests because spinners...
> [NG] Tree view: Asynchronous cases

- latest/src/app/documentation/demos/modal/modal-angular-static-backdrop.demo.html
- latest/src/app/documentation/demos/modal/modal-angular-static-backdrop.ts
- latest/src/app/documentation/demos/modal/modal.demo.html
Now the default is to ignore backdrop clicks
> [WEB] Fix docs about default modal backdrop click (#2852)

- golden/clr-angular.d.ts
- src/clr-angular/utils/dom-adapter/dom-adapter.ts
- src/clr-angular/utils/drag-and-drop/drag-and-drop-integrated.spec.ts
- src/clr-angular/utils/drag-and-drop/drag-event.ts
- src/clr-angular/utils/drag-and-drop/draggable/custom-ghost-integration.spec.ts
- src/clr-angular/utils/drag-and-drop/draggable/draggable.spec.ts
- src/clr-angular/utils/drag-and-drop/draggable/ghost-and-handle-integration.spec.ts
- src/clr-angular/utils/drag-and-drop/droppable/droppable.spec.ts
- src/clr-angular/utils/drag-and-drop/helpers.spec.ts
- src/clr-angular/utils/drag-and-drop/interfaces/drag-event.interface.ts
- src/clr-angular/utils/drag-and-drop/providers/drag-and-drop-event-bus.service.spec.ts
- src/clr-angular/utils/drag-and-drop/providers/drag-event-listener.service.spec.ts
- src/clr-angular/utils/drag-and-drop/providers/drag-event-listener.service.ts
DnD used to fire only absolute positions on the page. So if users needed to get positions relative to the initial position, they had to save the position from from `mousedown/touchstart` and subtract that from `mousemove/touchmove` positions, which makes their code complex. With this PR, DnD will also fire positions relative to its initial position. This feature is going to be very useful for refactoring the column resize feature with DnD.
> extend DnD to fire move positions relative to the starting positon

- latest/src/app/documentation/demos/datagrid/server-driven/server-driven.ts
Added a check on the "state" object, so we don't get errors can not find property "from of undefined".
> [WEB] Error when leaving server driven datagrid page (#2911)

- src/ks-app/src/app/app.component.html
- src/ks-app/src/app/app.component.scss
- src/ks-app/src/app/app.component.ts
- src/ks-app/src/app/containers/cards/cards.component.html
- src/ks-app/src/app/containers/forms/radios.component.html
- src/ks-app/src/app/containers/forms/selects.component.html
- src/ks-app/src/app/containers/progress/progress-bars.component.html
- src/ks-app/src/app/containers/tables/tables.component.html
- src/ks-app/src/app/containers/typography/typography.component.html
[KS-APP][A11Y] Skip repetitive content (#1936)
[KS-APP][A11Y] Heading levels in progress bar page (#1940)
[KS-APP][A11Y] Add scopes to table headers (#1934)
[KS-APP][A11Y] Label for="id" fix at Selects page (#1921)
[KS-APP][A11Y] Radiogroup labels ignored on Radios page (#1916)
[KS-APP][A11Y] Cards view - provide image alt (#1914)
>  [KS-APP][A11Y] A group of small a11y fixes on the ks-app (#1954)

- src/clr-angular/button/button-loading/loading-button.ts
In Chromium browsers button loading animation would not be visible with CSS multi-columns. Here is a minimal CSS/HTML only reproduction of the bug.
https://stackblitz.com/edit/js-bbvdrm?file=style.scss
It looks to be some kind of rendering bug. Changing certain properties cause the loader to render properly. Using `transform: translatez(0);` seems to fix the issue while not altering any of the existing rendered styles. This might also help the animation render performance as translatez will create a new layer for the browser to render with. We would want to use this dynamically as it's not ideal for every button to create its own layer.
closes #2700
> [NG] fix button animation issue

- src/clr-angular/data/datagrid/_datagrid.clarity.scss
Fixes https://github.com/vmware/clarity/issues/2924
Before:
After:
> remove unnecessary pagination separator

- src/clr-angular/popover/tooltip/_tooltips.clarity.scss
Fix small gap rendered between tooltip body and arrow in Safari. Also removed unnecessary ie10 style.
Tested in Chrome, Firefox, Safari, IE11 and Edge.
closes vmware#2715
> tooltip style fix

- package.json
- src/clr-angular/forms/datepicker/date-container.spec.ts
- tests/tslint/src/noBarrelImportsRule.ts
There was an issue where we were getting all import paths wrapped in a set of quotes like `'@angular/core'` and `'../common'`, and the quotes weren't being removed properly. This removes them always, and then checks the files that are imported from relative paths if they resolve to a file or a directory. It also adds support for verifying imports of json, html, and text files.
> fix lint rule for barrels

- src/clr-angular/emphasis/alert/alert.ts
In prod mode the first alert in alert list is not visible to the user. This happens when using `enableProdMode()` and is unrelated to AOT.
The check `isHidden()` only happens once during prod mode while in dev happens multiple times. In production it looks like `isHidden` is called before the `QueryList` of the parent alerts component has updated. So when `isHidden` checks to see if there are any alerts in the `QueryList` is empty the first time. Every subsequent check seems to work normally. 
I found a "fix" but I don't think its a good solution. The code change checks if the list is empty then it can assume its the first alert in the alert list and can fall into the correct if block. Any feedback or ideas would be appreciated.
closes #2430
> [NG] fix alert visibility issue

- src/clr-angular/data/datagrid/_datagrid.clarity.scss
- applies only when all other columns are hidden
- fixes #2976
> [UI] Fixes datagrid header bg color and row border

- golden/clr-angular.d.ts
- src/clr-angular/forms/datepicker/date-input.spec.ts
- src/clr-angular/forms/datepicker/date-input.ts
- src/clr-angular/forms/datepicker/providers/datepicker-focus.service.spec.ts
- src/clr-angular/forms/datepicker/providers/datepicker-focus.service.ts
- After date selected by user refocus the input.
- If updating the value from user then programmatically and back to the user, the output event
should fire properly for two way binding.
closes vmware#2792
closes vmware#2993
> [NG] datepicker fixes

- netlify.toml
- package-lock.json
- package.json
- scripts/netlify/download-icon.js
- src/website/src/app/icons/icons-sets/icon-detail-card/icon-detail-card.component.ts
- src/website/src/environments/environment.prod.ts
- src/website/src/sitemap.xml
This updates the website to now have a netlify function for downloading the icon files directly from github raw urls. GitHub doesn't set the Content-Disposition header for download of the binary, so this basically proxies the call to do that for you. It also updates the website to build the URL to the icon function.
fixes #3044
> [web] add icon download function

- golden/clr-angular.d.ts
- src/clr-angular/forms/datepicker/date-input.spec.ts
- src/clr-angular/forms/datepicker/date-input.ts
- src/clr-angular/forms/datepicker/providers/date-io.service.spec.ts
- src/clr-angular/forms/datepicker/providers/date-io.service.ts
- src/clr-angular/forms/datepicker/providers/datepicker-focus.service.spec.ts
- src/clr-angular/forms/datepicker/providers/datepicker-focus.service.ts
- src/clr-angular/forms/datepicker/utils/date-utils.spec.ts
- src/clr-angular/forms/datepicker/utils/date-utils.ts
When using clrDate input, setting input to null would not clear the input.
closes vmware#3012
> [NG] fix input reset on datepicker/refactor

- src/clr-angular/progress/progress-bars/_progress-bars.clarity.scss
- src/ks-app/src/app/containers/progress/progress-bars.component.html
The new grid classes don't impose position: relative on the container.
> [UI][KS-APP] Fix inline progress-bar (#2856)

- golden/clr-angular.d.ts
- src/clr-angular/data/datagrid/_datagrid.clarity.scss
- src/clr-angular/data/datagrid/all.spec.ts
- src/clr-angular/data/datagrid/datagrid-column-reorder-droppable.spec.ts
- src/clr-angular/data/datagrid/datagrid-column-reorder-droppable.ts
- src/clr-angular/data/datagrid/datagrid-column.spec.ts
- src/clr-angular/data/datagrid/datagrid-column.ts
- src/clr-angular/data/datagrid/datagrid-hideable-column.model.spec.ts
- src/clr-angular/data/datagrid/datagrid-hideable-column.spec.ts
- src/clr-angular/data/datagrid/datagrid.spec.ts
- src/clr-angular/data/datagrid/datagrid.ts
- src/clr-angular/data/datagrid/enums/header-sides.enum.ts
- src/clr-angular/data/datagrid/providers/column-order-model.service.mock.ts
- src/clr-angular/data/datagrid/providers/column-order-model.service.spec.ts
- src/clr-angular/data/datagrid/providers/column-order-model.service.ts
- src/clr-angular/data/datagrid/providers/column-orders-coordinator.service.spec.ts
- src/clr-angular/data/datagrid/providers/column-orders-coordinator.service.ts
- src/clr-angular/data/datagrid/providers/column-resizer.service.spec.ts
- src/clr-angular/data/datagrid/providers/table-size.service.spec.ts
- src/clr-angular/data/datagrid/render/header-renderer.spec.ts
- src/clr-angular/data/datagrid/render/header-renderer.ts
- src/clr-angular/data/datagrid/render/main-renderer.ts
- src/clr-angular/utils/drag-and-drop/droppable/droppable.ts
This PR solves a problem of activating a correct reorder droppable with a proper amount of drop tolerance. In this current implementation, every column header has two `clr-dg-column-reorder-droppable`s on its right and left sides. 
**This PR contains:**
- Partial implementation of two major services: `ColumnOrdersCoordinatorService` and `ColumnOrderModelService`
- Implementation of `ClrDatagridColumnReorderDroppable`
**The next PR will contain:**
- the business logic of dropping and swapping headers
- the animation of columns changing their positions.
Preview: http://gimme-drop-area.surge.sh/datagrids
> Reorder column droppable

- src/website/src/sitemap.xml
Missing/wrong URLs lead to 404 on browser refresh or direct link
> Fix sitemap to prevent 404 errors on website

- src/website/src/app/documentation/demos/datepicker/datepicker.demo.html
- src/website/src/app/documentation/demos/datepicker/demos/datepicker-api.demo.html
- src/website/src/app/documentation/demos/datepicker/demos/datepicker-api.demo.ts
- src/website/src/app/documentation/demos/datepicker/demos/datepicker-date-io.demo.html
- src/website/src/app/documentation/demos/datepicker/demos/datepicker-date-io.demo.ts
- src/website/src/app/documentation/demos/datepicker/demos/datepicker-enUS.demo.ts
- src/website/src/app/documentation/demos/datepicker/demos/datepicker-fr.demo.ts
- src/website/src/app/documentation/demos/datepicker/demos/datepicker-reactive-forms.html
- src/website/src/app/documentation/demos/datepicker/demos/datepicker-reactive-forms.ts
- src/website/src/app/documentation/demos/datepicker/demos/datepicker-template-driven-forms.html
- src/website/src/app/documentation/demos/datepicker/demos/datepicker-template-driven-forms.ts
- src/website/src/app/documentation/demos/forms/forms.demo.html
- src/website/src/app/documentation/demos/forms/forms.demo.ts
- src/website/src/app/documentation/demos/forms/ng/optional.html
- src/website/src/app/documentation/demos/toggles/toggles.demo.html
This addresses a bad link in the toggle page (#3119), adds date container to the docs (#3054), and adds optional vs required UX to forms (#3004)
closes #3119
closes #3054
closes #3004
Signed-off-by: Jeremy Wilken <gnomation@gnomeontherun.com>
> update website content for toggles, date picker, and forms

- src/website/src/app/documentation/demos/wizard/wizard.demo.html
The closing > on several code tags had been duplicated.
This commit removes the duplicates.
Signed-off-by: Jeremy Canady <jcanady@gmail.com>
> [WEB] Remove duplicate closing bracket on code tags

- src/clr-angular/data/datagrid/providers/selection.spec.ts
- src/clr-angular/data/datagrid/providers/selection.ts
Selection was not cleared when Filters were applied for SingleSelect mode
closes #3106
Signed-off-by: Sergiu Pantiru <12131904+sergiupantiru@users.noreply.github.com>
> [NG] fix DataGrid clearSelection for SingleSelect mode

- golden/clr-angular.d.ts
- src/clr-angular/button/button-group/button.spec.ts
- src/clr-angular/button/button-group/button.ts
* [NG] fix button title for button group
Properly set title attribute for button in button group.
closes #3132
> (v1 backport) [NG] fix button title for button group (#3136)

- src/schematics/README.md
- src/schematics/src/add/index.ts
This will setup the Clarity @next version when trying to use a n+1 version of Angular support.
Updated `ng add @clr/angular` to detect if you are using a version of Angular that is ahead of our latest version (such as beta releases) and automatically install our beta/rc version as well to avoid mismatches.
> feat(schematics) automatically support installing @next

- src/clr-angular/forms/datepicker/date-input.spec.ts
- src/clr-angular/forms/datepicker/date-input.ts
Fixes issue where `clrDate` did not emit or set the date value when the native datepicker was active.
closes #3139 
> [NG] datepicker event fix

- golden/clr-angular.d.ts
- src/clr-angular/data/datagrid/_datagrid.clarity.scss
- src/clr-angular/data/datagrid/datagrid-column.spec.ts
- src/clr-angular/data/datagrid/datagrid-column.ts
- src/clr-angular/image/_icons.clarity.scss
- Removes the svg from scss
- adds a clr-icon that can toggle between both sorting states
- removes the clr-icon when unsorted
> fix(datagrid): adds sort button icon to datagrid-column

- src/clr-angular/data/datagrid/all.spec.ts
- src/clr-angular/data/datagrid/datagrid-pagination.integration.spec.ts
- src/clr-angular/data/datagrid/datagrid-pagination.ts
- src/clr-angular/data/datagrid/providers/items.spec.ts
- src/clr-angular/data/datagrid/providers/items.ts
- src/clr-angular/data/datagrid/providers/page.ts
Because of a lifecycle quirk, we would instantiate as many ClrDatagridRow components
as we would have in the entire dataset. They wouldn't go throught their full Angular
lifecycle, but they would be instantiated nonetheless.
This commit fixes this by making the Items provider wait for the page size to be
available before emitting any changes.
Fixes #3082.
> [NG] Fix pagination init lifecycle

- src/clr-angular/data/datagrid/_datagrid.clarity.scss
- src/dev/src/app/datagrid/datagrid.demo.html
- src/dev/src/app/datagrid/datagrid.demo.module.ts
- src/dev/src/app/datagrid/datagrid.demo.routing.ts
- src/dev/src/app/datagrid/responsive-footer/responsive-footer.html
- src/dev/src/app/datagrid/responsive-footer/responsive-footer.ts
Made datagrid footer wrap to new lines on smaller screens.
Updated margins, removed dividers, as requested in the spec.
closes #2855 
closes #3097 
> [NG] Datagrid footer responsive layout (#3097)

- src/clr-angular/data/datagrid/datagrid-column-separator.ts
- src/clr-angular/data/datagrid/datagrid-footer.spec.ts
- src/clr-angular/data/datagrid/datagrid-footer.ts
- src/clr-angular/data/datagrid/datagrid-row-detail.spec.ts
- src/clr-angular/data/datagrid/datagrid-row-detail.ts
- src/clr-angular/data/datagrid/datagrid-row.spec.ts
- src/clr-angular/data/datagrid/datagrid-row.ts
- src/clr-angular/data/datagrid/datagrid.spec.ts
- src/clr-angular/data/datagrid/datagrid.ts
- src/clr-angular/data/datagrid/enums/column-changes.enum.ts
- src/clr-angular/data/datagrid/enums/selection-type.ts
- src/clr-angular/data/datagrid/helpers.spec.ts
- src/clr-angular/data/datagrid/interfaces/column-state.interface.ts
- src/clr-angular/data/datagrid/providers/columns.service.ts
- src/clr-angular/data/datagrid/providers/selection.spec.ts
- src/clr-angular/data/datagrid/providers/selection.ts
- src/clr-angular/data/datagrid/render/cell-renderer.spec.ts
- src/clr-angular/data/datagrid/render/cell-renderer.ts
- src/clr-angular/data/datagrid/render/constants.ts
- src/clr-angular/data/datagrid/render/header-renderer.spec.ts
- src/clr-angular/data/datagrid/render/header-renderer.ts
- src/clr-angular/data/datagrid/render/main-renderer.spec.ts
- src/clr-angular/data/datagrid/render/main-renderer.ts
- src/clr-angular/data/datagrid/render/render-organizer.spec.ts
- src/clr-angular/data/datagrid/render/render-organizer.ts
- src/clr-angular/data/datagrid/render/row-renderer.spec.ts
- src/clr-angular/data/datagrid/render/row-renderer.ts
- src/dev/src/app/datagrid/hide-show-columns/hide-show.html
- src/dev/src/app/datagrid/hide-show-columns/hide-show.ts
This will eventually be used to store several other stateful properties of columns, such as hidden and ordering information. For now, it is to give us a starting implementation point to store column states in a way that is consolidated and easily cached.
Internally, this lifts the state of the width calculations out of the render organizer into a centralized column service. This array of behaviorsubjects get passed into the column cells based on their index, and each cell subscribes to column changes. This privatizes some of the connection between the main/header and row/cell renderers. More work is to be done here, this is just a first pass at the basic architecture.
I also moved the SelectionType enum to its own file, since that is our pattern.
**Internal change - no release notes …
> adding a column service to datagrid to track widths

- src/clr-angular/emphasis/alert/alert.html
- src/clr-angular/emphasis/alert/alert.spec.ts
Removed unnecessary `aria-live` attribute when using `role="alert"`.
closes #3195
> [NG] remove duplicate aria behavior with alerts

- src/clr-angular/data/tree-view/models/recursive-tree-node.model.spec.ts
- src/clr-angular/data/tree-view/models/recursive-tree-node.model.ts
- src/clr-angular/data/tree-view/recursive-children.spec.ts
- src/clr-angular/data/tree-view/recursive-children.ts
We used to fetch children for lazy recursive trees only once, but we closed their selection Observable when we shouldn't. Rather than avoid closing the Observables when we reuse models, I decided to stop caching children altogether, letting the app decide whether they want to cache or not and do it on their side. It's less intrusive and more flexible.
Fixes #3209.
> [NG] Stop caching children for lazy recursive trees

- src/clr-angular/data/tree-view/tree-node.spec.ts
- src/clr-angular/data/tree-view/tree-node.ts
- src/dev/src/app/tree-view/eager-recursive-tree/eager-recursive-tree.html
- src/dev/src/app/tree-view/eager-recursive-tree/eager-recursive-tree.ts
- src/dev/src/app/tree-view/pre-selection/pre-selection.html
- src/dev/src/app/tree-view/pre-selection/pre-selection.ts
fix(tree) set tree view node event emitter to synchronous and don't output selected changes when setting input on node
A tree view with a number of nodes could be tricked into a state of uncertainty (flickering) by double clicking fast to trigger too many async event loops in the bindings. This stops the event propagation from firing in this specific case, but keeps it in the remainder where it is needed to update other nodes.
fixes #3073
Bugfix for tree view where it could trigger a flickering state by double clicking fast, or in any case where the tree tried to update before the tree had stabilized.
> Fix tree view flickering from async eventemitter

- src/website/src/manifest.json
Fixes 404 path issue for logo images with site metadata.
closes #3234
> [WEBSITE] fix logo paths

- src/clr-angular/button/_buttons.clarity.scss
Remove box shadow on disabled buttons to prevent shadow from showing on active state.
> [UI] remove box shadow on disabled buttons

- karma.conf.js
Since Sauce Labs is failing a large percentage of the time, this will disable it so we stop having failing builds on master. Its not doing us any good right now, and may need to be replaced.
> disable sauce labs

- golden/clr-angular.d.ts
- src/clr-angular/deprecations.spec.ts
- src/clr-angular/forms/common/form.spec.ts
- src/clr-angular/forms/common/form.ts
- src/clr-angular/forms/common/if-error/if-error.service.spec.ts
- src/clr-angular/forms/common/if-error/if-error.service.ts
- src/clr-angular/forms/common/providers/mark-control.service.ts
- src/clr-angular/forms/common/wrapped-control.spec.ts
- src/clr-angular/forms/common/wrapped-control.ts
- src/clr-angular/forms/styles/_checkbox.clarity.scss
- src/clr-angular/forms/styles/_radio.clarity.scss
- src/clr-angular/forms/tests/container.spec.ts
- src/clr-angular/forms/tests/control.spec.ts
- src/dev/src/app/forms/reset/reset.ts
- src/dev/src/app/input/input.demo.html
- src/dev/src/app/password/password.demo.html
- src/website/src/app/documentation/demos/forms/forms.demo.html
- src/website/src/app/documentation/demos/forms/ng/validate.txt
- src/website/src/app/documentation/demos/radio/radio.demo.html
This updates the validation logic to only care about the touched state of a control before it will show validation errors. The reason is we had a dirty state being considered as well, and it would cause validation errors to show too soon. In reality, we only care after the control has been touched (focused and blurred).
This deprecates the `ClrForm.markAsDirty` API in favor of a better named `ClrForm.markAsTouched`.
fixes #3221
fixes #3081
> fix premature validation appearing until after touched, fixed styling for disabled checkbox/radios

- src/clr-angular/layout/tabs/_tabs.clarity.scss
- src/clr-angular/layout/tabs/tab-content.ts
- src/clr-angular/layout/tabs/tabs.spec.ts
- src/clr-angular/layout/tabs/tabs.ts
The introduction of block-level section element had introduced the
need to explicitly manage the container height. Reverting it to
inline will allow direct visibility between the tab content and tabs
parent container.
> [NG] Enable tab content to scale to tabs container (#3279)

- golden/clr-angular.d.ts
- src/clr-angular/forms/common/error.spec.ts
- src/clr-angular/forms/common/error.ts
Minor adjustments for `clr-control-error` to make it more accessible to screen readers.
closes #3289 
> [NG] a11y improvements for control errors

- src/clr-angular/data/datagrid/datagrid-pagination.spec.ts
- src/clr-angular/data/datagrid/datagrid-pagination.ts
- src/clr-angular/data/datagrid/providers/items.spec.ts
- src/clr-angular/data/datagrid/providers/page.spec.ts
- src/clr-angular/data/datagrid/providers/page.ts
Page First Item and Last Item of None
Page's firstItem & lastItem can be used in generating page info by using the template
`{{page.firstItem + 1}} to {{page.lastItem + 1}} of {{page.totalItems}} items`
When both return -1 of none, the `1 to 20 of 0 items` bug could be fixed.
Happy new year.
Signed-off-by: KingMario <gcyyq@hotmail.com>
> Page First Item and Last Item of None

- golden/clr-angular.d.ts
- src/clr-angular/data/datagrid/datagrid-column-toggle-button.ts
- src/clr-angular/data/datagrid/datagrid-column-toggle-title.ts
- src/clr-angular/data/datagrid/datagrid-column-toggle.ts
- src/clr-angular/data/datagrid/datagrid.ts
- src/clr-angular/data/datagrid/providers/selection.ts
- src/clr-angular/deprecations.spec.ts
- src/clr-angular/emphasis/alert/alerts.spec.ts
- src/clr-angular/utils/i18n/common-strings.interface.ts
- src/clr-angular/utils/i18n/common-strings.service.ts
- src/dev/src/app/drag-and-drop/basic-droppable.demo.html
- src/dev/src/app/i18n-a11y/common-strings.service.ts
- src/dev/src/app/virtual-scroll/virtual-scroll.demo.ts
- src/ks-app/src/app/containers/drag-and-drop/dnd.component.html
- src/website/src/app/documentation/demos/datagrid/hide-show-columns/hide-show-columns.html
- src/website/src/app/documentation/demos/datagrid/hide-show-columns/hide-show-columns.ts
- src/website/src/app/documentation/demos/datagrid/single-selection/single-selection.html
- src/website/src/app/documentation/demos/i18n/i18n.demo.html
- src/website/src/app/documentation/demos/i18n/i18n.demo.module.ts
- src/website/src/app/documentation/demos/i18n/i18n.demo.ts
- src/website/src/app/documentation/documentation-routing.module.ts
- src/website/src/app/icons/icons-get-started/icons-get-started.component.html
- src/website/src/settings/componentlist.json
Deprecate the row selection and column toggler overrides. Row selection (#2933) is not accessible and column toggler (#3304) is being brought into line with the other i18n strings in Clarity.
This also adds a new i18n page in docs with how to use strings service.
closes #3304
closes #2933
> datagrid deprecations for row selection and column toggle title/buttons

- .travis.yml
This will stop uploading the gemini reference images and gemini failed images to S3/AWS.
After this is merged I can remove the AWS keys from the build settings. 
> [CORE] fix: Removes artifacts from travis config

- scripts/update-license.js
The pre-commit changes were not being staged and added to the commit so you'd have to amend your commit with the changes to get license header updates. This will stage the changes before they are committed.
> fix license update script to stage changes before commit

- src/clr-angular/data/datagrid/datagrid-cell.spec.ts
- src/clr-angular/data/datagrid/datagrid-cell.ts
- src/clr-angular/data/datagrid/datagrid-row.html
- src/clr-angular/data/datagrid/datagrid.html
This is the basic fix, but I'm still not getting it to read the column headers when reading a cell with VoiceOver. I also cannot get it to work in _any_ `role="grid"` component (ours or found anywhere on the web), unless it is an actual table element.
> change datagrid cell to gridcell role

- src/clr-angular/layout/grid/utilities/_align.clarity.scss
- src/clr-angular/layout/grid/utilities/_clearfix.clarity.scss
- src/clr-angular/layout/grid/utilities/_display.clarity.scss
- src/clr-angular/layout/grid/utilities/_flex.clarity.scss
- src/clr-angular/layout/grid/utilities/_float.clarity.scss
- src/clr-angular/layout/grid/utilities/_visibility.clarity.scss
- src/clr-angular/utils/_components.clarity.scss
The layout/responsive utilities were marked and removed from deprecation. Teams still use them even though they are undocumented. This PR adds them back and prefixes them with `clr-` so it is an easier migration to 2.0. In a later PR we can add visual diff tests (gemini I think is being removed so wait for applitools?) and document these APIs as they are useful and it makes sense to be included with Clarity UI.
closes #3403
> [UI] add layout utilities

- src/website/src/app/documentation/demos/datepicker/demos/datepicker-internationalization.demo.html
- src/website/src/app/documentation/demos/datepicker/demos/datepicker-internationalization.demo.ts
Updated the datepicker internationalization example in the documentation.
* What is the change?
Added codesnippets to show how to register the data of a locale and how to use  `LOCALE_ID ` to change the date format of the DatePicker
* What is a use case for this change?
Prevent errors while changing the locale
> [DOCS] Update datepicker internationaization example

- src/clr-angular/popover/dropdown/providers/dropdown-focus-handler.service.ts
- src/clr-angular/popover/dropdown/providers/dropdown-focus-handler.spec.ts
There was a small bug for the dropdown where the item that was focused retains the focus when you close the dropdown. This was happening only on dropdowns whose items weren't being destroyed (i.e. not using `*clrIfOpen`). This is a fix for that.
> [ng] clear focus on focused items inside dropdown container on focusout

- src/clr-angular/forms/styles/_mixins.forms.scss
This removes an important css overrid that was needed for deprecated forms. 
> fix(forms): remove deprecated from .clr-input elements.

- src/website/src/app/documentation/demos/i18n/i18n.demo.html
- src/website/src/app/documentation/demos/i18n/i18n.demo.module.ts
- src/website/src/app/documentation/demos/i18n/i18n.demo.ts
- src/website/src/app/documentation/documentation-routing.module.ts
- src/website/src/settings/componentlist.json
Backporting the Internationalization documentation from v2 to v1 under Patterns.
> [WEB] Backport the Internationalization documentation to V1

- src/clr-icons/clr-icons-element.ts
- src/clr-icons/clr-icons.spec.ts
- src/clr-icons/helpers.spec.ts
- src/clr-icons/utils/svg-tag-generator.ts
- src/website/src/app/icons/icons-a11y/icons-a11y.component.html
- src/website/src/app/icons/icons-a11y/icons-a11y.component.ts
- src/website/src/app/icons/icons-routing.module.ts
- src/website/src/app/icons/icons.component.html
- src/website/src/app/icons/icons.module.ts
Fixes icon a11y issue as well as documentation for the different use cases. Fixes issue where `aria-labelledby` should be on svg element to be properly read by screen reader. Also removes `aria-hidden` preventing screen reader from finding element.
> Icons a11y and docs

- angular.json
- src/website/src/robots.txt
Adds missing robots.txt file. This is for SEO related to search engine crawlers.
closes #3447
> [WEBSITE] fix add missing robots.txt file

- src/clr-angular/modal/modal-body.spec.ts
- src/clr-angular/modal/modal-body.ts
- src/clr-angular/modal/modal.module.ts
Adds a directive to dynamically attach the proper tabindex on instances of `.modal-body`.
closes #3424
> [NG] fixes modal body content keyboard scroll support

- src/clr-angular/layout/main-container/_variables.header.scss
- src/clr-angular/layout/nav/_header.clarity.scss
Fixes broken links in header layout when custom text spacing is applied to meet a11y spacing requirements. Test and ran gemini locally. Deleted unnecessary scoped header link styles.
closes #3367
> [UI] fix line height issue for custom text spacing

- src/clr-angular/accordion/_accordion.clarity.scss
- src/dev/src/app/accordion/accordion.demo.html
When no step or accordion content is given the button will now span the full width of the component.
closes #3454
> [UI] fix accordion button width

- src/clr-angular/popover/dropdown/dropdown-trigger.ts
Updates ClrDropdownTrigger to not use the private ifOpenService in the host attribute configuration to prevent issues with AOT compilation.
> ClrDropdownTrigger Angular AOT fix

- src/clr-angular/data/stack-view/stack-block.ts
- src/clr-angular/data/stack-view/stack-view.module.ts
- src/clr-angular/utils/animations/expandable-animation/expandable-animation.ts
Replaced with the animation component we created for datagrid
expandable rows.
Tested in safari - OK now.
closes #3350 
> Stackview animation fix (#3350)

- src/clr-angular/modal/modal.html
- src/clr-angular/modal/modal.spec.ts
Adding `aria-label` to the close button on top of the modal header.
Close #3413
> Modal close button needs an accessible name 

- golden/clr-angular.d.ts
- src/clr-angular/accordion/accordion-panel.html
- src/clr-angular/accordion/stepper/stepper-panel.spec.ts
- src/clr-angular/modal/modal.html
- src/clr-angular/modal/modal.spec.ts
- src/clr-angular/utils/_a11y.clarity.scss
- src/clr-angular/utils/i18n/common-strings.interface.ts
- src/clr-angular/utils/i18n/common-strings.service.ts
- src/website/src/app/utils/skip-link.component.ts
MacOS Safari + Voice Over do not properly support aria/role attributes for modals. This PR introduces screen reader only text that allows a screen reader only user to know when they are entering and leaving a modal.
closes #3414
> [NG] improve modal a11y for screen readers

- scripts/update-license.js
Currently, the update-license script that updates the year for modified files is throwing an error for deleted files and preventing me from committing deletion of files. Modifying the script to skip deleted files. Refer to documentation on `--diff-filter` here: https://git-scm.com/docs/git-diff
> [core] skip deleted files in script to update licensing info

- src/clr-angular/popover/dropdown/providers/dropdown-focus-handler.service.ts
fix bug where dropdown menu closes on clicking an item to open submenu on IE 11
> [ng] dropdown bug in IE 11

- golden/clr-angular.d.ts
- src/clr-angular/forms/datepicker/date-container.spec.ts
- src/clr-angular/forms/datepicker/date-container.ts
This change listens for the escape keyboard event and returns focus to the datepicker toggle button when the picker is closed via escape. 
- closes #3468
> [ng] fix(datepicker): Add HostListener for the datepicker toggle button

- golden/clr-angular.d.ts
- src/clr-angular/forms/datepicker/date-container.spec.ts
- src/clr-angular/forms/datepicker/date-container.ts
This is a backport of the fix for v1 into the v1 codebase. 
I had to modify the fix because of the dual templates that support both old and new forms in v1. 
I don't really like this fix but it avoids modifying other parts of v1 (AbstractPopover also has an escape listener and that seems to interfere with the HostListener in v1). Also ran into an issue where I couldn't `@ViewChild` the buttons because they are in templates. 
- closes #3468
> [ng] fix(datepicker): Add HostListener to focus on the datepicker toggle button

- golden/clr-angular.d.ts
- src/clr-angular/data/datagrid/datagrid-action-overflow.spec.ts
- src/clr-angular/data/datagrid/datagrid-action-overflow.ts
- src/clr-angular/data/datagrid/datagrid-filter.spec.ts
- src/clr-angular/data/datagrid/datagrid-filter.ts
- src/clr-angular/data/datagrid/datagrid.html
- src/clr-angular/data/datagrid/datagrid.ts
Done (4/5)
- When using the page count select box, when the selection is changed the focus should move back to the start of the newly displayed content.
- When using the previous/next pagination buttons, the focus should move back to the start of the newly displayed content.
- When closing a filter, the focus is lost to the page when it should return to the filter toggle button.
- Screen reader users will not be aware of actions available from the clr-dg-action-overflow component when it appears because focus remains on the trigger but should move into the menu.
Todo (1/5)
- When using the select all button, the focus is lost to the page when it should remain on the select all button.
Submitting 4/5 for early discussion on the clr-dg-action-overflow focus approach, which was inspired by …
> Datagrid focus management (#3370)

- src/clr-icons/shapes/essential-shapes.ts
Should end on Z. The M18 is half of the next Move command from the outline version.
closes #3546 
> Fix solid circle icon format

- src/clr-angular/layout/grid/mixins/_breakpoint.clarity.scss
- src/clr-angular/layout/grid/utilities/_visibility.clarity.scss
This utility classes hide elements responsively when the window crosses a maximum width threshold. They were unintentionally removed when we got rid of the old Bootstrap grid.
It's worth noting that Bootstrap removed these in a BS4-beta version.
Tested in:
✔︎ Chrome
✔︎ IE11
✔︎ Edge
Closes: #3457
> [BUG] Restoring hidden-[size]-down utility classes

- src/clr-angular/utils/bootstrap/utilities/_visibility.scss
The utility classes were present in 1.x but not prefixed. I added prefixed versions for the backport.
Tested in:
✔︎ Chrome
Closes: #3457
> [BUG] Restoring hidden-[size]-[up|down] utility classes

- golden/clr-angular.d.ts
- src/clr-angular/data/datagrid/datagrid-action-overflow.ts
- src/clr-angular/data/datagrid/datagrid-column-toggle-button.ts
- src/clr-angular/data/datagrid/datagrid-column-toggle.spec.ts
- src/clr-angular/data/datagrid/datagrid-column-toggle.ts
- src/clr-angular/utils/i18n/common-strings.interface.ts
- src/clr-angular/utils/i18n/common-strings.service.ts
- src/website/src/app/documentation/demos/i18n/i18n.demo.ts
- fixed focus lost after "select all" button clicked
- fixed no notification on popup opened
- fixed focus lost on column checkbox toggled
- minor selector improvement suggested by Shijir in part 1
closes #3370
> Datagrid focus management (part 2 - show/hide columns)

- golden/clr-angular.d.ts
- src/clr-angular/data/datagrid/datagrid-action-overflow.ts
- src/clr-angular/data/datagrid/datagrid-column-toggle.spec.ts
- src/clr-angular/data/datagrid/datagrid-column-toggle.ts
- src/clr-angular/utils/i18n/common-strings.interface.ts
- src/clr-angular/utils/i18n/common-strings.service.ts
- src/website/src/app/documentation/demos/i18n/i18n.demo.ts
Note! Some parts rewritten due to big codebase difference.
Will appreciate a review!!!
(cherry picked from commit 5de0dd6d456434a743593f80b9336eeeef5639f1)
- fixed focus lost after "select all" button clicked
- fixed no notification on popup opened
- fixed focus lost on column checkbox toggled
> Backport * Datagrid focus management (part 2 - show/hide columns)

- golden/clr-angular.d.ts
- src/clr-angular/forms/common/helper.spec.ts
- src/clr-angular/forms/common/helper.ts
- src/clr-angular/forms/common/wrapped-control.spec.ts
- src/clr-angular/forms/common/wrapped-control.ts
- src/clr-angular/forms/tests/container.spec.ts
closes #3554
This makes it possible for a screen reader to hear the helper text while they are on the input by using aria-described by in forms.
> fix(forms) link helper text to input with aria-describedby

- package-lock.json
- src/clr-icons/clr-icons-element.ts
- src/clr-icons/clr-icons.spec.ts
- src/website/src/app/documentation/demos/button-group/button-group.demo.html
- src/website/src/app/documentation/demos/button-group/button-group.demo.ts
- src/website/src/app/documentation/demos/buttons/buttons.demo.html
* Update website button group examples by adding `title` to button groups that have only icons.
* Adding a reminder for Developers to add a title to icons when the button doesn't have human-readable text
* Use only `Core Icons` inside the Buttons & Buttons Group examples. No need to load other icons sets.
* Make `clrIcon` shape attribute case-insensitive - `HOME` and `home` must equal the same icon.
Close #3530 
TODO: 
Backport it to V1
> Icons in buttons need accessible names

- golden/clr-angular.d.ts
- src/clr-angular/accordion/accordion-panel.html
- src/clr-angular/accordion/accordion-panel.ts
- src/clr-angular/accordion/stepper/models/stepper.model.spec.ts
- src/clr-angular/accordion/stepper/models/stepper.model.ts
- src/clr-angular/accordion/stepper/stepper-panel.spec.ts
- src/clr-angular/accordion/stepper/stepper-panel.ts
- Describe current state with button, helpful for screen reader users who tab back to a prior step.
- Disable button when locked on step (error or inactive)
closes #3529
> [NG] stepper a11y states

- BUILD.md
- package.json
- usage: `npm run format:file -- path/to/file`
- multiple files can be passed to the script as needed
N/A
Clarity developers can format one or more files:
`npm run format:file -- path/to/file`
> build: adds file formatting script for npm users

- golden/clr-angular.d.ts
- src/clr-angular/forms/common/error.spec.ts
- src/clr-angular/forms/common/error.ts
- src/clr-angular/forms/common/wrapped-control.spec.ts
- src/clr-angular/forms/common/wrapped-control.ts
Set the proper describe by when error message is visible on an input. The error message had the `aria-describeby` when it should of been the input instead. 
Issue Number:
closes #3561 
When an error occurs the input will now be described by the error message.
> fix(forms): describe by for input validation errors

- scripts/clr-icons-svg.js
The SVG build script wasn't building the text-edit icon set.
The SVG build script now builds the text-edit icon set.
Verified locally that the script works as expected. End result can be seen here https://github.com/vmware/clarity-assets/commit/865169f6ceeaa06152b653bb9d22d2b316bc7ba9
Those icons were built using this script.
> fix: adding the text-edit set to the svg icon build script

- src/dev/src/app/dropdown/dropdown-angular-close-item-false.demo.html
- src/dev/src/app/dropdown/dropdown-angular-nested.demo.html
- src/dev/src/app/dropdown/dropdown-angular-positioning.demo.html
- src/dev/src/app/dropdown/dropdown-static-buttonlink-toggle.demo.html
- src/dev/src/app/dropdown/dropdown-static-default.demo.html
- src/dev/src/app/dropdown/dropdown-static-icon-toggle.demo.html
- src/dev/src/app/dropdown/dropdown-static-positioning.demo.html
- src/ks-app/src/app/containers/cards/cards.component.html
- src/ks-app/src/app/containers/popover/dropdowns.component.html
- src/website/src/app/documentation/demos/dropdown/dropdown-angular-close-item-false.demo.html
- src/website/src/app/documentation/demos/dropdown/dropdown-angular-close-item-false.ts
- src/website/src/app/documentation/demos/dropdown/dropdown-angular-positioning.demo.html
- src/website/src/app/documentation/demos/dropdown/dropdown-static-buttonlink-toggle.demo.html
- src/website/src/app/documentation/demos/dropdown/dropdown-static-default.demo.html
- src/website/src/app/documentation/demos/dropdown/dropdown-static-fontawesome-toggle.demo.html
- src/website/src/app/documentation/demos/dropdown/dropdown-static-icon-toggle.demo.html
- src/website/src/app/documentation/demos/dropdown/dropdown-static-positioning.demo.html
- src/website/src/app/documentation/demos/dropdown/dropdown.demo.html
Screen reader (VoiceOver; possibly others too) is incorrectly announcing the total number of items in dropdown, as it counts every child element (including ones without the `role='menuitem'`). Also the dropdown headers are not read by screen reader.
Issue Number: #3551, #3552, #3553
Screen reader correctly only counts the items in dropdown. Docs are updated to show how to make the dropdown items announce the dropdown header.
> fix: dropdown item count by screen reader + docs update

- src/clr-angular/popover/dropdown/dropdown-item.spec.ts
- src/clr-angular/popover/dropdown/dropdown-item.ts
After introducing `disabled` as an input, missed connecting that to the disabled attribute in the dropdown item host element.
Note: I considered also automatically adding `disabled` class when the input is set. However, that breaks existing code in the case when the dropdown item is not a button (e.g. anchor tag). Since disabled attribute is not a valid attribute for things like anchor tag, it doesn't make sense to automatically handle the `disabled` css class. Just documenting for posterity. =)
Also note to self: Need to backport this to 1.1.x.
Issue Number: #3634
> fix(ng): dropdown item should add disabled attribute if set by input

- golden/clr-angular.d.ts
- src/clr-angular/data/datagrid/datagrid.html
- src/clr-angular/data/datagrid/datagrid.spec.ts
- src/clr-angular/data/datagrid/datagrid.ts
- src/clr-angular/utils/i18n/common-strings.interface.ts
- src/clr-angular/utils/i18n/common-strings.service.ts
- src/website/src/app/documentation/demos/i18n/i18n.demo.ts
Datagrid (first) row for expandable and single selection don't have a human-readable label.
I'm not sure that the labels are the best one - do we need to add some specific label like `Expandable` and `Single selection` or we could go with `Select` and `Expand` 
Backport it for `v1`
> [NG] adding labels to  Datagrid single & expandable column

- src/clr-angular/wizard/wizard.spec.ts
- src/clr-angular/wizard/wizard.ts
Prevent non closable wizards from closing with
the escape key.
closes #3499
When disabling a wizard from closing the user could still close by using the escape key.
When the wizard is not closable the wizard will not close after pressing the escape key.
> fix(wizard): prevent closing non closable wizards

- src/clr-angular/data/datagrid/datagrid-column-toggle.spec.ts
- src/clr-angular/data/datagrid/datagrid-column-toggle.ts
- src/clr-angular/data/datagrid/datagrid-row.html
- src/clr-angular/data/datagrid/datagrid.spec.ts
- src/dev/src/app/datagrid/expandable-rows/expandable-rows.html
non-expandable rows may fail to get rendered
May fail to render non-expandable rows in mixed content
Issue Number: #3617 
Renders non-expandable rows correctly
> fix(datagrid): mixed expandable non expandable bug

- src/clr-base/src/index.ts
- src/clr-base/src/lib/utils/css-vars/css-vars-ponyfill-fork.esm.js
- src/clr-base/src/lib/utils/css-vars/css-vars.spec.ts
- src/clr-base/src/lib/utils/css-vars/css-vars.ts
- src/clr-base/src/lib/utils/helpers/exists.spec.ts
- src/clr-base/src/lib/utils/helpers/exists.ts
• these are precursor changes to enable the css polyfill to run in IE11 and ODEdge
• more changes will be coming following on this one but largely focused on updates to the dev-app
• i broke these changes up so that changes to clr/base and the dev-app could be reviewed in isolation
• these changes largely remove over-optimization from the previous commit that was concerned with preventing the css-vars-ponyfill from running more than once
• a version of the ponyfill is now included in clr/base (hopefully temporarily) so that we can access the ponyfill's variableStore. ShadyCSS needs this so it can update web components in Lit Element.
Tested in:
✔︎ Chrome
✔︎ Firefox
✔︎ IE11
✔︎ Edge …
> fix: updates to clr/base to support ie11

- src/clr-angular/modal/modal-body.spec.ts
- src/clr-angular/modal/modal-body.ts
Only add focus style on modal content when tabbed to allow keyboard access. Example of desired behavior in vanilla JS https://stackblitz.com/edit/js-ich6zf 
When focusing the modal content using tab a keyboard user can use the arrows to scroll. This is causing focus styles to be applied on the modal body when inner elements are clicked.
Issue Number: closes #3642
Keyboard users can tab to modal body to navigate overflow content and get focus style. When a user focuses or clicks a inner element the focus style is no longer applied on the parent modal body.
> fix(modal): tab focus style

- src/clr-angular/forms/datepicker/model/day.model.spec.ts
- src/clr-angular/forms/datepicker/model/day.model.ts
- src/clr-angular/forms/datepicker/providers/date-navigation.service.ts
Remove unnecessary circular reference between day and calendar model. This removes the last of the circular ref warnings in the build.
There is a circular dependency between the day and calendar models. This is unnecessary and causes warnings in the build output.
Remove the circular dependency between day and calendar models.
> fix(datepicker): remove circular reference

- src/clr-angular/utils/_helpers.clarity.scss
- src/website/src/app/documentation/demos/datagrid/expandable-rows/expandable-rows.html
- src/website/src/app/documentation/demos/datagrid/expandable-rows/expandable-rows.ts
- src/website/src/app/documentation/demos/datagrid/filtering/examples.ts
- src/website/src/app/documentation/demos/datagrid/filtering/filtering.html
- src/website/src/app/documentation/demos/datagrid/utils/pokemon-comparator.ts
* Fix issue with sorting by Pokemon name column.
* User ID was not sortable but the 'hand' cursor was used when hovering the column. Remove 'hand' cursor when the column is not clickable.
* Filter for Date column is working as expected. 
The reason for showing columns that at first don't include the number `19` or any other number - is that the rows are created with `new Date()` 
```js
const row = new Date();
row.toString()
// => "Mon Jul 08 2018 19:40:56 GMT+0300 (Eastern European Summer Time)"
// We display 
"Jul 8 2018"
// When filtering 
row.toString().includes('19') 
// => true
```
So keep in mind what type of date have to be filtered and what is the exact value of the row.
Close #3505
> [WEB] Bug/3505

- golden/clr-angular.d.ts
- src/clr-angular/emphasis/alert/alert.html
- src/clr-angular/emphasis/alert/alert.spec.ts
- src/clr-angular/emphasis/alert/alert.ts
- src/clr-angular/utils/i18n/common-strings.default.ts
- src/clr-angular/utils/i18n/common-strings.interface.ts
- src/website/src/app/documentation/demos/alert/alerts.demo.html
- src/website/src/app/documentation/demos/i18n/i18n.demo.ts
- src/website/src/app/documentation/demos/wizard/wizard-async-completion.demo.html
- src/website/src/app/documentation/demos/wizard/wizard-async-completion.demo.ts
- src/website/src/app/documentation/demos/wizard/wizard-async-validation.demo.html
- src/website/src/app/documentation/demos/wizard/wizard-async-validation.demo.ts
- src/website/src/app/documentation/demos/wizard/wizard-design.demo.html
Add `aria-label` that the developer could overwrite if needed to provide additional information on the close button text.
Right now there is no way to change the alert close button text - also we use generic `Close` text that could be misleading.
Issue Number: #3489 
Close: #3498 
**NEED TO BE BACKPORTED TO V1**
> feat: add aria-label for alert close button

- src/dev/src/app/custom-props/custom-props.demo.ts
When you start out in the dev app on a non-custom-props module and then go to the custom-props demo, the polyfill doesn't run and the header that says it should never be red or black indeed shows up as black (warning sign!)
This change fixes that by forcing the polyfill to run on the component's init
Tested in:
✔︎ IE11
See above.
See above.
> fix: css vars pony fill needs to run on module init

- src/dev/src/app/stack-view/stack-view-angular-modal-edit.html
- src/website/src/app/documentation/demos/stack-view/stack-view-angular-modal-edit.html
- src/website/src/app/documentation/demos/stack-view/stack-view-angular-modal-edit.ts
• added clr-input classname so editable stack view form fields would look as expected
Tested in:
✔︎ Chrome
Dev app has unstyled form fields in stack view
Form fields in stack view are styled
> fix: editable stack view form fields looked unstyled in dev app

- golden/clr-angular.d.ts
- src/clr-angular/data/datagrid/datagrid.spec.ts
- src/clr-angular/data/datagrid/interfaces/state.interface.ts
- src/clr-angular/data/datagrid/providers/state.provider.ts
- src/website/src/app/documentation/demos/datagrid/server-driven/examples.ts
The `page` of a `ClrDatagridStateInterface` does not provide the current page of the `Page` from the `clrDgRefresh` event.  And with a paginated API that takes a page number as part of the parameters (ex. `some-paginated-api?page=1&size=10&sort=column,desc` ), this makes it unnecessarily difficult to consume the data using a server driven datagrid.
I found this related issue: https://github.com/vmware/clarity/issues/3100
Expose the current page in `page` of `ClrDatagridStateInterface` (from the `StateProvider`'s `Page`) as part of the `clrDgRefresh` event in order to get the current page for a paginated API request.
> feat(datagrid): Expose current page for clrDgRefresh

- golden/clr-angular.d.ts
- src/clr-angular/forms/datepicker/all.spec.ts
- src/clr-angular/forms/datepicker/date-container.spec.ts
- src/clr-angular/forms/datepicker/date-container.ts
- src/clr-angular/forms/datepicker/datepicker-view-manager.spec.ts
- src/clr-angular/forms/datepicker/datepicker-view-manager.ts
- src/clr-angular/forms/datepicker/day.spec.ts
- src/clr-angular/forms/datepicker/day.ts
- src/clr-angular/forms/datepicker/daypicker.html
- src/clr-angular/forms/datepicker/daypicker.spec.ts
- src/clr-angular/forms/datepicker/daypicker.ts
- src/clr-angular/forms/datepicker/model/day.model.spec.ts
- src/clr-angular/forms/datepicker/model/day.model.ts
- src/clr-angular/forms/datepicker/monthpicker.spec.ts
- src/clr-angular/forms/datepicker/yearpicker.spec.ts
- src/clr-angular/forms/datepicker/yearpicker.ts
- src/clr-angular/utils/i18n/common-strings.default.ts
- src/clr-angular/utils/i18n/common-strings.interface.ts
- src/dev/src/app/datepicker/datepicker.demo.module.ts
- src/website/src/app/documentation/demos/i18n/i18n.demo.html
- src/website/src/app/documentation/demos/i18n/i18n.demo.ts
- adds proper labels for all datepicker buttons
- adds live region for calendar view that updates month/year values for screen readers
- adds live region to year view that updates the decade range for screen readers
- closes #3467
Date picker needs the correct aria-labels on all of its buttons. It also needs two aria-live regions that will update screen readers in the daypicker view **and** the yearpicker view. 
Issue Number: #3467
All datepicker buttons have an aria-label related to what the button action does. There are two aria-live regions that change depending on user interactions with the datepicker.
> fix(datepicker): adds aria-labels for buttons

- golden/clr-angular.d.ts
- src/clr-angular/emphasis/alert/alert.html
- src/clr-angular/emphasis/alert/alert.spec.ts
- src/clr-angular/emphasis/alert/alert.ts
- src/dev/src/app/wizard/wizard-async-validation.demo.html
- src/website/src/app/documentation/demos/alert/alerts.demo.html
When a wizard has an alert in the page, it is read immediately and it is a simple status alert.
`clrAlert` has `role="alert" this automatically set the `aria-live="assertive"` so when trying to change it with `aria-live="polite"` it has no effect at all.
Issue Number: #3497
`role="alert"` was replaced with `aria-live` for more control on how the event has to be fired.
```html
// Wait your turn
<clr-alert ... clrPolite></clr-alert>
// Same as role="alert" 
<clr-alert ... clrAssertive></clr-alert>
// Don't do anything.
<clr-alert ... clrOff></clr-alert> 
```
Close: #3497
> fix: alerts in wizzard are read immediately when not urgent

- src/clr-angular/layout/nav/_links.clarity.scss
- src/clr-angular/layout/nav/_variables.nav.scss
- src/clr-angular/utils/_components.clarity.scss
notes:
• the link styles we were using for the dev app and website typography pages was getting duplicated each time the link variables were being imported
• i moved the styles to their own file and imported them where they were needed
• because these styles are only used for the dev app demos and typography demo on the website, i did not consider this a breaking change
• i have verified the styles are no longer duplicated
• i have tested the changes locally on the website and dev-app
• i have also tested the changes against gemini in both light and dark themes
Tested in:
✔︎ Chrome
Fixes|Closes: #3540
See above.
Issue Number: 3540
CSS …
> fix: preventing duplicate style declarations in CSS

- src/clr-angular/modal/modal.spec.ts
- src/clr-angular/modal/modal.ts
Removing unneeded todo for fixing already resolved Angular issue.
Issue Number: #3149 
The bug is originally reported for v1, but also apply to v2. 
So here is the branch with the fix for v1 - that must be applied as well.
https://github.com/bdryanovski/clarity/tree/bug/modal-3149
NOTE: this pull-request is cherry-picked from this branch.
> bug(modal): clrModalOpenChange was fired more than once when closing

- src/clr-angular/data/datagrid/_variables.datagrid.scss
Tested in:
✔︎ Chrome
* [!] Tests for the changes have been added (for bug fixes / features) <= this isn't something gemini is testing
The HSL changes inverted the color of the data grid spinner's background. This was a regression.
Issue Number: #3735 
It is fixed
> fix(datagrid): fix hsl regression

- src/clr-angular/popover/tooltip/_tooltips.clarity.scss
• this is a regression
• a deprecation in 2.0 was improperly applied and broke theming for the text inside a tooltip
Tested in:
✔︎ Chrome
See above.
Issue Number: #3740
> fix(tooltip): deprecation overwrote dark theme variable

- src/clr-angular/popover/dropdown/providers/dropdown-focus-handler.service.ts
- src/clr-angular/utils/focus/focus.service.spec.ts
- src/clr-angular/utils/focus/focus.service.ts
Fix issue with when there are no items into the dropdown the handle focus will throw an error when try to `moveTo` item. Right now the fix will just ignore this event and nothing will happen.
**Note**: We maybe need to handle this type of empty dropdowns with some message or animation that describe that this dropdown is empty and not stuck on the render stage.
This issue will close #3610 the last part with disabled that is not working. I had a talk with @jeeyun, we don't allow anymore to have disabled button into dropdowns based on the a11y spec. This is related to focusing on elements and so on.
The developer has to use `[clrDisabled]` if need to apply the `disabled="true"`
Issue …
> fix(dropdown): handle error when there are no items in dropdown to focus

- src/clr-angular/popover/dropdown/providers/dropdown-focus-handler.service.ts
- src/clr-angular/utils/focus/focus.service.spec.ts
- src/clr-angular/utils/focus/focus.service.ts
This is only backporting to this bugfix https://github.com/vmware/clarity/pull/3706 to master
Issue Number: #3610
> backport fix(dropdown): handle focus first item when there is non selectable item

- src/website/src/app/documentation/demos/forms/forms.demo.html
- src/website/src/app/documentation/demos/forms/ng/optional.html
This is needed as screen reader users will explore the form before filling it out. If there are validation messages this can be confusing as they are trying to just understand the form content.
Issue Number: #3557
Update docs to explain screen reader support for validation message behavior. Screen reader users need message describing how validation messages are triggered. This is needed as screen reader users will explore the form before filling it out.
Unfortunately Angular does not have an easy way to check if there are any validators applied to a given form so this will need to be managed on the application side. https://github.com/angular/angular/issues/13461
> docs(form): screen reader warning

- golden/clr-angular.d.ts
- src/clr-angular/forms/datepicker/calendar.html
- src/clr-angular/forms/datepicker/calendar.spec.ts
- src/clr-angular/forms/datepicker/calendar.ts
- src/clr-angular/forms/datepicker/datepicker-view-manager.ts
- src/clr-angular/forms/datepicker/daypicker.html
- src/clr-angular/forms/datepicker/daypicker.spec.ts
- src/clr-angular/forms/datepicker/interfaces/day-of-week.interface.ts
- src/clr-angular/forms/datepicker/providers/locale-helper.service.ts
closes #3466
No indication of beginning and end of modal when using screen reader.
Weekdays headings (SMTWTFS) are only read as a letter.
Issue Number: #3466
Begin/End bumpers added, only visible to screen readers.
Weekdays are read with their full names.
> fix(a11y): add bumpers to the datepicker

- src/clr-angular/layout/nav/_header.clarity.scss
The right icon in `clr-header` component is misaligned in IE11.
Issue Number: #3519 
The icon and the text are now aligned, like in any other browser that I tested on (Chrome, Mozilla, Edge).
The `initial` keyword is not supported in IE11.
> fix(header): clarity icons with text misaligned in ie11

- src/website/src/app/documentation/component-status/component-status.component.html
- src/website/src/app/documentation/demos/_doc-wrapper/doc-wrapper.html
- src/website/src/app/documentation/get-started/get-started.component.html
After activating any of the component demo router links in the first column on the left, the focus remains on the given router link. Screen reader users will not know what happened as a result of clicking the router link and will not know how to find the newly added content that appeared as a result of activating the router link.
Issue Number: #3173 
Once clicked on the component demo link in the first column, the focus will be set to the h1 of the each corresponding demo page.
> fix: website routing focus management

- src/website/src/app/documentation/demos/grid/grid.demo.html
- src/website/src/app/documentation/demos/toggles/toggles.demo.html
1. remove text supporting use of CSS order property, close #3412
2. fixed toggle docs language to reflect the need for visual labelling
Signed-off-by: Chris Lane <chlane@vmware.com>
Documentation is incorrect regarding CSS order property usage and visual labelling for toggle buttons
Issue Number: #3412
NA
> docs: updating documentation language

- CODING_GUIDELINES.md
- CONTRIBUTING.md
- DESIGN_CONTRIBUTION.md
I used the Code Spell Checked VSCode extension
* https://github.com/streetsidesoftware/vscode-spell-checker
> docs: fix typos in markdown documents

- src/dev/src/app/datepicker/css-regression.ts
- src/dev/src/app/datepicker/datepicker-AK.ts
- src/dev/src/app/datepicker/datepicker-AR.ts
- src/dev/src/app/datepicker/datepicker-DE.ts
- src/dev/src/app/datepicker/datepicker-HI.ts
- src/dev/src/app/datepicker/datepicker-KKJ.ts
- src/dev/src/app/datepicker/datepicker-date-input-explicit-wrapper.ts
- src/dev/src/app/datepicker/datepicker-date-input.ts
- src/dev/src/app/datepicker/datepicker-hr.ts
- src/dev/src/app/datepicker/datepicker-in-reactive-forms.ts
- src/dev/src/app/datepicker/datepicker-in-template-driven-forms.ts
- src/dev/src/app/datepicker/datepicker-locale-data.ts
- src/dev/src/app/datepicker/datepicker.demo.ts
- src/dev/src/app/datepicker/ngmodel-auto-wrapped.ts
- src/dev/src/app/datepicker/ngmodel-wrapper-explicit-wrapper.ts
Comments in some files under `src/app/datepicker`:
```
// Note the .css extension here, not .scss. That's the best we can have at the moment.
```
could be removed as the files in question have `.scss` extension now.
Outdated comments are removed.
> doc(datepicker): Remove outdated comments

- scripts/docker-cdc.js
The docker kill command was logging output to the command line when trying to kill an instance of clarity_chrome that wasn't already running.
Initially I think I put this there to prevent issues restarting but its changed over time. Because we are moving away from gemin I'm supressing the output of the kill command so its not logged rather than re-working the script logic.
Prevent output from the script that manages docker when running the visual tests.
> build: supress output from visual test script

- src/website/src/app/documentation/demos/alert/alerts.demo.html
#3549
There are examples featuring actions inside alerts.
Issue Number: #3549 
An Accessibility section was added, that
- Warns against using actions inside alerts.
- Explains why it is not recommended.
- Gives recommendations about using actions in static alerts.
> docs(alert): a11y warning against use of actions inside dynamic alerts

- src/clr-angular/modal/modal-body.spec.ts
- src/clr-angular/modal/modal-body.ts
Modal body starts with default `tabindex = 0` binding. But the binding gets removed once `mousedown` event gets registered so that when a user tries to click on or to select something in it, we won't set the focus on it. But once user release mouse click with `mouseup`, we would set the default `tabindex` binding back so it will continue to be keyboard focusable
Issue Number: https://github.com/vmware/clarity/issues/3754
> fix: selecting content in modal body

- src/website/src/app/documentation/demos/timeline/timeline.demo.html
- src/website/src/styles/components.scss
closes #3802
Signed-off-by: Florin Borceanu <florin.borceanu@bytex.ro>
The heading of the Input groups section overlaps previous Do/Don't section.
Issue Number: #3802 
Everything is ok.
The `height: 100%` set to `clrweb-DoxMedia-img` class was added for the Timeline component documentation, where one of the images was misaligned. I reverted that change and I added to the specific image a inline style.
> fix: on website input grouping heading overlaps example

- golden/clr-angular.d.ts
- src/clr-angular/data/stack-view/stack-block.spec.ts
- src/clr-angular/data/stack-view/stack-block.ts
Can't jump from header to controlled content. This is a IE/JAWS only issue, and JAWS only supports this functionality. No other screen reader does!
Issue Number: #3564 
JAWSKey + Alt + M jumps to controlled content.
> fix(stack-view): a11y add aria-controls to stack-view

- src/clr-angular/data/datagrid/all.spec.ts
- src/clr-angular/data/datagrid/built-in/filters/datagrid-numeric-filter-impl.spec.ts
- src/clr-angular/data/datagrid/built-in/filters/datagrid-numeric-filter-impl.ts
- src/clr-angular/data/datagrid/built-in/filters/datagrid-numeric-filter.spec.ts
- src/clr-angular/data/datagrid/datagrid-column.spec.ts
- src/clr-angular/data/datagrid/datagrid-column.ts
Numeric filter was not working when you only use binding input
Changing the order of `@Input` fix the issue with `colType` beeing undefined at the time when `numeric` filter is selected.
Issue Number: #3483
Close: #3483
> fix(datagrid): numeric filters are not working 

- src/clr-angular/data/datagrid/providers/filters.spec.ts
- src/clr-angular/data/datagrid/providers/filters.ts
* [n] Tests for the changes have been added (for bug fixes / features)
* [n/a] Docs have been added / updated (for bug fixes / features)
* [n/a] If applicable, have a visual design approval
Before the fix, custom filter doesn't  work for the 2nd column. 
Issue Number: 3486
https://github.com/vmware/clarity/issues/3486
After the fix, custom filter will work for all columns including the 2nd column. 
Signed-off-by: Kathy Laird <kathy.laird@emc.com>
> fix: datagrid custom filter for 2nd column doesn't work

- src/website/src/app/home/home.component.scss
Adds missing `padding-right` to the responsive footer of the clarity.design website.
In the responsive view of the footer on the website, the footer has `padding-left` but interestingly omits the corresponding `padding-right`. This has missing symmetry of padding. See image below.
Add symmetrical `padding-right` of the same value as the `padding-left` to the responsive footer of the website.
> fix(website): add padding-right to responsive footer

- src/clr-angular/typography/_code.clarity.scss
- src/website/src/app/utils/code-snippet.ts
BREAKING CHANGE: this changes the default height for a `pre` element, but can be easily overridden on app level
The `pre` element has a max height (which we override in our docs by the way)
closes #1138
The `pre` element is free to grow up and be full size.
> fix: remove max-height from `pre`

- .circleci/config.yml
- .travis.yml
Travis builds have been slower and with the changes to Core tests are going around 25 minutes. I've moved just the `build:ci` piece to CircleCI in this (which we can trial here) as part of our process, which in my test runs has been going under around 12-13 minutes. This will also free up a job in Travis, so we can run gemini and applitools tests at once, reducing overall build time.
It would be easy to disable and go back to Travis if we have issues. I also attempted to setup gemini testing on Circle, and found that using docker containers is problematic because it doesn't allow networking. I'm sure there is a way, but I didn't dig into it yet and our plan is to …
> build: use circleci for unit tests

- src/website/src/app/app.component.html
- src/website/src/app/app.component.ts
- src/website/src/app/home/home.component.html
This fixes the website urls for documentation links to align with a prerelease. Also for build previews/localhost it won't redirect to v2, only on clarity.design.
> chore: fix website version urls

- golden/clr-angular.d.ts
- src/clr-angular/data/datagrid/datagrid-row.html
- src/clr-angular/data/datagrid/datagrid-row.spec.ts
- src/clr-angular/data/datagrid/datagrid-row.ts
- src/clr-angular/data/datagrid/datagrid.ts
- src/clr-angular/data/datagrid/providers/selection.spec.ts
- src/clr-angular/data/datagrid/providers/selection.ts
- src/dev/src/app/datagrid/conditional-selection/conditional-selection.html
- src/dev/src/app/datagrid/conditional-selection/conditional-selection.ts
- src/dev/src/app/datagrid/datagrid.demo.html
- src/dev/src/app/datagrid/datagrid.demo.module.ts
- src/dev/src/app/datagrid/datagrid.demo.routing.ts
- src/dev/src/app/datagrid/selection-row-mode/selection-row-mode.html
- src/website/src/app/documentation/demos/datagrid/selection/selection.html
- src/website/src/app/documentation/demos/datagrid/selection/selection.ts
- src/website/src/app/documentation/demos/datagrid/single-selection/single-selection.html
- src/website/src/app/documentation/demos/datagrid/single-selection/single-selection.ts
Right now there is no way to disable a row from Datagrid and prevent interaction with the row.
Issue Number: #1018 
Added new input to `ClrDatagridRow` called `cldDgUnselectable` that except `boolean`. When set to true it will prevent the click event from firing and won't let the user change the state of the row. Also will mark the checkbox or radio button as disabled and change the cursor to mark the row as locked.
This is valid for both Single and Multi selectable rows. 
* Normal
* Disabled and can't be changed
* Disabled and marked as selected, also can't be changed
* Disabled and marked as selected
* Disabled and can't be changed
* Normal
Close: #1018 
Todo: need to be backported …
> feat(datagrid): disable single or multi rows from selection

- golden/clr-angular.d.ts
- src/clr-angular/data/datagrid/datagrid.ts
- src/clr-angular/data/datagrid/providers/selection.spec.ts
- src/clr-angular/data/datagrid/providers/selection.ts
- src/dev/src/app/datagrid/preserve-selection/preserve-selection.html
- src/dev/src/app/datagrid/preserve-selection/preserve-selection.ts
- src/website/src/app/documentation/demos/datagrid/selection/selection.html
Adds a clrDgPreserveSelection input to the datagrid which will not clear the selection when a filter is applied.
Issue Number: #2342 
A `clrDgPreserveSelection` input has been added to the datagrid which is disabled by default. When enabled, the selection is not cleared when a filter is applied. 
Signed-off-by: Kevin Buffington <kbuffington@gmail.com>
> feat(datagrid): preserve selection while filtering

- src/clr-angular/data/datagrid/_datagrid.clarity.scss
Currently, the height of the column title changes when column is sorted and column title & sort icon aren't aligned. That results in strange behavior (adding scrollbar) to the whole datagrid.
Unsorted:
Sorted (current state):
Sorted (with fix from PR):
Behavior can also be seen in comparison of the docs samples - by sorting of the e.g. name column datagrid's full demo:
https://deploy-preview-3866--vmware-clarity.netlify.com/documentation/datagrid/full
https://clarity.design/documentation/datagrid/full
> fix(datagrid): align column header vertically

- src/clr-angular/layout/tabs/_tabs.clarity.scss
Issue Number: #3748 
Tested on:
Internet Explorer 11 ✔
Edge ✔
Google Chrome ✔
Mozilla ✔
Safari ✔
> fix(tabs): extra spacing between tab and tab content in ie 11

- src/website/src/styles/code.scss
Unnecessary "Header" text fills up the title bar in mobile view.
Issue Number: #3853 
Fixes positioning of header tags in the examples.
> fix: removes unnecessary text from the mobile header title

- src/clr-angular/accordion/_accordion.clarity.scss
- src/clr-angular/button/button-group/_button-group.clarity.scss
- src/clr-angular/data/datagrid/_datagrid.clarity.scss
- src/clr-angular/data/stack-view/_stack-view.clarity.scss
- src/clr-angular/data/tree-view/_tree-view.clarity.scss
- src/clr-angular/emphasis/alert/_alert.clarity.scss
- src/clr-angular/forms/combobox/_combobox.clarity.scss
- src/clr-angular/forms/datepicker/_datepicker.clarity.scss
- src/clr-angular/forms/styles/_containers.clarity.scss
- src/clr-angular/forms/styles/_file.clarity.scss
- src/clr-angular/forms/styles/_mixins.forms.scss
- src/clr-angular/forms/styles/_select.clarity.scss
- src/clr-angular/forms/styles/_toggles.clarity.scss
- src/clr-angular/image/_images.clarity.scss
- src/clr-angular/layout/_card.clarity.scss
- src/clr-angular/layout/_login.clarity.scss
- src/clr-angular/layout/nav/_header.clarity.scss
- src/clr-angular/layout/nav/_responsive-nav.clarity.scss
- src/clr-angular/layout/nav/_sidenav.clarity.scss
- src/clr-angular/layout/vertical-nav/_vertical-nav.clarity.scss
- src/clr-angular/modal/_modal.clarity.scss
- src/clr-angular/popover/dropdown/_dropdown.clarity.scss
- src/clr-angular/popover/signpost/_signposts.clarity.scss
- src/clr-angular/progress/progress-bars/_progress-bars.clarity.scss
- src/clr-angular/progress/spinner/_spinner.clarity.scss
- src/clr-angular/timeline/_timeline.clarity.scss
- src/clr-angular/utils/_mixins.clarity.scss
- src/clr-angular/wizard/_wizard.clarity.scss
• added equilateral sass mixin
• it takes a size and then sets height and width to that size
• added size-zero sass mixin which just sets height and width to 0
• added forcemin-equilateral sass mixin which also sets min-height/width to size
• added forcemax-equilateral sass mixin which also sets max-height/width to size
Tested in:
✔︎ Chrome
Lots of copy-paste height/width styles. This is something that i found really annoying during all the remSizing changes.
We have an equilateral mixin that saves us some code.
> feat: adding equilateral sass mixins

- cypress/integration/select.js
- cypress/integration/spec.js
- src/clr-angular/utils/_theme.dark.clarity.scss
Adds back a scss var for select option elements. Issue with dark theme on windows chrome.
All browser combos were checked.
NOTE: This PR also adds in the select input visual regression tests
chrome on windows with select inputs had the wrong font color for option text color. 
option text color on chrome+windows has a black font color.
> fix(select): add select option font color

- src/website/src/app/documentation/demos/nav/nav.demo.module.ts
Website navigation documentation was missing module so the syntax highlighting was not working.
Also adding `website` as a valid scope for commit linting.
> fix: website is missing code-highlight utils module for navigation page

- package.json
This change allows smaller icon bundles because we aren't zipping and including all of the raw sets. People should download these from our assets directory instead.
Its unnecessary weight to ship these zipped files (plus they are duplicated in the all-shapes zip and individual shape sets). 
> chore: remove shape zips from NPM package

- .circleci/config.yml
- .travis.yml
- scripts/circleci/visual.sh
This moves the build job for applitools from Travis to Circle. This should be faster to execute, as well as helping us align our build tooling to one place long term.
> chore: use circle ci for applitools

- golden/clr-angular.d.ts
- src/clr-angular/utils/drag-and-drop/droppable/droppable.ts
- src/dev/src/app/datagrid/compact/compact.html
- src/dev/src/app/datagrid/hide-show-columns/hide-show.html
- src/dev/src/app/datagrid/kitchen-sink/kitchen-sink.ts
- src/dev/src/app/datagrid/responsive-footer/responsive-footer.html
- src/dev/tsconfig.dev.json
- tsconfig.json
Fix templates for private/unused variables.
- This enables to set `"fullTemplateTypeCheck": true` in `angularCompilerOptions` (current Angular CLI sets this).
- Enable `fullTemplateTypeCheck` in dev application
Angular prod build fails when `"fullTemplateTypeCheck": true` is set in `angularCompilerOptions` in `tsconfig.json`.
Issue Number: #3932
Angular build works :-)
None
> fix: templates for private/unused variables

- src/website/src/app/documentation/get-started/get-started.component.html
No description of the browser+ScreenReader that is supported by Clarity.
description of the browser+ScreenReader that is supported by Clarity to the get started page (in v3 docs only)
> docs: add text for screen reader support to get started page

- .travis.yml
- cypress/integration/spec.js
- src/clr-angular/data/datagrid/_datagrid.clarity.scss
- src/clr-angular/data/datagrid/datagrid-row-detail.spec.ts
- src/clr-angular/data/datagrid/datagrid-row-detail.ts
- src/clr-angular/data/datagrid/datagrid-row.html
- src/clr-angular/data/datagrid/datagrid-row.spec.ts
- src/clr-angular/data/datagrid/datagrid.html
- src/clr-angular/utils/_layers.clarity.scss
- src/dev/src/app/datagrid/inventory/inventory.ts
- src/dev/src/app/datagrid/kitchen-sink/kitchen-sink-data.ts
- src/dev/src/app/datagrid/pagination/pagination.html
This moves the datagrid row controls into the stick container and prepares for pinned columns (frontside). Styles were adjusted to handle the column separaters and flex the sticky and scrollable elements in the header as a row instead of a column.
RELATED CHANGES:
The pokemon generator was modified to produce consistent items from the three arrays that are used to generate data so that visual regression tests could be turned on and utilized for visual regression testing of the datagrid use cases. This commit will generate reference images for the baseline.
Datagrid row control buttons scroll on the x-axis when there is overflow. 
Issue …
> refactor(datagrid): move row controls into sticky container

- src/clr-angular/forms/datepicker/date-input.spec.ts
- src/clr-angular/forms/datepicker/date-input.ts
Signed-off-by: Martin Brom <martinbrom97@gmail.com>
Issue Number: #3224 
Datepicker now displays the correct day when selecting it on mobile devices in timezones greater than GMT+0.
Unit test without the fix only fails in time zones greater than GMT+0. To have the test without the fix failing for all time zones, it would be necessary to somehow mock the test browser time zone.
> fix(datepicker): prevent date input from displaying -1 day for specific timezones

- src/clr-angular/forms/datepicker/date-input.spec.ts
- src/clr-angular/forms/datepicker/date-input.ts
Signed-off-by: Martin Brom <martinbrom97@gmail.com>
Issue Number: #3961 
Date can now be selected without being deleted when using a mobile device and an input with a control element.
EDIT: Now contains a unit test. Should I also add the test for template driven?
I have tested this bug fix manually, but am having issues writing a unit test to reflect this faulty behavior.
> fix(datepicker): prevent date from being deleted when selected on mobile

- src/clr-angular/data/datagrid/datagrid-filter.spec.ts
- src/clr-angular/data/datagrid/datagrid-filter.ts
- src/dev/src/app/datagrid/filtering/filtering.html
- src/dev/src/app/datagrid/filtering/filtering.ts
`clrDgFilterOpenChange` was not called when `open` is toggle between `true|false`
Issue Number: #3804 
This change has to be added to `v2` branch as well. The original bug is from there.
Close #3804
> fix: datagrid clrDgFilterOpenChange was not fired

- src/clr-angular/data/datagrid/_datagrid.clarity.scss
The select-all checkbox's checkmark position was off in v3.0.
> fix: select-all checkmark position

- docs/core/cwc-button.md
- src/clr-core/button/button.element.scss
- src/clr-core/button/button.element.spec.ts
- src/clr-core/button/button.element.ts
- src/clr-core/common/base/button.base.ts
- src/dev-core/src/app/button/button.demo.html
- adding readonly attr for non-clickable elements
- changing state attr to status to align across component library
- clean up style to make text inside button not selectable
> feat(button): improvements to base button

- package.json
- src/clr-core/common/utils/__.ts
- src/clr-core/common/utils/exists.ts
- src/clr-core/common/utils/identity.ts
- src/clr-core/common/utils/register.ts
- src/clr-core/icon/utils/icon.classnames.ts
- src/clr-core/icon/utils/icon.has-shape.ts
- src/clr-core/icon/utils/icon.service-helpers.ts
- src/clr-core/tslint.json
- src/clr-icons/clr-icons.spec.ts
- Ramda was not properly treeshaking in certain tooling setups
- When running `core:build` standalone the ngpackagr would wipe out the global css files.
- When using Ramda we use direct path imports to ensure treeshaking as well as a TSLint enforcment
- `core:build` now preserves the global css output when ran standalone.
> core: treeshaking performance

- docs/core/cwc-badge.md
- docs/core/cwc-tag.md
- src/clr-angular/emphasis/_properties.label.scss
- src/clr-core/badge/_properties.scss
- src/clr-core/badge/badge.element.scss
- src/clr-core/badge/badge.element.ts
- src/clr-core/button/_properties.scss
- src/clr-core/tag/_properties.scss
- src/clr-core/tag/tag.element.scss
- src/clr-core/tag/tag.element.ts
- src/dev-core/src/app/badge/badge.demo.html
- src/dev-core/src/app/badge/badge.demo.scss
- src/dev-core/src/app/badge/badge.demo.ts
- src/dev-core/src/app/tag/tag.demo.html
Instead of using specific variable names like 
Instead of using specialized css variables like `--clr-badge-gray-bg-color`, opt to reuse the generic variable name `--clr-badge-bg-color`. This allows an override for the variation like:
```
:host([attr='value']) {
--clr-badge-bg-color: <custom background color>;
--clr-badge-color: <custom color>;
}
```
> core: fix badge and tag to re-use same custom properties for its variations

- src/website/src/app/documentation/demos/i18n/i18n.demo.ts
Adds signpostToggle and a description to the i18n docs page
closes #4095
Adds `signpostToggle` to common strings. 
signpostToggle common string was minning
Issue Number: #4095
Docs are updated.
> docs(signpost): updates i18n strings in documentation

- src/website/src/app/documentation/get-started/get-started.component.ts
PR Checklist
Corrects the node imports section when following the manual library installation steps on the Getting Started page to match what is is done when performing the installation with the Angular CLI.
The wrong paths are listed for the node module imports section.
Issue Number: #4047
> docs: Fix node imports for manual library installation on Getting Started page

- src/clr-angular/data/datagrid/datagrid-detail.ts
- src/clr-angular/utils/focus-trap/focus-trap.directive.spec.ts
- src/clr-angular/utils/focus-trap/focus-trap.directive.ts
The focus trap is too greedy for the detail pane use case, where we only want to trap focus for keyboard users. This adds a new local option that puts the rebound elements before and after the host and focus traps only when tabbing through the content. If you use a mouse to move focus outside of the Datagrid, it will disable the focus trap entirely.
fixes #3999
Issue Number: fixes #3999
The focus trap now has an optional 'local' mode where it only traps focus while the focus is cycling internally, but once focus is moved outside of the focus trap it disabled the trap.
> fix(datagrid): focus trap no longer steals focus when going outside

- golden/clr-angular.d.ts
- src/clr-angular/forms/datepicker/date-container.spec.ts
- src/clr-angular/forms/datepicker/date-container.ts
Prevent from calling focus on date picker when the calendar is not open (depend on ifOpenService)
Issue Number: #4060 
track ifOpenService state and prevent requesting for focus.
Close #4060
> fix(date-picker): prevent calling for focus, when date-picker is closed

- docs/core/cwc-icon.md
- src/clr-core/icon/icon.element.scss
- src/clr-core/icon/icon.element.ts
- src/dev-core/src/app/icon/icon.demo.html
• got rid of "error" colors
• deprecated CSS classnames that use "error"
• fixed issues with inverse colors not being applied
• fixed issue where 'danger' colors were coming from 'error' variables
• added demo of custom styling icons with CSS to verify changes
> fix(icons): css class collisions in icon error-danger classes

- src/clr-angular/data/datagrid/datagrid-row.html
- src/clr-angular/data/datagrid/datagrid-row.spec.ts
- src/clr-angular/data/datagrid/datagrid-row.ts
* `clrDgDetailCloseLabel` was returning the wrong label for the close button.
* `.datagrid-expandable-caret-button` Element was using the wrong service to track open/closed state and missing `aria-expanded` attribute
Issue Number: #4089
Close #4089
> fix(datagrid): datagrid-row add aria-expanded & aria-label on open/close

- docs/CODING_GUIDELINES_CORE.md
- src/clr-core/badge/badge.element.ts
- src/clr-core/button/button.element.ts
- src/clr-core/common/base/button.base.ts
- src/clr-core/common/decorators/property.spec.ts
- src/clr-core/common/decorators/property.ts
- src/clr-core/common/index.ts
- src/clr-core/icon-shapes/icon.element.ts
- src/clr-core/tag/tag.element.ts
- src/clr-core/test-dropdown/test-dropdown.element.ts
- src/clr-core/tslint.json
- Adds custom attr parser support for booleans and dates when using `@property`
- New `@property` decorator from `@clr/core/common` is same as lit-html but provides consistent defaults for all components.
> fix: add core property decorator with defaults

- package-lock.json
- package.json
Right now `npm run core:api` is run on every commit without the need of that
`npm run core:api` is required to run only when there are changed `ts|js` files inside the `src/clr-core` folder.
`lint-staged` will check staged files into pre-commit hook for files that have path matching `src/clr-core/**/*.{ts,js}` and will run the `npm run core:api` else no update on the documentation for core project will be done.
This is cutting on average 3-4s on committing at the moment (at least for me)
NOTE: This change will require `npm ci` or `npm install` to development env, new npm package is added.
> chore(build): run api documentation only when there is a change

- src/website/src/app/documentation/demos/datepicker/demos/datepicker-api.demo.html
- src/website/src/app/documentation/demos/datepicker/demos/datepicker-api.demo.ts
- src/website/src/app/documentation/demos/datepicker/demos/datepicker-date-io.demo.html
- src/website/src/app/documentation/demos/datepicker/demos/datepicker-date-io.demo.ts
- src/website/src/app/documentation/demos/datepicker/demos/datepicker-enUS.demo.ts
- src/website/src/app/documentation/demos/datepicker/demos/datepicker-fr.demo.ts
- src/website/src/app/documentation/demos/datepicker/demos/datepicker-reactive-forms.html
- src/website/src/app/documentation/demos/datepicker/demos/datepicker-reactive-forms.ts
This adds labels to the demos to demonstrate proper use of clr-date-containers and labels for accessible forms.
closes #3465
Current datepicker demos and example code show using `clrDate` without a label. 
This change adds clr-date-container and labels to the datepicker demos.
> docs(date-picker): add labels to website demos

- src/clr-angular/forms/datepicker/model/calendar-view.model.spec.ts
- src/clr-angular/forms/datepicker/model/calendar-view.model.ts
- src/clr-angular/forms/datepicker/model/day.model.spec.ts
- src/clr-angular/forms/datepicker/model/day.model.ts
- src/dev/src/app/datepicker/datepicker-min-max.html
- src/dev/src/app/datepicker/datepicker-min-max.ts
The day models were being converted to Date objects and then compared, which caused some potential issues with timezones in comparisons. This converts the comparisons to YYYYMMDD strings instead to do comparisons, which avoids timezones.
The dates are compared as date objects, which can cause some timezone drift and enable/disbable dates on the edges incorrectly.
closes #4144
The dates are converted to YYYYMMDD strings and compared to remove date drift.
> fix(date-picker): correctly compare min/max date limits

- docs/core/cwc-icon.md
- src/clr-core/icon-shapes/icon.element.spec.ts
- src/clr-core/icon-shapes/icon.element.ts
- src/clr-core/icon-shapes/utils/icon.svg-helpers.ts
- src/dev-core/src/app/icon-sets/icon-sets.demo.html
- src/dev-core/src/app/icon-sets/icon-sets.demo.ts
- Renders demo page (416 icons) around ~630-750ms compared to 1.1s - 1.2s on docs icon demo page built in prod mode on 2018 macbook pro.
- Remove use of getters and replace with form value changes observable. This prevents recalculation for each icon during each change detection cycle.
- Load icons immediately and create index object inline to prevent multiple renders/change detection cycles when angular component is created.
- Use CSS to show and hide icons to prevent large amount of components being created/destroyed when filtering/searching
- Remove table layout to reduce number of DOM nodes improving render times
- Single cwc-icon uses ~0.64ms of JS execution time vs current …
> fix: core icon performance and a11y

- .circleci/config.yml
- angular.json
- netlify.toml
- package-lock.json
- package.json
- scripts/dev.sh
- scripts/website.sh
Netlify has started to limit the number of build minutes available to us. This moves the build of the website to CircleCI and deploys it in essentially the same way, but saves us from using build minutes on Netlify. It actually builds and deploys the dev and website apps as separate deployments.
The main drawback here is that we lose the GitHub integration that posts comments and URLs into the PR, but we could do that manually if we setup a script.
> chore(build): move website build to circle not netlify

- src/clr-angular/forms/datepicker/date-container.ts
- src/clr-angular/popover/signpost/signpost-content.ts
There are two ClrCommonStringsService instances, but you could overwrite only one, so there is two active translation that leads to different localization strings across the app. 
Close #4018
Target is V2 branch, also need to be merged into master/v3/v1
> fix(a11y): service ClrCommonStringsService initialize twice at run-time

- golden/clr-angular.d.ts
- src/clr-angular/forms/datepicker/date-container.spec.ts
- src/clr-angular/forms/datepicker/date-container.ts
- src/clr-angular/forms/datepicker/date-input.ts
- src/clr-angular/forms/datepicker/providers/date-form-control.service.ts
- src/dev/src/app/datepicker/disabled.html
- src/dev/src/app/datepicker/disabled.ts
Handle when the `date-picker` container is not inside `clrForm` wrapper.
Issue Number: #4016 
Close: #4016 
Target branch is v3 - must be merged into master/v2/v1(not sure for v1)
> fix(date-picker): set disabled state without the need of clrForm

- commitlint.config.js
I'm getting super often this error:
```
✖   header must not be longer than 72 characters, current length is 74 [header-max-length]
```
Visible in the case when I use one of the long `scopes` like `date-picker`, `progress-bar` and so on.
So in the case of: 
```
feat(date-picker):<space><commit-message>
```
I'm losing 19 characters from the commit message just for tagging. And including one input or output name, there are no characters left to do a meaningful sentence. And the messages become a bit cryptic just to get inside the limitation. 
I don't suggest to go and try to fill the how 100 character limit, but having some additional characters could be handy.
Also, there is similar open PR for this change inside the [commitlint](https://github.com/conventional-changelog/commitlint/issues/30 …
> feat: update the limit of header-max-length from 72 to 100 characters

- docs/core/cwc-badge.md
- docs/core/cwc-button.md
- docs/core/cwc-tag.md
- src/clr-core/badge/badge.element.ts
- src/clr-core/button/button.element.ts
- src/clr-core/common/index.ts
- src/clr-core/common/interfaces/index.ts
- src/clr-core/tag/tag.element.ts
• added union type for default sizes (default|sm) that we see
in buttons and alerts
• added union types for t-shirt sizes used in modals
• added union types for statuses found in alerts, badges,
tags, and buttons
> feat(build): typescript cleanup

- golden/clr-angular.d.ts
- src/clr-angular/data/datagrid/datagrid-filter.spec.ts
- src/clr-angular/data/datagrid/datagrid-filter.ts
- src/clr-core/common/services/common-strings.default.ts
- src/clr-core/common/services/common-strings.interface.ts
In the conversion to the new popover utility a11y attributes were missed. This adds: aria-label, aria-expanded and aria-controls
to the datagrid filter button. This change closes #3985.
Datagrid filter buttons were missing aria-label, aria-controls and aria-expanded attributes on the toggle button. 
Issue Number: #3985
Datagrid filter buttons have aria-label, aria-controls and aria-expanded attributes on the toggle button.
> fix(datagrid): adds a11y attributes to datagrid filter button

- src/website/src/app/documentation/demos/vertical-nav/basic-nav/basic-nav.html
The `H2` element had a typo in Jigglypuff (as Jiggypuff). This corrects it to Jigglypuff.
Closes: #4216
Signed-off-by: Bruce McMoran <mcmoranbjr@gmail.com>
* [na] Tests for the changes have been added (for bug fixes / features)
* [na] If applicable, have a visual design approval
The `H2` element contains Jiggypuff as a typo of the character name Jigglypuff in the vertical nav example. See https://v2.clarity.design/vertical-nav/basic-structure/project-pokemon
Issue Number: #4216 
Display Jigglypuff in the `H2` element for the vertical nav example https://v2.clarity.design/vertical-nav/basic-structure/project-pokemon
* [x ] No
> docs(vertical-nav): Consistent Jigglypuff story character

- golden/clr-angular.d.ts
- src/clr-angular/button/button-group/button-group.ts
- src/clr-angular/forms/datepicker/date-input.spec.ts
- src/clr-angular/forms/datepicker/date-input.ts
There was a missing check for the optional service before using it. In the test adding a `disabled` attribute to confirm that it doesn't throw an error.
fixes: #4208
Also fixes linting issues.
> fix(date-picker): guard calling an optional date picker service

- golden/clr-angular.d.ts
- src/clr-angular/data/datagrid/datagrid-action-overflow.spec.ts
- src/clr-angular/data/datagrid/datagrid-action-overflow.ts
This change adds details around adding the clrPopoverCloseButton to items projected into the action overflow menu that also need to be able to close the menu. It also explains that the default behavior is to ignore clicks on projected content.
closes #3796
Adds details for datagrid action overflow menu related to the popover changes to fix clipping issues.
Consumers don't know that by default content projected into the menu will ignore user clicks. 
Issue Number: #3796
There is an explanation and demo showing both. The Edit button ignores user clicks but the Delete button will close the menu after user clicks it.
> fix(datagrid): update single action close behavior

- docs/core/cwc-icon.md
- src/clr-core/icon-shapes/icon.element.scss
- src/clr-core/icon-shapes/icon.element.spec.ts
- src/clr-core/icon-shapes/icon.element.ts
- src/dev-core/src/app/icon-deprecated/icon.demo.html
- src/dev-core/src/app/icon/icon.demo.html
• merged badge, alert, and badgeType properties into badge
• replaced alert terminology with a `warning-triangle` status
• this eliminates impossible states introduced by former API
• removed pitched (but not supported by code) inverse state of badges
• replaced inverse badges with `inherit` status
• `inherit` status makes badge same color as rest of icon
• added `inherit-triangle` for a similar feature with alerted icons
Issue Number: #4235
> feat(icons): update to clr-core icons API

- angular.json
- golden/clr-angular.d.ts
- package-lock.json
- package.json
- src/clr-angular/forms/checkbox/checkbox-container.ts
- src/clr-angular/forms/common/abstract-container.ts
- src/clr-angular/forms/common/all.spec.ts
- src/clr-angular/forms/common/common.module.ts
- src/clr-angular/forms/common/control-container.spec.ts
- src/clr-angular/forms/common/control-container.ts
- src/clr-angular/forms/common/control.spec.ts
- src/clr-angular/forms/common/control.ts
- src/clr-angular/forms/common/index.ts
- src/clr-angular/forms/datalist/datalist-container.ts
- src/clr-angular/forms/password/password-container.ts
- src/clr-angular/forms/radio/radio-container.ts
- src/clr-angular/forms/range/range-container.ts
- src/clr-angular/forms/select/select-container.ts
- src/clr-angular/forms/textarea/textarea-container.ts
- src/dev/src/app/forms/forms.demo.module.ts
- src/dev/src/app/forms/forms.demo.routing.ts
- src/dev/src/app/forms/forms.demo.ts
- src/dev/src/app/forms/generic-container/generic-container.html
- src/dev/src/app/forms/generic-container/generic-container.ts
- src/website/src/app/documentation/demos/forms/forms.demo.html
- src/website/src/app/documentation/demos/forms/forms.demo.ts
- src/website/src/app/documentation/demos/forms/ng/generic.html
- src/website/src/app/documentation/demos/forms/ng/generic.txt
- src/website/src/app/utils/code-snippet.ts
This implements a new `clr-control-container` component and `clrControl` directive for wrapping potentially any form control to work with Clarity forms. Any controls must implement FormControlAccessor to properly wire up with the forms logic, but it works for internal or third party components.
closes: #2886
> feat(form): support a generic control container

- src/clr-angular/wizard/_wizard.clarity.scss
- src/clr-angular/wizard/wizard.html
- src/website/src/styles/global.scss
Use H1 and H2 tags instead of H3 to provide better accessibility.
**THIS IS BREAKING CHANGE**
Issue Number: #3994 
Close #3994
> fix(a11y): change how wizard use h1, h2 and h3 tags for accessibility

- src/clr-angular/button/button-group/button.spec.ts
- src/clr-angular/button/button-group/button.ts
- src/website/tsconfig.app.json
The popover toggle was always being called when any button in a button group was clicked, instead of just those inside of the menu.
Issue Number: #4267
> fix(button): only toggle overflow when button is in overflow menu

- src/clr-angular/forms/datepicker/date-input.spec.ts
- src/clr-angular/forms/datepicker/date-input.ts
- src/dev/src/app/datepicker/disabled.html
Add/Remove the `disabled` attribute to the input field at date-input component.
this way all click-events are disabled and the input won't be editable  
Issue Number: #4228 
Close #4228
> fix: datepicker input disabled state

- src/website/src/app/documentation/demos/stepper/angular-stepper-reactive.demo.html
- src/website/src/app/documentation/demos/stepper/angular-stepper-template.demo.html
- src/website/src/app/utils/code-snippet.ts
Some time `clr-snippet-code` will not render the code snippet. This is related to this change 
https://github.com/vmware/clarity/pull/4280/files#diff-5dbf67b916308dc690e7a6ad15467451
Also, resolve this error
https://clarity.design/documentation/stepper
> fix: clr-snippet-code sometimes won't render the code

- src/clr-core/common/utils/exists.ts
- src/clr-core/common/utils/global.spec.ts
- src/clr-core/common/utils/global.ts
• we can't count on having the proper version of typescript, so i got rid of sets
• i added a bunch of guards to over-protect vs. potential SSR breakages
• tested in ngUniversal SSR build; it works
Issue Number: #4319 
Stackblitz is strugglin'. They force the code editors to a version of typescript that doesn't support `Set` (or rather compiles Set into broken ES5.
As a result, I'm making our code less awesome so things will work in Stackblitz again. I also ran this through SSR. It works as of ng9.0.0.
> fix: downgrade es2015 code in version tracker

- golden/clr-angular.d.ts
- src/clr-angular/popover/dropdown/dropdown-item.spec.ts
- src/clr-angular/popover/dropdown/dropdown-item.ts
- src/clr-angular/popover/dropdown/providers/dropdown-focus-handler.service.ts
- src/clr-angular/popover/dropdown/providers/dropdown-focus-handler.spec.ts
Move the code that set the `id` for `ClrDropdownItem` from `DropdownFocusHandler ` into the component. This way we could overwrite the `id` from the outside and keep the same functionality 
Currently, the `id` for every dropdown item is set by the focus service. This is making hard to overwrite it from outside. This change is moving this into the component itself to handle it. And the focus service is no longer responsible for setting the id.
Issue Number: #3795 
Close #3795
> fix(dropdown): let user overwrite ClrDropdownItem id

- src/clr-angular/utils/focus/key-focus/key-focus.spec.ts
- src/clr-angular/utils/focus/key-focus/key-focus.ts
The key-focus component does not handle properly the focus initialization, when some of the focusable elements are being removed.
In case the focus was on an element, whose index is no longer available, the component throws a type error.
This change handles the case by initializing the focus on the last focusable element.
Signed-off-by: Zdravko Popov <zpopov@vmware.com>
https://stackblitz.com/edit/clarity-dark-theme-v2-zushxr?file=src%2Fapp%2Fapp.component.ts
The focus is initialized on the last focusable element.
This bug was introduced with the addition of the key-focus component.
For this reason, the fix needs to be back-ported to v2 and v1 branches.
> fix(a11y): type error on focus initialization

- src/clr-core/common/index.ts
• this was throwing off some versions/configurations of Jest
• the module loader was looking for a CSS file
We have to export the base element styles. These are generated `*.css.js` styles.
Some configs/implementations of Jest don't try to look for `*css.js`. They stop looking at `*.css`.
I added the full path. This is the only Clarity issue I've been able to find that impedes Jest configuration. Every other issue in #4094 and #4196 are (thus far) solvable by properly configuring an application.
> fix: adding .js extension to exported *.css.js file

- commitlint.config.js
- src/schematics/src/add/index.ts
If you install Clarity using schematics onto an Angular project that is older than latest, it would incorrectly assign `next` as the tag. This calculates the correct version of Clarity for older Angular versions based on the gap between releases (Angular 9 -> Clarity 3).
fixes #4341
Issue Number: #4341
> fix(schematics): set correct version of Clarity during ng add in older Angular projects

- src/clr-angular/accordion/stepper/models/stepper.model.spec.ts
- src/clr-angular/accordion/stepper/models/stepper.model.ts
- src/website/src/app/documentation/demos/stepper/angular-stepper-reactive.demo.html
`StepperModel.openFirstPanel` is called on every `StepperModel.updatePanelOrder()` this is forcing the first panel of the stepper to be open again and again. This change prevents it to be open again. 
You will need to `reset` the stepper before the code for `openFirstPanel` is executable again.
Issue Number: #4353
Close #4353
> fix(stepper): make sure openFirstPanel is call only once

- src/website/src/app/documentation/demos/datagrid/detail/detail.html
The detail pane demo had 1px extra from the color column, removed it and have it displaying a nicer table instead for the detail pane.
> docs: fix website detail pane demo from extra pixel in row

- src/clr-core/styles/typography/_typography.scss
- src/clr-core/styles/typography/typography.stories.mdx
- src/clr-core/styles/typography/typography.stories.ts
• added "inline" option for cds-text
• h* styles were serendipitously inheriting the correct font-family
• this meant they weren't being styled by the alt header font token
• font family styles were dependent on the cds body text being applied
• that has been fixed as well
• docs added for cds-text="inline"
> fix: fix heading typography changes, add inline

- golden/clr-angular.d.ts
- src/clr-angular/forms/common/error.ts
Inside `clr-control-container` we have this inside the template.
```html
<ng-content select="clr-control-error" *ngIf="invalid"></ng-content>
```
That will trigger the announcement inside the `clr-control-error` and when voice-over is turn on - the user will hear all possible error without seeing them on the screen. 
The reason is that Angular will render the `clr-control-error` and hide it from the view, but will trigger all of its lifecycles and with that trigger the aria-live announcement. This also prevents `clr-control-error` to be destroyed until the parent component is alive - so when there is a new error or the error is visible - no announcement will be made.
The fix below is only hiding the issue until a better solution is found. But with the plans of deprecation and moving …
> fix(a11y): prevent clr-control-error from announcing unwanted messages

- src/clr-core/button/button.element.scss
- src/clr-core/button/button.element.ts
- src/clr-core/button/button.stories.ts
- src/clr-core/common/base/base.element.scss
- src/clr-core/common/utils/dom.spec.ts
- src/clr-core/common/utils/dom.ts
- src/clr-core/styles/mixins/_mixins.scss
- src/clr-core/styles/tokens/tokens.yml
- src/clr-core/styles/typography/_typography.scss
• per discussion, not using layouts here but tokens
• this is to preserve ease of atomically re-styling the buttons with custom props
• fixed inset box shadows on active states – was not working
• applied new layouts to all buttons demos
• fixed a very precise sizing issue with line height erasers
• had to use precise sizings and paddings for buttons though; it's voodoo math at the moment but the existing equations are missing a variable somehow
• i believe the combination of a LHE inside of a "button" is throwing off the LHEs
• f-fox was applying `-webkit-appearance: button` to the `cds-button` b/c it has an attribute of `type="button"` or `type="submit"`
• we should be careful in the future not to use common HTML attribute names
• we should consider changing this attr/prop to not be …
> fix: migrate buttons to use design tokens

- src/website/src/app/app.component.html
- src/website/src/app/app.component.ts
- src/website/src/index.html
Removes the Clarity happiness survey alert from the app shell. 
There is an alert that opens a new tab to the Clarity survey. 
The alert is gone.
> docs: remove clarity happiness survey alert

- src/clr-core/styles/layout/_type-horizontal.scss
- src/clr-core/styles/layout/_type-vertical.scss
- src/clr-core/test-bundles/bundlesize.json
This change adds support to use the core layout system support for slotted elements in shadow DOM. 
In web component template
```html
<slot cds-layout="vertical gap:md"></slot>
```
Consuming App
```html
<my-element>
<p>item 1</p>
<p>item 1</p>
<p>item 1</p>
</my-element>
```
Consuming App Override
```html
<my-element>
<div cds-layout="horizontal gap:xs">
<p>item 1</p>
<p>item 1</p>
<p>item 1</p>
</div>
</my-element>
```
The fix adds a slotted selector that allows us to select slotted elements to apply the gaps to each item. This is needed because we have DOM existing both in light and shadow DOM in this scenario.
In an ideal world we would not need any of these and could use `flex-gap` …
> fix: core support slotted layout

- src/clr-icons/shapes/technology-shapes.ts
• tape drive icon was missing an expected space in front of the classnames attr
• verified that there are no other occurrences of this issue in the codebase
Issue Number: #4451 
I've verified that this is an issue in v2 as well. So I will need to backport once I get it merged into master.
> fix: tape drive icon html issue

- src/clr-angular/button/_properties.buttons.scss
- src/clr-angular/button/_variables.buttons.scss
- src/clr-angular/data/datagrid/_datagrid.clarity.scss
- src/clr-angular/data/datagrid/_properties.datagrid.scss
- src/clr-angular/layout/nav/_header.clarity.scss
- src/clr-angular/utils/variables/_variables.global.scss
- src/clr-core/button/button.element.scss
• this is a bit of a sledgehammer to force rgb values in to rgba() functions
• SASS is working in some instances but not others – likely due to custom properties
• this should fix a problem VMware teams were having from trying to pull our CSS in to their LESS builds
• this should be considered a stopgap for now as much of this SASS/CSS will be replaced by core in the long term
Issue Number: #4441
> fix: changing rgba() to use rgb values

- src/clr-angular/data/datagrid/datagrid-row.html
- src/clr-angular/data/datagrid/datagrid-row.spec.ts
- src/clr-angular/data/datagrid/datagrid-row.ts
Depending on `clr-dg-row-detail`'s presence, we project row cells in different view containers. When `clr-dg-row-detail` gets toggled, Datagrid row tries to transfer cells between those two view containers. But because we don't have `ng-content`, we lose the cells. This PR adds that necessary `ng-content` in the datagrid row so that it could still retain its cells.
Issue Number: #4466
> fix: add missing ng-content for row cells

- src/schematics/src/add/index.ts
If you used symbols like ^ or ~ in your Angular version, it was throwing `NaN` errors when trying to parse it as an integer. This adds a replace to drop non-digits before parsing.
This also removes installing Core by default.
fixes #4444
> fix(schematics): ng add was not resolving Angular version 

- golden/clr-angular.d.ts
- src/clr-angular/utils/drag-and-drop/drag-and-drop-integrated.spec.ts
- src/clr-angular/utils/drag-and-drop/drag-event.ts
- src/clr-angular/utils/drag-and-drop/draggable-ghost.spec.ts
- src/clr-angular/utils/drag-and-drop/draggable-ghost.ts
- src/clr-angular/utils/drag-and-drop/draggable/draggable.spec.ts
- src/clr-angular/utils/drag-and-drop/draggable/draggable.ts
- src/clr-angular/utils/drag-and-drop/droppable/droppable.spec.ts
- src/clr-angular/utils/drag-and-drop/droppable/droppable.ts
- src/clr-angular/utils/drag-and-drop/helpers.spec.ts
- src/clr-angular/utils/drag-and-drop/interfaces/drag-event.interface.ts
- src/clr-angular/utils/drag-and-drop/providers/drag-event-listener.service.mock.ts
- src/clr-angular/utils/drag-and-drop/providers/drag-event-listener.service.spec.ts
- src/clr-angular/utils/drag-and-drop/providers/drag-event-listener.service.ts
- src/dev/src/app/drag-and-drop/basic-draggable.demo.html
- src/dev/src/app/drag-and-drop/draggable-handle.demo.html
This PR introduces `clrDragStartDelay` input to `clrDraggable` directive. The input defines the hold duration for initiating the drag start event.
Example: 
```html
<button class="btn btn-primary" clrDraggable [clrDragStartDelay]="500">draggable</button>
```
> feat(dnd): add clrDragStartDelay input property to clrDraggable

- src/clr-core/icon-shapes/icon.element.ts
• renaming `ariaLabel` property on icon.element
• the old naming was causing a collision with some browsers b/c they were expecting it to be a property on the HTMLElement
• we need to be careful about not stomping on the DOM API when naming properties
• needs to be back ported to v3
Issue Number: #4473
> fix(icons): changing private property on core icon element

- src/clr-core/icon-shapes/icon.element.scss
See PR title. Just moving previous sass vars and custom properties to core tokens (a fancy concept for improved architecture behind sass vars and custom properties)
> fix(icons): migrate core icons scss to use tokens

- src/clr-core/badge/badge.element.scss
- src/clr-core/button/base-button.element.scss
- src/clr-core/button/button.stories.mdx
- src/clr-core/button/button.stories.ts
- src/clr-core/button/icon-button.stories.mdx
- src/clr-core/button/icon-button.stories.ts
- src/clr-core/tag/tag.element.scss
- src/clr-core/tag/tag.stories.ts
• block buttons were left out of the PR earlier this week
• this PR corrects that
• block button stories added for both regular and icon buttons
• working through demos, i noticed the bottom of tags were being cutoff in layouts
• this problem was because some of the content inside of tags were overflowing the component
• these edits fix that problem as well
• a number of nudges were able to be removed as a result
> fix: core - adding block buttons back in, tag fixes

- packages/angular/projects/clr-angular/src/button/_properties.buttons.scss
- packages/angular/projects/clr-angular/src/forms/styles/_properties.forms.scss
- packages/angular/projects/clr-angular/src/layout/_properties.login.scss
• sass variable keys were being passed as values into css custom properties
• this cleans those up so the actual values make it into the generated CSS
Fixes: #4526
Issue Number: #4526 
This needs to be backported to v3.
> fix: cleaning up stray sass variables

- golden/clr-angular.d.ts
- src/clr-angular/button/_properties.buttons.scss
- src/clr-angular/forms/styles/_properties.forms.scss
- src/clr-angular/layout/_properties.login.scss
• sass variable keys were being passed as values into css custom properties
• this cleans those up so the actual values make it into the generated CSS
Fixes: #4526
> fix: cleaning up stray sass variables - v3 backport

- packages/angular/projects/clr-angular/src/emphasis/alert/_alert.clarity.scss
This change fixes #4548. IE11 doesn't calculate the correct height of .alert-text.
IE11 has an issue calculating the height of long multiline content for global alerts when flex-basis is set to auto. 
Issue Number: #4548
`.alert-text` elements set a percentage for other device size screens. This PR updates the default to be 100%
> fix(alert): fix alert-text width for IE11

- src/clr-angular/data/datagrid/datagrid-column.spec.ts
- src/clr-angular/data/datagrid/datagrid-column.ts
The order of the `@Input` needed to be changed, cause we are asking for a `colType` before it was assigned so it always defaulted to `string`
Issue Number: #4567
Close #4567
> fix: numberic filters type was not applyed on dg-column

- packages/core/docs/browser-support.stories.mdx
- packages/core/docs/getting-started.stories.mdx
- packages/core/src/button/base-button.element.scss
- packages/core/src/button/button.stories.ts
- packages/core/src/button/icon-button.stories.ts
- packages/core/src/list/list.scss
- packages/core/src/modal/modal.element.ts
- packages/core/src/modal/modal.stories.mdx
- packages/core/src/modal/modal.stories.ts
- packages/core/src/styles/color/color.stories.mdx
- packages/core/src/styles/layout/_optimize.scss
- packages/core/src/styles/layout/docs/grid.stories.mdx
- packages/core/src/styles/layout/docs/horizontal.stories.mdx
- packages/core/src/styles/layout/docs/layout.stories.mdx
- packages/core/src/styles/layout/docs/patterns.stories.mdx
- packages/core/src/styles/layout/docs/spacing.stories.mdx
- packages/core/src/styles/layout/docs/utilities.stories.mdx
- packages/core/src/styles/layout/docs/vertical.stories.mdx
- packages/core/src/styles/layout/layout.stories.ts
- packages/core/src/styles/layout/mixins/_mixins.scss
- packages/core/src/styles/spacing/spacing.stories.mdx
- packages/core/src/styles/tokens/tokens.stories.mdx
- packages/core/src/styles/tokens/tokens.stories.ts
- packages/core/src/styles/typography/typography.stories.mdx
- packages/core/src/styles/typography/typography.stories.ts
- packages/core/src/tag/tag.stories.ts
- packages/core/test-bundles/bundlesize.json
- packages/core/tokens.yml
• added "2px" spacer
• added "4px" spacer
• these are needed for sizing layouts in compact versions of our components
• shifted all existing values up a size
• sizes now go from xxs to xxl
> feat: adding smaller values to core layout spacing

- packages/angular/golden/clr-angular.d.ts
- packages/angular/projects/clr-angular/src/utils/loading/loading.ts
Adds input setter coercion to enable a nullable input (as it is already handled by the code) for projects with strict template checks.
https://angular.io/guide/template-typecheck#input-setter-coercion
Signed-off-by: Tobias Wittwer <t.wittwer95@gmail.com>
It is not possible to use an observable with async pipe as data source for `clrLoading` in strict template mode, because async pipe intially emits `null` and `clrLoading` only accepts `boolean | ClrLoadingState` but handles null as well.
`clrLoading` accepts `boolean | ClrLoadingState | null` via input setter coercion.
> fix: adds input setter coercion for ClrLoading

- packages/angular/golden/clr-angular.d.ts
- packages/angular/projects/clr-angular/src/forms/datepicker/date-input.ts
Adds input setter coercion for the date input to enable a nullable input according  to the nullable output in projects with strict template checks.
https://angular.io/guide/template-typecheck#input-setter-coercion
Signed-off-by: Tobias Wittwer <t.wittwer95@gmail.com>
It is not possible to pass `null` as empty value to the date picker input in strict template mode.
Date picker accepts `Date | null` as input.
A better option would be add `null` in the input setter as well in the output.
```diff
- @Output('clrDateChange') dateChange: EventEmitter<Date> = new EventEmitter<Date>(false);
+ @Output('clrDateChange') dateChange: EventEmitter<Date | null> = new EventEmitter<Date | null>(false); …
```
> fix(date-picker): adds input setter coercion

- packages/angular/golden/clr-angular.d.ts
- packages/angular/projects/clr-angular/src/utils/conditional/if-open.directive.ts
Adds input setter coercion for the IfOpen directive to enable a usage without a value (`<clr-dropdown-menu *clrIfOpen>`) in projects with strict template checks.
https://angular.io/guide/template-typecheck#input-setter-coercion
Signed-off-by: Tobias Wittwer <t.wittwer95@gmail.com>
If the IfOpen directive is used like proposed in the docs without a value:  
`<clr-dropdown-menu *clrIfOpen>`  
A type error is thrown in case the consuming project enables [strict template checks](https://angular.io/guide/template-typecheck#strict-mode).  
The reason is the implicit conversion of this construct in:
```
<ng-template [clrIfOpen]="''">
<clr-dropdown-menu>...</clr-dropdown-menu>
</ng-template> …
```
> fix(dropdown): adds input setter coercion

- packages/angular/projects/clr-angular/src/data/datagrid/providers/selection.spec.ts
- packages/angular/projects/clr-angular/src/data/datagrid/providers/selection.ts
Backport fix from v3 to master/v4
#4626
> backport: prevent of calling indexOf on non array inside the datagrid and selection service

- src/clr-angular/data/datagrid/providers/selection.spec.ts
- src/clr-angular/data/datagrid/providers/selection.ts
When using `ngFor` instead of `clrDgItems` `all` may not be populated so there is a need to have a check to be sure that `all` is array before we try to call array specific methods on it.
Issue Number: #4504 
Close #4504
> fix: prevent of calling indexOf on non array inside the datagrid and selection service

- packages/angular/projects/clr-angular/src/utils/popover/popover-content.spec.ts
- packages/angular/projects/clr-angular/src/utils/popover/popover-content.ts
Close: #4430
Signed-off-by: Bram Meerten <bram.mee@gmail.com>
When opening and closing a popover synchronously, the following error is thrown:
```TypeError: Cannot read property 'rootNodes' of undefined```
Issue Number: #4430
When handling the content-check events in the ClrPopoverContent, make sure view is still defined before updating the renderer style.
> fix: don't update view after opening and immediately closing a popover

- packages/core/src/modal/modal.element.ts
A tiny PR to add the missing import of close icon in the core modal.
> fix(modal): import close icon in core modal

- packages/angular/projects/clr-angular/src/data/datagrid/all.spec.ts
- packages/angular/projects/clr-angular/src/data/datagrid/providers/state.provider.spec.ts
- packages/angular/projects/dev/src/app/datagrid/preserve-selection/preserve-selection.ts
- packages/angular/projects/dev/src/app/datagrid/selection-single/selection-single.ts
- packages/angular/projects/dev/src/app/datagrid/selection/selection.ts
- packages/angular/projects/dev/src/app/datagrid/server-driven/server-driven.ts
* update pagination firstItem and lastItem description in documentation
* use page.size * (page.current - 1) to fetch items in server-driven datagrid
* partially add unit test for state provider
Note: website changes not merged in master/v4
Signed-off-by: KingMario <gcyyq@hotmail.com>
> fix: firstItem-related issues; port from v3

- src/website/src/app/documentation/get-started/get-started.component.html
The link to the ATTRIBUTION.md file is missing the docs directory.
The link to the ATTRIBUTION file does not work 
The link to the ATTRIBUTION file now works.
> Correct link to ATTRIBUTION.md file

- packages/core/src/button/base-button.element.scss
- packages/core/src/button/button.element.scss
• went for visual correctness as opposed to numerical correctness
• spacing added around icons and font glyphs made numerical correctness break visual direction
• fixed alignment issues with button content
Changes requested by visual design.
Issue Number: #4522
> fix(button): update internal negative space per visual design feedback

- packages/angular/karma.conf.js
- packages/core/karma.conf.js
- packages/core/package.json
- packages/icons/karma.conf.js
* Change CI karma reporters to use dots to indicate that Karma is working but fix the issue with how `progress` reporter is been logged inside CI logs noise.
```
...
Chrome Headless 83.0.4103.97 (Linux x86_64): Executed 17 of 64 SUCCESS (0 secs / 0.162 secs)
Chrome Headless 83.0.4103.97 (Linux x86_64): Executed 18 of 64 SUCCESS (0 secs / 0.178 secs)
Chrome Headless 83.0.4103.97 (Linux x86_64): Executed 19 of 64 SUCCESS (0 secs / 0.179 secs)
Chrome Headless 83.0.4103.97 (Linux x86_64): Executed 20 of 64 SUCCESS (0 secs / 0.185 secs)
Chrome Headless 83.0.4103.97 (Linux x86_64): Executed 21 of 64 SUCCESS (0 secs / 0.186 secs)
Chrome Headless 83.0.4103.97 (Linux x86_64): Executed 22 of 64 SUCCESS (0 secs / 0.187 secs)
Chrome Headless 83.0.4103.97 (Linux x86_64): Executed 23 of 64 SUCCESS (0 …
```
> build: improve ci logging

- packages/angular/projects/clr-angular/src/data/datagrid/datagrid-placeholder.spec.ts
- packages/angular/projects/clr-angular/src/data/datagrid/datagrid-placeholder.ts
Provide `role='row'` and `role='gridcell'` to datagrid-placeholder so it could be selectable by SR when visible.
Issue Number: #4090 
Close #4090
> fix(a11y): let datagrid placeholder to be focusable from SR

- packages/angular/projects/clr-angular/src/utils/focus-trap/focus-trap-config.interface.ts
- packages/angular/projects/clr-angular/src/utils/focus-trap/focus-trap.directive.spec.ts
- packages/angular/projects/clr-angular/src/utils/focus-trap/focus-trap.directive.ts
- if the focus goes out to the top rebound element, it means a user has pressed SHIFT+TAB from the first focusable element in the trap.
So the focus trap will rebound the focus to its last focusable element.
- if the focus goes out to the bottom rebound element, it means a user has pressed TAB from the last focusable element in the trap.
So the focus trap will rebound the focus to its first focusable element.
- if the focus goes out to an element outside that is not rebounder element, it means a user has used a mouse to click and focus.
So the focus trap will rebound the focus to its host element. This is the case if the focus trap config is on strict mode.
If the trap config is on not strict mode, the focus trap will not rebound the focus.
Fixes #2400
Signed-off-by: stsogoo …
> feat: enable SHIFT+TAB in focus trap

- packages/angular/projects/clr-angular/src/forms/common/wrapped-control.spec.ts
- packages/angular/projects/clr-angular/src/forms/common/wrapped-control.ts
Issue Number: #4480 
When you go to a form and click on a control for example of type "number" and then click outside of the control errors are shown if there are any.
> fix(form): missing ng-touched on controls that are touched

- packages/angular/projects/clr-angular/src/forms/styles/_containers.clarity.scss
- packages/angular/projects/clr-angular/src/forms/styles/_input-group.clarity.scss
- packages/angular/projects/clr-angular/src/forms/styles/_input.clarity.scss
- packages/angular/projects/clr-angular/src/forms/styles/_mixins.forms.scss
- packages/angular/projects/clr-angular/src/forms/styles/_properties.forms.scss
- packages/angular/projects/clr-angular/src/forms/styles/_variables.forms.scss
- packages/angular/projects/clr-angular/src/utils/_mixins.scss
- packages/angular/projects/clr-angular/src/utils/_overwrites.clarity.scss
- packages/angular/projects/clr-angular/src/utils/_theme.dark.clarity.scss
- packages/angular/projects/dev/src/app/forms/disabled/disabled.html
- packages/angular/projects/dev/src/app/forms/disabled/disabled.ts
Adding a `clr-form-placeholder` SCSS and CSS variable to set the input/textarea/select and every other component placeholder color to a solid one and remove the `opacity` option on it. In addition, change the opacity to all disabled items from 0.54 to 0.55. 
The changes try to improve the accessibility of the colors to be more closely to 3:1 ration - and try to avoid the use of opacity as a form of color shading.
The breaking change from this PR is the change of 0.01 opacity for placeholder color and disabled form elements.
> feat: introduce clr-form-placeholder solid color and set disabled opacity to 0.55

- packages/angular/projects/clr-angular/src/utils/popover/popover-close-button.spec.ts
- packages/angular/projects/clr-angular/src/utils/popover/popover-close-button.ts
- packages/angular/projects/clr-angular/src/utils/popover/popover-content.spec.ts
- packages/angular/projects/clr-angular/src/utils/popover/popover-open-close-button.ts
- packages/angular/projects/clr-angular/src/utils/popover/providers/popover-toggle.service.spec.ts
- packages/angular/projects/clr-angular/src/utils/popover/providers/popover-toggle.service.ts
Issue Number: #3622
When the container is too large and an arrow key initiates page scrolling, but at the same time initiates a popover opening, the popover doesn't close and stays open.
It is somehow tricky to create a unit test for this because it is part of the popovers and they are represented as directives and services, and at the same time, it requires a parent with a template that has a scroll and a popover child component in it. It is not a good idea to add the unit test in the popover but at the same time it is not a good idea to set a single unit test for example only in dropdown cause this can be the same issue in the tooltips.
> fix(toggle): popover toggle prevents default behavior of arrow key events

- src/clr-angular/layout/tabs/_tabs.clarity.scss
Issue Number: #3748
The tab-content is full width on IE 11.
> fix(tabs): width tab-content in ie 11

- packages/angular/projects/clr-angular/src/layout/vertical-nav/vertical-nav.html
- packages/angular/projects/clr-angular/src/layout/vertical-nav/vertical-nav.spec.ts
Hide a helper button from tabbing to prevent noise from SR
Issue Number: #4117 
Close #4117
> fix(a11y): hidden button into vertical-nav from been tabbable

- packages/angular/projects/clr-angular/src/forms/common/if-control-state/if-error.ts
Unhandle that there is a case at the start that the container could be undefined and calling a method on it will throw `undefined` error.
Close #4813
> fix(form): if-error call on undefined ViewContainerRef throw error

- apps/core-parcel-js/package.json
- packages/core/docs/angular.stories.mdx
- packages/core/docs/angularjs.stories.mdx
- packages/core/docs/preact.stories.mdx
- packages/core/docs/react.stories.mdx
- packages/core/docs/vue.stories.mdx
- packages/core/src/button/base-button.element.scss
- packages/core/src/styles/typography/_typography.scss
- packages/core/src/styles/typography/typography.stories.mdx
- packages/core/src/styles/typography/typography.stories.ts
- packages/core/tokens.yml
- minor improve getting started guides
Added react docs from react package readme and added a link to the demo apps.
- link styles in cds-button in global context
When global styles exist they could override a link style in the cds-button component
- font heading weights
The weights were scalling up to high in browsers since CIty is loading the regular weight vs medium font file. This caused excess font weight in the browser when compared to the medium font file in the original design. 
- typography docs
Added example of the heading/paragraph API
> fix: core doc fixes

- apps/website/components/button-group/README.md
- apps/website/components/card/demo.md.orig
- apps/website/components/checkbox/README.md
- apps/website/components/header/README.md
- apps/website/components/password/README.md
- apps/website/components/radio/README.md
- apps/website/components/signpost/README.md
- apps/website/components/table/README.md
- apps/website/foundation/app-layout/README.md
- apps/website/get-started/angular.md
Some of the anchor tags are pointing to pages that not exist and some words are misspelled.
The anchor tags are pointing to the correct pages and words are spelled correctly.
> docs: fix page anchor links and words spelling in website

- apps/website/.vuepress/public/demos/themes/angular.json
- apps/website/.vuepress/public/demos/themes/webpack.js
- apps/website/.vuepress/theme/styles/containers.scss
- apps/website/foundation/navigation/README.md
- apps/website/foundation/themes/README.md
Updated navigation code snippits to use doc-demo
Adds a constraint class that can be combined with main-container to limit height to content size
Change to the home page for new website. 
Simplified transition between hero and content. 
> docs(navigation): adds height constraint to css demos

- apps/website/.vuepress/theme/components/Home.vue
Margins were initially used to add whitespace around content and images but this caused x-scrolling. Section targeted padding fixes this issue.
mobile/responsive viewports have undesirable x-scrolling at the smallest viewport size. 
Remove styles the  caused x-scrollbar.
> docs: fixes x-scrolling on smallest responsive screen

- apps/website/.vuepress/public/demos/sidenav/icons-css.html
- apps/website/.vuepress/theme/core.js
- apps/website/data/icon-inventory.js
- packages/core/src/icon/icon.element.scss
Fixes an issue where cds-icon does not apply fill color based on legacy clr-ui behavior. Swaps the website icons to use cds-icon legacy mode instead of clr-icon. This reduces the home page landing JS from 417kb gzip to about 218kb gzip.
> fix: core icon color, website core icon load

- apps/website/components/accordion/README.md
- apps/website/components/accordion/api.md
- apps/website/components/button-group/api.md
- apps/website/components/stepper/api.md
- apps/website/components/tab/README.md
- apps/website/components/tab/api.md
- apps/website/components/toggle/README.md
- apps/website/components/tooltip/api.md
- apps/website/components/tree-view/README.md
- apps/website/components/vertical-nav/README.md
This change removes any `.html` or `.md` file extensions from intra site links. 
> docs: fixes for links with file extensions

- apps/website/components/alert/README.md
- apps/website/components/alert/api.md
- packages/angular/src/stories/combobox/basic.html
- packages/angular/src/stories/combobox/combobox.stories.ts
Summary of Options exists in Alert overview page. There is no basic Combobox basic story 
Summary of Options removed from Alert overview page and Combobox basic story is available at storybook
> docs: remove SoO from alert overview and add combobox basic story

- scripts/update-license.js
Fixes #4679
Signed-off-by: Sajini De Silva <sdesilva28@gmail.com>
Files from Untracked and Changes not staged for commit zone are pulled into the staging (and subsequently into commit) by npm run license:fix script run by pre-commit githook.
Issue Number: #4679
Stash all the files that are not staged before fixing the license and
then un-stash them after.
> chore: Fix license only on staged files

- packages/angular/projects/clr-angular/src/accordion/_accordion.clarity.scss
When last panel is open, the border radius should not apply to header.
> fix(accordion):  border bottom

- src/clr-angular/data/datagrid/_datagrid.clarity.scss
Issue Number: #4872
The title doesn't wrap on column resize.
Before
After (horizontal scroll available)
After (min-width => title content)
> fix(datagrid): disable whitespace wrap in column title

- src/clr-angular/data/datagrid/_datagrid.clarity.scss
This reverts commit 6468cda9187cc23433fd01e3cc193ff0037b3223.
Seems like the fix causes issues we didn't expect. We need to figure out a better way to fix it.
> Revert "fix(datagrid): disable whitespace wrap in column title" 

- apps/website/.vuepress/theme/global-components/DocDemo.vue
- apps/website/.vuepress/theme/global-components/DocTypographyTable.vue
- apps/website/.vuepress/theme/layouts/Layout.vue
- apps/website/.vuepress/theme/styles/overrides.scss
- apps/website/foundation/typography/README.md
We had to override clr-ui styles in our website. That was affecting the app-layout page's demos too. Thus, in this PR, those layout style changes are isolated within the Layout.vue component.
> docs: isolate layout style changes

- src/clr-angular/accordion/stepper/models/stepper.model.spec.ts
- src/clr-angular/accordion/stepper/models/stepper.model.ts
Handle case when there is not yet the first element to open.
Close: #4822
> fix: handle stepper throwing TypeError

- packages/angular/golden/clr-angular.d.ts
- packages/angular/projects/clr-angular/src/wizard/wizard-stepnav-item.spec.ts
- packages/angular/projects/clr-angular/src/wizard/wizard-stepnav-item.ts
The active pages in the Wizard were being assigned the `aria-selected` attribute.
Issue Number: 4080
The active pages are assigned the `aria-current: 'step'` attribute instead. This allows the assistive technologies to communicate that the element being read represents the current step in a series of steps.
fixes #4080
> fix(a11y): set aria-current instead of aria-selected in the Wizard's steps

- packages/angular/projects/clr-angular/src/wizard/wizard-button.ts
- [ x ] Bugfix
Everything works fine.
Everything works the same.
- [ x ] No
The component style of `[attr.aria-hidden]` in the wizard-button.ts component is a bit confusing, as its selector doesn't actually target anything in the component itself (missing `:host`. Showing/Hiding the buttons in the wizard is handled by _wizard.clarity.scss line 353, and keeping this line here may be a bit confusing.
> Remove inline style on wizard-button.ts

- packages/angular/golden/clr-angular.d.ts
- packages/angular/projects/clr-angular/src/forms/combobox/_combobox.clarity.scss
- packages/angular/projects/clr-angular/src/forms/combobox/combobox.html
- packages/angular/projects/clr-angular/src/forms/combobox/combobox.ts
The combobox focus indicator pushed down 1px and was not animating as expected. This updates the focus indicator to match the rest of Clarity controls.
> fix(combobox): focus indicator was not animating

- src/clr-angular/data/datagrid/_datagrid.clarity.scss
When there are two or more words in column title and the column size gets smaller the text starts to wrap. When the text starts to wrap, it forces the header to shrinks vertically and goes over the data in the grid.
The `min-height` with `position:sticky` make the .datagrid-header to keep its height and even when the content wraps the `height` of the .datagrid-header stays the same. That's why the header content goes over the data.
Issue Number: #4872
The header of datagrid doesn't hide some of the data based on column headers content size.
More 
Before
After
> fix(datagrid): header visually goes over the data

- packages/angular/golden/clr-angular.d.ts
- packages/angular/projects/clr-angular/src/data/stack-view/stack-block.ts
The Stack View expand/collapse icon has a title attribute. The parent element also has an attribute `aria-expanded` which conveys the state and serves the same purpose.
Issue Number: #4525
The title attribute on the Stack View icon is removed as it's redundant and creates a tooltip that's not keyboard accessible.
fixes #4525
> fix(a11y): remove redundant title attribute from Stack View expand/collapse icon

- .github/workflows/lock-threads.yml
As part of our proposed issue management strategy, this PR introduces auto-locking after 14 days of closure. It only locks a closed issue, and batches them nightly. It will only run 50 at a time to avoid hitting API limits.
Caution: this will generate a lot of email noise for anyone on those old threads. You might want to setup an email filter for these.
> chore: add auto-locking old threads to CI

- golden/clr-angular.d.ts
- src/clr-angular/data/datagrid/datagrid-column.spec.ts
- src/clr-angular/data/datagrid/datagrid-column.ts
Angular doesn't guarantee in what order the Input will be assigned. That's why we need to use `ngOnChanges` to be sure that all methods that require multiple inputs from outside are already assigned and are ready to be used.
After this PR is merged will need to be backported to v4 as it also affected by this.
Issue Number: #4567
Close: #4567
> fix: make sure that colType and field are set before trying to configure filters

- packages/angular/golden/clr-angular.d.ts
- packages/angular/projects/clr-angular/src/data/stack-view/stack-block.ts
> fix(a11y): remove redundant title attribute from Stack View expand/collapse icon (backport)

- packages/angular/golden/clr-angular.d.ts
- packages/angular/projects/clr-angular/src/data/datagrid/datagrid-column.spec.ts
- packages/angular/projects/clr-angular/src/data/datagrid/datagrid-column.ts
Angular could assign colType and field in an random order, so we need
to wait before we could start using them to assign the filter type
for that reason we use ngOnChanges to be sure everything is set and
then call setupDefaultFilter
Backport from v3 to v4 (master)
> fix(datagrid): colType and field are set before trying to configure filters

- .github/workflows/build.yml
- .github/workflows/dev.yml
- .github/workflows/website.yml
Add action/cache to improve Github Actions build time by not
downloading and installing yarn/npm package every time.
Saving ~3-4min from every build/website/dev workflow.
First, run after a change of the `yarn.lock` the file will add additional `~7-9min` but after that, we gonna spend only `3min` to unpack the cached `node_modules`
Try the official guidelines but that did not save a lot of time, caching node_modules provided the most time saving - I suspect that the reason for that is that we don't run `postinstall` scripts for the packages and don't precompile others.
> build: use action cache to improve CI build time

- .vscode/settings.json
VS Code can use a lot of CPU cycles due to it trying to follow symlink paths. This is a problem with using Yarn since it uses symlinks extensively.
Disabling this flag improved VSCode performance significantly. Typically we don't store editor specific settings in the repo but this one seemed pretty important to set. If we dont want to include this one I can close this PR out.
> fix: symlink setting vscode monorepo

- packages/angular/golden/clr-angular.d.ts
- packages/angular/projects/clr-angular/src/forms/common/form.ts
Values provided without binding are ignored:
```
<form clrForm clrLayout="horizontal" clrLabelSize="6">
```
Issue Number: #4432
Values provided without binding are converted to numbers and set as the size.
closes #4432
> fix: accept clrLabelSize values provided without binding

- packages/angular/projects/clr-angular/src/modal/_modal.clarity.scss
- packages/angular/projects/clr-angular/src/modal/modal.html
- packages/angular/projects/clr-angular/src/modal/modal.spec.ts
- packages/angular/projects/clr-angular/src/wizard/_wizard.clarity.scss
The visual order in the Modal/Wizard is the following:
1. Title
2. Close button
The DOM order is:
1. Close button
2. Title
Issue Number: #4083 
Now, the DOM order matches the visual order:
1. Title
2. Close button
##
ToDo:
> fix(a11y): match the DOM order of the Modal's title and close button with their visual order

- packages/angular/projects/clr-angular/src/modal/_modal.clarity.scss
- packages/angular/projects/clr-angular/src/modal/modal.html
- packages/angular/projects/clr-angular/src/modal/modal.spec.ts
- packages/angular/projects/clr-angular/src/wizard/_wizard.clarity.scss
Backport of https://github.com/vmware/clarity/pull/4894
> fix(a11y): match the DOM order of the Modal's title and close button with their visual order (backport)

- packages/core/package.js
- packages/react/package.js
- packages/react/package.json
- packages/react/tsconfig.build.json
- packages/react/tsconfig.json
- updated react package to use built core file like demo apps
- updated the parcel based dev app to use cache
- updated react package's @clr/core dependency to point to locally built one
> fix: build script for react wrapper

- packages/angular/projects/clr-angular/src/data/datagrid/_datagrid.clarity.scss
When there are two or more words in column title and the column size gets smaller the text starts to wrap. When the text starts to wrap, it forces the header to shrinks vertically and goes over the data in the grid.
The min-height with position:sticky make the .datagrid-header to keep its height and even when the content wraps the height of the .datagrid-header stays the same. That's why the header content goes over the data.
Issue Number: #4919
> fix: header visually goes over the data

- packages/react/package.json
Fixing relative path for building core as a pre-step to react package's `start` script.
> fix: react package.json path for core build

- packages/core/src/button/inline-button.element.scss
- packages/core/src/button/inline-button.element.ts
- packages/core/src/styles/typography/_typography.scss
Links and inline buttons should have the underline style
Links and buttons have the proper underline style. Also removed a trailing white space that caused a bit of excess underline in the inline button.
minor visual but a fix for a11y
> fix: core link styles a11y

- packages/core/src/icon/icon.element.ts
- packages/core/src/internal/decorators/property.spec.ts
- packages/core/src/internal/decorators/property.ts
The prop warning will now check if the prop was set with a value before logging. Currently it logs regardless of the value.
> fix: core check that prop exists before warning

- packages/core/src/icon/icon.element.ts
- packages/core/src/internal/decorators/property.spec.ts
- packages/core/src/internal/decorators/property.ts
Back port of https://github.com/vmware/clarity/pull/4981
> fix: backport core check that prop exists before warning

- packages/core/src/button/button.element.ts
- packages/core/src/icon/utils/icon.classnames.ts
- packages/core/src/internal/enums/aria-roles.ts
Reduces the `@clr/core` memory size with 0.2MB.
Reduces the `@clr/core` with 0.2MB by moving the possible enums to `const` enums
Unchanged
Unchanged
> chore: update core possible enums to const enums

- packages/angular/golden/clr-angular.d.ts
- packages/angular/projects/clr-angular/src/forms/common/index.ts
- packages/angular/projects/clr-angular/src/forms/common/label.spec.ts
- packages/angular/projects/clr-angular/src/forms/common/layout.spec.ts
- packages/angular/projects/clr-angular/src/forms/common/layout.ts
- packages/angular/projects/clr-angular/src/forms/common/providers/layout.service.spec.ts
- packages/angular/projects/clr-angular/src/forms/common/providers/layout.service.ts
- packages/angular/projects/clr-angular/src/forms/datepicker/date-container.spec.ts
- packages/angular/projects/clr-angular/src/forms/tests/container.spec.ts
This opens up the Layout enum for Angular to be able to reference, and renames it for our public API. This is not considered a breaking change because this was internal before.
closes #4847 #4601
Issue Number: #4847
> fix(form): export form layout enum for strict typing

- packages/core/src/internal/base/focus-trap.base.spec.ts
- packages/core/src/internal/base/focus-trap.base.ts
- packages/core/src/internal/utils/focus-trap.ts
The modal could throw an exception in certain use cases. If the modal is added to the DOM with a hidden attr applied by default an exception would occur due to the focus service not being defined. The fix was to create the focus service every time and then trigger and check if it should be activated or deactivated in the connected callback or attr change callback.
> fix: core modal exception

- packages/core/src/internal/utils/dom.ts
This is a fix for an optimization I missed in the Core button icons PR yesterday. 
The spanWrapper fn does not properly reference the parent node.
The spanWrapper fn properly wraps the parent node.
> fix: change the node reference for spanWrapper

- packages/angular/projects/clr-angular/src/forms/common/if-control-state/if-control-state.service.spec.ts
- packages/angular/projects/clr-angular/src/forms/common/if-control-state/if-control-state.service.ts
Handle case when calling triggerStatusChange without `this.control` to be defined
```
main.28fcef2b19421f832d4b.js:1 ERROR TypeError: Cannot read property 'status' of undefined
at triggerStatusChange (main.28fcef2b19421f832d4b.js:1)
at triggerValidation (main.28fcef2b19421f832d4b.js:1)
at triggerValidation (main.28fcef2b19421f832d4b.js:1)
at main.28fcef2b19421f832d4b.js:1
at ps (main.28fcef2b19421f832d4b.js:1)
at r (main.28fcef2b19421f832d4b.js:1)
at HTMLInputElement.<anonymous> (main.28fcef2b19421f832d4b.js:1)
at HTMLInputElement.n (main.28fcef2b19421f832d4b.js:1)
at l.invokeTask (polyfills.52bd7f36c0afeeaa4ae2.js:1)
at Object.onInvokeTask (main.28fcef2b19421f832d4b.js:1)
at l.invokeTask (polyfills.52bd7f36c0afeeaa4ae2.js:1)
at i.runTask (polyfills.52bd7f36c0afeeaa4ae2.js:1)
at …
```
> fix: handle TypeError when calling triggerStatusChange

- packages/angular/projects/clr-angular/src/forms/combobox/combobox.html
- packages/angular/projects/clr-angular/src/forms/combobox/providers/combobox-focus-handler.service.spec.ts
- packages/angular/projects/clr-angular/src/forms/combobox/providers/combobox-focus-handler.service.ts
- also fix prevention of auto-suggestion ontop of the popover
Opens popover with options on enter.
Submits form when using enter to select an option.
Shows browser form suggestions.
Issue Number: #4983 
Submits form on enter when popover is closed.
Does not submit form when using enter to select an option.
Browser does not show form suggestions.
> fix: prevent combobox form submit on selection with enter

- packages/angular/projects/clr-angular/src/forms/combobox/combobox.html
- packages/angular/projects/clr-angular/src/forms/combobox/providers/combobox-focus-handler.service.spec.ts
- packages/angular/projects/clr-angular/src/forms/combobox/providers/combobox-focus-handler.service.ts
- also fix prevention of auto-suggestion ontop of the popover
Issue Number: #4983
> fix: prevent combobox form submit on selection with enter backport

- packages/core/src/button/button.element.ts
- packages/core/src/file/file.element.spec.ts
- packages/core/src/internal/utils/dom.ts
This change removes a guard in the Core button element to make sure that the spanWrapper wrapps all textNodes in button elements for all browsers. 
There is a guard that prevents a supported check that limits spanWrapping to only Safari and IE11. 
spanWrapper will run for buttons in all browsers.
> fix: remove browser guard from core button element

- packages/angular/projects/clr-angular/src/data/datagrid/providers/selection.spec.ts
- packages/angular/projects/clr-angular/src/data/datagrid/providers/selection.ts
The current selection is now immutable, so that selection can directly be used with @ngrx/store strict checking.
Signed-off-by: Skip Geldens <skip@skipgeldens.nl>
Currently I cannot use [clrDgSelected] directly from a ngrx/store async variable because the datagrids mutates the content of the array of selected items instead of replacing the complete array. Shown in: https://stackblitz.com/edit/clarity-light-theme-v2-cpfinp
Issue Number: https://github.com/vmware/clarity/issues/4528
The `_current` array in the selection provider is not mutated but replaced on change.
> fix(datagrid): current selection immutability

- packages/core/src/alert/alert-group.element.spec.ts
- packages/core/src/alert/alert-group.element.ts
Tested in:
✔︎ Chrome
Fixes: #5023
Backport of #5026
> fix(alert): sync child alerts when slot changes in alert group (v4 backport)

- packages/core/src/alert/alert-group.element.spec.ts
- packages/core/src/alert/alert-group.element.ts
Tested in:
✔︎ Chrome
Fixes: #5023
Adding an alert to an alert group asynchronously does not align the child alert with the alert group's settings
Issue Number: #5023
This works now
> fix(alert): sync child alerts when slot changes in alert group

- packages/angular/golden/clr-angular.d.ts
- packages/angular/projects/clr-angular/src/accordion/accordion-panel.ts
There was an inconsistency in how the `id` property of the accordion panel and stepper panels were implemented that Typescript 4 did not like. This resolves the inconsistency and should work fine on TS 3.9 or 4. Angular bumped support to TS 4 and this is an unexpected side effect.
fixes #5015
> fix(accordion): updated panel property to match stepper panel for TS 4

- packages/angular/projects/clr-angular/src/data/datagrid/providers/selection.spec.ts
- packages/angular/projects/clr-angular/src/data/datagrid/providers/selection.ts
Caused by fix in the "current selection immutability" fix
Issue Number: #4528
> fix(datagrid): double event on selection

- packages/angular/projects/clr-angular/src/data/datagrid/providers/selection.spec.ts
- packages/angular/projects/clr-angular/src/data/datagrid/providers/selection.ts
Caused by fix in the "current selection immutability" fix
> fix(datagrid): double event on selection (backport)

- apps/website/.vuepress/theme/components/SkipTo.vue
- apps/website/.vuepress/theme/layouts/Layout.vue
- apps/website/foundation/navigation/api.md
- apps/website/foundation/navigation/demo.md
1. Adds a skip to link for all content pages
2. Removes the demo tab from foundation/navigation
I'm adding a skip to link and removing an unused demo tab fro the navigation content. 
n/x
All pages should show a skip to link similar to the current website that places focus on the #content-area container. 
foundation/navigation should only have usage and api tabs.
> docs: two small launch fixes for website

- packages/angular/projects/clr-angular/src/data/datagrid/datagrid-row.spec.ts
- packages/angular/projects/clr-angular/src/data/datagrid/datagrid-row.ts
- packages/angular/projects/dev/src/app/datagrid/conditional-selection/conditional-selection.html
- packages/angular/projects/dev/src/app/datagrid/conditional-selection/conditional-selection.ts
Same as `colDgType`, `clrDgSelectable` is called in some cases before `clrDgItem` is defined so there is no way to lock it or unlock it. 
Moving this inside `ngOnChanges` and checking it there solve this. 
Issue Number: #4993
Close #4993
> fix: datagrid-row correct way of assigning clrDgSelectable

- packages/angular/projects/clr-angular/src/forms/styles/_input.clarity.scss
The issue reported was the animated blue underline when an input was given focus was going the full width of the inputs parent container (a .clr-input-wrapper element). This is a partial fix for evergreen browsers. I have an idea that might also work for IE11 but we need to set up the dev app to build for ie11 (e.g compile for es5).
As such, this is a partial fix for #5009.
Limit the clr-input-wrapper element to the width of its content. 
inputs with the animated underline look like they oveflow the container. 
Issue Number: #5009 
Tested in: Chrome, Safari, Firefox and Edge. I am pretty sure this fix will not address the issue in IE11. …
> fix: clr-input-wrapper max width

- packages/angular/projects/clr-angular/src/data/datagrid/_datagrid.clarity.scss
This change fixes a regression that breaks the sticky behavior of datagrid column headers.
Closes #4889
There was a regression introduced that broke the sticky column (header row) behavior in datagrid. This reverts that change. 
Currently sticky headers will scroll out of view when the last visible row overflows the container element. This was happening because the `.datagrid` container had a display: flex on it. 
The code removed indicates that it was added to fix content stretching in Safari but I couldn't see what that issue was when it was removed. 
Issue Number: #4889 
Datagrid headers stay in view when row content overflows no …
> fix: make datagrid header sticky no matter how many rows

- packages/react/src/converter/react-wrapper.test.tsx
- packages/react/src/converter/react-wrapper.tsx
The [Storybook page about the Icon API](https://clarity.design/storybook/core/?path=/story/components-icon-getting-started--page#api) shows that it should be possible to change the color with `--color`.
In practice, I could not find a way to apply a `className` to the `CdsIcon` React component because the `className` property was being swallowed. [Here is a sandbox](https://codesandbox.io/s/great-swanson-kdb39?file=/src/App.tsx) to demonstrate the issue.
After removing this, this would be the expected behavior:
(I couldn't figure out how to patch dependencies on CodeSandbox)
I'm not sure if this is the right way to do that, and I'm more than happy to edit my PR if …
> Allow className to be passed down to the underlying component

- packages/core/.storybook/preview.js
- packages/core/.storybook/public/demo.css
- packages/core/import-map.importmap
- packages/core/src/divider/divider.element.scss
- packages/core/src/divider/divider.element.spec.ts
- packages/core/src/divider/divider.element.ts
- packages/core/src/divider/divider.stories.mdx
- packages/core/src/divider/divider.stories.ts
- packages/core/src/divider/entrypoint.tsconfig.json
- packages/core/src/divider/index.ts
- packages/core/src/divider/package.json
- packages/core/src/divider/register.ts
- packages/core/src/styles/layout/layout.stories.ts
- packages/core/tsconfig.project.json
- packages/react/App.tsx
- packages/react/src/divider/__snapshots__/index.test.tsx.snap
- packages/react/src/divider/entrypoint.tsconfig.json
- packages/react/src/divider/index.test.tsx
- packages/react/src/divider/index.tsx
- packages/react/src/divider/package.json
- packages/react/tsconfig.project.json
• needed for menus, cards, datagrid headers, and other components
• added stories
• added horizontal dividers
• added vertical dividers for use within layouts
• added vertical-fill dividers for use within sized containers that aren't using layouts
• added unit tests
• added react wrappers and tests for dividers
• updated project tsconfig to account for all components
• update example app layouts to use dividers
• cleaned up example app layouts as CSS borders are no longer needed
People have to use CSS to put dividers between sections. Or use custom stylings on divs to create dividers themselves (see: datagrid header)
We …
> feat: adding cds-divider component to core

- README.md
- packages/angular/projects/clr-angular/README.md
- packages/core/README.md
- packages/icons/README.md
- packages/react/README.md
- packages/ui/README.md
Currently, we do not have a way to navigate to npm packages from GitHub docs.
P.S. I am looking forward to something a little bit more complex like - having badges for every version of the packages we support but generated automatically. 
https://github.com/badges/shields is cool but we will bring a new npm package in the build pipeline in order to reach what I describe in the previous sentence.
Having a version badge pointing to the latest available version in NPM.
> docs: add npm version badges

- packages/angular/projects/clr-angular/src/data/datagrid/_datagrid.clarity.scss
This is a cherry-pick  for this fix: 
- https://github.com/vmware/clarity/commit/ee7cbc562b981c0cb31135aa88178e4e36a7f226
------------------------------------------------------------------------------------------
This change fixes a regression that breaks the sticky behavior of datagrid column headers.
Closes #4889
Issue Number: #4889
> fix(v4 backport): make datagrid header sticky no matter how many rows

- packages/core/src/internal-components/close-button/close-button.stories.ts
- packages/core/src/internal/base/focus-trap.base.spec.ts
- packages/core/src/internal/base/focus-trap.base.ts
- packages/core/src/internal/services/focus-trap-tracker.service.spec.ts
- packages/core/src/internal/services/focus-trap-tracker.service.ts
- packages/core/src/internal/utils/array.spec.ts
- packages/core/src/internal/utils/array.ts
- packages/core/src/internal/utils/dom.spec.ts
- packages/core/src/internal/utils/dom.ts
- packages/core/src/internal/utils/focus-trap.spec.ts
- packages/core/src/internal/utils/focus-trap.ts
- packages/core/src/styles/layout/_container.scss
- packages/react/App.tsx
• refactored focus traps
• decoupled scroll lockdown from layouts
• allows end-users to use the layout lockdown without getting stomped on by focus traps
• made focus trap tracker 100% static
• now no longer keeps track of focus traps, just asks dom for them
• allows for more than one instance to exist if that sort of thing happens in the wild
• guarding against focus trap tracker being passed the same id more than once
• added focus-trap inception to react dev app
• manually verifies that focus traps can be layered and work as expected
• can be replaced with a dropdown in the modal once overlays are ready
• unit test to validate focus-trap inception
• decoupling focus trap refactor from the overlay component
Please check if your PR …
> fix: refactor focus-traps

- apps/website/.vuepress/theme/components/Page.vue
- apps/website/.vuepress/theme/global-components/DocCode.vue
- apps/website/.vuepress/theme/styles/overrides.scss
These are a few more targeted fixes for parts of the website that affect multiple pages at a time on the website. 
- moved aria-expanded to the code demo container and made button text darker
- adjust Page child elements for focus order and screen-reader flow
- hide code blocks from screen readers when they are not expanded
Website accessibility fixes for multiple pages on the website. 
n/a
> fix: address accessibility items that affect multiple pages

- packages/angular/projects/clr-angular/src/forms/styles/_input.clarity.scss
This is a cherry-picked backport of the fix on master into the v4 branch. 
-----------------------------------------------------
The issue reported was the animated blue underline when an input was given focus was going the full width of the inputs parent container (a .clr-input-wrapper element). This is a partial fix for evergreen browsers. I have an idea that might also work for IE11 but we need to set up the dev app to build for ie11 (e.g compile for es5).
As such, this is a partial fix for #5009.
> [BACKPORT -> v4] fix: clr-input-wrapper max width

- apps/website/.vuepress/theme/components/Footer.vue
- apps/website/.vuepress/theme/components/NavToc.vue
- apps/website/.vuepress/theme/components/Sidebar.vue
There are two navigations that can appear on the page and the user cannot know which one is using.
The social icons don't have a label so the user can know which one is focused on.
When tabbing the user will know which navigation is currently using and also when the user gets to the social link will know which one is focused.
> docs: addd website a11y for social icons and navigation

- packages/angular/projects/clr-angular/src/forms/common/wrapped-control.spec.ts
- packages/angular/projects/clr-angular/src/forms/common/wrapped-control.ts
Signed-off-by: Wallabeng <marcel@ring-mail.at>
Workaround for touching controls (#4767), touches all controls inside a form, because MarkControlService is provided on form level. So validation messages (e.g. for required validator) inside the form are shown, regardless of any user interaction.
Workaround for touching control touches the blurred control only.
> fix(form): mark only blurred control as touched instead of whole form

- packages/core/src/tag/tag.element.scss
• the wrong default color was implemented initially
• the color that was implemented was too light
• this change aligns the core tag text color with the clr/ui label text color
Issue Number: #5104
> fix(a11y): improve default core tag accessibility

- packages/core/src/tag/tag.element.scss
• the wrong default color was implemented initially
• the color that was implemented was too light
• this change aligns the core tag text color with the clr/ui label text color
> fix(a11y): improve default core tag accessibility (backport to v4)

- packages/angular/projects/clr-angular/src/accordion/_accordion.clarity.scss
• some css properties were not applied to the accordion
• this fixes that issue
The accordion had not been wired up to use a couple of CSS custom properties.
Issue Number: #5076
It is now.
> fix(accordion): css variables for accordion

- .github/workflows/website.yml
- package.json
In order to download icons the lambda function needs to be built and deployed. 
This change will do that. 
Build and deploy the icons lambda fn for the website. 
Individual icon download button results in 404. 
Individual icon download button downloads the correct svg file from github.
> fix: adds CI build step for netlify lambda fn

- packages/core/src/icon/index.ts
• it was our intent to allow users to create their own icons using our icon template format
• we do not export the code to convert an icon template into an SVG
• this change exposes that code
• the renderIcon() function was not rolled up into the icon service because I wanted it to remain tree shakable and not bundled in with the icons API
• using render icon is an advanced use case; most users would not import it and use it.
• this will be back ported to 4.0
Users cannot create bonafide clarity icons using the icon templates that @clr/core uses
the renderIcon() function is exported so that advanced users can now build …
> feat(icons): [core] allow for custom icons to be added from icon templates

- packages/core/src/icon/index.ts
• it was our intent to allow users to create their own icons using our icon template format
• we do not export the code to convert an icon template into an SVG
• this change exposes that code
• the renderIcon() function was not rolled up into the icon service because I wanted it to remain tree shakable and not bundled in with the icons API
• using render icon is an advanced use case; most users would not import it and use it.
• this will be back ported to 4.0
> feat(icons): [core] allow for custom icons to be added from icon templates (backport v4)

- packages/core/src/icon/icon.element.scss
- packages/core/src/icon/icon.element.spec.ts
- packages/core/src/icon/icon.element.ts
- packages/core/src/icon/icon.service.spec.ts
- packages/core/src/icon/icon.service.ts
- packages/core/src/icon/utils/icon.classnames.spec.ts
- packages/core/src/icon/utils/icon.classnames.ts
Removing the deprecated methods and styles introduced in previous versions and marked as deprecated for v5 in Icons.
Issue Number: #4925
Removed deprecated code
Anybody who uses the old icon sizes styles, `dir` property of `cds-icon` and `get`, `add` and `alias` methods from `icon.service` will be affected.
> fix: remove core icons deprecated styles and methods

- packages/angular/projects/clr-angular/src/data/datagrid/datagrid.ts
issue #5085
When Ivy is turned off, the displayedRows list accumulates old ghost items, which mess the proper child views visualization. Thus, after been filtered out, rows are not shown back when the filter is removed.
Issue Number: #5085 
Works fine both with and without Ivy
Please note, that because of the complicated setup we can't make a test for the no-Ivy scenario. We can't have a test run with and without Ivy unless we run a new task with new test setup.
> fix: (datagrid) filtering not working well with Ivy off

- packages/angular/projects/clr-angular/src/forms/common/wrapped-control.spec.ts
- packages/angular/projects/clr-angular/src/forms/common/wrapped-control.ts
Back port for a v4 issue that was fixed with this commit. 
Signed-off-by: Wallabeng <marcel@ring-mail.at>
> [v4 BACKPORT] fix(form): mark only blurred control as touched instead of whole form

- packages/angular/projects/clr-angular/src/forms/combobox/_combobox.clarity.scss
- packages/angular/projects/clr-angular/src/forms/combobox/combobox.html
- packages/angular/projects/clr-angular/src/forms/combobox/combobox.spec.ts
- [] If applicable, have a visual design approval
Issue Number: #4868
The `openClose` button is disabled when the `combobox` is disabled.
> fix(combobox): disable openClose button

- packages/angular/projects/clr-angular/src/popover/signpost/signpost-content.ts
Currently the header appears after the contents in the DOM, but is visually positioned absolutely at the beginning.  This breaks screen readers, but fortunately we can just reorder the elements and have the same visual result.
Closes: #4986
Signpost headers correctly appear before the contents on the screen, but are after the contents in the DOM and a11y tree.  This makes all three match.
> fix(signpost): put header before contents to fix DOM/a11y tree order

- packages/eslint-plugin-clarity-migration/README.md
- packages/eslint-plugin-clarity-migration/package.json
- packages/eslint-plugin-clarity-migration/src/html-parser.ts
- packages/eslint-plugin-clarity-migration/src/types/index.d.ts
- packages/eslint-plugin-clarity-migration/test/no-clr-button.spec.ts
- packages/eslint-plugin-clarity-migration/test/test-helper.ts
- yarn.lock
This PR fixes the case when the traversed HTML file has multiple root
elements, e.g.:
```
<div></div>
<button class="btn btn-primary"></button>
```
The `eslint-plugin-clarity-migration` package now has a custom HTML
parser. The parser is a patched version of [eslint-html-parser](https://github.com/medicomp/eslint-html-parser).
Signed-off-by: Stanimira Vlaeva <stanimira.vlaeva@gmail.com>
Currently, the plugin uses `eslint-html-parser` to traverse HTML files. However, that package cannot handle the case with multiple root elements in one file.
Now, the plugin has its own HTML parser based on `eslint-html-parser`. The current HTML parser creates an empty `HTMLElement` …
> fix: (eslint-plugin-clarity-migration) catch multiple root elements in HTML file

- packages/angular/projects/clr-angular/src/forms/combobox/combobox.spec.ts
For some reason, the `placeholder` input is not included in `v4` branch so the test has to be removed in the branch
> fix(combobox): remove placeholder input in unit test

- src/clr-angular/popover/signpost/signpost-content.ts
Backport of #5130
Signed-off-by: Bogdan Bogdanov bbogdanov@vmware.com
Signed-off-by: Alex Mellnik a.r.mellnik@gmail.com
Credits to @amellnik
> fix(signpost): put header before contents to fix DOM/a11y tree order (backport)

- packages/angular/projects/clr-angular/src/data/datagrid/datagrid-column.spec.ts
- packages/angular/projects/clr-angular/src/data/datagrid/datagrid-column.ts
fix for a11y-issue-136 (also a11y-issue-176, which is duplicate of 136)
closes #4135 
Screan readers read headers of sortable columns as "Sort column", and the cell content is not read at all
Issue Number: #4135
"Sort column" override is removed and sorting state/action is conveyed by the cell aria-sort attribute, as seen in this W3C example:
https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html
> fix(datagrid): remove column a11y name override

- packages/angular/projects/clr-angular/src/data/datagrid/datagrid-column.spec.ts
- packages/angular/projects/clr-angular/src/data/datagrid/datagrid-column.ts
> fix(datagrid): remove column a11y name override (backport)

- netlify.toml
- scripts/netlify-build.sh
Prevent (yarn) installs on netlify for now because they keep timing out. 
Yarn installs time out on netlify infrastructure. 
Run a simple ignore script and exit with 0 on netlify infrastructure.
> build: prevent dependency installs on netlify infrastructure

- packages/angular/projects/website/src/app/documentation/get-started/get-started.component.html
The Metropolis project was recently deleted from GitHub, so we have to link to our saved versions of the assets which I've uploaded to GitHub.
closes #5177
Issue Number: #5177
> docs: fix metropolis link

- packages/eslint-plugin-clarity-migration/package.json
- packages/eslint-plugin-clarity-migration/src/rules/no-clr-button/index.ts
- packages/eslint-plugin-clarity-migration/test/no-clr-button.spec.ts
- yarn.lock
Currently, when the ESLint rule finds `<button class="btn btn-primary"></button>` in a component template, it reports the error/warning for the template node. That means that the IDE will underline the whole template instead of the specific button node within the template.
I switched `node-html-parser` for `jsdom`. We use `jsdom` to create an AST out of the template content. Thanks to the `jsdom` API, we can find the location (line and column) of the buttons within the template. Then, we can calculate the correct location in the full source and report it. The result is that now the IDE underlines the button node within the template …
> fix: report correct location of ESLint error in component templates

- packages/angular/.eslintrc.js
- packages/angular/package.json
- packages/angular/projects/clr-angular/src/data/datagrid/datagrid-column.spec.ts
- packages/angular/projects/clr-angular/src/deprecations.spec.ts
- packages/angular/projects/clr-angular/src/forms/common/if-control-state/if-success.ts
- packages/angular/projects/clr-angular/src/utils/popover/popover-close-button.spec.ts
- packages/angular/src/stories/combobox/combobox.stories.ts
- packages/angular/src/stories/signpost/signpost.stories.ts
and fix files that break the rule
Add back rule that used to be in tslint, but is not applied in eslint
Can merge files with unused imports
Won't be able to merge files with unused imports
> chore: add back no-unused-imports lint rule

- apps/website/.vuepress/theme/components/AlgoliaSearchBox.vue
- apps/website/.vuepress/theme/components/Home.vue
- apps/website/.vuepress/theme/components/Page.vue
- apps/website/.vuepress/theme/components/PageSubnav.vue
- apps/website/.vuepress/theme/global-components/DocIconsPreviewSettings.vue
- apps/website/.vuepress/theme/global-components/DocIconsSearch.vue
- apps/website/.vuepress/theme/global-components/DocIconsSet.vue
- apps/website/.vuepress/theme/global-components/Release.vue
1. This makes the website `.page` element/container have a sticky header for its `PageSubnav.vue` content. 
2. There are some Home page typography and spacing changes that content presentation.
Page title scrolls out of view. 
Page title remains visible.
> docs(website): add sticky header for docs pages

- packages/angular/projects/clr-angular/src/data/datagrid/_datagrid.clarity.scss
Fix UI issue that let the placeholder icon and text to be center in both
horizontal and vertical. By design, it has to be only horizontal.
close #5139
Issue Number: #5139
Need to be backported to v3, v4 and v2
> fix: datagrid issue with placeholder position

- packages/angular/projects/clr-angular/src/data/datagrid/datagrid-column-toggle.spec.ts
- packages/angular/projects/clr-angular/src/data/datagrid/datagrid-column-toggle.ts
- packages/angular/projects/clr-angular/src/data/datagrid/datagrid-column.spec.ts
- packages/angular/projects/clr-angular/src/data/datagrid/datagrid-column.ts
- packages/angular/projects/clr-angular/src/layout/tabs/tabs.spec.ts
- packages/angular/projects/clr-angular/src/layout/tabs/tabs.ts
When icons are part of a button (icon only) it's better to add the
`aria-hidden` and `title` to the button wrapper not to the icon.
This change affects datagrid and tab component
fixes: #4454
Issue Number: 4454
> fix: accessibility issues with clr-icon involving title and aria-hidden

- packages/angular/golden/clr-angular.d.ts
- packages/angular/projects/clr-angular/src/data/datagrid/built-in/filters/datagrid-string-filter.spec.ts
- packages/angular/projects/clr-angular/src/data/datagrid/built-in/filters/datagrid-string-filter.ts
- packages/angular/projects/clr-angular/src/utils/i18n/common-strings.default.ts
- packages/angular/projects/clr-angular/src/utils/i18n/common-strings.interface.ts
- packages/core/src/internal/services/common-strings.default.ts
- packages/core/src/internal/services/common-strings.interface.ts
Add a new common string for "Search" and use it to add an aria-label to the datagrid default string filter input.  This string can probably be used elsewhere in the future.
Partially closes: #4756
~WIP to resolve some build issues that I think are unrelated.~
The datagrid default string filter does not have an aria-label or placeholder.  
Issue Number: #4986 
This adds the aria label via a new common string.  It doesn't populate the placeholder but that would be easy to do.
> fix(datagrid): add aria-label to string filter input

- packages/angular/projects/clr-angular/src/data/stack-view/_stack-view.clarity.scss
Removes custom focus styles for the row triggers in stack grids.  It adds the default outline that's used for buttons and other elements, keeping hover behavior the same.
Issue Number: #4899
Standardizes the focus indicator.
> fix(stack-view): use normal outline focus indicators

- packages/angular/projects/clr-angular/src/data/datagrid/datagrid-column-toggle.ts
Add an aria-label to the column chooser dialog.
Closes: #4754
The column chooser dialog has the dialog role, but there's no label associated with it.  There is a invisible div inside the dialog that describes it, but since it's not an aria-label its not read again as the screen reader virtual focus exits the dialog.
Removes the invisible div and moves the message to the aria-label of the dialog.
> fix(datagrid): add an aria-label to the column chooser dialog
